document.createElement("canvas").getContext||function(z){function L(){return this.context_||(this.context_=new A(this))}function M(a,b){var c=F.call(arguments,2);return function(){return a.apply(b,c.concat(F.call(arguments)))}}function N(a){var b=a.srcElement;switch(a.propertyName){case "width":b.style.width=b.attributes.width.nodeValue+"px";b.getContext().clearRect();break;case "height":b.style.height=b.attributes.height.nodeValue+"px";b.getContext().clearRect();break}}function O(a){a=a.srcElement;
if(a.firstChild){a.firstChild.style.width=a.clientWidth+"px";a.firstChild.style.height=a.clientHeight+"px"}}function B(){return[[1,0,0],[0,1,0],[0,0,1]]}function s(a,b){for(var c=B(),d=0;d<3;d++)for(var e=0;e<3;e++){for(var h=0,g=0;g<3;g++)h+=a[d][g]*b[g][e];c[d][e]=h}return c}function G(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=a.shadowOffsetX;b.shadowOffsetY=
a.shadowOffsetY;b.strokeStyle=a.strokeStyle;b.globalAlpha=a.globalAlpha;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_;b.lineScale_=a.lineScale_}function H(a){var b,c=1;a=String(a);if(a.substring(0,3)=="rgb"){b=a.indexOf("(",3);var d=a.indexOf(")",b+1);d=a.substring(b+1,d).split(",");b="#";for(var e=0;e<3;e++)b+=I[Number(d[e])];if(d.length==4&&a.substr(3,1)=="a")c=d[3]}else b=a;return{color:b,alpha:c}}function P(a){switch(a){case "butt":return"flat";case "round":return"round";case "square":default:return"square"}}
function A(a){this.m_=B();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=k*1;this.globalAlpha=1;this.canvas=a;var b=a.ownerDocument.createElement("div");b.style.width=a.clientWidth+"px";b.style.height=a.clientHeight+"px";b.style.overflow="hidden";b.style.position="absolute";a.appendChild(b);this.element_=b;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function J(a,b,c,d){a.currentPath_.push({type:"bezierCurveTo",
cp1x:b.x,cp1y:b.y,cp2x:c.x,cp2y:c.y,x:d.x,y:d.y});a.currentX_=d.x;a.currentY_=d.y}function t(a,b,c){var d;a:{for(d=0;d<3;d++)for(var e=0;e<2;e++)if(!isFinite(b[d][e])||isNaN(b[d][e])){d=false;break a}d=true}if(d){a.m_=b;if(c)a.lineScale_=Q(R(b[0][0]*b[1][1]-b[0][1]*b[1][0]))}}function w(a){this.type_=a;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function K(){}var n=Math,j=n.round,C=n.sin,D=n.cos,R=n.abs,Q=n.sqrt,k=10,r=k/2,F=Array.prototype.slice,E={init:function(a){if(/MSIE/.test(navigator.userAgent)&&
!window.opera){a=a||document;a.createElement("canvas");z(M(this.init_,this,a))}},init_:function(a){a.namespaces.g_vml_||a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");a.namespaces.g_o_||a.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");if(!a.styleSheets.ex_canvas_){var b=a.createStyleSheet();b.owningElement.id="ex_canvas_";b.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}g_vml_\\:*{behavior:url(#default#VML)}g_o_\\:*{behavior:url(#default#VML)}"}a=
a.getElementsByTagName("canvas");for(b=0;b<a.length;b++)this.initElement(a[b])},initElement:function(a){if(!a.getContext){a.getContext=L;a.innerHTML="";a.attachEvent("onpropertychange",N);a.attachEvent("onresize",O);var b=a.attributes;if(b.width&&b.width.specified)a.style.width=b.width.nodeValue+"px";else a.width=a.clientWidth;if(b.height&&b.height.specified)a.style.height=b.height.nodeValue+"px";else a.height=a.clientHeight}return a}};E.init();for(var I=[],i=0;i<16;i++)for(var x=0;x<16;x++)I[i*16+
x]=i.toString(16)+x.toString(16);i=A.prototype;i.clearRect=function(){this.element_.innerHTML=""};i.beginPath=function(){this.currentPath_=[]};i.moveTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"moveTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};i.lineTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};i.bezierCurveTo=function(a,b,c,d,e,h){e=this.getCoords_(e,h);a=this.getCoords_(a,
b);c=this.getCoords_(c,d);J(this,a,c,e)};i.quadraticCurveTo=function(a,b,c,d){a=this.getCoords_(a,b);c=this.getCoords_(c,d);d={x:this.currentX_+2/3*(a.x-this.currentX_),y:this.currentY_+2/3*(a.y-this.currentY_)};J(this,d,{x:d.x+(c.x-this.currentX_)/3,y:d.y+(c.y-this.currentY_)/3},c)};i.arc=function(a,b,c,d,e,h){c*=k;var g=h?"at":"wa",f=a+D(d)*c-r,l=b+C(d)*c-r;d=a+D(e)*c-r;e=b+C(e)*c-r;if(f==d&&!h)f+=0.125;a=this.getCoords_(a,b);f=this.getCoords_(f,l);d=this.getCoords_(d,e);this.currentPath_.push({type:g,
x:a.x,y:a.y,radius:c,xStart:f.x,yStart:f.y,xEnd:d.x,yEnd:d.y})};i.rect=function(a,b,c,d){this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath()};i.strokeRect=function(a,b,c,d){var e=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath();this.stroke();this.currentPath_=e};i.fillRect=function(a,b,c,d){var e=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+
c,b+d);this.lineTo(a,b+d);this.closePath();this.fill();this.currentPath_=e};i.createLinearGradient=function(a,b,c,d){var e=new w("gradient");e.x0_=a;e.y0_=b;e.x1_=c;e.y1_=d;return e};i.createRadialGradient=function(a,b,c,d,e,h){var g=new w("gradientradial");g.x0_=a;g.y0_=b;g.r0_=c;g.x1_=d;g.y1_=e;g.r1_=h;return g};i.drawImage=function(a){var b,c,d,e,h,g,f,l;d=a.runtimeStyle.width;e=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height="auto";var o=a.width,p=a.height;a.runtimeStyle.width=
d;a.runtimeStyle.height=e;if(arguments.length==3){b=arguments[1];c=arguments[2];h=g=0;f=d=o;l=e=p}else if(arguments.length==5){b=arguments[1];c=arguments[2];d=arguments[3];e=arguments[4];h=g=0;f=o;l=p}else if(arguments.length==9){h=arguments[1];g=arguments[2];f=arguments[3];l=arguments[4];b=arguments[5];c=arguments[6];d=arguments[7];e=arguments[8]}else throw Error("Invalid number of arguments");var m=this.getCoords_(b,c),q=[];q.push(" <g_vml_:group",' coordsize="',k*10,",",k*10,'"',' coordorigin="0,0"',
' style="width:',10,"px;height:",10,"px;position:absolute;");if(this.m_[0][0]!=1||this.m_[0][1]){var u=[];u.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",j(m.x/k),",","Dy=",j(m.y/k),"");var v=this.getCoords_(b+d,c),y=this.getCoords_(b,c+e);b=this.getCoords_(b+d,c+e);m.x=n.max(m.x,v.x,y.x,b.x);m.y=n.max(m.y,v.y,y.y,b.y);q.push("padding:0 ",j(m.x/k),"px ",j(m.y/k),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",u.join(""),", sizingmethod='clip');")}else q.push("top:",
j(m.y/k),"px;left:",j(m.x/k),"px;");q.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',k*d,"px;"," height:",k*e,'px;"',' cropleft="',h/o,'"',' croptop="',g/p,'"',' cropright="',(o-h-f)/o,'"',' cropbottom="',(p-g-l)/p,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",q.join(""))};i.stroke=function(a){var b=[],c=H(a?this.fillStyle:this.strokeStyle),d=c.color;c=c.alpha*this.globalAlpha;b.push("<g_vml_:shape",' filled="',!!a,'"',' style="position:absolute;width:',10,
"px;height:",10,'px;"',' coordorigin="0 0" coordsize="',k*10," ",k*10,'"',' stroked="',!a,'"',' path="');for(var e={x:null,y:null},h={x:null,y:null},g=0;g<this.currentPath_.length;g++){var f=this.currentPath_[g];switch(f.type){case "moveTo":b.push(" m ",j(f.x),",",j(f.y));break;case "lineTo":b.push(" l ",j(f.x),",",j(f.y));break;case "close":b.push(" x ");f=null;break;case "bezierCurveTo":b.push(" c ",j(f.cp1x),",",j(f.cp1y),",",j(f.cp2x),",",j(f.cp2y),",",j(f.x),",",j(f.y));break;case "at":case "wa":b.push(" ",
f.type," ",j(f.x-this.arcScaleX_*f.radius),",",j(f.y-this.arcScaleY_*f.radius)," ",j(f.x+this.arcScaleX_*f.radius),",",j(f.y+this.arcScaleY_*f.radius)," ",j(f.xStart),",",j(f.yStart)," ",j(f.xEnd),",",j(f.yEnd));break}if(f){if(e.x==null||f.x<e.x)e.x=f.x;if(h.x==null||f.x>h.x)h.x=f.x;if(e.y==null||f.y<e.y)e.y=f.y;if(h.y==null||f.y>h.y)h.y=f.y}}b.push(' ">');if(a)if(typeof this.fillStyle=="object"){d=this.fillStyle;f=0;a={x:0,y:0};c=0;var l=1;if(d.type_=="gradient"){f=d.x1_/this.arcScaleX_;e=d.y1_/
this.arcScaleY_;g=this.getCoords_(d.x0_/this.arcScaleX_,d.y0_/this.arcScaleY_);f=this.getCoords_(f,e);f=Math.atan2(f.x-g.x,f.y-g.y)*180/Math.PI;if(f<0)f+=360;if(f<1.0E-6)f=0}else{g=this.getCoords_(d.x0_,d.y0_);c=h.x-e.x;l=h.y-e.y;a={x:(g.x-e.x)/c,y:(g.y-e.y)/l};c/=this.arcScaleX_*k;l/=this.arcScaleY_*k;g=n.max(c,l);c=2*d.r0_/g;l=2*d.r1_/g-c}e=d.colors_;e.sort(function(y,S){return y.offset-S.offset});h=e.length;var o=e[0].color,p=e[h-1].color,m=e[0].alpha*this.globalAlpha,q=e[h-1].alpha*this.globalAlpha,
u=[];for(g=0;g<h;g++){var v=e[g];u.push(v.offset*l+c+" "+v.color)}b.push('<g_vml_:fill type="',d.type_,'"',' method="none" focus="100%"',' color="',o,'"',' color2="',p,'"',' colors="',u.join(","),'"',' opacity="',q,'"',' g_o_:opacity2="',m,'"',' angle="',f,'"',' focusposition="',a.x,",",a.y,'" />')}else b.push('<g_vml_:fill color="',d,'" opacity="',c,'" />');else{a=this.lineScale_*this.lineWidth;if(a<1)c*=a;b.push("<g_vml_:stroke",' opacity="',c,'"',' joinstyle="',this.lineJoin,'"',' miterlimit="',
this.miterLimit,'"',' endcap="',P(this.lineCap),'"',' weight="',a,'px"',' color="',d,'" />')}b.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",b.join(""))};i.fill=function(){this.stroke(true)};i.closePath=function(){this.currentPath_.push({type:"close"})};i.getCoords_=function(a,b){var c=this.m_;return{x:k*(a*c[0][0]+b*c[1][0]+c[2][0])-r,y:k*(a*c[0][1]+b*c[1][1]+c[2][1])-r}};i.save=function(){var a={};G(this,a);this.aStack_.push(a);this.mStack_.push(this.m_);this.m_=s(B(),this.m_)};
i.restore=function(){G(this.aStack_.pop(),this);this.m_=this.mStack_.pop()};i.translate=function(a,b){t(this,s([[1,0,0],[0,1,0],[a,b,1]],this.m_),false)};i.rotate=function(a){var b=D(a);a=C(a);t(this,s([[b,a,0],[-a,b,0],[0,0,1]],this.m_),false)};i.scale=function(a,b){this.arcScaleX_*=a;this.arcScaleY_*=b;t(this,s([[a,0,0],[0,b,0],[0,0,1]],this.m_),true)};i.transform=function(a,b,c,d,e,h){t(this,s([[a,b,0],[c,d,0],[e,h,1]],this.m_),true)};i.setTransform=function(a,b,c,d,e,h){t(this,[[a,b,0],[c,d,0],
[e,h,1]],true)};i.clip=function(){};i.arcTo=function(){};i.createPattern=function(){return new K};w.prototype.addColorStop=function(a,b){b=H(b);this.colors_.push({offset:a,color:b.color,alpha:b.alpha})};G_vmlCanvasManager=E;CanvasRenderingContext2D=A;CanvasGradient=w;CanvasPattern=K;z.support.canvas="shim";G_vmlCanvasManager.fixElement_=function(a){var b=a.outerHTML,c=a.ownerDocument.createElement(b);if(b.slice(-2)!="/>"){b="/"+a.tagName;for(var d;(d=a.nextSibling)&&d.tagName!=b;)d.removeNode();d&&
d.removeNode()}else return a;a.parentNode.replaceChild(c,a);return c};G_vmlCanvasManager.fixDynamicElement=function(a){return G_vmlCanvasManager.initElement(G_vmlCanvasManager.fixElement_(a))};z.webshims.addMethod("getContext",function(a){this.getContext||E.fixDynamicElement(this);return this.getContext(a)})}(jQuery);
