(function(a){if(!navigator.geolocation){a.support.geolocation="shim";var h=function(){setTimeout(function(){throw"document.write is overwritten by geolocation shim. This method is incompatibel with this plugin";},1)},i=0;navigator.geolocation=function(){var g,f={getCurrentPosition:function(b,c,d){var k=function(){clearTimeout(e);if(!(g||!window.google||!google.loader||!google.loader.ClientLocation)){var j=google.loader.ClientLocation;g={latitude:j.latitude,longitude:j.longitude,altitude:null,accuracy:43E3,
altitudeAccuracy:null,heading:parseInt("NaN",10),velocity:null}}if(g)b({coords:g,timestamp:(new Date).getTime()});else c&&c({code:2,message:"POSITION_UNAVAILABLE"})},e;if(!window.google||!google.loader){if(a.webshims.loader.modules.geolocation.options.destroyWrite){document.write=h;document.writeln=h}a(document).one("google-loaderReady",k);a.webshims.loader.loadScript("http://www.google.com/jsapi",false,"google-loader");if(d&&d.timeout)e=setTimeout(function(){a(document).unbind("google-loader",k);
c&&c({code:3,message:"TIMEOUT"})},d.timeout)}else setTimeout(k,1)},clearWatch:a.noop};f.watchPosition=function(b,c,d){f.getCurrentPosition(b,c,d);i++;return i};return f}()}})(jQuery);
(function(a){if(!a.support.validity){var h={radio:1,checkbox:1},i={};a.webshims.addInputType=function(b,c){i[b]=c};var g={customError:false,typeMismatch:false,rangeUnderflow:false,rangeOverflow:false,stepMismatch:false,tooLong:false,patternMismatch:false,valueMissing:false,valid:true},f={valueMissing:function(b,c){if(!b.attr("required"))return false;return h[b[0].type]?!a(b[0].form&&b[0].name?b[0].form[b[0].name]:[]).filter(":checked")[0]:!c},tooLong:function(b,c){if(c==="")return false;var d=b.attr("maxlength"),
k=false,e=c.length;if(e&&d>=0&&c.replace&&(typeof d=="number"||d&&d==d*1)){if(k=e>d)return k;c.replace(/\u0A/g,function(){e++});k=e>d}return k},typeMismatch:function(b,c,d){if(c==="")return false;var k=false;if(!("type"in d))d.type=(b[0].getAttribute("type")||"").toLowerCase();if(i[d.type]&&i[d.type].mismatch)k=i[d.type].mismatch(c,b);return k},patternMismatch:function(b,c){if(c==="")return false;var d=b.attr("pattern");if(!d)return false;return!RegExp("^(?:"+d+")$").test(c)}};a.webshims.addMethod("checkValidity",
function(){var b,c=function(d){var k,e=a.attr(d,"validity");if(e)a.data(d,"cachedValidity",e);else e={valid:true};if(!e.valid){k=a.Event("invalid");var j=a(d).trigger(k);if(!k.isDefaultPrevented()){b||a.webshims.validityAlert.showFor(j);b=true}}a.data(d,"cachedValidity",false);return e.valid};return function(){b=false;if(a.nodeName(this,"form")||a.nodeName(this,"fieldset")){for(var d=true,k=this.elements||a("input, textarea, select",this),e=0,j=k.length;e<j;e++)c(k[e])||(d=false);return d}else return this.form?
c(this):true}}());a.event.special.invalid={add:function(){a.data(this,"invalidEventShim")||a.event.special.invalid.setup.call(this)},setup:function(){a(this).bind("submit",a.event.special.invalid.handler).data("invalidEventShim",true);var b=a(this).data("events").submit;b&&b.length>1&&b.unshift(b.pop())},teardown:function(){a(this).unbind("submit",a.event.special.invalid.handler).data("invalidEventShim",false)},handler:function(b){if(!(b.type!="submit"||!a.nodeName(b.target,"form")||a.attr(b.target,
"novalidate")!==undefined))if(!a(b.target).checkValidity()){!b.originalEvent&&!window.debugValidityShim&&window.console&&console.log&&console.log("submit");b.stopImmediatePropagation();return false}}};a.webshims.attr("validity",{elementNames:["input","select","textarea"],getter:function(b){var c=a.data(b,"cachedValidity");if(c)return c;c=a.extend({},g);if(!a.attr(b,"willValidate"))return c;var d=a(b),k=d.val(),e={};c.customError=!!a.data(b,"customvalidationMessage");if(c.customError)c.valid=false;
if((b.nodeName||"").toLowerCase()=="select")return c;a.each(f,function(j,l){if(l(d,k,e)){c[j]=true;c.valid=false}});return c}});a.webshims.addMethod("setCustomValidity",function(b){a.data(this,"customvalidationMessage",""+b)});a.webshims.attr("validationMessage",{elementNames:["input","select","textarea"],getter:function(b,c){var d=c()||a.data(b,"customvalidationMessage");return!d||!a.attr(b,"willValidate")?"":d}});a.webshims.createBooleanAttrs("required",["input","textarea"]);a.webshims.attr("willValidate",
{elementNames:["input","select","textarea"],getter:function(){var b={button:1,reset:1,add:1,remove:1,"move-up":1,"move-down":1,hidden:1,submit:1};return function(c){return!!(c.name&&c.form&&!c.disabled&&!c.readonly&&!b[c.type]&&a.attr(c.form,"novalidate")===undefined)}}()});a.webshims.attr("type",{elementNames:["input"],getter:function(b){var c=(b.getAttribute("type")||"").toLowerCase();return i[c]?c:b.type||b.getAttribute("type")},setter:true});a.webshims.addInputType("email",{mismatch:function(){var b=
/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|(\x22((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?\x22))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)*(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i;
return function(c){return!b.test(c)}}()});a.webshims.addInputType("url",{mismatch:function(){var b=/^([a-z]([a-z]|\d|\+|-|\.)*):(\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?((\[(|(v[\da-f]{1,}\.(([a-z]|\d|-|\.|_|~)|[!\$&'\(\)\*\+,;=]|:)+))\])|((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=])*)(:\d*)?)(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*|(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)|((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)|((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)){0})(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
return function(c){return!b.test(c)}}()});a.webshims.addReady(function(b){a("form",b).bind("invalid",a.noop)})}})(jQuery);
(function(a){if(a.support.validity!==true){a.support.validity="shim";a.support.fieldsetValidation="shim";var h={input:1,textarea:1},i={radio:1,checkbox:1,submit:1,button:1,image:1,reset:1,color:1,range:1},g=function(f){var b;f[0].getAttribute("type");var c=f.val(),d=function(e){if(f){var j=f.val();if(j!==c){c=j;if(!e||e.type!="input")f.trigger("input")}}},k=function(){f.unbind("focusout",k).unbind("input",d);clearInterval(b);d();f=null};clearInterval(b);b=setInterval(d,150);setTimeout(d,9);f.bind("focusout",
k).bind("input",d)};a(document).bind("focusin",function(f){if(f.target&&f.target.type&&!f.target.readonly&&!f.target.readOnly&&!f.target.disabled&&h[(f.target.nodeName||"").toLowerCase()]&&!i[f.target.type])g(a(f.target))})}})(jQuery);
(function(a){var h,i,g;a.support.validity===true&&document.addEventListener&&!window.noHTMLExtFixes&&window.opera&&document.addEventListener("submit",function(b){b.target.checkValidity&&b.target.checkValidity()},true);a(document).bind("invalid",function(b){if(!h){g=b.target.form;if(a.support.validity===true&&g&&!window.noHTMLExtFixes){var c=a(g).bind("submit.preventInvalidSubmit",function(d){if(a.attr(g,"novalidate")===undefined){d.stopImmediatePropagation();return false}}).data("events").submit;
c&&c.length>1&&c.unshift(c.pop())}h=a.Event("firstinvalid");a(b.target).trigger(h)}h&&h.isDefaultPrevented()&&b.preventDefault();clearTimeout(i);i=setTimeout(function(){h=false;a(g).unbind("submit.preventInvalidSubmit")},9)});var f=function(){this._create()};f.prototype={_create:function(){this.alert=a('<div class="validity-alert"><div class="va-box" /></div>').css({position:"absolute",display:"none"});this.hideTimer=false;this.boundHide=a.proxy(this,"hide")},hideDelay:5E3,createAlert:function(){if(!this.created){this.created=
true;var b=this;a(function(){b.alert.appendTo("body")})}},showFor:function(b,c){b=a(b);var d=b.data("inputUIReplace");if(d)b=d.visual;this.createAlert();this.clear();this.getMessage(b);this.position(b);this.show();c||b.focus();this.hideTimer=setTimeout(this.boundHide,this.hideDelay);a(document).bind("focusout.validityalert",this.boundHide)},getMessage:function(b){a("> div",this.alert).html(b.attr("validationMessage"))},position:function(b){var c=b.offset();c.top+=b.outerHeight();this.alert.css(c)},
clear:function(){clearTimeout(this.hideTimer);a(document).unbind("focusout.validityalert");this.alert.stop().css({opacity:""})},show:function(){this.alert.fadeIn()},hide:function(){this.clear();this.alert.fadeOut()}};a.webshims.validityAlert=new f})(jQuery);
(function(a){if(!a.support.validationMessage){a.support.validationMessage="shim";a.webshims.validityMessages=[];a.webshims.validityMessages[""]={typeMismatch:{email:"{%value} is not a legal email address",url:"{%value} is not a valid web address",number:"{%value} is not a number!",date:"{%value} is not a date",time:"{%value} is not a time",range:"{%value} is not a number!","datetime-local":"{%value} is not a correct date-time format."},rangeUnderflow:"{%value} is too low. The lowest value you can use is {%min}.",
rangeOverflow:"{%value}  is too high. The highest value you can use is {%max}.",stepMismatch:"The value {%value} is not allowed for this form. Only certain values are allowed for this field. {%title}",tooLong:"The entered text is too large! You used {%valueLen} letters and the limit is {%maxlength}.",patternMismatch:"{%value} is not in the format this page requires! {%title}",valueMissing:"You have to specify a value"};a.webshims.validityMessages.de={typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",
url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",
tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",valueMissing:"Sie m\u00fcssen einen Wert eingeben"};var h;a(document).bind("htmlExtLangChange",function(){a.webshims.activeLang(a.webshims.validityMessages,"validation-base",function(i){h=i})});a.webshims.attr("validationMessage",{elementNames:["input","select","textarea"],getter:function(i){var g=
"";if(!a.attr(i,"willValidate"))return g;if(g="validationMessage"in i?i.validationMessage:a.data(i,"customvalidationMessage"))return g;var f=a.attr(i,"validity")||{valid:1};if(f.valid)return"";a.each(f,function(b,c){if(!(b=="valid"||!c)){if((g=h[b])&&typeof g!=="string")g=g[(i.getAttribute("type")||"").toLowerCase()]||g.defaultMessage;if(g)return false}});g&&a.each(["value","min","max","title","maxlength"],function(b,c){if(g.indexOf("%"+c)!==-1){var d=a.attr(i,c)||"";g=g.replace("{%"+c+"}",d);if("value"==
c)g=g.replace("{%valueLen}",d.length)}});return g||""}})}})(jQuery);(function(a){if(!(a.support.validity!==true||a.support.fieldsetValidation||window.noHTMLExtFixes)){a.support.fieldsetValidation="shim";a.webshims.addMethod("checkValidity",function(){if(a.nodeName(this,"fieldset")){var h=true;a(this.elements||"input, textarea, select",this).each(function(){if(this.checkValidity)this.checkValidity()||(h=false)});return h}else if(this.checkValidity)return this.checkValidity()})}})(jQuery);
(function(a){if(!a.support.placeholder){a.support.placeholder="shim";var h=function(){var f=function(e){if(!this.value||e===true){a(this).addClass("placeholder-visible");this.value=this.getAttribute("placeholder")||""}},b=function(){if(a(this).hasClass("placeholder-visible")){this.value="";a(this).removeClass("placeholder-visible")}},c=0,d=/\n|\r|\f|\t/g,k={text:1,search:1,url:1,email:1,password:1,tel:1};return{create:function(e){if(!a.data(e,"placeHolder")){var j=function(){b.apply(e)};c++;a.data(e,
"placeHolder",c);a(e).bind("blur",f).bind("focus",b);a(window).bind("unload.id-"+c,j);a(e.form).bind("submit.id-"+c,j)}},changesValidity:function(e,j){if(a.support.validity===true&&a.attr(e,"willValidate")){if(a.attr(e,"required"))return true;var l=a.attr(e,"value");a.attr(e,"value",j);a.attr(e,"validity");a.attr(e,"value",l)}return false},update:function(e,j){var l=a.attr(e,"type");if(k[l]||a.nodeName(e,"textarea"))if(j){l=a(e);j=j.replace(d,"");e.setAttribute("placeholder",j);if(h.changesValidity(e,
j))h.destroy(e);else{h.create(e);l.val()||f.call(e,true)}}else{h.destroy(e);e.removeAttribute("placeholder")}},destroy:function(e){var j=a.data(e,"placeHolder");if(j){a.data(e,"placeHolder",false);a(e).unbind("blur",f).unbind("focus",b);a(window).unbind("unload.id-"+j);a(e.form).unbind("submit.id-"+j);b.apply(this)}}}}();a.webshims.attr("placeholder",{elementNames:["input","textarea"],setter:function(f,b){h.update(f,b)},getter:function(f){return f.getAttribute("placeholder")}});var i={elementNames:["input",
"textarea"],setter:function(f,b,c){var d=f.getAttribute("placeholder");if(d&&"value"in f)b?a(f).removeClass("placeholder-visible"):h.update(f,d);c()},getter:function(f,b){if(a(f).hasClass("placeholder-visible"))return"";return b()}};a.webshims.attr("value",i);var g=a.fn.val;a.fn.val=function(f){if(f===undefined){if(this[0]&&a(this[0]).hasClass("placeholder-visible"))return"";return g.apply(this,arguments)}else{var b=g.apply(this,arguments);this.each(function(){this.nodeType===1&&this.getAttribute("placeholder")&&
i.setter(this,f,a.noop)});return b}};a.webshims.addReady(function(f){a("input[placeholder], textarea[placeholder]",f).attr("placeholder",function(b,c){return c})})}})(jQuery);
