jQuery.webshims.ready("es5",function(d,k,z,q,n){var r=d.support,u=k.modules,s=Object.prototype.hasOwnProperty,y=d.attr,p={},o={};d.attr=function(c,b,a,f,g){var i=(c.nodeName||"").toLowerCase();if(!i||c.nodeType!==1)return y(c,b,a,f,g);var j=p[i],h,l,m;if(j)j=j[b];if(!j)if(j=p["*"])j=j[b];if(j){m=d.data(c,"_polyfillblockProperty")||d.data(c,"_polyfillblockProperty",{get:{},set:{},contentInit:{}});if(a===n){if(m.get[b])return;m.get[b]=true;l=j.get?j.get.call(c):j.value;m.get[b]=false;return l}else if(j.set){if(m.set[b])return;
m.set[b]=true;if(c.readyState==="loading"&&!m.contentInit&&!m.get[b]&&j.get&&a===k.contentAttr(c,b)){m.contentInit=true;a=j.get.call(c)}l=j.set.call(c,a);h=true;m.set[b]=false}}h||(l=y(c,b,a,f,g));a!==n&&o[i]&&o[i][b]&&d.each(o[i][b],function(t,x){x.call(c,a)});return l};var w=function(c,b,a){p[c]||(p[c]={});var f=p[c][b],g=function(i,j,h){if(j&&j[i])return j[i];if(h&&h[i])return h[i];return function(l){return y(this,b,l)}};p[c][b]=a;if(a.value===n){if(!a.set)a.set=a.writeable?g("set",a,f):function(){throw b+
"is readonly on "+c;};if(!a.get)a.get=g("get",a,f)}d.each(["value","get","set"],function(i,j){if(a[j])a["_sup"+j]=g(j,f)})};(function(){var c=q.createElement("span"),b=c.style,a={},f=function(g){g.props.forEach(function(i){if(!a[i]){a[i]=true;b.behavior+=", "+i;if(g.feature&&c.readyState!="complete"){k.waitReady(g.feature);d(c).one("readystatechange",function(){k.unwaitReady(g.feature)})}}})};k.preloadHTCs.forEach(f);k.preloadHTCs={push:f}})();var v=function(){var c={},b={},a;k.addReady(function(j,
h){var l=function(m){if(!c[m]){c[m]=d(j.getElementsByTagName(m));if(h[0]&&d.nodeName(h[0],m))c[m]=c[m].add(h)}};c={};d.each(b,function(m,t){l(m);t.forEach(function(x){c[m].each(x)})});a=true});var f=function(j,h){if(b[j])b[j].push(h);else b[j]=[h];if(a){c[j]=c[j]||d(q.getElementsByTagName(j));c[j].each(h)}},g={},i={};return{extend:function(j,h,l){g[h]||(g[h]=0);g[h]++;f(j,function(){e(this,h,l,"_sup"+h+g[h]);k.defineProperty(this,h,l)})},extendDHTML:function(j,h,l,m){k.preloadHTCs.push({feature:m,
props:[h]});i[j]||(i[j]="");if(i[j].indexOf(h)==-1){i[j]+=h;f(j,function(){this.style.behavior+=this.style.behavior?", "+h:h})}},init:function(j,h,l){f(j,function(){var m=d(this);if(l!=="all")m=m.filter("["+h+"]");m.attr(h,function(t,x){return x})})}}}(),e=function(c,b,a,f){var g,i=function(j,h){if(j&&j[h])return j[h];if(j.value!==n){if(h=="set")return f?function(l){d.data(c,f).value=l}:function(l){j.value=l};if(h=="get")return f?function(){return d.data(c,f).value}:function(){return j.value}}return function(l){return k.contentAttr(this,
b,l)}};if(c&&b){for(;c&&b in c&&!s.call(c,b);)c=k.getPrototypeOf(c);g=k.getOwnPropertyDescriptor(c,b)||{configurable:true};if(!g.configurable&&!g.writeable)return false;f&&d.data(c,f,g);if(a.get)a._supget=i(g,"get");if(a.set)a._supset=i(g,"set");if(a.value||g.value!==n)a._supvalue=g.value}if(a.value===n){if(!a.set)a.set=a._supset||!a.writeable?function(){throw b+"is readonly on "+this.nodeName;}:i(a,"set");if(!a.get)a.get=a._supget||i(a,"get")}return true};d.extend(k,{defineNodeNameProperty:function(c,
b,a,f,g,i){a=d.extend({writeable:true},a);var j,h=false,l;k.cfg.extendNative&&f&&function(){var m=q.createElement(c);if(r.objectAccessor&&r.contentAttr){var t=k.getPrototypeOf(m);if(b in m)if(s.call(m,b)){j=k.getOwnPropertyDescriptor(m,b);if(j.configurable){v.extend(c,b,a);h=true}}else{if(e(t,b,a)){k.defineProperty(t,b,a);h=true}}else{e(false,false,a);k.defineProperty(t,b,a);h=true}}else if(a.value!==n){v.extend(c,b,a);h=true}else if(g&&r.dhtmlBehavior&&!(b in m)){l=h=true;w(c,b,a);v.extendDHTML(c,
"url("+k.loader.makePath("htc/"+(typeof g=="string"?g:b)+".htc")+")",b,i)}}();if(!h){f&&k.cfg.extendNative&&k.log("could not extend "+c+"["+b+"] fallback to jQuery extend");w(c,b,a)}if(a.contentAttr&&!l||a.init)v.init(c,b);return a},defineNodeNamesProperty:function(c,b,a,f,g,i){if(typeof c=="string")c=c.split(/\s*,\s*/);c.forEach(function(j){k.defineNodeNameProperty(j,b,a,f,g,i)})},onNodeNamesPropertyModify:function(c,b,a){if(typeof c=="string")c=c.split(/\s*,\s*/);if(d.isFunction(a))a={set:a};c.forEach(function(f){o[f]||
(o[f]={});o[f][b]||(o[f][b]=[]);a.set&&o[f][b].push(a.set);a.init&&v.init(f,b)})},defineNodeNamesBooleanProperty:function(c,b,a,f,g,i){k.defineNodeNamesProperty(c,b,{set:function(j){j=this.readyState==="loading"&&typeof j=="string"&&j===k.contentAttr(this,b)?true:!!j;k.contentAttr(this,b,j);a&&a.set.call(this,j);return j},get:function(){return k.contentAttr(this,b)!=null}},f,g,i)},contentAttr:function(c,b,a){if(c.nodeName){if(a===n){a=(c.attributes[b]||{}).value;return a==null?n:a}if(typeof a=="boolean")a?
c.setAttribute(b,b):c.removeAttribute(b);else c.setAttribute(b,a)}},activeLang:function(){var c=[navigator.browserLanguage||navigator.language||""],b=d("html").attr("lang"),a;b&&c.push(b);return function(f,g,i){if(f)if(!g||!i){if(f!==c[0]){c[0]=f;clearTimeout(a);a=setTimeout(function(){d(q).triggerHandler("webshimLocalizationReady",c)},0)}}else{var j=(g=u[g].options)&&g.availabeLangs,h=function(l){if(d.inArray(l,j)!==-1){k.loader.loadScript(g.langSrc+l+".js",function(){f[l]&&i(f[l])});return true}return false};
d.each(c,function(l,m){var t=m.split("-")[0];if(f[m]||f[t]){i(f[m]||f[t]);return false}if(j&&g.langSrc&&(h(m)||h(t)))return false})}return c}}()});k.isReady("webshimLocalization",true);k.isReady("dom-extend",true)});jQuery.webshims.gcEval=function(d,k){return function(z){eval(z)}.call(k||window,d)};
jQuery.webshims.ready("dom-extend",function(d,k,z,q,n){k.getVisualInput=function(a){a=d(a);return(a.data("inputUIReplace")||{visual:a}).visual};var r=d.support,u=k.getVisualInput,s={checkbox:1,radio:1},y=d([]),p=function(a){a=d(a);return s[a[0].type]&&a[0].name?d(q.getElementsByName(a[0].name)).not(a[0]):y},o={number:1,range:1,date:1,time:1,"datetime-local":1,datetime:1,month:1,week:1};d.extend(d.expr.filters,{"valid-element":function(a){return!!(d.attr(a,"willValidate")&&(d.attr(a,"validity")||{valid:true}).valid)},
"invalid-element":function(a){return!!(d.attr(a,"willValidate")&&!w(a))},"required-element":function(a){return!!(d.attr(a,"willValidate")&&d.attr(a,"required")===true)},"optional-element":function(a){return!!(d.attr(a,"willValidate")&&d.attr(a,"required")===false)},"in-range":function(a){if(!o[d.attr(a,"type")]||!d.attr(a,"willValidate"))return false;a=d.attr(a,"validity");return!!(a&&!a.rangeOverflow&&!a.rangeUnderflow)},"out-of-range":function(a){if(!o[d.attr(a,"type")]||!d.attr(a,"willValidate"))return false;
a=d.attr(a,"validity");return!!(a&&(a.rangeOverflow||a.rangeUnderflow))}});["valid","invalid","required","optional"].forEach(function(a){d.expr.filters[a]=d.expr.filters[a+"-element"]});var w=function(a){return(d.attr(a,"validity")||{valid:true}).valid},v=d.attr,e={selectedIndex:1,value:1,checked:1,disabled:1,readonly:1},c;d.attr=function(a,f,g){if(a.form&&e[f]&&g!==n&&d(a).hasClass("form-ui-invalid")){var i=v.apply(this,arguments);if(w(a)){u(a).removeClass("form-ui-invalid");f=="checked"&&g&&p(a).removeClass("form-ui-invalid").removeAttr("aria-invalid")}return i}return v.apply(this,
arguments)};d(document).bind("focusout change refreshValidityStyle",function(a){if(!(c||!a.target||!a.target.form||a.target.type=="submit")){var f=d.attr(a.target,"html5element")||a.target;if(d.attr(f,"willValidate")){var g,i;if(w(a.target)){g="form-ui-valid";i="form-ui-invalid";s[a.target.type]&&a.target.checked&&p(f).removeClass(i).removeAttr("aria-invalid")}else{g="form-ui-invalid";i="form-ui-valid";s[a.target.type]&&!a.target.checked&&p(f).removeClass(i)}u(f).addClass(g).removeClass(i);c=true;
setTimeout(function(){c=false},9)}else u(f).removeClass("form-ui-invalid form-ui-valid")}});k.triggerInlineForm=function(){var a=function(f){if(typeof f!="string"||f.indexOf("-")!==-1||f.indexOf(".")!==-1||f.indexOf('"')!==-1)return"";return"var "+f+' = this.form["'+f+'"];'};return function(f,g){var i=f["on"+g]||f.getAttribute("on"+g)||"",j;g=d.Event({type:g,target:f[0],currentTarget:f[0]});if(i&&typeof i=="string"&&f.form&&f.form.elements){j="";for(var h=0,l=f.form.elements,m=l.length;h<m;h++){var t=
l[h].name,x=l[h].id;if(t)j+=a(t);if(x&&x!==t)j+=a(x)}j=k.gcEval(j+i,f)}if(j===false){g.stopPropagation();g.preventDefault()}d(f).trigger(g);return j}}();var b=function(){k.scrollRoot=d.browser.webkit||q.compatMode=="BackCompat"?d(q.body):d(q.documentElement)};b();d(b);k.validityAlert=function(){var a=!d.browser.msie||parseInt(d.browser.version,10)>7?"span":"label",f={hideDelay:5E3,showFor:function(m,t,x){m=d(m);var A=u(m);l();f.clear();this.getMessage(m,t);this.position(A);g.css({fontSize:m.css("fontSize"),
fontFamily:m.css("fontFamily")});this.show();if(this.hideDelay)i=setTimeout(j,this.hideDelay);x||this.setFocus(A,m[0])},setFocus:function(m,t){var x=d("input, select, textarea, .ui-slider-handle",m).filter(":visible:first");x[0]||(x=m);var A=k.scrollRoot.scrollTop(),B=x.offset().top,C;g.attr("for",k.getID(x));if(A>B){if((C=t.id&&d('label[for="'+t.id+'"]',t.form).offset())&&C.top<B)B=C.top;k.scrollRoot.animate({scrollTop:B-5},{queue:false,duration:Math.max(Math.min(450,(A-B)*2),140)});C=true}try{x[0].focus()}catch(D){}C&&
k.scrollRoot.scrollTop(A);d(q).bind("focusout.validityalert",j)},getMessage:function(m,t){d("> span.va-box",g).text(t||m.attr("customValidationMessage")||m.attr("validationMessage"))},position:function(m){var t=m.offset();t.top+=m.outerHeight();g.css(t)},show:function(){g.css("display")==="none"?g.fadeIn():g.fadeTo(400,1)},hide:function(){f.clear();g.fadeOut()},clear:function(){clearTimeout(i);d(q).unbind("focusout.validityalert");g.stop().removeAttr("for")},alert:d("<"+a+' class="validity-alert" role="alert"><span class="va-arrow"><span class="va-arrow-box" /></span><span class="va-box" /></'+
a+">").css({position:"absolute",display:"none"})},g=f.alert,i=false,j=d.proxy(f,"hide"),h=false,l=function(){if(!h){h=true;d(function(){g.appendTo("body")})}};return f}();(function(){var a,f=[],g;d(q).bind("invalid",function(i){var j=d(i.target).addClass("form-ui-invalid").removeClass("form-ui-valid");if(!a){a=d.Event("firstinvalid");j.trigger(a)}a&&a.isDefaultPrevented()&&i.preventDefault();f.push(i.target);i.extraData="fix";clearTimeout(g);g=setTimeout(function(){var h={type:"lastinvalid",cancelable:false,
invalidlist:d(f)};a=false;f=[];d(void 0).unbind("submit.preventInvalidSubmit");j.trigger(h,h)},9)})})();(function(){if(!(!r.validity||z.noHTMLExtFixes||r.fieldsetValidation)){var a=function(g){var i=(d.attr(g,"validity")||{valid:true}).valid;!i&&g.checkValidity&&g.checkValidity()&&d(g).trigger("invalid");return i},f=["fieldset"];r.output||(f=["input","textarea","select","form","fieldset"]);k.defineNodeNamesProperty(f,"checkValidity",{value:function(){if(this.elements||d.nodeName(this,"fieldset")){var g=
true;d(this.elements||"input, textarea, select",this).each(function(){a(this)||(g=false)});return g}else if(this.checkValidity)return a(this)}})}})();k.isReady("form-core",true)});
jQuery.webshims.ready("form-core",function(d,k,z,q){var n=k.validityMessages,r=d.support;n.en=n.en||n["en-US"]||{typeMismatch:{email:"{%value} is not a legal email address",url:"{%value} is not a valid web address",number:"{%value} is not a number!",date:"{%value} is not a date",time:"{%value} is not a time",range:"{%value} is not a number!","datetime-local":"{%value} is not a correct date-time format."},rangeUnderflow:"{%value} is too low. The lowest value you can use is {%min}.",rangeOverflow:"{%value}  is too high. The highest value you can use is {%max}.",
stepMismatch:"The value {%value} is not allowed for this form.",tooLong:"The entered text is too large! You used {%valueLen} letters and the limit is {%maxlength}.",patternMismatch:"{%value} is not in the format this page requires! {%title}",valueMissing:"You have to specify a value"};n["en-US"]=n["en-US"]||n.en;n[""]=n[""]||n["en-US"];n.de=n.de||{typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",
date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",
patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",valueMissing:"Sie m\u00fcssen einen Wert eingeben"};var u=n[""];d(q).bind("webshimLocalizationReady",function(){k.activeLang(n,"form-message",function(s){u=s})});k.createValidationMessage=function(s,y){var p=u[y];if(p&&typeof p!=="string")p=p[(s.getAttribute("type")||"").toLowerCase()]||p.defaultMessage;p&&["value","min","max","title","maxlength","label"].forEach(function(o){if(p.indexOf("{%"+o)!==-1){var w=(o=="label"?
d.trim(d('label[for="'+s.id+'"]',s.form).text()).replace(/\*$|:$/,""):d.attr(s,o))||"";p=p.replace("{%"+o+"}",w);if("value"==o)p=p.replace("{%valueLen}",w.length)}});return p||""};q=k.overrideValidationMessages||k.implement.customValidationMessage?["customValidationMessage"]:[];if(!z.noHTMLExtFixes&&!r.validationMessage||!r.validity)q.push("validationMessage");q.forEach(function(s){["input","select","textarea","fieldset","output","button"].forEach(function(y){var p=k.defineNodeNameProperty(y,s,{get:function(){var o=
this,w="";if(!d.attr(o,"willValidate"))return w;var v=d.attr(o,"validity")||{valid:1};if(v.valid)return w;if(w=o.getAttribute("x-moz-errormessage")||o.getAttribute("data-errormessage")||"")return w;if(v.customError&&o.nodeName)if(w=r.validationMessage&&p._supget?p._supget.call(o):d.data(o,"customvalidationMessage"))return w;d.each(v,function(e,c){if(!(e=="valid"||!c))if(w=k.createValidationMessage(o,e))return false});return w||""},set:d.noop},s=="validationMessage","validity-base","form-message")})})});
jQuery.webshims.ready("form-message form-core",function(d,k,z,q,n){var r=d.support;if(r.validity){var u=k.inputTypes,s={};k.addInputType=function(g,i){u[g]=i};k.addValidityRule=function(g,i){s[g]=i};k.addValidityRule("typeMismatch",function(g,i,j,h){if(i==="")return false;h=h.typeMismatch;if(!("type"in j))j.type=(g[0].getAttribute("type")||"").toLowerCase();if(u[j.type]&&u[j.type].mismatch)h=u[j.type].mismatch(i,g);return h});var y=k.overrideValidationMessages,p=!r.requiredSelect||!r.numericDateProps||
y,o=["customError","typeMismatch","rangeUnderflow","rangeOverflow","stepMismatch","tooLong","patternMismatch","valueMissing","valid"],w=d.attr,v=d.fn.val,e=y?{value:1,checked:1}:{value:1},c=y?["textarea"]:[],b={radio:1,checkbox:1},a=function(g,i){if(g.form){var j=(g.getAttribute&&g.getAttribute("type")||g.type||"").toLowerCase();if(!y)if(!(!r.requiredSelect&&j=="select-one")&&!u[j])return;y&&!i&&b[j]&&g.name?d(q.getElementsByName(g.name)).each(function(){d.attr(this,"validity")}):d.attr(g,"validity")}};
k.defineNodeNamesProperty(["input","textarea","select"],"setCustomValidity",{value:function(g){g+="";this.setCustomValidity(g);if(p){d.data(this,"hasCustomError",!!g);a(this)}}});if(!z.noHTMLExtFixes&&!r.requiredSelect||y){d.extend(e,{required:1,size:1,multiple:1,selectedIndex:1});c.push("select")}if(!r.numericDateProps||y){d.extend(e,{min:1,max:1,step:1});c.push("input")}if(!r.requiredSelect){k.defineNodeNamesBooleanProperty(["select"],"required",{set:function(g){this.setAttribute("aria-required",
g?"true":"false")},init:true});k.addValidityRule("valueMissing",function(g,i,j,h){if(j.nodeName=="select"&&!i&&g.attr("required")&&g[0].size<2){if(!j.type)j.type=g[0].type;if(j.type=="select-one"&&d("> option:first-child:not(:disabled)",g).attr("selected"))return true}return h.valueMissing})}if(p){c.forEach(function(g){var i=k.defineNodeNameProperty(g,"validity",{get:function(){var j=this,h=i._supget.call(this);if(!h)return h;var l={};o.forEach(function(D){l[D]=h[D]});if(!d.attr(j,"willValidate"))return l;
var m=d(j),t={type:(j.getAttribute&&j.getAttribute("type")||"").toLowerCase(),nodeName:(j.nodeName||"").toLowerCase()},x=v.call(m),A=!!d.data(j,"hasCustomError"),B;l.customError=A;if(l.valid&&l.customError)l.valid=false;else if(!l.valid){var C=true;d.each(l,function(D,E){if(E)return C=false});if(C)l.valid=true}d.each(s,function(D,E){l[D]=E(m,x,t,l);if(l[D]&&(l.valid||!B&&y)){j.setCustomValidity(k.createValidationMessage(j,D));l.valid=false;B=true}});l.valid&&j.setCustomValidity("");return l},set:d.noop},
true)});d.fn.val=function(){var g=v.apply(this,arguments);this.each(function(){a(this)});return g};d.attr=function(g,i,j){var h=w.apply(this,arguments);e[i]&&j!==n&&g.form&&a(g);return h};if(q.addEventListener){q.addEventListener("change",function(g){a(g.target)},true);r.numericDateProps||q.addEventListener("input",function(g){a(g.target)},true)}var f=c.join(",");k.addReady(function(g,i){d(f,g).add(i.filter(f)).attr("validity")})}k.isReady("form-extend",true)}});
jQuery.webshims.ready("form-extend",function(d,k,z){k.getStep=function(e,c){var b=d.attr(e,"step");if(b==="any")return b;c=c||s(e);if(!n[c]||!n[c].step)return b;b=v.number.asNumber(b);return(!isNaN(b)&&b>0?b:n[c].step)*n[c].stepScaleFactor};k.addMinMaxNumberToCache=function(e,c,b){if(!(e+"AsNumber"in b)){b[e+"AsNumber"]=n[b.type].asNumber(c.attr(e));if(isNaN(b[e+"AsNumber"])&&e+"Default"in n[b.type])b[e+"AsNumber"]=n[b.type][e+"Default"]}};var q=parseInt("NaN",10),n=k.inputTypes,r=function(e){return typeof e==
"number"||e&&e==e*1},u=function(e){return d('<input type="'+e+'" />').attr("type")===e},s=function(e){return(e.getAttribute("type")||"").toLowerCase()},y=k.addMinMaxNumberToCache,p=function(e,c){e=""+e;c-=e.length;for(var b=0;b<c;b++)e="0"+e;return e};k.addValidityRule("stepMismatch",function(e,c,b){if(c==="")return false;if(!("type"in b))b.type=s(e[0]);if(b.type=="date")return false;var a=false;if(n[b.type]&&n[b.type].step){if(!("step"in b))b.step=k.getStep(e[0],b.type);if(b.step=="any")return false;
if(!("valueAsNumber"in b))b.valueAsNumber=n[b.type].asNumber(c);if(isNaN(b.valueAsNumber))return false;y("min",e,b);e=b.minAsNumber;if(isNaN(e))e=n[b.type].stepBase||0;a=Math.abs((b.valueAsNumber-e)%b.step);a=!(a<=1.0E-7||Math.abs(a-b.step)<=1.0E-7)}return a});[{name:"rangeOverflow",attr:"max",factor:1},{name:"rangeUnderflow",attr:"min",factor:-1}].forEach(function(e){k.addValidityRule(e.name,function(c,b,a){var f=false;if(b==="")return f;if(!("type"in a))a.type=s(c[0]);if(n[a.type]&&n[a.type].asNumber){if(!("valueAsNumber"in
a))a.valueAsNumber=n[a.type].asNumber(b);if(isNaN(a.valueAsNumber))return false;y(e.attr,c,a);if(isNaN(a[e.attr+"AsNumber"]))return f;f=a[e.attr+"AsNumber"]*e.factor<a.valueAsNumber*e.factor-1.0E-7}return f})});var o={get:function(){var e=s(this);return n[e]&&n[e].asNumber?n[e].asNumber(d.attr(this,"value")):q},set:function(e){var c=s(this);if(n[c]&&n[c].numberToString)if(isNaN(e))d.attr(this,"value","");else{c=n[c].numberToString(e);if(c!==false)d.attr(this,"value",c);else throw"INVALID_STATE_ERR: DOM Exception 11";
}else o._supset.call(this,arguments)}},w={get:function(){var e=s(this);return n[e]&&n[e].asDate&&!n[e].noAsDate?n[e].asDate(d.attr(this,"value")):w._supget.call(this)},set:function(e){var c=s(this);if(n[c]&&n[c].dateToString){if(!z.noHTMLExtFixes)throw"there are some serious issues in opera's implementation. don't use!";if(e===null){d.attr(this,"value","");return""}c=n[c].dateToString(e);if(c!==false){d.attr(this,"value",c);return c}else throw"INVALID_STATE_ERR: DOM Exception 11";}else return w._supset(this,
arguments)}};k.defineNodeNameProperty("input","valueAsNumber",o,true,"input-date-number","form-number-date");k.defineNodeNameProperty("input","valueAsDate",w,true,"input-date-number","form-number-date");var v={number:{mismatch:function(e){return!r(e)},step:1,stepScaleFactor:1,asNumber:function(e){return r(e)?e*1:q},numberToString:function(e){return r(e)?e:false}},range:{minDefault:0,maxDefault:100},date:{mismatch:function(e){if(!e||!e.split||!/\d$/.test(e))return true;var c=e.split(/\u002D/);if(c.length!==
3)return true;var b=false;d.each(c,function(a,f){if(!(r(f)||f&&f=="0"+f*1)){b=true;return false}});if(b)return b;if(c[0].length!==4||c[1].length!=2||c[1]>12||c[2].length!=2||c[2]>33)b=true;return e!==this.dateToString(this.asDate(e,true))},step:1,stepScaleFactor:864E5,asDate:function(e,c){if(!c&&this.mismatch(e))return null;return new Date(this.asNumber(e,true))},asNumber:function(e,c){var b=q;if(c||!this.mismatch(e)){e=e.split(/\u002D/);b=Date.UTC(e[0],e[1]-1,e[2])}return b},numberToString:function(e){return r(e)?
this.dateToString(new Date(e*1)):false},dateToString:function(e){return e&&e.getFullYear?e.getUTCFullYear()+"-"+p(e.getUTCMonth()+1,2)+"-"+p(e.getUTCDate(),2):false}},time:{mismatch:function(e,c){if(!e||!e.split||!/\d$/.test(e))return true;e=e.split(/\u003A/);if(e.length<2||e.length>3)return true;var b=false,a;if(e[2]){e[2]=e[2].split(/\u002E/);a=parseInt(e[2][1],10);e[2]=e[2][0]}d.each(e,function(f,g){if(!(r(g)||g&&g=="0"+g*1)||g.length!==2){b=true;return false}});if(b)return true;if(e[0]>23||e[0]<
0||e[1]>59||e[1]<0)return true;if(e[2]&&(e[2]>59||e[2]<0))return true;if(a&&isNaN(a))return true;if(a)if(a<100)a*=100;else if(a<10)a*=10;return c===true?[e,a]:false},step:60,stepBase:0,stepScaleFactor:1E3,asDate:function(e){e=new Date(this.asNumber(e));return isNaN(e)?null:e},asNumber:function(e){var c=q;e=this.mismatch(e,true);if(e!==true){c=Date.UTC("1970",0,1,e[0][0],e[0][1],e[0][2]||0);if(e[1])c+=e[1]}return c},dateToString:function(e){if(e&&e.getUTCHours){var c=p(e.getUTCHours(),2)+":"+p(e.getUTCMinutes(),
2),b=e.getSeconds();if(b!="0")c+=":"+p(b,2);b=e.getUTCMilliseconds();if(b!="0")c+="."+p(b,3);return c}else return false}},"datetime-local":{mismatch:function(e,c){if(!e||!e.split||(e+"special").split(/\u0054/).length!==2)return true;e=e.split(/\u0054/);return n.date.mismatch(e[0])||n.time.mismatch(e[1],c)},noAsDate:true,asDate:function(e){e=new Date(this.asNumber(e));return isNaN(e)?null:e},asNumber:function(e){var c=q,b=this.mismatch(e,true);if(b!==true){e=e.split(/\u0054/)[0].split(/\u002D/);c=
Date.UTC(e[0],e[1]-1,e[2],b[0][0],b[0][1],b[0][2]||0);if(b[1])c+=b[1]}return c},dateToString:function(e,c){return n.date.dateToString(e)+"T"+n.time.dateToString(e,c)}}};u("number")||k.addInputType("number",v.number);u("range")||k.addInputType("range",d.extend({},v.number,v.range));u("date")||k.addInputType("date",v.date);u("time")||k.addInputType("time",d.extend({},v.date,v.time));u("datetime-local")||k.addInputType("datetime-local",d.extend({},v.date,v.time,v["datetime-local"]));k.defineNodeNameProperty("input",
"type",{get:function(){var e=s(this);return k.inputTypes[e]?e:this.type||this.getAttribute("type")},set:d.noop});k.isReady("form-number-date",true)});
jQuery.webshims.ready("form-number-date",function(d,k,z,q){var n=k.triggerInlineForm,r=function(c,b){var a={w:c.width()};if(a.w){var f={mL:parseInt(b.css("marginLeft"),10)||0,w:b.outerWidth()};a.mR=parseInt(c.css("marginRight"),10)||0;a.mR&&c.css("marginRight",0);if(f.mL<=f.w*-1){b.css("marginRight",Math.floor(Math.abs(f.w+f.mL)+a.mR));c.css("paddingRight",(parseInt(c.css("paddingRight"),10)||0)+Math.abs(f.mL));c.css("width",Math.floor(a.w+f.mL))}else{b.css("marginRight",a.mR);c.css("width",Math.floor(a.w-
f.mL-f.w))}}},u=d.webshims.modules.inputUI.options,s,y=d([]),p=d.support,o=function(c,b){d("input",c).add(b.filter("input")).each(function(){var a=d.attr(this,"type");o[a]&&!d.data(this,"inputUIReplace")&&o[a](d(this))})};o.common=function(c,b,a){if(u.replaceNative)(function(){var i=[],j;c.bind("firstinvalid",function(h){clearTimeout(j);i.push(h);j=setTimeout(function(){if(!d.data(h.target,"maybePreventedinvalid")&&(!i[0]||!i[0].isDefaultPrevented())&&(!i[1]||!i[1].isDefaultPrevented())){var l=h.target,
m=l.nodeName;if(l.id)m+="#"+l.id;if(l.name)m+='[name="'+l.name+'"]';if(l.className)m+="."+l.className.split(" ").join(".");throw m+" can not be focused. handle the invalid event.";}i=[]},30)})})();else p.validity&&c.bind("firstinvalid",function(i){clearTimeout(s);s=setTimeout(function(){!d.data(i.target,"maybePreventedinvalid")&&!i.isDefaultPrevented()&&k.validityAlert.showFor(i.target)},30)});var f=c.attr("id");f={css:{marginRight:c.css("marginRight"),marginLeft:c.css("marginLeft")},outerWidth:c.outerWidth(),
label:f?d('label[for="'+f+'"]',c[0].form):y};var g=k.getID(f.label);b.addClass(c[0].className).data("html5element",c);c.after(b).data("inputUIReplace",{visual:b,methods:a}).hide();if(b.length==1&&!d("*",b)[0]){b.attr("aria-labeledby",g);f.label.bind("click",function(){b.focus();return false})}return f};if(!p.dateUI||u.replaceNative){var w={trigger:[0.65,0.35],normal:[0.6,0.4]},v=!d.browser.msie||parseInt(d.browser.version,10)>6?0:0.45;o["datetime-local"]=function(c){if(d.fn.datepicker){var b=d('<span role="group" class="input-datetime-local"><input type="text" class="input-datetime-local-date" /><input type="time" class="input-datetime-local-time" /></span>'),
a=this.common(c,b,o["datetime-local"].attrs),f=d("input.input-datetime-local-date",b),g=f.datepicker(d.extend({},u.datepicker,c.data("datepicker"))).bind("change",function(j){var h=f.attr("value"),l=d("input.input-datetime-local-time",b).attr("value");if(h){try{h=(h=d.datepicker.parseDate(f.datepicker("option","dateFormat"),h))?d.datepicker.formatDate("yy-mm-dd",h):f.attr("value")}catch(m){h=f.attr("value")}if(!l){l="00:00";d("input.input-datetime-local-time",b).attr("value",l)}}h=!h&&!l?"":h+"T"+
l;o["datetime-local"].blockAttr=true;c.attr("value",h);o["datetime-local"].blockAttr=false;j.stopImmediatePropagation();n(c[0],"input");n(c[0],"change")}).data("datepicker");g.dpDiv.addClass("input-date-datepicker-control").css({fontSize:f.css("fontSize"),fontFamily:f.css("fontFamily")});d("input.input-datetime-local-time",b).bind("change",function(j){var h=d.attr(this,"value"),l=c.attr("value").split("T");if(h&&(l.length<2||!l[0]))l[0]=d.datepicker.formatDate("yy-mm-dd",new Date);if(l[1]=h)try{f.attr("value",
d.datepicker.formatDate(f.datepicker("option","dateFormat"),d.datepicker.parseDate("yy-mm-dd",l[0])))}catch(m){}l=!l[0]&&!l[1]?"":l.join("T");o["datetime-local"].blockAttr=true;c.attr("value",l);o["datetime-local"].blockAttr=false;j.stopImmediatePropagation();n(c[0],"input");n(c[0],"change")});d("input",b).data("html5element",d.data(b[0],"html5element"));b.attr("aria-labeledby",a.label.attr("id"));a.label.bind("click",function(){f.focus();return false});if(a.css){b.css(a.css);if(a.outerWidth){b.outerWidth(a.outerWidth);
a=b.width();var i=g.trigger[0]?w.trigger:w.normal;f.outerWidth(Math.floor(a*i[0]-v),true);d("input.input-datetime-local-time",b).outerWidth(Math.floor(a*i[1]-v),true);g.trigger[0]&&r(f,g.trigger)}}k.triggerDomUpdate(b[0]);d.each(["disabled","min","max","value","step"],function(j,h){c.attr(h,function(l,m){return m||""})})}};o["datetime-local"].attrs={disabled:function(c,b,a){d("input.input-datetime-local-date",b).datepicker("option","disabled",!!a);d("input.input-datetime-local-time",b).attr("disabled",
!!a)},step:function(c,b,a){d("input.input-datetime-local-time",b).attr("step",a)},min:function(c,b,a){a=a.split?a.split("T"):[];try{a=d.datepicker.parseDate("yy-mm-dd",a[0])}catch(f){a=false}a&&d("input.input-datetime-local-date",b).datepicker("option","minDate",a)},max:function(c,b,a){a=a.split?a.split("T"):[];try{a=d.datepicker.parseDate("yy-mm-dd",a[0])}catch(f){a=false}a&&d("input.input-datetime-local-date",b).datepicker("option","maxDate",a)},value:function(c,b,a){if(!o["datetime-local"].blockAttr){var f;
a=a.split?a.split("T"):[];try{f=d.datepicker.parseDate("yy-mm-dd",a[0])}catch(g){f=false}if(f){d("input.input-datetime-local-date",b).datepicker("setDate",f);d("input.input-datetime-local-time",b).attr("value",a[1]||"00:00")}else{d("input.input-datetime-local-date",b).attr("value",a[0]||"");d("input.input-datetime-local-time",b).attr("value",a[1]||"")}}}};o.date=function(c){if(d.fn.datepicker){var b=d('<input type="text" class="input-date" />'),a=this.common(c,b,o.date.attrs),f=b.datepicker(d.extend({},
u.datepicker,c.data("datepicker"))).bind("change",function(g){o.date.blockAttr=true;var i;try{i=(i=d.datepicker.parseDate(b.datepicker("option","dateFormat"),b.attr("value")))?d.datepicker.formatDate("yy-mm-dd",i):b.attr("value")}catch(j){i=b.attr("value")}c.attr("value",i);o.date.blockAttr=false;g.stopImmediatePropagation();n(c[0],"input");n(c[0],"change")}).data("datepicker");f.dpDiv.addClass("input-date-datepicker-control").css({fontSize:b.css("fontSize"),fontFamily:b.css("fontFamily")});if(a.css){b.css(a.css);
a.outerWidth&&b.outerWidth(a.outerWidth);f.trigger[0]&&r(b,f.trigger)}d.each(["disabled","min","max","value"],function(g,i){c.attr(i,function(j,h){return h||""})})}};o.date.attrs={disabled:function(c,b,a){b.datepicker("option","disabled",!!a)},min:function(c,b,a){try{a=d.datepicker.parseDate("yy-mm-dd",a)}catch(f){a=false}a&&b.datepicker("option","minDate",a)},max:function(c,b,a){try{a=d.datepicker.parseDate("yy-mm-dd",a)}catch(f){a=false}a&&b.datepicker("option","maxDate",a)},value:function(c,b,
a){if(!o.date.blockAttr){try{var f=d.datepicker.parseDate("yy-mm-dd",a)}catch(g){f=false}f?b.datepicker("setDate",f):b.attr("value",a)}}}}if(!p.rangeUI||u.replaceNative){o.range=function(c){if(d.fn.slider){var b=d('<span class="input-range"><span class="ui-slider-handle" role="slider" tabindex="0" /></span>'),a=this.common(c,b,o.range.attrs),f=function(g,i){if(g.originalEvent){o.range.blockAttr=true;c.attr("value",i.value);o.range.blockAttr=false;g.type=="slidechange"?n(c[0],"change"):n(c[0],"input")}};
d("span",b).attr("aria-labeledby",a.label.attr("id"));a.label.bind("click",function(){d("span",b).focus();return false});if(a.css){b.css(a.css);a.outerWidth&&b.outerWidth(a.outerWidth)}b.slider(d.extend({},u.slider,c.data("slider"),{change:f,slide:f}));d.each(["disabled","min","max","value","step"],function(g,i){c.attr(i,function(j,h){return h||""})})}};o.range.attrs={disabled:function(c,b,a){a=!!a;b.slider("option","disabled",a);d("span",b).attr({"aria-disabled":a+"",tabindex:a?"-1":"0"})},min:function(c,
b,a){a=a?a*1||0:0;b.slider("option","min",a);d("span",b).attr({"aria-valuemin":a})},max:function(c,b,a){a=a||a===0?a*1||100:100;b.slider("option","max",a);d("span",b).attr({"aria-valuemax":a})},value:function(c,b,a){a=d(c).attr("valueAsNumber");if(isNaN(a)){a=(b.slider("option","max")-b.slider("option","min"))/2;c.value=a}o.range.blockAttr||b.slider("option","value",a);d("span",b).attr({"aria-valuenow":a,"aria-valuetext":a})},step:function(c,b,a){a=a&&d.trim(a)?a*1||1:1;b.slider("option","step",a)}}}d.each(["disabled",
"min","max","value","step"],function(c,b){k.onNodeNamesPropertyModify("input",b,{set:function(a,f){var g=d.data(a,"inputUIReplace");g&&g.methods[b]&&g.methods[b](a,g.visual,f)}})});var e=function(c){if(c){c=d.extend({},c,u.date);d("input.hasDatepicker").filter(".input-date, .input-datetime-local-date").datepicker("option",c).each(function(){var b=d.data(this,"html5element");b&&d.each(["disabled","min","max","value"],function(a,f){b.attr(f,function(g,i){return i||""})})});d.datepicker.setDefaults(c)}};
d(q).bind("jquery-uiReady.langchange input-widgetsReady.langchange",function(){d.datepicker&&d(q).bind("webshimLocalizationReady",function(){k.activeLang(d.datepicker.regional,"inputUI",e)}).unbind("jquery-uiReady.langchange input-widgetsReady.langchange")});k.addReady(function(c,b){d(q).bind("jquery-uiReady.initinputui input-widgetsReady.initinputui",function(){if(d.datepicker||d.fn.slider)o(c,b);d.datepicker&&d.fn.slider&&d(q).unbind("jquery-uiReady.initinputui input-widgetsReady.initinputui");
c===q&&k.isReady("inputUI",true)})});(function(){if(!(p.numericDateProps||!k.modules["form-number-date"])){var c=k.modules["form-number-date"].options,b=k.inputTypes,a=function(i,j,h){h=h||{};if(!("type"in h))h.type=d.attr(i,"type");if(!("step"in h))h.step=k.getStep(i,h.type);if(!("valueAsNumber"in h))h.valueAsNumber=b[h.type].asNumber(d.attr(i,"value"));var l=h.step=="any"?b[h.type].step*b[h.type].stepScaleFactor:h.step;k.addMinMaxNumberToCache("min",d(i),h);k.addMinMaxNumberToCache("max",d(i),h);
if(isNaN(h.valueAsNumber))h.valueAsNumber=b[h.type].stepBase||0;if(h.step!=="any")if((i=Math.round((h.valueAsNumber-(h.minAsnumber||0))%h.step*1E7)/1E7)&&Math.abs(i)!=h.step)h.valueAsNumber-=i;i=h.valueAsNumber+l*j;if(!isNaN(h.minAsNumber)&&i<h.minAsNumber)i=h.valueAsNumber*j<h.minAsNumber?h.minAsNumber:isNaN(h.maxAsNumber)?Number.MAX_VALUE:h.maxAsNumber;else if(!isNaN(h.maxAsNumber)&&i>h.maxAsNumber)i=h.valueAsNumber*j>h.maxAsNumber?h.maxAsNumber:isNaN(h.minAsNumber)?Number.MIN_VALUE:h.minAsNumber;
return Math.round(i*1E7)/1E7};k.modules["form-number-date"].getNextStep=a;var f=function(i,j,h){if(!(i.disabled||i.readOnly||d(h).hasClass("step-controls"))){d.attr(i,"value",b[j].numberToString(a(i,d(h).hasClass("step-up")?1:-1,{type:j})));d(i).unbind("blur.stepeventshim");n(i,"input");if(q.activeElement){if(q.activeElement!==i)try{i.focus()}catch(l){}setTimeout(function(){if(q.activeElement!==i)try{i.focus()}catch(m){}d(i).one("blur.stepeventshim",function(){n(i,"change")})},0)}}};if(c.stepArrows){k.onNodeNamesPropertyModify("input",
"disabled",{set:function(i){var j=d.data(i,"step-controls");if(j)j[i.disabled||i.readonly?"addClass":"removeClass"]("disabled-step-control")}});k.onNodeNamesPropertyModify("input","readonly",{set:function(i){var j=d.data(i,"step-controls");if(j)j[i.disabled||i.readonly?"addClass":"removeClass"]("disabled-step-control")}})}var g={38:1,40:-1};k.addReady(function(i,j){c.stepArrows&&d("input",i).add(j.filter("input")).each(function(){var h=d.attr(this,"type");if(!(!b[h]||!b[h].asNumber||!c.stepArrows||
c.stepArrows!==true&&!c.stepArrows[h]||d(this).hasClass("has-step-controls"))){var l=this,m=d('<span class="step-controls" unselectable="on"><span class="step-up" /><span class="step-down" /></span>').insertAfter(this).bind("selectstart dragstart",function(){return false}).bind("mousedown mousepress",function(x){f(l,h,x.target);return false}),t=d(this).addClass("has-step-controls").data("step-controls",m).attr({readonly:this.readOnly,disabled:this.disabled,autocomplete:"off",role:"spinbutton"}).bind(d.browser.msie?
"keydown":"keypress",function(x){if(!(this.disabled||this.readOnly||!g[x.keyCode])){d.attr(this,"value",b[h].numberToString(a(this,g[x.keyCode],{type:h})));n(this,"input");return false}});if(c.calculateWidth){r(t,m);m.css("marginTop",(t.outerHeight()-m.outerHeight())/2)}}})})}})()});
