(function(b){if(!b.support.placeholder){b.support.placeholder="shim";var q=function(){var e=function(){if(!this.value){b(this).addClass("placeholder-visible");this.value=this.getAttribute("placeholder")||""}},f=function(){if(b(this).hasClass("placeholder-visible")){this.value="";b(this).removeClass("placeholder-visible")}},m=0,o=/\n|\r|\f|\t/g,i={text:1,search:1,url:1,email:1,password:1,tel:1,url:1};return{create:function(n){var r=b.attr(n,"type");if(!(b.data(n,"placeHolder")||!i[r]&&!b.nodeName("textarea",
n))){r=function(){f.apply(n)};m++;b.data(n,"placeHolder",m);b(n).bind("blur",e).bind("focus",f);b(window).bind("unload.id-"+m,r);b(n.form).bind("submit.id-"+m,r)}},changesValidity:function(n,r){if(b.support.validity===true&&b.attr(n,"willValidate")){if(b.attr(n,"required"))return true;var a=b.attr(n,"value");b.attr(n,"value",r);b.attr(n,"validity");b.attr(n,"value",a)}return false},update:function(n,r){if(r){var a=b(n);r=r.replace(o,"");n.setAttribute("placeholder",r);if(q.changesValidity(n,r))q.destroy(n);
else{q.create(n);if(!a.val()){a.addClass("placeholder-visible");n.value=r}}}else{q.destroy(n);n.removeAttribute("placeholder")}},destroy:function(n){var r=b.data(n,"placeHolder");if(r){b.data(n,"placeHolder",false);b(n).unbind("blur",e).unbind("focus",f);b(window).unbind("unload.id-"+r);b(n.form).unbind("submit.id-"+r);f.apply(this)}}}}();b.htmlExt.attr("placeholder",{elementNames:["input","textarea"],setter:function(e,f){q.update(e,f)},getter:function(e){return e.getAttribute("placeholder")}});var l=
{elementNames:["input","textarea"],setter:function(e,f,m){var o=e.getAttribute("placeholder");if(o&&"value"in e)f?b(e).removeClass("placeholder-visible"):q.update(e,o);m()},getter:function(e,f){if(b(e).hasClass("placeholder-visible"))return"";return f()}};b.htmlExt.attr("value",l);var h=b.fn.val;b.fn.val=function(e){if(e===undefined){if(this[0]&&b(this[0]).hasClass("placeholder-visible"))return"";return h.apply(this,arguments)}else{var f=h.apply(this,arguments);this.each(function(){this.nodeType===
1&&this.getAttribute("placeholder")&&l.setter(this,e,b.noop)});return f}};b.htmlExt.addReady(function(e){b("input[placeholder], textarea[placeholder]",e).attr("placeholder",function(f,m){return m})})}})(jQuery);
(function(b){if(!b.support.validity){var q=parseInt("a",10),l=function(a){return typeof a=="number"||a&&a==a*1},h={radio:1,checkbox:1},e=function(a){return(a.getAttribute("type")||"").toLowerCase()},f=function(a,c){var d=b.attr(a,"step");if(d==="any")return d;c=c||e(a);if(!i[c]||!i[c].step)return d;d=i.number.asNumber(d);return(!isNaN(d)&&d>0?d:i[c].step)*i[c].stepScaleFactor},m=function(a,c,d){if(!(a+"AsNumber"in d)){d[a+"AsNumber"]=i[d.type].asNumber(c.attr(a));if(isNaN(d[a+"AsNumber"])&&a+"Default"in
i[d.type])d[a+"AsNumber"]=i[d.type][a+"Default"]}},o=function(a,c){a=""+a;c-=a.length;for(var d=0;d<c;d++)a="0"+a;return a};(function(){var a={11:"INVALID_STATE_ERR"};return function(c){throw{code:c,name:a[c],message:a[c]+": DOM Exception "+c};}})();var i={};b.htmlExt.addInputType=function(a,c){i[a]=c};var n={customError:false,typeMismatch:false,rangeUnderflow:false,rangeOverflow:false,stepMismatch:false,tooLong:false,patternMismatch:false,valueMissing:false,valid:true},r={valueMissing:function(a,
c){if(!a.attr("required"))return false;return h[a[0].type]?!b(a[0].form&&a[0].name?a[0].form[a[0].name]:[]).filter(":checked")[0]:!c},tooLong:function(a,c){if(c==="")return false;var d=a.attr("maxlength"),k=false,g=c.length;if(g&&d>=0&&c.replace&&l(d)){if(k=g>d)return k;c.replace(/\u0A/g,function(){g++});k=g>d}return k},typeMismatch:function(a,c,d){if(c==="")return false;var k=false;if(!("type"in d))d.type=e(a[0]);if(i[d.type]&&i[d.type].mismatch)k=i[d.type].mismatch(c,a);return k},stepMismatch:function(a,
c,d){if(c==="")return false;if(!("type"in d))d.type=e(a[0]);if(d.type=="date")return false;var k=false;if(i[d.type]&&i[d.type].step){if(!("step"in d))d.step=f(a[0],d.type);if(d.step=="any")return false;if(!("valueAsNumber"in d))d.valueAsNumber=i[d.type].asNumber(c);if(isNaN(d.valueAsNumber))return false;m("min",a,d);a=d.minAsNumber;if(isNaN(a))a=i[d.type].stepBase||0;k=Math.abs((d.valueAsNumber-a)%d.step);k=!(k<=1.0E-7||Math.abs(k-d.step)<=1.0E-7)}return k},patternMismatch:function(a,c){if(c==="")return false;
var d=a.attr("pattern");if(!d)return false;return!RegExp("^(?:"+d+")$").test(c)}};b.each([{name:"rangeOverflow",attr:"max",factor:1},{name:"rangeUnderflow",attr:"min",factor:-1}],function(a,c){r[c.name]=function(d,k,g){var p=false;if(k==="")return p;if(!("type"in g))g.type=e(d[0]);if(i[g.type]&&i[g.type].asNumber){if(!("valueAsNumber"in g))g.valueAsNumber=i[g.type].asNumber(k);if(isNaN(g.valueAsNumber))return false;m(c.attr,d,g);if(isNaN(g[c.attr+"AsNumber"]))return p;p=g[c.attr+"AsNumber"]*c.factor<=
g.valueAsNumber*c.factor-1.0E-7}return p}});b.htmlExt.addMethod("checkValidity",function(){var a,c=function(d){var k,g=b.attr(d,"validity");if(g)b.data(d,"cachedValidity",g);else g={valid:true};if(!g.valid){k=b.Event("invalid");var p=b(d).trigger(k);if(!k.isDefaultPrevented()){a||b.htmlExt.validityAlert.showFor(p);a=true}}b.data(d,"cachedValidity",false);return g.valid};return function(){a=false;if(b.nodeName(this,"form")||b.nodeName(this,"fieldset")){for(var d=true,k=this.elements||b("input, textarea, select",
this),g=0,p=k.length;g<p;g++)c(k[g])||(d=false);return d}else return this.form?c(this):true}}());b.event.special.invalid={add:function(){b.data(this,"invalidEventShim")||b.event.special.invalid.setup.call(this)},setup:function(){b(this).bind("submit",b.event.special.invalid.handler).data("invalidEventShim",true);var a=b(this).data("events").submit;a&&a.length>1&&a.unshift(a.pop())},teardown:function(){b(this).unbind("submit",b.event.special.invalid.handler).data("invalidEventShim",false)},handler:function(a){if(!(a.type!=
"submit"||!b.nodeName(a.target,"form")||b.attr(a.target,"novalidate")))if(!b(a.target).checkValidity()){!a.originalEvent&&!window.debugValidityShim&&window.console&&console.log&&console.log("submit");a.stopImmediatePropagation();return false}}};b.htmlExt.attr("validity",{elementNames:["input","select","textarea"],getter:function(a){var c=b.data(a,"cachedValidity");if(c)return c;c=b.extend({},n);if(!b.attr(a,"willValidate"))return c;var d=b(a),k=d.val(),g={};c.customError=!!b.data(a,"customvalidationMessage");
if(c.customError)c.valid=false;if((a.nodeName||"").toLowerCase()=="select")return c;b.each(r,function(p,j){if(j(d,k,g)){c[p]=true;c.valid=false}});return c}});b.htmlExt.addMethod("setCustomValidity",function(a){b.data(this,"customvalidationMessage",""+a)});b.htmlExt.attr("validationMessage",{elementNames:["input","select","textarea"],getter:function(a,c){var d=c()||b.data(a,"customvalidationMessage");return!d||!b.attr(a,"willValidate")?"":d}});b.htmlExt.createBooleanAttrs("required",["input","textarea"]);
b.htmlExt.attr("willValidate",{elementNames:["input","select","textarea"],getter:function(){var a={button:1,reset:1,add:1,remove:1,"move-up":1,"move-down":1,hidden:1,submit:1};return function(c){return!!(c.name&&c.form&&!c.disabled&&!c.readonly&&!a[c.type]&&!b.attr(c.form,"novalidate"))}}()});b.htmlExt.attr("valueAsNumber",{elementNames:["input"],getter:function(a){var c=e(a);return i[c]&&i[c].asNumber?i[c].asNumber(b.attr(a,"value")):q},setter:function(a,c,d){var k=e(a);if(i[k]&&i[k].numberToString){c=
i[k].numberToString(c);c!==false&&b.attr(a,"value",c)}else d()}});b.htmlExt.attr("valueAsDate",{elementNames:["input"],getter:function(a){var c=e(a);return i[c]&&i[c].asDate&&!i[c].noAsDate?i[c].asDate(b.attr(a,"value")):null},setter:function(a,c,d){var k=e(a);if(i[k]&&i[k].dateToString){c=i[k].dateToString(c);c!==false&&b.attr(a,"value",c)}else d()}});b.htmlExt.attr("type",{elementNames:["input"],getter:function(a){var c=e(a);return i[c]?c:a.type||a.getAttribute("type")},setter:true});b.htmlExt.addInputType("email",
{mismatch:function(){var a=/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|(\x22((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?\x22))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)*(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i;
return function(c){return!a.test(c)}}()});b.htmlExt.addInputType("url",{mismatch:function(){var a=/^([a-z]([a-z]|\d|\+|-|\.)*):(\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?((\[(|(v[\da-f]{1,}\.(([a-z]|\d|-|\.|_|~)|[!\$&'\(\)\*\+,;=]|:)+))\])|((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=])*)(:\d*)?)(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*|(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)|((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)|((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)){0})(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
return function(c){return!a.test(c)}}()});b.htmlExt.addInputType("number",{mismatch:function(a){return!l(a)},step:1,stepScaleFactor:1,asNumber:function(a){return l(a)?a*1:q},numberToString:function(a){return l(a)?a:false}});b.htmlExt.addInputType("range",b.extend({},i.number,{minDefault:0,maxDefault:100}));b.htmlExt.addInputType("date",{mismatch:function(a){if(!a||!a.split||!/\d$/.test(a))return true;var c=a.split(/\u002D/);if(c.length!==3)return true;var d=false;b.each(c,function(k,g){if(!(l(g)||
g&&g=="0"+g*1)){d=true;return false}});if(d)return d;if(c[0].length!==4||c[1].length!=2||c[1]>12||c[2].length!=2||c[2]>33)d=true;return a!==this.dateToString(this.asDate(a,true))},step:1,stepScaleFactor:864E5,asDate:function(a,c){if(!c&&this.mismatch(a))return null;a=a.split(/\u002D/);var d=new Date;d.setUTCMilliseconds(0);d.setUTCSeconds(0);d.setUTCMinutes(0);d.setUTCHours(0);d.setUTCDate(a[2]);d.setUTCMonth(a[1]-1);d.setUTCFullYear(a[0]);return d},asNumber:function(a){a=this.asDate(a);return a===
null?q:a.getTime()},numberToString:function(a){return l(a)?this.dateToString(new Date(a)):false},dateToString:function(a){return a&&a.getUTCFullYear?a.getUTCFullYear()+"-"+o(a.getUTCMonth()+1,2)+"-"+o(a.getUTCDate(),2):false}});b.htmlExt.addInputType("time",b.extend({},i.date,{mismatch:function(a,c){if(!a||!a.split||!/\d$/.test(a))return true;a=a.split(/\u003A/);if(a.length<2||a.length>3)return true;var d=false,k;if(a[2]){a[2]=a[2].split(/\u002E/);k=a[2][1];a[2]=a[2][0]}b.each(a,function(g,p){if(!(l(p)||
p&&p=="0"+p*1)||p.length!==2){d=true;return false}});if(d)return true;if(a[0]>23||a[0]<0||a[1]>59||a[1]<0)return true;if(a[2]&&(a[2]>59||a[2]<0))return true;if(k&&!l(k))return true;return c===true?[a,k]:false},step:60,stepBase:0,stepScaleFactor:1E3,asDate:function(a){a=this.mismatch(a,true);if(a===true)return null;var c=new Date;c.setUTCMilliseconds(a[1]||0);c.setUTCSeconds(a[0][2]||0);c.setUTCMinutes(a[0][1]);c.setUTCHours(a[0][0]);c.setUTCDate("1");c.setUTCMonth(0);c.setUTCFullYear("1970");return c},
dateToString:function(a){if(a&&a.getUTCHours){var c=o(a.getUTCHours(),2)+":"+o(a.getUTCMinutes(),2),d=a.getUTCSeconds();if(d!="0")c+=":"+o(d,2);d=a.getUTCMilliseconds();if(d!="0")c+="."+o(d,3);return c}else return false}}));b.htmlExt.addInputType("datetime-local",b.extend({},i.time,{mismatch:function(a,c){if(!a||!a.split||(a+"special").split(/\u0054/).length!==2)return true;a=a.split(/\u0054/);return i.date.mismatch(a[0])||i.time.mismatch(a[1],c)},noAsDate:true,asDate:function(a){var c=this.mismatch(a,
true);if(c===true)return null;var d=new Date;d.setUTCMilliseconds(c[1]||0);d.setUTCSeconds(c[0][2]||0);d.setUTCMinutes(c[0][1]);d.setUTCHours(c[0][0]);a=a.split(/\u0054/)[0].split(/\u002D/);d.setUTCDate(a[2]);d.setUTCMonth(a[1]-1);d.setUTCFullYear(a[0]);return d},dateToString:function(a,c){return i.date.dateToString(a)+"T"+i.time.dateToString(a,c)}}));(function(){var a=b.htmlExt.loader.modules.validity.options,c=function(g,p,j){j=j||{};if(!("type"in j))j.type=e(g);if(!("step"in j))j.step=f(g,j.type);
if(!("valueAsNumber"in j))j.valueAsNumber=i[j.type].asNumber(b.attr(g,"value"));var s=j.step=="any"?i[j.type].step*i[j.type].stepScaleFactor:j.step;m("min",b(g),j);m("max",b(g),j);if(isNaN(j.valueAsNumber))j.valueAsNumber=i[j.type].stepBase||0;if(j.step!=="any")j.valueAsNumber=Math.round((j.valueAsNumber-(j.valueAsNumber-(j.minAsnumber||0))%j.step)*1E7)/1E7;g=j.valueAsNumber+s*p;if(g<j.minAsNumber)g=j.valueAsNumber>j.minAsNumber?j.minAsNumber:j.maxAsNumber;else if(g>j.maxAsNumber)g=j.valueAsNumber<
j.maxAsNumber?j.maxAsNumber:j.minAsNumber;return g},d=function(g,p,j){if(!(g.disabled||g.readOnly||b(j).hasClass("step-controls"))){b.attr(g,"value",i[p].numberToString(c(g,b(j).hasClass("step-up")?1:-1,{type:p})));b(g).unbind("blur.stepeventshim").trigger("input");if(document.activeElement){if(document.activeElement!==g)try{g.focus()}catch(s){}setTimeout(function(){if(document.activeElement!==g)try{g.focus()}catch(t){}b(g).one("blur.stepeventshim",function(){b(g).trigger("change")})},0)}}};if(a.stepArrows){var k=
{elementNames:["input"],setter:function(g,p,j){j();if(p=b.data(g,"step-controls"))p[g.disabled||g.readonly?"addClass":"removeClass"]("disabled-step-control")}};b.htmlExt.attr("disabled",k);b.htmlExt.attr("readonly",k)}b.htmlExt.addReady(function(g){b("form",g).bind("invalid",b.noop);a.stepArrows&&b("input",g).each(function(){var p=e(this);if(!(!i[p]||!i[p].asNumber||!a.stepArrows||a.stepArrows!==true&&!a.stepArrows[p])){var j=this,s=b(this).css("direction")=="rtl"?{action:"insertBefore",side:"Left",
otherSide:"right"}:{action:"insertAfter",side:"Right",otherSide:"left"},t=b('<span class="step-controls" unselectable><span class="step-up" tabindex="-1" /><span class="step-down" tabindex="-1" /></span>')[s.action](this).bind("mousedown mousepress",function(v){d(j,p,v.target);return false});b(this).addClass("has-step-controls").data("step-controls",t).attr({readonly:this.readOnly,disabled:this.disabled});if(a.recalcWidth){var u=t.outerWidth(true)+(parseInt(b(this).css("padding"+s.side),10)||0),w=
parseInt(b(this).css("border"+s.side+"width"),10)||0;t.css(s.otherSide,(w+u)*-1);u++;b(this).css("width",b(this).width()-u).css("padding"+s.side,u)}}})})})()}})(jQuery);
(function(b){if(b.support.validity!==true){b.support.validity="shim";b.support.fieldsetValidation="shim";var q={input:1,textarea:1},l={radio:1,checkbox:1,submit:1,button:1,image:1,reset:1,color:1,range:1},h=function(e){var f;e[0].getAttribute("type");var m=e.val(),o=function(n){if(e){var r=e.val();if(r!==m){m=r;if(!n||n.type!="input")e.trigger("input")}}},i=function(){e.unbind("focusout",i).unbind("input",o);clearInterval(f);o();e=null};clearInterval(f);f=setInterval(o,150);setTimeout(o,9);e.bind("focusout",
i).bind("input",o)};b(document).bind("focusin",function(e){if(e.target&&e.target.type&&!e.target.readonly&&!e.target.readOnly&&!e.target.disabled&&q[(e.target.nodeName||"").toLowerCase()]&&!l[e.target.type])h(b(e.target))})}})(jQuery);
(function(b){if(!b.support.validationMessage){b.support.validationMessage="shim";b.htmlExt.validityMessages=[];b.htmlExt.validityMessages.de={typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value}  ist keine Nummer!",date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value}  ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",
rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",valueMissing:"Sie m\u00fcssen einen Wert eingeben"};b.htmlExt.validityMessages[""]=
b.htmlExt.validityMessages.de;var q;b(document).bind("htmlExtLangChange",function(){b.htmlExt.activeLang(b.htmlExt.validityMessages,"validation-message",function(l){q=l})});b.htmlExt.attr("validationMessage",{elementNames:["input","select","textarea"],getter:function(l){var h="";if(!b.attr(l,"willValidate"))return h;if(h="validationMessage"in l?l.validationMessage:b.data(l,"customvalidationMessage"))return h;var e=b.attr(l,"validity")||{valid:1};if(e.valid)return"";b.each(e,function(f,m){if(!(f==
"valid"||!m)){if((h=q[f])&&typeof h!=="string")h=h[(l.getAttribute("type")||"").toLowerCase()];if(h)return false}});h&&b.each(["value","min","max","title","maxlength"],function(f,m){var o=b.attr(l,m)||"";h=h.replace("{%"+m+"}",o);if("value"==m)h=h.replace("{%valueLen}",o.length)});return h||""}})}})(jQuery);
(function(b){if(!(b.support.validity!==true||b.support.fieldsetValidation||window.noHTMLExtFixes)){b.support.fieldsetValidation="shim";b.htmlExt.addMethod("checkValidity",function(){if(b.nodeName(this,"fieldset")){var q=true;b(this.elements||"input, textarea, select",this).each(function(){if(this.checkValidity)this.checkValidity()||(q=false)});return q}else if(this.checkValidity)return this.checkValidity()})}})(jQuery);
(function(b){b.support.inputUI="shim";var q=b.htmlExt.loader.modules["input-ui"].options;q.availabeLangs="af ar az bg bs cs da de el en-GB eo es et eu fa fi fo fr fr-CH he hr hu hy id is it ja ko it lt lv ms nl no pl pt-BR ro ru sk sl sq sr sr-SR sv ta th tr uk vi zh-CN zh-HK zh-TW".split(" ");q.juiSrc&&(!b.fn.slider||b.fn.datepicker)?b.htmlExt.loader.loadScript(q.juiSrc,false,"jquery-ui"):b.htmlExt.createReadyEvent("jquery-ui");var l=function(h){b("input",h).each(function(){var e=b.attr(this,"type");
l[e]&&l[e](b(this))})};l.common=function(h,e,f){q.nativeIsReplaced&&h.bind("invalid",function(o){setTimeout(function(){if(!o.isDefaultPrevented())throw"you have to handle invalid events, if you replace native input-widgets.";},0)});var m={css:{marginRight:h.css("marginRight"),marginLeft:h.css("marginLeft")},outerWidth:h.outerWidth()};e.addClass(h[0].className).data("html5element",h);h.after(e).data("inputUIReplace",{visual:e,methods:f}).hide();return m};l.date=function(h){var e=b('<input type="text" class="input-date" />'),
f=this.common(h,e,l.date.attrs);if(f.css){e.css(f.css);f.outerWidth&&e.outerWidth(f.outerWidth)}e.datepicker(b.extend({},q.date,{onSelect:function(){l.date.blockAttr=true;h.attr("value",b.datepicker.formatDate("yy-mm-dd",e.datepicker("getDate")));l.date.blockAttr=false;h.trigger("change")}})).data("datepicker").dpDiv.addClass("input-date-datepicker-control");b.each(["disabled","min","max","value"],function(m,o){h.attr(o,function(i,n){return n||""})})};l.date.attrs={disabled:function(h,e,f){e.datepicker("option",
"disabled",!!f)},min:function(h,e,f){try{f=b.datepicker.parseDate("yy-mm-dd",f)}catch(m){f=false}f&&e.datepicker("option","minDate",f)},max:function(h,e,f){try{f=b.datepicker.parseDate("yy-mm-dd",f)}catch(m){f=false}f&&e.datepicker("option","maxDate",f)},value:function(h,e,f){if(!l.date.blockAttr){try{var m=b.datepicker.parseDate("yy-mm-dd",f)}catch(o){m=false}m?e.datepicker("setDate",m):e.attr("value",f)}}};l.range=function(h){var e=b('<span class="input-range" />'),f=this.common(h,e,l.range.attrs);
if(f.css){e.css(f.css);f.outerWidth&&e.outerWidth(f.outerWidth)}e.slider(b.extend(q.slider,{change:function(m,o){if(m.originalEvent){l.range.blockAttr=true;h.attr("value",o.value);l.range.blockAttr=false;h.trigger("change")}}}));b.each(["disabled","min","max","value","step"],function(m,o){h.attr(o,function(i,n){return n||""})})};l.range.attrs={disabled:function(h,e,f){e.slider("option","disabled",!!f)},min:function(h,e,f){f=f?f*1||0:0;e.slider("option","min",f)},max:function(h,e,f){f=f||f===0?f*1||
100:100;e.slider("option","max",f)},value:function(h,e,f){f=b(h).attr("valueAsNumber");if(isNaN(f)){f=(e.slider("option","max")-e.slider("option","min"))/2;h.value=f}l.range.blockAttr||e.slider("option","value",f)},step:function(h,e,f){f=f?f*1||1:1;e.slider("option","step",f)}};b.each(["disabled","min","max","value","step"],function(h,e){b.htmlExt.attr(e,{elementNames:["input"],setter:function(f,m,o){var i=b.data(f,"inputUIReplace");o();i&&i.methods[e]&&i.methods[e](f,i.visual,m)},getter:true})});
(function(h){var e=function(f){if(f){f=h.extend({},f,q.date);h("input.input-date.hasDatepicker").datepicker("option",f).each(function(){var m=h.data(this,"html5element");m&&h.each(["disabled","min","max","value"],function(o,i){m.attr(i,function(n,r){return r||""})})});h.datepicker.setDefaults(f)}};h(document).one("jquery-uiReady",function(){h(document).bind("htmlExtLangChange",function(){h.htmlExt.activeLang(h.datepicker.regional,"input-ui",e)})})})(jQuery);b.htmlExt.addReady(function(h){b(document).bind("jquery-uiReady",
function(){l(h)})})})(jQuery);
