(function(){var b=Object.prototype.hasOwnProperty,h=Object.prototype.toString;if(!Array.isArray)Array.isArray=function(d){return h.call(d)=="[object Array]"};if(!Object.keys){var z=true,t=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","constructor"],u=t.length;for(var x in{toString:null})z=false;Object.keys=function(d){if(typeof d!=="object"&&typeof d!=="function"||d===null)throw new TypeError("Object.keys called on a non-object");var i=[];for(var j in d)b.call(d,
j)&&i.push(j);if(z)for(j=0;j<u;j++){var r=t[j];b.call(d,r)&&i.push(r)}return i}}var y=true;Object.defineProperty&&Object.prototype.__defineGetter__&&function(){try{var d=document.createElement("foo");Object.defineProperty(d,"bar",{get:function(){return true}});y=!!d.bar}catch(i){y=false}if(!y)jQuery.support.advancedObjectProperties=false}();if((!y||!Object.create||!Object.defineProperties||!Object.getOwnPropertyDescriptor||!Object.defineProperty)&&window.jQuery&&jQuery.webshims){var v=jQuery.webshims;
v.objectCreate=function(d,i,j){var r=function(){};r.prototype=d;d=new r;i&&v.defineProperties(d,i);if(j){d.options=jQuery.extend(true,{},d.options||{},j);j=d.options}d._create&&jQuery.isFunction(d._create)&&d._create(j);return d};v.defineProperties=function(d,i){for(var j in i)b.call(i,j)&&v.defineProperty(d,j,i[j]);return d};var w=["configurable","enumerable","writable"];v.defineProperty=function(d,i,j){if(typeof j!="object")return d;if(Object.defineProperty){for(var r=0;r<3;r++)if(!(w[r]in j)&&
(w[r]!=="writable"||j.value!==undefined))j[w[r]]=true;try{Object.defineProperty(d,i,j);return}catch(e){}}if(b.call(j,"value")){d[i]=j.value;return d}if(d.__defineGetter__){typeof j.get=="function"&&d.__defineGetter__(i,j.get);typeof j.set=="function"&&d.__defineSetter__(i,j.set)}return d};v.getPrototypeOf=function(d){return Object.getPrototypeOf&&Object.getPrototypeOf(d)||d.__proto__||d.constructor&&d.constructor.prototype};v.getOwnPropertyDescriptor=function(d,i){if(typeof d!=="object"&&typeof d!==
"function"||d===null)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object");var j;if(Object.defineProperty&&Object.getOwnPropertyDescriptor)try{return j=Object.getOwnPropertyDescriptor(d,i)}catch(r){}j={configurable:true,enumerable:true,writable:true,value:undefined};var e=d.__lookupGetter__&&d.__lookupGetter__(i),n=d.__lookupSetter__&&d.__lookupSetter__(i);if(!e&&!n){if(!b.call(d,i))return;j.value=d[i];return j}delete j.writable;delete j.value;j.get=j.set=undefined;if(e)j.get=
e;if(n)j.set=n;return j}}if(isNaN(Date.parse("T00:00")))Date=function(d){var i=function(e,n,a,f,c,k,m){var l=arguments.length;if(this instanceof d){l=l===1&&String(e)===e?new d(i.parse(e)):l>=7?new d(e,n,a,f,c,k,m):l>=6?new d(e,n,a,f,c,k):l>=5?new d(e,n,a,f,c):l>=4?new d(e,n,a,f):l>=3?new d(e,n,a):l>=2?new d(e,n):l>=1?new d(e):new d;l.constructor=i;return l}return d.apply(this,arguments)},j=RegExp("^(?:((?:[+-]\\d\\d)?\\d\\d\\d\\d)(?:-(\\d\\d)(?:-(\\d\\d))?)?)?(?:T(\\d\\d):(\\d\\d)(?::(\\d\\d)(?:\\.(\\d\\d\\d))?)?)?(?:Z|([+-])(\\d\\d):(\\d\\d))?$");
for(var r in d)i[r]=d[r];i.now=d.now;i.UTC=d.UTC;i.prototype=d.prototype;i.prototype.constructor=i;i.parse=function(e){var n=j.exec(e);if(n){n.shift();for(var a=n[0]===undefined,f=0;f<10;f++)if(f!==7){n[f]=+(n[f]||(f<3?1:0));f===1&&n[f]--}if(a)return((n[3]*60+n[4])*60+n[5])*1E3+n[6];a=(n[8]*60+n[9])*60*1E3;if(n[6]==="-")a=-a;return d.UTC.apply(this,n.slice(0,7))+a}return d.parse.apply(this,arguments)};return i}(Date);var s=Array.prototype.slice;if(!Function.prototype.bind)Function.prototype.bind=
function(d){var i=this;if(typeof i.apply!="function"||typeof i.call!="function")return new TypeError;var j=s.call(arguments),r=function(){if(this instanceof r){var e=Object.create(i.prototype);i.apply(e,j.concat(s.call(arguments)));return e}else return i.call.apply(i,j.concat(s.call(arguments)))};r.bound=i;r.boundTo=d;r.boundArgs=j;r.length=typeof i=="function"?Math.max(i.length-j.length,0):0;return r}})();
jQuery.webshims.ready("es5",function(b,h,z,t,u){var x=b.support,y=h.modules,v=Object.prototype.hasOwnProperty,w=b.webshims.getPrototypeOf(t.createElement("foobar")),s,d=b.attr,i={},j={};b.attr=function(a,f,c,k,m){var l=(a.nodeName||"").toLowerCase();if(!l||a.nodeType!==1)return d(a,f,c,k,m);var g=i[l],o,q,p;if(g)g=g[f];if(!g)if(g=i["*"])g=g[f];if(g){p=b.data(a,"_polyfillblockProperty")||b.data(a,"_polyfillblockProperty",{get:{},set:{},contentInit:{}});if(c===u){if(p.get[f])return;p.get[f]=true;q=
g.get?g.get.call(a):g.value;p.get[f]=false;return q}else if(g.set){if(p.set[f])return;p.set[f]=true;if(a.readyState==="loading"&&!p.contentInit&&!p.get[f]&&g.get&&c===h.contentAttr(a,f)){p.contentInit=true;c=g.get.call(a)}q=g.set.call(a,c);o=true;p.set[f]=false}}o||(q=d(a,f,c,k,m));c!==u&&j[l]&&j[l][f]&&b.each(j[l][f],function(A,B){B.call(a,c)});return q};var r=function(a,f,c){i[a]||(i[a]={});var k=i[a][f],m=function(l,g,o){if(g&&g[l])return g[l];if(o&&o[l])return o[l];return function(q){return d(this,
f,q)}};i[a][f]=c;if(c.value===u){if(!c.set)c.set=c.writeable?m("set",c,k):function(){throw f+"is readonly on "+a;};if(!c.get)c.get=m("get",c,k)}b.each(["value","get","set"],function(l,g){if(c[g])c["_sup"+g]=m(g,k)})};(function(){var a=t.createElement("span"),f=a.style,c={};h.preloadHTCs={push:function(k){k.props.forEach(function(m){if(!c[m]){c[m]=true;f.behavior+=", "+m;if(k.feature&&a.readyState!="complete"){h.waitReady(k.feature);b(a).one("readystatechange",function(){h.unwaitReady(k.feature)})}}})}}})();
var e=function(){var a={},f={},c;h.addReady(function(g,o){var q=function(p){if(!a[p]){a[p]=b(g.getElementsByTagName(p));if(o[0]&&b.nodeName(o[0],p))a[p]=a[p].add(o)}};a={};b.each(f,function(p,A){q(p);A.forEach(function(B){a[p].each(B)})});c=true});var k=function(g,o){if(f[g])f[g].push(o);else f[g]=[o];if(c){a[g]=a[g]||b(t.getElementsByTagName(g));a[g].each(o)}},m={},l={};return{extend:function(g,o,q){m[o]||(m[o]=0);m[o]++;k(g,function(){n(this,o,q,"_sup"+o+m[o]);h.defineProperty(this,o,q)})},extendDHTML:function(g,
o,q,p){h.preloadHTCs.push({feature:p,props:[o]});l[g]||(l[g]="");if(l[g].indexOf(o)==-1){l[g]+=o;k(g,function(){this.style.behavior+=this.style.behavior?", "+o:o})}},init:function(g,o,q){k(g,function(){var p=b(this);if(q!=="all")p=p.filter("["+o+"]");p.attr(o,function(A,B){return B})})}}}(),n=function(a,f,c,k){var m,l=function(g,o){if(g&&g[o])return g[o];if(g.value!==u){if(o=="set")return k?function(q){b.data(a,k).value=q}:function(q){g.value=q};if(o=="get")return k?function(){return b.data(a,k).value}:
function(){return g.value}}return function(q){return h.contentAttr(this,f,q)}};if(a&&f){for(;a&&f in a&&!v.call(a,f);)a=h.getPrototypeOf(a);m=h.getOwnPropertyDescriptor(a,f)||{configurable:true};if(!m.configurable&&!m.writeable)return false;k&&b.data(a,k,m);if(c.get)c._supget=l(m,"get");if(c.set)c._supset=l(m,"set");if(c.value||m.value!==u)c._supvalue=m.value}if(c.value===u){if(!c.set)c.set=c._supset||!c.writeable?function(){throw f+"is readonly on "+this.nodeName;}:l(c,"set");if(!c.get)c.get=c._supget||
l(c,"get")}return true};b.extend(h,{waitReady:function(a){h.waitReadys[a]=h.waitReadys[a]||0;h.waitReadys[a]++},unwaitReady:function(a){h.waitReadys[a]=h.waitReadys[a]||1;h.waitReadys[a]--;h.waitReadys[a+"ReadyCall"]&&!h.waitReadys[a]&&h.isReady(a,true)},defineNodeNameProperty:function(a,f,c,k,m,l){c=b.extend({writeable:true},c);var g,o=false,q;h.cfg.extendNative&&k&&function(){var p=t.createElement(a);if(x.objectAccessor&&x.contentAttr&&w){var A=h.getPrototypeOf(p);if(w===A){e.extend(a,f,c);o=true}else if(f in
p)if(v.call(p,f)){g=h.getOwnPropertyDescriptor(p,f);if(g.configurable){e.extend(a,f,c);o=true}}else{if(n(A,f,c)){h.defineProperty(A,f,c);o=true}}else{n(false,false,c);h.defineProperty(A,f,c);o=true}}else if(c.value!==u){e.extend(a,f,c);o=true}else if(m&&x.dhtmlBehavior&&!(f in p)){q=o=true;r(a,f,c);e.extendDHTML(a,"url("+h.loader.makePath("htc/"+(typeof m=="string"?m:f)+".htc")+")",f,l)}}();if(!o){k&&h.cfg.extendNative&&h.log("could not extend "+a+"["+f+"] fallback to jQuery extend");r(a,f,c)}if(!s&&
h.debug&&k&&h.cfg.extendNative&&m){s=true;b.ajax({url:h.loader.makePath("htc/"+(typeof m=="string"?m:f)+".htc"),complete:function(p){if(p.getResponseHeader){p=p.getResponseHeader("Content-Type")||"";if(p!="text/x-component"){h.warn('content-type of htc-files should be "text/x-component", but was "'+p+'"');h.info("you should also let the client cache htc-files. use a proper expire header for htc-files")}p.indexOf("text/")!==0&&h.warn("Error: content-type of htc-files is not text, this can not work in IE")}}})}if(c.contentAttr&&
!q||c.init)e.init(a,f);return c},defineNodeNamesProperty:function(a,f,c,k,m,l){if(typeof a=="string")a=a.split(/\s*,\s*/);a.forEach(function(g){h.defineNodeNameProperty(g,f,c,k,m,l)})},onNodeNamesPropertyModify:function(a,f,c){if(typeof a=="string")a=a.split(/\s*,\s*/);if(b.isFunction(c))c={set:c};a.forEach(function(k){j[k]||(j[k]={});j[k][f]||(j[k][f]=[]);c.set&&j[k][f].push(c.set);c.init&&e.init(k,f)})},defineNodeNamesBooleanProperty:function(a,f,c,k,m,l){h.defineNodeNamesProperty(a,f,{set:function(g){g=
this.readyState==="loading"&&typeof g=="string"&&g===h.contentAttr(this,f)?true:!!g;h.contentAttr(this,f,g);c&&c.set.call(this,g);return g},get:function(){return h.contentAttr(this,f)!=null}},k,m,l)},contentAttr:function(a,f,c){if(a.nodeName){if(c===u){c=(a.attributes[f]||{}).value;return c==null?u:c}if(typeof c=="boolean")c?a.setAttribute(f,f):a.removeAttribute(f);else a.setAttribute(f,c)}},activeLang:function(){var a=[navigator.browserLanguage||navigator.language||""],f=b("html").attr("lang"),c;
f&&a.push(f);return function(k,m,l){if(k)if(!m||!l){if(k!==a[0]){a[0]=k;clearTimeout(c);c=setTimeout(function(){b(t).triggerHandler("webshimLocalizationReady",a)},0)}}else{var g=(m=y[m].options)&&m.availabeLangs,o=function(q){if(b.inArray(q,g)!==-1){h.loader.loadScript(m.langSrc+q+".js",function(){k[q]&&l(k[q])});return true}return false};b.each(a,function(q,p){var A=p.split("-")[0];if(k[p]||k[A]){l(k[p]||k[A]);return false}if(g&&m.langSrc&&(o(p)||o(A)))return false})}return a}}()});h.isReady("webshimLocalization",
true);h.isReady("dom-extend",true)});jQuery.webshims.gcEval=function(b,h){return function(z){eval(z)}.call(h||window,b)};
jQuery.webshims.ready("es5",function(b,h,z,t,u){h.getVisualInput=function(e){e=b(e);return(e.data("inputUIReplace")||{visual:e}).visual};var x=h.getVisualInput,y={checkbox:1,radio:1},v=b([]),w=function(e){e=b(e);return y[e[0].type]&&e[0].name?b(t.getElementsByName(e[0].name)).not(e[0]):v},s={number:1,range:1,date:1,time:1,"datetime-local":1,datetime:1,month:1,week:1};b.extend(b.expr.filters,{"valid-element":function(e){return!!(b.attr(e,"willValidate")&&(b.attr(e,"validity")||{valid:true}).valid)},
"invalid-element":function(e){return!!(b.attr(e,"willValidate")&&!d(e))},"required-element":function(e){return!!(b.attr(e,"willValidate")&&b.attr(e,"required")===true)},"optional-element":function(e){return!!(b.attr(e,"willValidate")&&b.attr(e,"required")===false)},"in-range":function(e){if(!s[b.attr(e,"type")]||!b.attr(e,"willValidate"))return false;e=b.attr(e,"validity");return!!(e&&!e.rangeOverflow&&!e.rangeUnderflow)},"out-of-range":function(e){if(!s[b.attr(e,"type")]||!b.attr(e,"willValidate"))return false;
e=b.attr(e,"validity");return!!(e&&(e.rangeOverflow||e.rangeUnderflow))}});["valid","invalid","required","optional"].forEach(function(e){b.expr.filters[e]=b.expr.filters[e+"-element"]});var d=function(e){return(b.attr(e,"validity")||{valid:true}).valid},i=b.attr,j={selectedIndex:1,value:1,checked:1,disabled:1,readonly:1},r;b.attr=function(e,n,a){if(e.form&&j[n]&&a!==u&&b(e).hasClass("form-ui-invalid")){var f=i.apply(this,arguments);if(d(e)){x(e).removeClass("form-ui-invalid");n=="checked"&&a&&w(e).removeClass("form-ui-invalid").removeAttr("aria-invalid")}return f}return i.apply(this,
arguments)};b(document).bind("focusout change refreshValidityStyle",function(e){if(!(r||!e.target||!e.target.form||e.target.type=="submit")){var n=b.attr(e.target,"html5element")||e.target;if(b.attr(n,"willValidate")){var a,f;if(d(e.target)){a="form-ui-valid";f="form-ui-invalid";y[e.target.type]&&e.target.checked&&w(n).removeClass(f).removeAttr("aria-invalid")}else{a="form-ui-invalid";f="form-ui-valid";y[e.target.type]&&!e.target.checked&&w(n).removeClass(f)}x(n).addClass(a).removeClass(f);r=true;
setTimeout(function(){r=false},9)}else x(n).removeClass("form-ui-invalid form-ui-valid")}});h.triggerInlineForm=function(){var e=function(n){if(typeof n!="string"||n.indexOf("-")!==-1||n.indexOf(".")!==-1||n.indexOf('"')!==-1)return"";return"var "+n+' = this.form["'+n+'"];'};return function(n,a){var f=n["on"+a]||n.getAttribute("on"+a)||"",c;a=b.Event({type:a,target:n[0],currentTarget:n[0]});if(f&&typeof f=="string"&&n.form&&n.form.elements){c="";for(var k=0,m=n.form.elements,l=m.length;k<l;k++){var g=
m[k].name,o=m[k].id;if(g)c+=e(g);if(o&&o!==g)c+=e(o)}c=h.gcEval(c+f,n)}if(c===false){a.stopPropagation();a.preventDefault()}b(n).trigger(a);return c}}();z=function(){h.scrollRoot=b.browser.webkit||t.compatMode=="BackCompat"?b(t.body):b(t.documentElement)};z();b(z);h.validityAlert=function(){var e=!b.browser.msie||parseInt(b.browser.version,10)>7?"span":"label",n={hideDelay:5E3,showFor:function(l,g,o){l=b(l);var q=x(l);m();n.clear();this.getMessage(l,g);this.position(q);a.css({fontSize:l.css("fontSize"),
fontFamily:l.css("fontFamily")});this.show();if(this.hideDelay)f=setTimeout(c,this.hideDelay);o||this.setFocus(q,l[0])},setFocus:function(l,g){var o=b("input, select, textarea, .ui-slider-handle",l).filter(":visible:first");o[0]||(o=l);var q=h.scrollRoot.scrollTop(),p=o.offset().top,A;a.attr("for",h.getID(o));if(q>p){if((A=g.id&&b('label[for="'+g.id+'"]',g.form).offset())&&A.top<p)p=A.top;h.scrollRoot.animate({scrollTop:p-5},{queue:false,duration:Math.max(Math.min(450,(q-p)*2),140)});A=true}try{o[0].focus()}catch(B){}A&&
h.scrollRoot.scrollTop(q);b(t).bind("focusout.validityalert",c)},getMessage:function(l,g){b("> span.va-box",a).text(g||l.attr("customValidationMessage")||l.attr("validationMessage"))},position:function(l){var g=l.offset();g.top+=l.outerHeight();a.css(g)},show:function(){a.css("display")==="none"?a.fadeIn():a.fadeTo(400,1)},hide:function(){n.clear();a.fadeOut()},clear:function(){clearTimeout(f);b(t).unbind("focusout.validityalert");a.stop().removeAttr("for")},alert:b("<"+e+' class="validity-alert" role="alert"><span class="va-arrow"><span class="va-arrow-box" /></span><span class="va-box" /></'+
e+">").css({position:"absolute",display:"none"})},a=n.alert,f=false,c=b.proxy(n,"hide"),k=false,m=function(){if(!k){k=true;b(function(){a.appendTo("body")})}};return n}();(function(){var e,n=[],a;b(t).bind("invalid",function(f){var c=b(f.target).addClass("form-ui-invalid").removeClass("form-ui-valid");if(!e){e=b.Event("firstinvalid");c.trigger(e)}e&&e.isDefaultPrevented()&&f.preventDefault();n.push(f.target);f.extraData="fix";clearTimeout(a);a=setTimeout(function(){var k={type:"lastinvalid",cancelable:false,
invalidlist:b(n)};e=false;n=[];b(void 0).unbind("submit.preventInvalidSubmit");c.trigger(k,k)},9)})})();h.isReady("form-core",true)});
jQuery.webshims.ready("form-core dom-extend",function(b,h,z,t){var u=h.validityMessages,x=b.support;u.en=u.en||u["en-US"]||{typeMismatch:{email:"{%value} is not a legal email address",url:"{%value} is not a valid web address",number:"{%value} is not a number!",date:"{%value} is not a date",time:"{%value} is not a time",range:"{%value} is not a number!","datetime-local":"{%value} is not a correct date-time format."},rangeUnderflow:"{%value} is too low. The lowest value you can use is {%min}.",rangeOverflow:"{%value}  is too high. The highest value you can use is {%max}.",
stepMismatch:"The value {%value} is not allowed for this form.",tooLong:"The entered text is too large! You used {%valueLen} letters and the limit is {%maxlength}.",patternMismatch:"{%value} is not in the format this page requires! {%title}",valueMissing:"You have to specify a value"};u["en-US"]=u["en-US"]||u.en;u[""]=u[""]||u["en-US"];u.de=u.de||{typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",
date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",
patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",valueMissing:"Sie m\u00fcssen einen Wert eingeben"};var y=u[""];b(t).bind("webshimLocalizationReady",function(){h.activeLang(u,"form-message",function(v){y=v})});h.createValidationMessage=function(v,w){var s=y[w];if(s&&typeof s!=="string")s=s[(v.getAttribute("type")||"").toLowerCase()]||s.defaultMessage;s&&["value","min","max","title","maxlength","label"].forEach(function(d){if(s.indexOf("{%"+d)!==-1){var i=(d=="label"?
b.trim(b('label[for="'+v.id+'"]',v.form).text()).replace(/\*$|:$/,""):b.attr(v,d))||"";s=s.replace("{%"+d+"}",i);if("value"==d)s=s.replace("{%valueLen}",i.length)}});return s||""};t=h.overrideValidationMessages||h.implement.customValidationMessage?["customValidationMessage"]:[];if(!z.noHTMLExtFixes&&!x.validationMessage||!x.validity)t.push("validationMessage");t.forEach(function(v){["input","select","textarea","fieldset","output","button"].forEach(function(w){var s=h.defineNodeNameProperty(w,v,{get:function(){var d=
this,i="";if(!b.attr(d,"willValidate"))return i;var j=b.attr(d,"validity")||{valid:1};if(j.valid)return i;if(i=d.getAttribute("x-moz-errormessage")||d.getAttribute("data-errormessage")||"")return i;if(j.customError&&d.nodeName)if(i=x.validationMessage&&s._supget?s._supget.call(d):b.data(d,"customvalidationMessage"))return i;b.each(j,function(r,e){if(!(r=="valid"||!e))if(i=h.createValidationMessage(d,r))return false});return i||""},set:b.noop},v=="validationMessage","validity-base","form-message")})});
h.isReady("form-message",true)});
jQuery.webshims.ready("form-message form-core",function(b,h,z,t,u){var x=b.support;if(x.validity){var y=h.inputTypes,v={};h.addInputType=function(c,k){y[c]=k};h.addValidityRule=function(c,k){v[c]=k};h.addValidityRule("typeMismatch",function(c,k,m,l){if(k==="")return false;l=l.typeMismatch;if(!("type"in m))m.type=(c[0].getAttribute("type")||"").toLowerCase();if(y[m.type]&&y[m.type].mismatch)l=y[m.type].mismatch(k,c);return l});var w=h.overrideValidationMessages,s=!x.requiredSelect||!x.numericDateProps||
w,d=["customError","typeMismatch","rangeUnderflow","rangeOverflow","stepMismatch","tooLong","patternMismatch","valueMissing","valid"],i=b.attr,j=b.fn.val,r=w?{value:1,checked:1}:{value:1},e=w?["textarea"]:[],n={radio:1,checkbox:1},a=function(c,k){if(c.form){var m=(c.getAttribute&&c.getAttribute("type")||c.type||"").toLowerCase();if(!w)if(!(!x.requiredSelect&&m=="select-one")&&!y[m])return;w&&!k&&n[m]&&c.name?b(t.getElementsByName(c.name)).each(function(){b.attr(this,"validity")}):b.attr(c,"validity")}};
h.defineNodeNamesProperty(["input","textarea","select"],"setCustomValidity",{value:function(c){c+="";this.setCustomValidity(c);if(s){b.data(this,"hasCustomError",!!c);a(this)}}});if(!z.noHTMLExtFixes&&!x.requiredSelect||w){b.extend(r,{required:1,size:1,multiple:1,selectedIndex:1});e.push("select")}if(!x.numericDateProps||w){b.extend(r,{min:1,max:1,step:1});e.push("input")}if(s){e.forEach(function(c){var k=h.defineNodeNameProperty(c,"validity",{get:function(){var m=this,l=k._supget.call(this);if(!l)return l;
var g={};d.forEach(function(C){g[C]=l[C]});if(!b.attr(m,"willValidate"))return g;var o=b(m),q={type:(m.getAttribute&&m.getAttribute("type")||"").toLowerCase(),nodeName:(m.nodeName||"").toLowerCase()},p=j.call(o),A=!!b.data(m,"hasCustomError"),B;g.customError=A;if(g.valid&&g.customError)g.valid=false;else if(!g.valid){var E=true;b.each(g,function(C,D){if(D)return E=false});if(E)g.valid=true}b.each(v,function(C,D){g[C]=D(o,p,q,g);if(g[C]&&(g.valid||!B&&w)){m.setCustomValidity(h.createValidationMessage(m,
C));g.valid=false;B=true}});g.valid&&m.setCustomValidity("");return g},set:b.noop},true)});b.fn.val=function(){var c=j.apply(this,arguments);this.each(function(){a(this)});return c};b.attr=function(c,k,m){var l=i.apply(this,arguments);r[k]&&m!==u&&c.form&&a(c);return l};if(t.addEventListener){t.addEventListener("change",function(c){a(c.target)},true);x.numericDateProps||t.addEventListener("input",function(c){a(c.target)},true)}var f=e.join(",");h.addReady(function(c,k){b(f,c).add(k.filter(f)).attr("validity")})}h.isReady("form-extend",
true)}});
jQuery.webshims.ready("dom-extend",function(b,h,z,t,u){var x=b.support;if(!(!x.validity||z.noHTMLExtFixes)){var y="value"in t.createElement("output")&&"list"in t.createElement("input"),v=[],w;if(z.addEventListener){var s={timer:u,prevented:false};z.addEventListener("submit",function(d){!s.prevented&&d.target.checkValidity&&b.attr(d.target,"novalidate")==null&&b(d.target).checkValidity()},true);t=function(d){if(b.attr(d.target,"formnovalidate")!=null){s.timer&&clearTimeout(s.timer);s.prevented=true;
s.timer=setTimeout(function(){s.prevented=false},20)}};z.addEventListener("click",t,true);z.addEventListener("touchstart",t,true);z.addEventListener("touchend",t,true)}b(document).bind("firstinvalid",function(d){if(w=d.target.form)(d=b(w).unbind("submit.preventInvalidSubmit").bind("submit.preventInvalidSubmit",function(i){if(b.attr(w,"novalidate")==null){i.stopImmediatePropagation();return false}}).data("events").submit)&&d.length>1&&d.unshift(d.pop())}).bind("invalid",function(d){v.indexOf(d.target)==
-1?v.push(d.target):d.stopImmediatePropagation()}).bind("lastinvalid",function(d,i){var j=i.invalidlist[0];j&&!y&&document.activeElement&&j!==document.activeElement&&!b.data(j,"maybePreventedinvalid")&&h.validityAlert.showFor(j);v=[];w&&b(w).unbind("submit.preventInvalidSubmit")});(function(){if(!(!b.browser.webkit||parseInt(b.browser.version,10)>533)){var d=function(i){var j=(b.attr(i,"validity")||{valid:true}).valid;!j&&i.checkValidity&&i.checkValidity()&&b(i).trigger("invalid");return j};h.defineNodeNamesProperty(["input",
"textarea","select","form"],"checkValidity",{value:function(){if(this.elements||b.nodeName(this,"fieldset")){var i=true;b(this.elements||"input, textarea, select",this).each(function(){d(this)||(i=false)});return i}else if(this.checkValidity)return d(this)}})}})();x.requiredSelect||h.ready("form-extend",function(){h.defineNodeNamesBooleanProperty(["select"],"required",{set:function(d){this.setAttribute("aria-required",d?"true":"false")},contentAttr:true},true);h.addValidityRule("valueMissing",function(d,
i,j,r){if(j.nodeName=="select"&&!i&&d.attr("required")&&d[0].size<2){if(!j.type)j.type=d[0].type;if(j.type=="select-one"&&b("> option:first-child:not(:disabled)",d).attr("selected"))return true}return r.valueMissing});h.ready("DOM",function(){b("select[required]").attr("validity")})})}});
