(function(b){var m,p=[],o,e;b.support.validity===true&&document.addEventListener&&!window.noHTMLExtFixes&&window.opera&&document.addEventListener("submit",function(i){i.target.checkValidity&&i.target.checkValidity()},true);b(document).bind("invalid",function(i){if(!m){e=i.target.form;if(b.support.validity===true&&e&&!window.noHTMLExtFixes){var l=b(e).bind("submit.preventInvalidSubmit",function(k){if(b.attr(e,"novalidate")===undefined){k.stopImmediatePropagation();return false}}).data("events").submit;
l&&l.length>1&&l.unshift(l.pop())}m=b.Event("firstinvalid");b(i.target).trigger(m)}m&&m.isDefaultPrevented()&&i.preventDefault();p.push(i.target);clearTimeout(o);o=setTimeout(function(){var k={type:"lastinvalid",cancelable:false,invalidlist:b(p)};m=false;b(e).unbind("submit.preventInvalidSubmit");p=[];b(i.target).trigger(k,k)},9)});var q=function(){this._create()};q.prototype={_create:function(){this.alert=b('<div class="validity-alert" role="alert"><div class="va-box" /></div>').css({position:"absolute",
display:"none"});this.hideTimer=false;this.boundHide=b.proxy(this,"hide")},hideDelay:5E3,createAlert:function(){if(!this.created){this.created=true;var i=this;b(function(){i.alert.appendTo("body")})}},showFor:function(i,l){i=b(i);var k=i.data("inputUIReplace");if(k)i=k.visual;this.createAlert();this.clear();this.getMessage(i);this.position(i);this.show();l||i.focus();this.hideTimer=setTimeout(this.boundHide,this.hideDelay);b(document).bind("focusout.validityalert",this.boundHide)},getMessage:function(i){b("> div",
this.alert).html(i.attr("validationMessage"))},position:function(i){var l=i.offset();l.top+=i.outerHeight();this.alert.css(l)},clear:function(){clearTimeout(this.hideTimer);b(document).unbind("focusout.validityalert");this.alert.stop().css({opacity:""})},show:function(){this.alert.fadeIn()},hide:function(){this.clear();this.alert.fadeOut()}};b.webshims.validityAlert=new q;b.webshims.validityMessages.en=b.webshims.validityMessages.en||b.webshims.validityMessages["en-US"]||{typeMismatch:{email:"{%value} is not a legal email address",
url:"{%value} is not a valid web address",number:"{%value} is not a number!",date:"{%value} is not a date",time:"{%value} is not a time",range:"{%value} is not a number!","datetime-local":"{%value} is not a correct date-time format."},rangeUnderflow:"{%value} is too low. The lowest value you can use is {%min}.",rangeOverflow:"{%value}  is too high. The highest value you can use is {%max}.",stepMismatch:"The value {%value} is not allowed for this form. Only certain values are allowed for this field. {%title}",
tooLong:"The entered text is too large! You used {%valueLen} letters and the limit is {%maxlength}.",patternMismatch:"{%value} is not in the format this page requires! {%title}",valueMissing:"You have to specify a value"};b.webshims.validityMessages["en-US"]=b.webshims.validityMessages["en-US"]||b.webshims.validityMessages.en;b.webshims.validityMessages[""]=b.webshims.validityMessages[""]||b.webshims.validityMessages.en;b.webshims.validityMessages.de=b.webshims.validityMessages.de||{typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",
url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",
tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",valueMissing:"Sie m\u00fcssen einen Wert eingeben"};var n;b(document).bind("htmlExtLangChange",function(){b.webshims.activeLang(b.webshims.validityMessages,"validation-base",function(i){n=i})});b.each(b.support.validationMessage?["customValidationMessage"]:["customValidationMessage","validationMessage"],
function(i,l){b.webshims.attr(l,{elementNames:["input","select","textarea"],getter:function(k){var a="";if(!b.attr(k,"willValidate"))return a;var c=b.attr(k,"validity")||{valid:1};if(c.valid)return a;if(c.customError||l==="validationMessage")if(a="validationMessage"in k?k.validationMessage:b.data(k,"customvalidationMessage"))return a;b.each(c,function(d,h){if(!(d=="valid"||!h)){if((a=n[d])&&typeof a!=="string")a=a[(k.getAttribute("type")||"").toLowerCase()]||a.defaultMessage;if(a)return false}});
a&&b.each(["value","min","max","title","maxlength","label"],function(d,h){if(a.indexOf("%"+h)!==-1){var f=(h=="label"?b.trim(b("label[for="+k.id+"]",k.form).text()).replace(/\*$|:$/,""):b.attr(k,h))||"";a=a.replace("{%"+h+"}",f);if("value"==h)a=a.replace("{%valueLen}",f.length)}});return a||""}})});b.support.validationMessage="shim"})(jQuery);
(function(b){if(!(b.support.validity!==true||b.support.fieldsetValidation||window.noHTMLExtFixes)){b.support.fieldsetValidation="shim";b.webshims.addMethod("checkValidity",function(){if(b.nodeName(this,"fieldset")){var m=true;b(this.elements||"input, textarea, select",this).each(function(){if(this.checkValidity)this.checkValidity()||(m=false)});return m}else if(this.checkValidity)return this.checkValidity()})}})(jQuery);
(function(b){if(!(b.support.validity===true&&(b('<input type="datetime-local" />').attr("type")!=="datetime-local"||b('<input type="range" />').attr("type")!=="range"))){var m=b.webshims.inputTypes;b.webshims.addInputType=function(o,e){m[o]=e};var p={};b.webshims.addValidityRule=function(o,e){p[o]=e}}})(jQuery);
(function(b){var m,p=function(){if(!m){m=true;var o=parseInt("NaN",10),e=b.webshims.inputTypes,q=function(a){return typeof a=="number"||b.trim(a)&&a==a*1},n=function(a){return(a.getAttribute("type")||"").toLowerCase()},i=function(a,c){var d=b.attr(a,"step");if(d==="any")return d;c=c||n(a);if(!e[c]||!e[c].step)return d;d=e.number.asNumber(d);return(!isNaN(d)&&d>0?d:e[c].step)*e[c].stepScaleFactor},l=function(a,c,d){if(!(a+"AsNumber"in d)){d[a+"AsNumber"]=e[d.type].asNumber(c.attr(a));if(isNaN(d[a+
"AsNumber"])&&a+"Default"in e[d.type])d[a+"AsNumber"]=e[d.type][a+"Default"]}},k=function(a,c){a=""+a;c-=a.length;for(var d=0;d<c;d++)a="0"+a;return a};b.webshims.addValidityRule("stepMismatch",function(a,c,d){if(c==="")return false;if(!("type"in d))d.type=n(a[0]);if(d.type=="date")return false;var h=false;if(e[d.type]&&e[d.type].step){if(!("step"in d))d.step=i(a[0],d.type);if(d.step=="any")return false;if(!("valueAsNumber"in d))d.valueAsNumber=e[d.type].asNumber(c);if(isNaN(d.valueAsNumber))return false;
l("min",a,d);a=d.minAsNumber;if(isNaN(a))a=e[d.type].stepBase||0;h=Math.abs((d.valueAsNumber-a)%d.step);h=!(h<=1.0E-7||Math.abs(h-d.step)<=1.0E-7)}return h});b.each([{name:"rangeOverflow",attr:"max",factor:1},{name:"rangeUnderflow",attr:"min",factor:-1}],function(a,c){b.webshims.addValidityRule(c.name,function(d,h,f){var j=false;if(h==="")return j;if(!("type"in f))f.type=n(d[0]);if(e[f.type]&&e[f.type].asNumber){if(!("valueAsNumber"in f))f.valueAsNumber=e[f.type].asNumber(h);if(isNaN(f.valueAsNumber))return false;
l(c.attr,d,f);if(isNaN(f[c.attr+"AsNumber"]))return j;j=f[c.attr+"AsNumber"]*c.factor<=f.valueAsNumber*c.factor-1.0E-7}return j})});b.webshims.attr("valueAsNumber",{elementNames:["input"],getter:function(a){var c=n(a);return e[c]&&e[c].asNumber?e[c].asNumber(b.attr(a,"value")):o},setter:function(a,c,d){var h=n(a);if(e[h]&&e[h].numberToString)if(isNaN(c))b.attr(a,"value","");else{c=e[h].numberToString(c);if(c!==false)b.attr(a,"value",c);else throw"INVALID_STATE_ERR: DOM Exception 11";}else d()}});
b.webshims.attr("valueAsDate",{elementNames:["input"],getter:function(a){var c=n(a);return e[c]&&e[c].asDate&&!e[c].noAsDate?e[c].asDate(b.attr(a,"value")):null},setter:function(a,c,d){var h=n(a);if(e[h]&&e[h].dateToString)if(c===null)b.attr(a,"value","");else{c=e[h].dateToString(c);if(c!==false)b.attr(a,"value",c);else throw"INVALID_STATE_ERR: DOM Exception 11";}else d()}});b.webshims.addInputType("number",{mismatch:function(a){return!q(a)},step:1,stepScaleFactor:1,asNumber:function(a){return q(a)?
a*1:o},numberToString:function(a){return q(a)?a:false}});b.webshims.addInputType("range",b.extend({},e.number,{minDefault:0,maxDefault:100}));b.webshims.addInputType("date",{mismatch:function(a){if(!a||!a.split||!/\d$/.test(a))return true;var c=a.split(/\u002D/);if(c.length!==3)return true;var d=false;b.each(c,function(h,f){if(!(q(f)||f&&f=="0"+f*1)){d=true;return false}});if(d)return d;if(c[0].length!==4||c[1].length!=2||c[1]>12||c[2].length!=2||c[2]>33)d=true;return a!==this.dateToString(this.asDate(a,
true))},step:1,stepScaleFactor:864E5,asDate:function(a,c){if(!c&&this.mismatch(a))return null;return new Date(this.asNumber(a,true))},asNumber:function(a,c){var d=o;if(c||!this.mismatch(a)){a=a.split(/\u002D/);d=Date.UTC(a[0],a[1]-1,a[2])}return d},numberToString:function(a){return q(a)?this.dateToString(new Date(a*1)):false},dateToString:function(a){return a&&a.getFullYear?a.getUTCFullYear()+"-"+k(a.getUTCMonth()+1,2)+"-"+k(a.getUTCDate(),2):false}});b.webshims.addInputType("time",b.extend({},e.date,
{mismatch:function(a,c){if(!a||!a.split||!/\d$/.test(a))return true;a=a.split(/\u003A/);if(a.length<2||a.length>3)return true;var d=false,h;if(a[2]){a[2]=a[2].split(/\u002E/);h=parseInt(a[2][1],10);a[2]=a[2][0]}b.each(a,function(f,j){if(!(q(j)||j&&j=="0"+j*1)||j.length!==2){d=true;return false}});if(d)return true;if(a[0]>23||a[0]<0||a[1]>59||a[1]<0)return true;if(a[2]&&(a[2]>59||a[2]<0))return true;if(h&&isNaN(h))return true;if(h)if(h<100)h*=100;else if(h<10)h*=10;return c===true?[a,h]:false},step:60,
stepBase:0,stepScaleFactor:1E3,asDate:function(a){a=new Date(this.asNumber(a));return isNaN(a)?null:a},asNumber:function(a){var c=o;a=this.mismatch(a,true);if(a!==true){c=Date.UTC("1970",0,1,a[0][0],a[0][1],a[0][2]||0);if(a[1])c+=a[1]}return c},dateToString:function(a){if(a&&a.getUTCHours){var c=k(a.getUTCHours(),2)+":"+k(a.getUTCMinutes(),2),d=a.getSeconds();if(d!="0")c+=":"+k(d,2);d=a.getUTCMilliseconds();if(d!="0")c+="."+k(d,3);return c}else return false}}));b.webshims.addInputType("datetime-local",
b.extend({},e.time,{mismatch:function(a,c){if(!a||!a.split||(a+"special").split(/\u0054/).length!==2)return true;a=a.split(/\u0054/);return e.date.mismatch(a[0])||e.time.mismatch(a[1],c)},noAsDate:true,asDate:function(a){a=new Date(this.asNumber(a));return isNaN(a)?null:a},asNumber:function(a){var c=o,d=this.mismatch(a,true);if(d!==true){a=a.split(/\u0054/)[0].split(/\u002D/);c=Date.UTC(a[0],a[1]-1,a[2],d[0][0],d[0][1],d[0][2]||0);if(d[1])c+=d[1]}return c},dateToString:function(a,c){return e.date.dateToString(a)+
"T"+e.time.dateToString(a,c)}}));(function(){var a=b.webshims.loader.modules["number-date-type"].options,c=function(f,j,g){g=g||{};if(!("type"in g))g.type=n(f);if(!("step"in g))g.step=i(f,g.type);if(!("valueAsNumber"in g))g.valueAsNumber=e[g.type].asNumber(b.attr(f,"value"));var r=g.step=="any"?e[g.type].step*e[g.type].stepScaleFactor:g.step;l("min",b(f),g);l("max",b(f),g);if(isNaN(g.valueAsNumber))g.valueAsNumber=e[g.type].stepBase||0;if(g.step!=="any")g.valueAsNumber=Math.round((g.valueAsNumber-
(g.valueAsNumber-(g.minAsnumber||0))%g.step)*1E7)/1E7;f=g.valueAsNumber+r*j;if(!isNaN(g.minAsNumber)&&f<g.minAsNumber)f=g.valueAsNumber*j<g.minAsNumber?g.minAsNumber:isNaN(g.maxAsNumber)?Number.MAX_VALUE:g.maxAsNumber;else if(!isNaN(g.maxAsNumber)&&f>g.maxAsNumber)f=g.valueAsNumber*j>g.maxAsNumber?g.maxAsNumber:isNaN(g.minAsNumber)?Number.MIN_VALUE:g.minAsNumber;return f},d=function(f,j,g){if(!(f.disabled||f.readOnly||b(g).hasClass("step-controls"))){b.attr(f,"value",e[j].numberToString(c(f,b(g).hasClass("step-up")?
1:-1,{type:j})));b(f).unbind("blur.stepeventshim").trigger("input");if(document.activeElement){if(document.activeElement!==f)try{f.focus()}catch(r){}setTimeout(function(){if(document.activeElement!==f)try{f.focus()}catch(s){}b(f).one("blur.stepeventshim",function(){b(f).trigger("change")})},0)}}};if(a.stepArrows){var h={elementNames:["input"],setter:function(f,j,g){g();if(j=b.data(f,"step-controls"))j[f.disabled||f.readonly?"addClass":"removeClass"]("disabled-step-control")}};b.webshims.attr("disabled",
h);b.webshims.attr("readonly",h)}b.webshims.addReady(function(f){a.stepArrows&&b("input",f).each(function(){var j=n(this);if(!(!e[j]||!e[j].asNumber||!a.stepArrows||a.stepArrows!==true&&!a.stepArrows[j])){var g=this,r=b(this).css("direction")=="rtl"?{action:"insertBefore",side:"Left",otherSide:"right"}:{action:"insertAfter",side:"Right",otherSide:"left"},s=b('<span class="step-controls"><span class="step-up" /><span class="step-down" tabindex="-1" /></span>')[r.action](this).bind("mousedown mousepress",
function(u){d(g,j,u.target);return false});b(this).addClass("has-step-controls").data("step-controls",s).attr({readonly:this.readOnly,disabled:this.disabled});if(a.recalcWidth){var t=s.outerWidth(true)+(parseInt(b(this).css("padding"+r.side),10)||0),v=parseInt(b(this).css("border"+r.side+"width"),10)||0;s.css(r.otherSide,(v+t)*-1);t++;b(this).css("width",b(this).width()-t).css("padding"+r.side,t)}}})})})();b.webshims.attr("type",{elementNames:["input"],getter:function(a){var c=n(a);return b.webshims.inputTypes[c]?
c:a.type||a.getAttribute("type")},setter:true})}};if(b.webshims.addValidityRule)p();else b.support.validity===true?b.webshims.readyModules("implement-types",p):b.webshims.readyModules("validity",p)})(jQuery);
