jQuery.webshims.ready("es5",function(a){a.extend(a.expr.filters,{valid:function(p){return(a.attr(p,"validity")||{valid:true}).valid},invalid:function(p){return!a.expr.filters.valid(p)},willValidate:function(p){return a.attr(p,"willValidate")}});a.webshims.validityAlert=function(){var p={hideDelay:5E3,showFor:function(k,n){k=a(k);var o=(k.data("inputUIReplace")||{visual:k}).visual;c();p.clear();m.attr("for",o.attr("id"));this.getMessage(k);this.position(o);this.show();if(this.hideDelay)s=setTimeout(d,
this.hideDelay);if(!n){o.focus();a(document).bind("focusout.validityalert",d)}},getMessage:function(k){a("> span",m).html(k.attr("validationMessage"))},position:function(k){var n=k.offset();n.top+=k.outerHeight();m.css(n)},show:function(){m.css("display")==="none"?m.fadeIn():m.fadeTo(400,1)},hide:function(){p.clear();m.fadeOut()},clear:function(){clearTimeout(s);a(document).unbind("focusout.validityalert");m.stop().removeAttr("for")},alert:a('<label class="validity-alert" role="alert"><span class="va-box" /></label>').css({position:"absolute",
display:"none"})},m=p.alert,s=false,d=a.proxy(p,"hide"),f=false,c=function(){if(!f){f=true;a(function(){m.appendTo("body")})}};return p}();a.webshims.validityMessages.en=a.webshims.validityMessages.en||a.webshims.validityMessages["en-US"]||{typeMismatch:{email:"{%value} is not a legal email address",url:"{%value} is not a valid web address",number:"{%value} is not a number!",date:"{%value} is not a date",time:"{%value} is not a time",range:"{%value} is not a number!","datetime-local":"{%value} is not a correct date-time format."},
rangeUnderflow:"{%value} is too low. The lowest value you can use is {%min}.",rangeOverflow:"{%value}  is too high. The highest value you can use is {%max}.",stepMismatch:"The value {%value} is not allowed for this form.",tooLong:"The entered text is too large! You used {%valueLen} letters and the limit is {%maxlength}.",patternMismatch:"{%value} is not in the format this page requires! {%title}",valueMissing:"You have to specify a value"};a.webshims.validityMessages["en-US"]=a.webshims.validityMessages["en-US"]||
a.webshims.validityMessages.en;a.webshims.validityMessages[""]=a.webshims.validityMessages[""]||a.webshims.validityMessages.en;a.webshims.validityMessages.de=a.webshims.validityMessages.de||{typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},
rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",
valueMissing:"Sie m\u00fcssen einen Wert eingeben"};(function(){var p,m=[],s,d,f,c;if(a.support.validity===true&&window.addEventListener&&!window.noHTMLExtFixes){var k={timer:undefined,prevented:false};window.addEventListener("submit",function(o){if(!k.prevented&&o.target.checkValidity&&a.attr(o.target,"novalidate")===undefined&&!o.target.checkValidity())f=true},true);var n=function(o){if(a.attr(o.target,"formnovalidate")!==undefined){k.timer&&clearTimeout(k.timer);k.prevented=true;k.timer=setTimeout(function(){k.prevented=
false},20)}};window.addEventListener("click",n,true);window.addEventListener("touchstart",n,true);window.addEventListener("touchend",n,true)}a(document).bind("invalid",function(o){if(!p){d=o.target.form;if(a.support.validity===true&&d&&!window.noHTMLExtFixes){var r=a(d).bind("submit.preventInvalidSubmit",function(q){if(a.attr(d,"novalidate")===undefined){q.stopImmediatePropagation();return false}}).data("events").submit;r&&r.length>1&&r.unshift(r.pop())}p=a.Event("firstinvalid");a(o.target).trigger(p)}p&&
p.isDefaultPrevented()&&o.preventDefault();if(a.support.validity!==true||m.indexOf(o.target)==-1)m.push(o.target);else if(!window.noHTMLExtFixes){c=true;o.stopImmediatePropagation()}o.extraData="fix";clearTimeout(s);s=setTimeout(function(){var q={type:"lastinvalid",cancelable:false,invalidlist:a(m)};f&&!c&&p.target!==document.activeElement&&document.activeElement&&!a.data(p.target,"maybePreventedinvalid")&&a.webshims.validityAlert.showFor(p.target);f=p=c=false;m=[];a(d).unbind("submit.preventInvalidSubmit");
a(o.target).trigger(q,q)},0)})})();(function(){if(!(a.support.validity!==true||a.support.fieldsetValidation||window.noHTMLExtFixes)){a.support.fieldsetValidation="shim";a.webshims.addMethod("checkValidity",function(){if(a.nodeName(this,"fieldset")){var p=true;a(this.elements||"input, textarea, select",this).each(function(){if(this.checkValidity)this.checkValidity()||(p=false)});return p}else if(this.checkValidity)return this.checkValidity()})}})();(function(){var p=a.support.validity===true&&a.webshims.overrideValidationMessages,
m=a.support.validity!==true||"required"in document.createElement("select")||window.noHTMLExtFixes,s=!!(a.support.validity!==true||a('<input type="datetime-local" />')[0].type=="datetime-local"&&a('<input type="range" />')[0].type=="range"),d=!m||!s||p,f=a.webshims.inputTypes,c={},k=["customError","typeMismatch","rangeUnderflow","rangeOverflow","stepMismatch","tooLong","patternMismatch","valueMissing","valid"],n=a.attr,o=a.fn.val,r=p?{value:1,checked:1}:{value:1},q=p?["textarea"]:[],b={radio:1,checkbox:1},
g=function(e,l){if(e.form){if(!p){var i=(e.getAttribute&&e.getAttribute("type")||e.type||"").toLowerCase();if(!m&&i=="select-one"||!f[i])return}p&&!l&&b[e.type]?a(document.getElementsByName(e.name)).each(function(){a.attr(e,"validity")}):a.attr(e,"validity")}};if(!m||p){a.extend(r,{required:1,size:1,multiple:1,selectedIndex:1});q.push("select")}if(!s||p){a.extend(r,{min:1,max:1,step:1});q.push("input")}select=null;var h=a.webshims.validityMessages[""];a(document).bind("htmlExtLangChange",function(){a.webshims.activeLang(a.webshims.validityMessages,
"validation-base",function(e){h=e})});a.webshims.createValidationMessage=function(e,l){var i=h[l];if(i&&typeof i!=="string")i=i[(e.getAttribute("type")||"").toLowerCase()]||i.defaultMessage;i&&["value","min","max","title","maxlength","label"].forEach(function(j){if(i.indexOf("{%"+j)!==-1){var t=(j=="label"?a.trim(a("label[for="+e.id+"]",e.form).text()).replace(/\*$|:$/,""):a.attr(e,j))||"";i=i.replace("{%"+j+"}",t);if("value"==j)i=i.replace("{%valueLen}",t.length)}});return i||""};a.webshims.attr("validationMessage",
{elementNames:["input","select","textarea"],getter:function(e){var l="";if(!a.attr(e,"willValidate"))return l;var i=a.attr(e,"validity")||{valid:1};if(i.valid)return l;if(l="validationMessage"in e?e.validationMessage:a.data(e,"customvalidationMessage"))return l;a.each(i,function(j,t){if(!(j=="valid"||!t))if(l=a.webshims.createValidationMessage(e,j))return false});return l||""}});a.support.validationMessage=a.support.validationMessage||"shim";a.webshims.addMethod("setCustomValidity",function(e){e+=
"";if(this.setCustomValidity){this.setCustomValidity(e);if(d){a.data(this,"hasCustomError",!!e);g(this)}}else a.data(this,"customvalidationMessage",""+e)});if(a.support.validity===true){a.webshims.addInputType=function(e,l){f[e]=l};a.webshims.addValidityRule=function(e,l){c[e]=l};a.webshims.addValidityRule("typeMismatch",function(e,l,i,j){if(l==="")return false;j=j.typeMismatch;if(!("type"in i))i.type=(e[0].getAttribute("type")||"").toLowerCase();if(f[i.type]&&f[i.type].mismatch)j=f[i.type].mismatch(l,
e);return j})}if(!m){a.webshims.createBooleanAttrs("required",["select"]);a.webshims.addValidityRule("valueMissing",function(e,l,i,j){if(i.nodeName=="select"&&!l&&e.attr("required")&&e[0].size<2){if(!i.type)i.type=e[0].type;if(i.type=="select-one"&&a("> option:first-child:not(:disabled)",e).attr("selected"))return true}return j.valueMissing})}if(d){a.webshims.attr("validity",{elementNames:q,getter:function(e){var l=e.validity;if(!l)return l;var i={};k.forEach(function(u){i[u]=l[u]});if(!a.attr(e,
"willValidate"))return i;var j=a(e),t={type:(e.getAttribute&&e.getAttribute("type")||"").toLowerCase(),nodeName:(e.nodeName||"").toLowerCase()},v=o.call(j),x=!!a.data(e,"hasCustomError"),w;i.customError=x;if(i.valid&&i.customError)i.valid=false;else if(!i.valid){var y=true;a.each(i,function(u,z){if(z)return y=false});if(y)i.valid=true}a.each(c,function(u,z){i[u]=z(j,v,t,i);if(i[u]&&(i.valid||!w&&p)){e.setCustomValidity(a.webshims.createValidationMessage(e,u));i.valid=false;w=true}});i.valid&&e.setCustomValidity("");
return i}});a.fn.val=function(){var e=o.apply(this,arguments);this.each(function(){g(this)});return e};a.attr=function(e,l,i){var j=n.apply(this,arguments);r[l]&&i!==undefined&&e.form&&g(e);return j};if(document.addEventListener){document.addEventListener("change",function(e){g(e.target)},true);s||document.addEventListener("input",function(e){g(e.target)},true)}a.webshims.addReady(function(e){e===document?a(q.join(",")).each(function(){g(this,true)}):a(q.join(","),e).each(function(){g(this,true)})})}})();
a.webshims.createReadyEvent("validation-base")},true);
(function(a){var p,m=function(){if(!p){p=true;var s=parseInt("NaN",10),d=a.webshims.inputTypes,f=function(b){return typeof b=="number"||b&&b==b*1},c=function(b){return a('<input type="'+b+'" />').attr("type")===b},k=function(b){return(b.getAttribute("type")||"").toLowerCase()},n=function(b,g){var h=a.attr(b,"step");if(h==="any")return h;g=g||k(b);if(!d[g]||!d[g].step)return h;h=d.number.asNumber(h);return(!isNaN(h)&&h>0?h:d[g].step)*d[g].stepScaleFactor},o=function(b,g,h){if(!(b+"AsNumber"in h)){h[b+
"AsNumber"]=d[h.type].asNumber(g.attr(b));if(isNaN(h[b+"AsNumber"])&&b+"Default"in d[h.type])h[b+"AsNumber"]=d[h.type][b+"Default"]}},r=function(b,g){b=""+b;g-=b.length;for(var h=0;h<g;h++)b="0"+b;return b};a.webshims.addValidityRule("stepMismatch",function(b,g,h){if(g==="")return false;if(!("type"in h))h.type=k(b[0]);if(h.type=="date")return false;var e=false;if(d[h.type]&&d[h.type].step){if(!("step"in h))h.step=n(b[0],h.type);if(h.step=="any")return false;if(!("valueAsNumber"in h))h.valueAsNumber=
d[h.type].asNumber(g);if(isNaN(h.valueAsNumber))return false;o("min",b,h);b=h.minAsNumber;if(isNaN(b))b=d[h.type].stepBase||0;e=Math.abs((h.valueAsNumber-b)%h.step);e=!(e<=1.0E-7||Math.abs(e-h.step)<=1.0E-7)}return e});[{name:"rangeOverflow",attr:"max",factor:1},{name:"rangeUnderflow",attr:"min",factor:-1}].forEach(function(b){a.webshims.addValidityRule(b.name,function(g,h,e){var l=false;if(h==="")return l;if(!("type"in e))e.type=k(g[0]);if(d[e.type]&&d[e.type].asNumber){if(!("valueAsNumber"in e))e.valueAsNumber=
d[e.type].asNumber(h);if(isNaN(e.valueAsNumber))return false;o(b.attr,g,e);if(isNaN(e[b.attr+"AsNumber"]))return l;l=e[b.attr+"AsNumber"]*b.factor<e.valueAsNumber*b.factor-1.0E-7}return l})});a.webshims.attr("valueAsNumber",{elementNames:["input"],getter:function(b){var g=k(b);return d[g]&&d[g].asNumber?d[g].asNumber(a.attr(b,"value")):s},setter:function(b,g,h){var e=k(b);if(d[e]&&d[e].numberToString)if(isNaN(g))a.attr(b,"value","");else{g=d[e].numberToString(g);if(g!==false)a.attr(b,"value",g);else throw"INVALID_STATE_ERR: DOM Exception 11";
}else h()}});a.webshims.attr("valueAsDate",{elementNames:["input"],getter:function(b){var g=k(b);return d[g]&&d[g].asDate&&!d[g].noAsDate?d[g].asDate(a.attr(b,"value")):null},setter:function(b,g,h){var e=k(b);if(d[e]&&d[e].dateToString){if(!window.noHTMLExtFixes)throw"there are some serious issues in opera's implementation. don't use!";if(g===null)a.attr(b,"value","");else{g=d[e].dateToString(g);if(g!==false)a.attr(b,"value",g);else throw"INVALID_STATE_ERR: DOM Exception 11";}}else h()}});var q={number:{mismatch:function(b){return!f(b)},
step:1,stepScaleFactor:1,asNumber:function(b){return f(b)?b*1:s},numberToString:function(b){return f(b)?b:false}},range:{minDefault:0,maxDefault:100},date:{mismatch:function(b){if(!b||!b.split||!/\d$/.test(b))return true;var g=b.split(/\u002D/);if(g.length!==3)return true;var h=false;a.each(g,function(e,l){if(!(f(l)||l&&l=="0"+l*1)){h=true;return false}});if(h)return h;if(g[0].length!==4||g[1].length!=2||g[1]>12||g[2].length!=2||g[2]>33)h=true;return b!==this.dateToString(this.asDate(b,true))},step:1,
stepScaleFactor:864E5,asDate:function(b,g){if(!g&&this.mismatch(b))return null;return new Date(this.asNumber(b,true))},asNumber:function(b,g){var h=s;if(g||!this.mismatch(b)){b=b.split(/\u002D/);h=Date.UTC(b[0],b[1]-1,b[2])}return h},numberToString:function(b){return f(b)?this.dateToString(new Date(b*1)):false},dateToString:function(b){return b&&b.getFullYear?b.getUTCFullYear()+"-"+r(b.getUTCMonth()+1,2)+"-"+r(b.getUTCDate(),2):false}},time:{mismatch:function(b,g){if(!b||!b.split||!/\d$/.test(b))return true;
b=b.split(/\u003A/);if(b.length<2||b.length>3)return true;var h=false,e;if(b[2]){b[2]=b[2].split(/\u002E/);e=parseInt(b[2][1],10);b[2]=b[2][0]}a.each(b,function(l,i){if(!(f(i)||i&&i=="0"+i*1)||i.length!==2){h=true;return false}});if(h)return true;if(b[0]>23||b[0]<0||b[1]>59||b[1]<0)return true;if(b[2]&&(b[2]>59||b[2]<0))return true;if(e&&isNaN(e))return true;if(e)if(e<100)e*=100;else if(e<10)e*=10;return g===true?[b,e]:false},step:60,stepBase:0,stepScaleFactor:1E3,asDate:function(b){b=new Date(this.asNumber(b));
return isNaN(b)?null:b},asNumber:function(b){var g=s;b=this.mismatch(b,true);if(b!==true){g=Date.UTC("1970",0,1,b[0][0],b[0][1],b[0][2]||0);if(b[1])g+=b[1]}return g},dateToString:function(b){if(b&&b.getUTCHours){var g=r(b.getUTCHours(),2)+":"+r(b.getUTCMinutes(),2),h=b.getSeconds();if(h!="0")g+=":"+r(h,2);h=b.getUTCMilliseconds();if(h!="0")g+="."+r(h,3);return g}else return false}},"datetime-local":{mismatch:function(b,g){if(!b||!b.split||(b+"special").split(/\u0054/).length!==2)return true;b=b.split(/\u0054/);
return d.date.mismatch(b[0])||d.time.mismatch(b[1],g)},noAsDate:true,asDate:function(b){b=new Date(this.asNumber(b));return isNaN(b)?null:b},asNumber:function(b){var g=s,h=this.mismatch(b,true);if(h!==true){b=b.split(/\u0054/)[0].split(/\u002D/);g=Date.UTC(b[0],b[1]-1,b[2],h[0][0],h[0][1],h[0][2]||0);if(h[1])g+=h[1]}return g},dateToString:function(b,g){return d.date.dateToString(b)+"T"+d.time.dateToString(b,g)}}};c("number")||a.webshims.addInputType("number",q.number);c("range")||a.webshims.addInputType("range",
a.extend({},q.number,q.range));c("date")||a.webshims.addInputType("date",q.date);c("time")||a.webshims.addInputType("time",a.extend({},q.date,q.time));c("datetime-local")||a.webshims.addInputType("datetime-local",a.extend({},q.date,q.time,q["datetime-local"]));(function(){var b=a.webshims.modules["number-date-type"].options,g=function(l,i,j){j=j||{};if(!("type"in j))j.type=k(l);if(!("step"in j))j.step=n(l,j.type);if(!("valueAsNumber"in j))j.valueAsNumber=d[j.type].asNumber(a.attr(l,"value"));var t=
j.step=="any"?d[j.type].step*d[j.type].stepScaleFactor:j.step;o("min",a(l),j);o("max",a(l),j);if(isNaN(j.valueAsNumber))j.valueAsNumber=d[j.type].stepBase||0;if(j.step!=="any")j.valueAsNumber=Math.round((j.valueAsNumber-(j.valueAsNumber-(j.minAsnumber||0))%j.step)*1E7)/1E7;l=j.valueAsNumber+t*i;if(!isNaN(j.minAsNumber)&&l<j.minAsNumber)l=j.valueAsNumber*i<j.minAsNumber?j.minAsNumber:isNaN(j.maxAsNumber)?Number.MAX_VALUE:j.maxAsNumber;else if(!isNaN(j.maxAsNumber)&&l>j.maxAsNumber)l=j.valueAsNumber*
i>j.maxAsNumber?j.maxAsNumber:isNaN(j.minAsNumber)?Number.MIN_VALUE:j.minAsNumber;return l};a.webshims.modules["number-date-type"].getNextStep=g;var h=function(l,i,j){if(!(l.disabled||l.readOnly||a(j).hasClass("step-controls"))){a.attr(l,"value",d[i].numberToString(g(l,a(j).hasClass("step-up")?1:-1,{type:i})));a(l).unbind("blur.stepeventshim").trigger("input");if(document.activeElement){if(document.activeElement!==l)try{l.focus()}catch(t){}setTimeout(function(){if(document.activeElement!==l)try{l.focus()}catch(v){}a(l).one("blur.stepeventshim",
function(){a(l).trigger("change")})},0)}}};if(b.stepArrows){var e={elementNames:["input"],setter:function(l,i,j){j();if(i=a.data(l,"step-controls"))i[l.disabled||l.readonly?"addClass":"removeClass"]("disabled-step-control")}};a.webshims.attr("disabled",e);a.webshims.attr("readonly",e)}a.webshims.addReady(function(l){b.stepArrows&&a("input",l).each(function(){var i=k(this);if(!(!d[i]||!d[i].asNumber||!b.stepArrows||b.stepArrows!==true&&!b.stepArrows[i])){var j=this,t=a(this).css("direction")=="rtl"?
{action:"insertBefore",side:"Left",otherSide:"right"}:{action:"insertAfter",side:"Right",otherSide:"left"},v=a('<span class="step-controls"><span class="step-up" /><span class="step-down" tabindex="-1" /></span>')[t.action](this).bind("mousedown mousepress",function(y){h(j,i,y.target);return false});a(this).addClass("has-step-controls").data("step-controls",v).attr({readonly:this.readOnly,disabled:this.disabled});if(b.calculateWidth){var x=a(this).width()||parseInt(a(this).css("width"),10);if(x){var w=
(parseInt(a(this).css("margin"+t.side),10)||0)+(parseInt(v.css("margin"+t.side),10)||0);a(this).css("width",x-v.outerWidth(true));w&&v.css("margin"+t.side,w)}}}})})})();a.webshims.attr("type",{elementNames:["input"],getter:function(b){var g=k(b);return a.webshims.inputTypes[g]?g:b.type||b.getAttribute("type")},setter:true});a.webshims.createReadyEvent("number-date-type")}};a.support.validity===true?a.webshims.ready("validation-base",m,true):a.webshims.ready("validity",m,true)})(jQuery);
(function(a){a.support.inputUI="shim";var p=a.webshims.modules.inputUI.options,m=function(d){a("input",d).each(function(){var f=a.attr(this,"type");m[f]&&!a.data(this,"inputUIReplace")&&m[f](a(this))})};m.common=function(d,f,c){a.support.validity===true&&d.bind("firstinvalid",function(n){setTimeout(function(){a.data(n.target,"maybePreventedinvalid")||a.webshims.validityAlert.showFor(n.target)},30)});var k={css:{marginRight:d.css("marginRight"),marginLeft:d.css("marginLeft")},outerWidth:d.getouterWidth()};
f.addClass(d[0].className).data("html5element",d);d.after(f).data("inputUIReplace",{visual:f,methods:c}).hide();return k};m["datetime-local"]=function(d){if(a.fn.datepicker){var f=a('<span class="input-datetime-local"><input type="text" class="input-datetime-local-date" /><input type="time" class="input-datetime-local-time" /></span>'),c=this.common(d,f,m["datetime-local"].attrs),k=a("input.input-datetime-local-date",f);a("input",f).data("html5element",a.data(f[0],"html5element"));if(c.css){f.css(c.css);
if(c.outerWidth){f.outerWidth(c.outerWidth);c=f.getwidth();k.css({marginLeft:0,marginRight:2}).outerWidth(Math.floor(c*0.61));a("input.input-datetime-local-time").css({marginLeft:2,marginRight:0}).outerWidth(Math.floor(c*0.37))}}a.webshims.triggerDomUpdate(f);c=a("input.input-datetime-local-date",f).datepicker(a.extend({},p.date)).bind("change",function(){var n,o=a("input.input-datetime-local-time",f).attr("value");try{n=(n=a.datepicker.parseDate(k.datepicker("option","dateFormat"),k.attr("value")))?
a.datepicker.formatDate("yy-mm-dd",n):k.attr("value")}catch(r){n=k.attr("value")}if(!a("input.input-datetime-local-time",f).attr("value")){o="00:00";a("input.input-datetime-local-time",f).attr("value",o)}m["datetime-local"].blockAttr=true;d.attr("value",n+"T"+o);m["datetime-local"].blockAttr=false;d.trigger("change")}).data("datepicker");a("input.input-datetime-local-time",f).bind("input change",function(){var n=d.attr("value").split("T");if(n.length<2||!n[0])n[0]=a.datepicker.formatDate("yy-mm-dd",
new Date);n[1]=a.attr(this,"value");m["datetime-local"].blockAttr=true;try{k.attr("value",a.datepicker.formatDate(k.datepicker("option","dateFormat"),a.datepicker.parseDate("yy-mm-dd",n[0])))}catch(o){}d.attr("value",n.join("T"));m["datetime-local"].blockAttr=false;d.trigger("change")});c.dpDiv.addClass("input-date-datepicker-control");a.each(["disabled","min","max","value"],function(n,o){d.attr(o,function(r,q){return q||""})})}};m["datetime-local"].attrs={disabled:function(d,f,c){a("input.input-datetime-local-date",
f).datepicker("option","disabled",!!c);a("input.input-datetime-local-time",f).attr("disabled",!!c)},min:function(d,f,c){c=c.split?c.split("T"):[];try{c=a.datepicker.parseDate("yy-mm-dd",c[0])}catch(k){c=false}c&&a("input.input-datetime-local-date",f).datepicker("option","minDate",c)},max:function(d,f,c){c=c.split?c.split("T"):[];try{c=a.datepicker.parseDate("yy-mm-dd",c[0])}catch(k){c=false}c&&a("input.input-datetime-local-date",f).datepicker("option","maxDate",c)},value:function(d,f,c){if(!m["datetime-local"].blockAttr){var k;
c=c.split?c.split("T"):[];try{k=a.datepicker.parseDate("yy-mm-dd",c[0])}catch(n){k=false}if(k){a("input.input-datetime-local-date",f).datepicker("setDate",k);a("input.input-datetime-local-time",f).attr("value",c[1]||"00:00")}else{a("input.input-datetime-local-date",f).attr("value",c[0]||"");a("input.input-datetime-local-time",f).attr("value",c[1]||"")}}}};m.date=function(d){if(a.fn.datepicker){var f=a('<input type="text" class="input-date" />'),c=this.common(d,f,m.date.attrs);if(c.css){f.css(c.css);
c.outerWidth&&f.outerWidth(c.outerWidth)}f.datepicker(a.extend({},p.date)).bind("change",function(){m.date.blockAttr=true;var k;try{k=(k=a.datepicker.parseDate(f.datepicker("option","dateFormat"),f.attr("value")))?a.datepicker.formatDate("yy-mm-dd",k):f.attr("value")}catch(n){k=f.attr("value")}d.attr("value",k);m.date.blockAttr=false;d.trigger("change")}).data("datepicker").dpDiv.addClass("input-date-datepicker-control");a.each(["disabled","min","max","value"],function(k,n){d.attr(n,function(o,r){return r||
""})})}};m.date.attrs={disabled:function(d,f,c){f.datepicker("option","disabled",!!c)},min:function(d,f,c){try{c=a.datepicker.parseDate("yy-mm-dd",c)}catch(k){c=false}c&&f.datepicker("option","minDate",c)},max:function(d,f,c){try{c=a.datepicker.parseDate("yy-mm-dd",c)}catch(k){c=false}c&&f.datepicker("option","maxDate",c)},value:function(d,f,c){if(!m.date.blockAttr){try{var k=a.datepicker.parseDate("yy-mm-dd",c)}catch(n){k=false}k?f.datepicker("setDate",k):f.attr("value",c)}}};m.range=function(d){if(a.fn.slider){var f=
a('<span class="input-range" />'),c=this.common(d,f,m.range.attrs);if(c.css){f.css(c.css);c.outerWidth&&f.outerWidth(c.outerWidth)}f.slider(a.extend(p.slider,{change:function(k,n){if(k.originalEvent){m.range.blockAttr=true;d.attr("value",n.value);m.range.blockAttr=false;d.trigger("change")}}}));a.each(["disabled","min","max","value","step"],function(k,n){d.attr(n,function(o,r){return r||""})})}};m.range.attrs={disabled:function(d,f,c){f.slider("option","disabled",!!c)},min:function(d,f,c){c=c?c*1||
0:0;f.slider("option","min",c)},max:function(d,f,c){c=c||c===0?c*1||100:100;f.slider("option","max",c)},value:function(d,f,c){c=a(d).attr("valueAsNumber");if(isNaN(c)){c=(f.slider("option","max")-f.slider("option","min"))/2;d.value=c}m.range.blockAttr||f.slider("option","value",c)},step:function(d,f,c){c=c&&a.trim(c)?c*1||1:1;f.slider("option","step",c)}};a.each(["disabled","min","max","value","step"],function(d,f){a.webshims.attr(f,{elementNames:["input"],setter:function(c,k,n){var o=a.data(c,"inputUIReplace");
n();o&&o.methods[f]&&o.methods[f](c,o.visual,k)},getter:true})});var s=function(d){if(d){d=a.extend({},d,p.date);a("input.hasDatepicker").filter(".input-date, .input-datetime-local-date").datepicker("option",d).each(function(){var f=a.data(this,"html5element");f&&a.each(["disabled","min","max","value"],function(c,k){f.attr(k,function(n,o){return o||""})})});a.datepicker.setDefaults(d)}};a(document).bind("jquery-uiReady.langchange input-widgetsReady.langchange",function(){a.datepicker&&a(document).bind("htmlExtLangChange",
function(){a.webshims.activeLang(a.datepicker.regional,"inputUI",s)}).unbind("jquery-uiReady.langchange input-widgetsReady.langchange")});a.webshims.ready("number-date-type",function(){a.webshims.addReady(function(d){a(document).bind("jquery-uiReady.initinputui input-widgetsReady.initinputui",function(){if(a.datepicker||a.fn.slider){m(d);a.datepicker&&a.fn.slider&&a(document).unbind("jquery-uiReady.initinputui input-widgetsReady.initinputui")}})});a.webshims.createReadyEvent("inputUI")},true)})(jQuery);
