jQuery.webshims.ready("es5",function(c,s,C){var l=s.validityMessages,r=c.support,y=false,p=document;if(r.validity)y=!C.noHTMLExtFixes;c.extend(c.expr.filters,{valid:function(d){return(c.attr(d,"validity")||{valid:true}).valid},invalid:function(d){return!c.expr.filters.valid(d)},willValidate:function(d){return c.attr(d,"willValidate")}});s.triggerInlineForm=function(){var d=function(e){if(typeof e!="string"||e.indexOf("-")!==-1||e.indexOf(".")!==-1||e.indexOf('"')!==-1)return"";return"var "+e+' = this.form["'+
e+'"];'};return function(e,b){var i=e["on"+b]||e.getAttribute("on"+b)||"",k;b=c.Event({type:b,target:e[0],currentTarget:e[0]});if(i&&typeof i=="string"&&e.form&&e.form.elements){var m="";k=0;for(var u=e.form.elements,j=u.length;k<j;k++){var a=u[k].name,f=u[k].id;if(a)m+=d(a);if(f&&f!==a)m+=d(f)}k=function(){eval(m+i)}.call(e,b)}c(e).trigger(b);return k}}();s.validityAlert=function(){var d=!c.browser.msie||parseInt(c.browser.version,10)>7?"span":"label",e={hideDelay:5E3,showFor:function(j,a,f){j=c(j);
var h=(j.data("inputUIReplace")||{visual:j}).visual;u();e.clear();this.getMessage(j,a);this.position(h);this.show();if(this.hideDelay)i=setTimeout(k,this.hideDelay);if(!f){j=c("input, select, textarea, .ui-slider-handle",h).filter(":visible:first");j[0]||(j=h);b.attr("for",s.getID(j));j.focus();c(p).bind("focusout.validityalert",k)}},getMessage:function(j,a){c("> span",b).text(a||j.attr("validationMessage"))},position:function(j){var a=j.offset();a.top+=j.outerHeight();b.css(a)},show:function(){b.css("display")===
"none"?b.fadeIn():b.fadeTo(400,1)},hide:function(){e.clear();b.fadeOut()},clear:function(){clearTimeout(i);c(p).unbind("focusout.validityalert");b.stop().removeAttr("for")},alert:c("<"+d+' class="validity-alert" role="alert"><span class="va-box" /></'+d+">").css({position:"absolute",display:"none"})},b=e.alert,i=false,k=c.proxy(e,"hide"),m=false,u=function(){if(!m){m=true;c(function(){b.appendTo("body")})}};return e}();l.en=l.en||l["en-US"]||{typeMismatch:{email:"{%value} is not a legal email address",
url:"{%value} is not a valid web address",number:"{%value} is not a number!",date:"{%value} is not a date",time:"{%value} is not a time",range:"{%value} is not a number!","datetime-local":"{%value} is not a correct date-time format."},rangeUnderflow:"{%value} is too low. The lowest value you can use is {%min}.",rangeOverflow:"{%value}  is too high. The highest value you can use is {%max}.",stepMismatch:"The value {%value} is not allowed for this form.",tooLong:"The entered text is too large! You used {%valueLen} letters and the limit is {%maxlength}.",
patternMismatch:"{%value} is not in the format this page requires! {%title}",valueMissing:"You have to specify a value"};l["en-US"]=l["en-US"]||l.en;l[""]=l[""]||l["en-US"];l.de=l.de||{typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},
rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",
valueMissing:"Sie m\u00fcssen einen Wert eingeben"};var D=l[""];c(p).bind("htmlExtLangChange",function(){s.activeLang(l,"validation-base",function(d){D=d})});s.createValidationMessage=function(d,e){var b=D[e];if(b&&typeof b!=="string")b=b[(d.getAttribute("type")||"").toLowerCase()]||b.defaultMessage;b&&["value","min","max","title","maxlength","label"].forEach(function(i){if(b.indexOf("{%"+i)!==-1){var k=(i=="label"?c.trim(c("label[for="+d.id+"]",d.form).text()).replace(/\*$|:$/,""):c.attr(d,i))||
"";b=b.replace("{%"+i+"}",k);if("value"==i)b=b.replace("{%valueLen}",k.length)}});return b||""};c.each(r.validationMessage?["customValidationMessage"]:["customValidationMessage","validationMessage"],function(d,e){s.attr(e,{elementNames:["input","select","textarea"],getter:function(b){var i="";if(!c.attr(b,"willValidate"))return i;var k=c.attr(b,"validity")||{valid:1};if(k.valid)return i;if(k.customError||e==="validationMessage")if(i="validationMessage"in b?b.validationMessage:c.data(b,"customvalidationMessage"))return i;
c.each(k,function(m,u){if(!(m=="valid"||!u))if(i=s.createValidationMessage(b,m))return false});return i||""}})});(function(){var d,e=[],b="value"in p.createElement("output")&&"list"in p.createElement("input"),i,k;if(y&&C.addEventListener){var m={timer:void 0,prevented:false};C.addEventListener("submit",function(j){!m.prevented&&j.target.checkValidity&&c.attr(j.target,"novalidate")==null&&c(j.target).checkValidity()},true);var u=function(j){if(c.attr(j.target,"formnovalidate")!=null){m.timer&&clearTimeout(m.timer);
m.prevented=true;m.timer=setTimeout(function(){m.prevented=false},20)}};C.addEventListener("click",u,true);C.addEventListener("touchstart",u,true);C.addEventListener("touchend",u,true)}c(p).bind("invalid",function(j){if(y&&c.attr(j.target,"validity").valid){j.stopImmediatePropagation();return false}if(!d){if((k=j.target.form)&&y){var a=c(k).bind("submit.preventInvalidSubmit",function(f){if(c.attr(k,"novalidate")==null){f.stopImmediatePropagation();return false}}).data("events").submit;a&&a.length>
1&&a.unshift(a.pop())}d=c.Event("firstinvalid");c(j.target).trigger(d)}d&&d.isDefaultPrevented()&&j.preventDefault();if(!r.validity||e.indexOf(j.target)==-1)e.push(j.target);else y&&j.stopImmediatePropagation();j.extraData="fix";clearTimeout(i);i=setTimeout(function(){var f={type:"lastinvalid",cancelable:false,invalidlist:c(e)};y&&!b&&p.activeElement&&d&&d.target!==p.activeElement&&!c.data(d.target,"maybePreventedinvalid")&&s.validityAlert.showFor(d.target);d=false;e=[];c(k).unbind("submit.preventInvalidSubmit");
c(j.target).trigger(f,f)},9)})})();(function(){if(!(!y||r.fieldsetValidation)){var d=function(e){var b=(c.attr(e,"validity")||{valid:true}).valid;!b&&e.checkValidity()&&c(e).trigger("invalid");return b};s.addMethod("checkValidity",function(){if(this.elements||c.nodeName(this,"fieldset")){var e=true;c(this.elements||"input, textarea, select",this).each(function(){d(this)||(e=false)});return e}else if(this.checkValidity)return d(this)})}})();(function(){if(r.validity){var d=s.inputTypes,e={};s.addInputType=
function(g,t){d[g]=t};s.addValidityRule=function(g,t){e[g]=t};s.addValidityRule("typeMismatch",function(g,t,q,o){if(t==="")return false;o=o.typeMismatch;if(!("type"in q))q.type=(g[0].getAttribute("type")||"").toLowerCase();if(d[q.type]&&d[q.type].mismatch)o=d[q.type].mismatch(t,g);return o});var b=s.overrideValidationMessages,i=!r.requiredSelect||!r.inputUI||b,k=["customError","typeMismatch","rangeUnderflow","rangeOverflow","stepMismatch","tooLong","patternMismatch","valueMissing","valid"],m=c.attr,
u=c.fn.val,j=b?{value:1,checked:1}:{value:1},a=b?["textarea"]:[],f={radio:1,checkbox:1},h=function(g,t){if(g.form){var q=(g.getAttribute&&g.getAttribute("type")||g.type||"").toLowerCase();if(!b)if(!(!r.requiredSelect&&q=="select-one")&&!d[q])return;b&&!t&&f[q]&&g.name?c(p.getElementsByName(g.name)).each(function(){c.attr(this,"validity")}):c.attr(g,"validity")}};s.addMethod("setCustomValidity",function(g){g+="";if(this.setCustomValidity){this.setCustomValidity(g);if(i){c.data(this,"hasCustomError",
!!g);h(this)}}else c.data(this,"customvalidationMessage",g)});if(!r.requiredSelect||b){c.extend(j,{required:1,size:1,multiple:1,selectedIndex:1});a.push("select")}if(!r.inputUI||b){c.extend(j,{min:1,max:1,step:1});a.push("input")}if(!r.requiredSelect){s.createBooleanAttrs("required",["select"]);s.addValidityRule("valueMissing",function(g,t,q,o){if(q.nodeName=="select"&&!t&&g.attr("required")&&g[0].size<2){if(!q.type)q.type=g[0].type;if(q.type=="select-one"&&c("> option:first-child:not(:disabled)",
g).attr("selected"))return true}return o.valueMissing})}if(i){s.attr("validity",{elementNames:a,getter:function(g){var t=g.validity;if(!t)return t;var q={};k.forEach(function(w){q[w]=t[w]});if(!c.attr(g,"willValidate"))return q;var o=c(g),v={type:(g.getAttribute&&g.getAttribute("type")||"").toLowerCase(),nodeName:(g.nodeName||"").toLowerCase()},n=u.call(o),x=!!c.data(g,"hasCustomError"),z;q.customError=x;if(q.valid&&q.customError)q.valid=false;else if(!q.valid){var B=true;c.each(q,function(w,A){if(A)return B=
false});if(B)q.valid=true}c.each(e,function(w,A){q[w]=A(o,n,v,q);if(q[w]&&(q.valid||!z&&b)){g.setCustomValidity(s.createValidationMessage(g,w));q.valid=false;z=true}});q.valid&&g.setCustomValidity("");return q}});c.fn.val=function(){var g=u.apply(this,arguments);this.each(function(){h(this)});return g};c.attr=function(g,t,q){var o=m.apply(this,arguments);j[t]&&q!==void 0&&g.form&&h(g);return o};if(p.addEventListener){p.addEventListener("change",function(g){h(g.target)},true);r.inputUI||p.addEventListener("input",
function(g){h(g.target)},true)}s.addReady(function(g){c(a.join(","),g).each(function(){h(this,true)})})}}})();s.createReadyEvent("validation-base")},true);
(function(c){var s,C=function(l,r,y){if(!s){s=true;var p=parseInt("NaN",10),D=document,d=r.inputTypes,e=function(a){return typeof a=="number"||a&&a==a*1},b=function(a){return l('<input type="'+a+'" />').attr("type")===a},i=function(a){return(a.getAttribute("type")||"").toLowerCase()},k=function(a,f){var h=l.attr(a,"step");if(h==="any")return h;f=f||i(a);if(!d[f]||!d[f].step)return h;h=d.number.asNumber(h);return(!isNaN(h)&&h>0?h:d[f].step)*d[f].stepScaleFactor},m=function(a,f,h){if(!(a+"AsNumber"in
h)){h[a+"AsNumber"]=d[h.type].asNumber(f.attr(a));if(isNaN(h[a+"AsNumber"])&&a+"Default"in d[h.type])h[a+"AsNumber"]=d[h.type][a+"Default"]}},u=function(a,f){a=""+a;f-=a.length;for(var h=0;h<f;h++)a="0"+a;return a};r.addValidityRule("stepMismatch",function(a,f,h){if(f==="")return false;if(!("type"in h))h.type=i(a[0]);if(h.type=="date")return false;var g=false;if(d[h.type]&&d[h.type].step){if(!("step"in h))h.step=k(a[0],h.type);if(h.step=="any")return false;if(!("valueAsNumber"in h))h.valueAsNumber=
d[h.type].asNumber(f);if(isNaN(h.valueAsNumber))return false;m("min",a,h);a=h.minAsNumber;if(isNaN(a))a=d[h.type].stepBase||0;g=Math.abs((h.valueAsNumber-a)%h.step);g=!(g<=1.0E-7||Math.abs(g-h.step)<=1.0E-7)}return g});[{name:"rangeOverflow",attr:"max",factor:1},{name:"rangeUnderflow",attr:"min",factor:-1}].forEach(function(a){r.addValidityRule(a.name,function(f,h,g){var t=false;if(h==="")return t;if(!("type"in g))g.type=i(f[0]);if(d[g.type]&&d[g.type].asNumber){if(!("valueAsNumber"in g))g.valueAsNumber=
d[g.type].asNumber(h);if(isNaN(g.valueAsNumber))return false;m(a.attr,f,g);if(isNaN(g[a.attr+"AsNumber"]))return t;t=g[a.attr+"AsNumber"]*a.factor<g.valueAsNumber*a.factor-1.0E-7}return t})});r.attr("valueAsNumber",{elementNames:["input"],getter:function(a){var f=i(a);return d[f]&&d[f].asNumber?d[f].asNumber(l.attr(a,"value")):p},setter:function(a,f,h){var g=i(a);if(d[g]&&d[g].numberToString)if(isNaN(f))l.attr(a,"value","");else{f=d[g].numberToString(f);if(f!==false)l.attr(a,"value",f);else throw"INVALID_STATE_ERR: DOM Exception 11";
}else h()}});r.attr("valueAsDate",{elementNames:["input"],getter:function(a){var f=i(a);return d[f]&&d[f].asDate&&!d[f].noAsDate?d[f].asDate(l.attr(a,"value")):null},setter:function(a,f,h){var g=i(a);if(d[g]&&d[g].dateToString){if(!y.noHTMLExtFixes)throw"there are some serious issues in opera's implementation. don't use!";if(f===null)l.attr(a,"value","");else{f=d[g].dateToString(f);if(f!==false)l.attr(a,"value",f);else throw"INVALID_STATE_ERR: DOM Exception 11";}}else h()}});var j={number:{mismatch:function(a){return!e(a)},
step:1,stepScaleFactor:1,asNumber:function(a){return e(a)?a*1:p},numberToString:function(a){return e(a)?a:false}},range:{minDefault:0,maxDefault:100},date:{mismatch:function(a){if(!a||!a.split||!/\d$/.test(a))return true;var f=a.split(/\u002D/);if(f.length!==3)return true;var h=false;l.each(f,function(g,t){if(!(e(t)||t&&t=="0"+t*1)){h=true;return false}});if(h)return h;if(f[0].length!==4||f[1].length!=2||f[1]>12||f[2].length!=2||f[2]>33)h=true;return a!==this.dateToString(this.asDate(a,true))},step:1,
stepScaleFactor:864E5,asDate:function(a,f){if(!f&&this.mismatch(a))return null;return new Date(this.asNumber(a,true))},asNumber:function(a,f){var h=p;if(f||!this.mismatch(a)){a=a.split(/\u002D/);h=Date.UTC(a[0],a[1]-1,a[2])}return h},numberToString:function(a){return e(a)?this.dateToString(new Date(a*1)):false},dateToString:function(a){return a&&a.getFullYear?a.getUTCFullYear()+"-"+u(a.getUTCMonth()+1,2)+"-"+u(a.getUTCDate(),2):false}},time:{mismatch:function(a,f){if(!a||!a.split||!/\d$/.test(a))return true;
a=a.split(/\u003A/);if(a.length<2||a.length>3)return true;var h=false,g;if(a[2]){a[2]=a[2].split(/\u002E/);g=parseInt(a[2][1],10);a[2]=a[2][0]}l.each(a,function(t,q){if(!(e(q)||q&&q=="0"+q*1)||q.length!==2){h=true;return false}});if(h)return true;if(a[0]>23||a[0]<0||a[1]>59||a[1]<0)return true;if(a[2]&&(a[2]>59||a[2]<0))return true;if(g&&isNaN(g))return true;if(g)if(g<100)g*=100;else if(g<10)g*=10;return f===true?[a,g]:false},step:60,stepBase:0,stepScaleFactor:1E3,asDate:function(a){a=new Date(this.asNumber(a));
return isNaN(a)?null:a},asNumber:function(a){var f=p;a=this.mismatch(a,true);if(a!==true){f=Date.UTC("1970",0,1,a[0][0],a[0][1],a[0][2]||0);if(a[1])f+=a[1]}return f},dateToString:function(a){if(a&&a.getUTCHours){var f=u(a.getUTCHours(),2)+":"+u(a.getUTCMinutes(),2),h=a.getSeconds();if(h!="0")f+=":"+u(h,2);h=a.getUTCMilliseconds();if(h!="0")f+="."+u(h,3);return f}else return false}},"datetime-local":{mismatch:function(a,f){if(!a||!a.split||(a+"special").split(/\u0054/).length!==2)return true;a=a.split(/\u0054/);
return d.date.mismatch(a[0])||d.time.mismatch(a[1],f)},noAsDate:true,asDate:function(a){a=new Date(this.asNumber(a));return isNaN(a)?null:a},asNumber:function(a){var f=p,h=this.mismatch(a,true);if(h!==true){a=a.split(/\u0054/)[0].split(/\u002D/);f=Date.UTC(a[0],a[1]-1,a[2],h[0][0],h[0][1],h[0][2]||0);if(h[1])f+=h[1]}return f},dateToString:function(a,f){return d.date.dateToString(a)+"T"+d.time.dateToString(a,f)}}};b("number")||r.addInputType("number",j.number);b("range")||r.addInputType("range",l.extend({},
j.number,j.range));b("date")||r.addInputType("date",j.date);b("time")||r.addInputType("time",l.extend({},j.date,j.time));b("datetime-local")||r.addInputType("datetime-local",l.extend({},j.date,j.time,j["datetime-local"]));(function(){var a=r.modules["number-date-type"].options,f=l.browser.msie&&parseInt(l.browser.version,10)<8?2:0,h=function(o,v,n){n=n||{};if(!("type"in n))n.type=i(o);if(!("step"in n))n.step=k(o,n.type);if(!("valueAsNumber"in n))n.valueAsNumber=d[n.type].asNumber(l.attr(o,"value"));
var x=n.step=="any"?d[n.type].step*d[n.type].stepScaleFactor:n.step;m("min",l(o),n);m("max",l(o),n);if(isNaN(n.valueAsNumber))n.valueAsNumber=d[n.type].stepBase||0;if(n.step!=="any")if((o=Math.round((n.valueAsNumber-(n.minAsnumber||0))%n.step*1E7)/1E7)&&Math.abs(o)!=n.step)n.valueAsNumber-=o;o=n.valueAsNumber+x*v;if(!isNaN(n.minAsNumber)&&o<n.minAsNumber)o=n.valueAsNumber*v<n.minAsNumber?n.minAsNumber:isNaN(n.maxAsNumber)?Number.MAX_VALUE:n.maxAsNumber;else if(!isNaN(n.maxAsNumber)&&o>n.maxAsNumber)o=
n.valueAsNumber*v>n.maxAsNumber?n.maxAsNumber:isNaN(n.minAsNumber)?Number.MIN_VALUE:n.minAsNumber;return Math.round(o*1E7)/1E7};r.modules["number-date-type"].getNextStep=h;var g=function(o,v,n){if(!(o.disabled||o.readOnly||l(n).hasClass("step-controls"))){l.attr(o,"value",d[v].numberToString(h(o,l(n).hasClass("step-up")?1:-1,{type:v})));l(o).unbind("blur.stepeventshim");r.triggerInlineForm(o,"input");if(D.activeElement){if(D.activeElement!==o)try{o.focus()}catch(x){}setTimeout(function(){if(D.activeElement!==
o)try{o.focus()}catch(z){}l(o).one("blur.stepeventshim",function(){l(o).trigger("change")})},0)}}};if(a.stepArrows){var t={elementNames:["input"],setter:function(o,v,n){n();if(v=l.data(o,"step-controls"))v[o.disabled||o.readonly?"addClass":"removeClass"]("disabled-step-control")}};r.attr("disabled",t);r.attr("readonly",t)}var q={38:1,40:-1};r.addReady(function(o){a.stepArrows&&l("input",o).each(function(){var v=i(this);if(!(!d[v]||!d[v].asNumber||!a.stepArrows||a.stepArrows!==true&&!a.stepArrows[v])){var n=
this,x=l(this).css("direction")=="rtl"?{action:"insertBefore",side:"Left",otherSide:"right"}:{action:"insertAfter",side:"Right",otherSide:"Left"},z=l('<span class="step-controls" unselectable="on"><span class="step-up" /><span class="step-down" /></span>')[x.action](this).bind("selectstart dragstart",function(){return false}).bind("mousedown mousepress",function(E){g(n,v,E.target);return false});l(this).addClass("has-step-controls").data("step-controls",z).attr({readonly:this.readOnly,disabled:this.disabled,
autocomplete:"off"}).bind(l.browser.msie?"keydown":"keypress",function(E){if(!(this.disabled||this.readOnly||!q[E.keyCode])){l.attr(this,"value",d[v].numberToString(h(this,q[E.keyCode],{type:v})));r.triggerInlineForm(this,"input");return false}});if(a.calculateWidth){var B=l(this),w={w:B.getwidth()};if(w.w){var A={mL:parseInt(z.css("margin"+x.otherSide),10)||0,w:z.getouterWidth()};w.mR=parseInt(B.css("margin"+x.side),10)||0;f?z.css("marginBottom",(B.innerHeight()-z.height()/2)/2-1):z.css("marginBottom",
(parseInt(B.css("paddingBottom"),10)||0)/-2);w.mR&&B.css("margin"+x.side,0);if(A.mL<=A.w*-1){z.css("margin"+x.side,Math.floor(Math.abs(A.w+A.mL)+w.mR));B.css("padding"+x.side,(parseInt(l(this).css("padding"+x.side),10)||0)+Math.abs(A.mL));B.css("width",Math.floor(w.w+A.mL))}else{z.css("margin"+x.side,w.mR);B.css("width",Math.floor(w.w-A.mL-A.w))}}}}})})})();r.attr("type",{elementNames:["input"],getter:function(a){var f=i(a);return r.inputTypes[f]?f:a.type||a.getAttribute("type")},setter:true});r.createReadyEvent("number-date-type")}};
c.support.validity?c.webshims.ready("validation-base",C,true):c.webshims.ready("validity",C,true)})(jQuery);
jQuery.webshims.ready("number-date-type",function(c,s,C,l){var r=c.webshims.modules.inputUI.options,y,p=function(d){c("input",d).each(function(){var e=c.attr(this,"type");p[e]&&!c.data(this,"inputUIReplace")&&p[e](c(this))})};p.common=function(d,e,b){if(r.replaceNative)(function(){var m=[],u;d.bind("firstinvalid invalid",function(j){clearTimeout(u);m.push(j);u=setTimeout(function(){if(!c.data(j.target,"maybePreventedinvalid")&&(!m[0]||!m[0].isDefaultPrevented())&&(!m[1]||!m[1].isDefaultPrevented())){var a=
j.target,f=a.nodeName;if(a.id)f+="#"+a.id;if(a.name)f+="[name="+a.name+"]";if(a.className)f+="."+a.className.split(" ").join(".");throw f+" can not be focused. handle the invalid event.";}m=[]},30)})})();else c.support.validity&&d.bind("firstinvalid",function(m){clearTimeout(y);y=setTimeout(function(){!c.data(m.target,"maybePreventedinvalid")&&!m.isDefaultPrevented()&&s.validityAlert.showFor(m.target)},30)});var i=d.attr("id");i={css:{marginRight:d.css("marginRight"),marginLeft:d.css("marginLeft")},
outerWidth:d.getouterWidth(),label:i?c("label[for="+i+"]",d[0].form):c([])};var k=s.getID(i.label);e.addClass(d[0].className).data("html5element",d);d.after(e).data("inputUIReplace",{visual:e,methods:b}).hide();if(e.length==1&&!c("*",e)[0]){e.attr("aria-labeledby",k);i.label.bind("click",function(){e.focus();return false})}return i};p["datetime-local"]=function(d){if(c.fn.datepicker){var e=c('<span class="input-datetime-local"><input type="text" class="input-datetime-local-date" /><input type="time" class="input-datetime-local-time" /></span>'),
b=this.common(d,e,p["datetime-local"].attrs),i=c("input.input-datetime-local-date",e);c("input",e).data("html5element",c.data(e[0],"html5element"));i.attr("aria-labeledby",b.label.attr("id"));b.label.bind("click",function(){i.focus();return false});if(b.css){e.css(b.css);if(b.outerWidth){e.outerWidth(b.outerWidth);b=e.getwidth()-4;i.css({marginLeft:0,marginRight:2}).outerWidth(Math.floor(b*0.6));c("input.input-datetime-local-time",e).css({marginLeft:2,marginRight:0}).outerWidth(Math.floor(b*0.4))}}s.triggerDomUpdate(e);
c("input.input-datetime-local-date",e).datepicker(c.extend({},r.datepicker)).bind("change",function(){var k,m=c("input.input-datetime-local-time",e).attr("value");try{k=(k=c.datepicker.parseDate(i.datepicker("option","dateFormat"),i.attr("value")))?c.datepicker.formatDate("yy-mm-dd",k):i.attr("value")}catch(u){k=i.attr("value")}if(!c("input.input-datetime-local-time",e).attr("value")){m="00:00";c("input.input-datetime-local-time",e).attr("value",m)}p["datetime-local"].blockAttr=true;d.attr("value",
k+"T"+m);p["datetime-local"].blockAttr=false;d.trigger("change")}).data("datepicker").dpDiv.addClass("input-date-datepicker-control");c("input.input-datetime-local-time",e).bind("input change",function(){var k=d.attr("value").split("T");if(k.length<2||!k[0])k[0]=c.datepicker.formatDate("yy-mm-dd",new Date);k[1]=c.attr(this,"value");p["datetime-local"].blockAttr=true;try{i.attr("value",c.datepicker.formatDate(i.datepicker("option","dateFormat"),c.datepicker.parseDate("yy-mm-dd",k[0])))}catch(m){}d.attr("value",
k.join("T"));p["datetime-local"].blockAttr=false;d.trigger("change")});c.each(["disabled","min","max","value","step"],function(k,m){d.attr(m,function(u,j){return j||""})})}};p["datetime-local"].attrs={disabled:function(d,e,b){c("input.input-datetime-local-date",e).datepicker("option","disabled",!!b);c("input.input-datetime-local-time",e).attr("disabled",!!b)},step:function(d,e,b){c("input.input-datetime-local-time",e).attr("step",b)},min:function(d,e,b){b=b.split?b.split("T"):[];try{b=c.datepicker.parseDate("yy-mm-dd",
b[0])}catch(i){b=false}b&&c("input.input-datetime-local-date",e).datepicker("option","minDate",b)},max:function(d,e,b){b=b.split?b.split("T"):[];try{b=c.datepicker.parseDate("yy-mm-dd",b[0])}catch(i){b=false}b&&c("input.input-datetime-local-date",e).datepicker("option","maxDate",b)},value:function(d,e,b){if(!p["datetime-local"].blockAttr){var i;b=b.split?b.split("T"):[];try{i=c.datepicker.parseDate("yy-mm-dd",b[0])}catch(k){i=false}if(i){c("input.input-datetime-local-date",e).datepicker("setDate",
i);c("input.input-datetime-local-time",e).attr("value",b[1]||"00:00")}else{c("input.input-datetime-local-date",e).attr("value",b[0]||"");c("input.input-datetime-local-time",e).attr("value",b[1]||"")}}}};p.date=function(d){if(c.fn.datepicker){var e=c('<input type="text" class="input-date" />'),b=this.common(d,e,p.date.attrs);if(b.css){e.css(b.css);b.outerWidth&&e.outerWidth(b.outerWidth)}e.datepicker(c.extend({},r.datepicker)).bind("change",function(){p.date.blockAttr=true;var i;try{i=(i=c.datepicker.parseDate(e.datepicker("option",
"dateFormat"),e.attr("value")))?c.datepicker.formatDate("yy-mm-dd",i):e.attr("value")}catch(k){i=e.attr("value")}d.attr("value",i);p.date.blockAttr=false;d.trigger("change")}).data("datepicker").dpDiv.addClass("input-date-datepicker-control");c.each(["disabled","min","max","value"],function(i,k){d.attr(k,function(m,u){return u||""})})}};p.date.attrs={disabled:function(d,e,b){e.datepicker("option","disabled",!!b)},min:function(d,e,b){try{b=c.datepicker.parseDate("yy-mm-dd",b)}catch(i){b=false}b&&e.datepicker("option",
"minDate",b)},max:function(d,e,b){try{b=c.datepicker.parseDate("yy-mm-dd",b)}catch(i){b=false}b&&e.datepicker("option","maxDate",b)},value:function(d,e,b){if(!p.date.blockAttr){try{var i=c.datepicker.parseDate("yy-mm-dd",b)}catch(k){i=false}i?e.datepicker("setDate",i):e.attr("value",b)}}};p.range=function(d){if(c.fn.slider){var e=c('<span class="input-range"><span class="ui-slider-handle" role="slider" tabindex="0" /></span>'),b=this.common(d,e,p.range.attrs),i=function(k,m){if(k.originalEvent){p.range.blockAttr=
true;d.attr("value",m.value);p.range.blockAttr=false;k.type=="slidechange"?d.trigger("change"):s.triggerInlineForm(d[0],"input")}};c("span",e).attr("aria-labeledby",b.label.attr("id"));b.label.bind("click",function(){c("span",e).focus();return false});if(b.css){e.css(b.css);b.outerWidth&&e.outerWidth(b.outerWidth)}e.slider(c.extend(r.slider,{change:i,slide:i}));c.each(["disabled","min","max","value","step"],function(k,m){d.attr(m,function(u,j){return j||""})})}};p.range.attrs={disabled:function(d,
e,b){b=!!b;e.slider("option","disabled",b);c("span",e).attr({"aria-disabled":b+"",tabindex:b?"-1":"0"})},min:function(d,e,b){b=b?b*1||0:0;e.slider("option","min",b);c("span",e).attr({"aria-valuemin":b})},max:function(d,e,b){b=b||b===0?b*1||100:100;e.slider("option","max",b);c("span",e).attr({"aria-valuemax":b})},value:function(d,e,b){b=c(d).attr("valueAsNumber");if(isNaN(b)){b=(e.slider("option","max")-e.slider("option","min"))/2;d.value=b}p.range.blockAttr||e.slider("option","value",b);c("span",
e).attr({"aria-valuenow":b,"aria-valuetext":b})},step:function(d,e,b){b=b&&c.trim(b)?b*1||1:1;e.slider("option","step",b)}};c.each(["disabled","min","max","value","step"],function(d,e){s.attr(e,{elementNames:["input"],setter:function(b,i,k){var m=c.data(b,"inputUIReplace");k();m&&m.methods[e]&&m.methods[e](b,m.visual,i)},getter:true})});var D=function(d){if(d){d=c.extend({},d,r.date);c("input.hasDatepicker").filter(".input-date, .input-datetime-local-date").datepicker("option",d).each(function(){var e=
c.data(this,"html5element");e&&c.each(["disabled","min","max","value"],function(b,i){e.attr(i,function(k,m){return m||""})})});c.datepicker.setDefaults(d)}};c(l).bind("jquery-uiReady.langchange input-widgetsReady.langchange",function(){c.datepicker&&c(l).bind("htmlExtLangChange",function(){s.activeLang(c.datepicker.regional,"inputUI",D)}).unbind("jquery-uiReady.langchange input-widgetsReady.langchange")});s.addReady(function(d){c(l).bind("jquery-uiReady.initinputui input-widgetsReady.initinputui",
function(){if(c.datepicker||c.fn.slider)p(d);c.datepicker&&c.fn.slider&&c(l).unbind("jquery-uiReady.initinputui input-widgetsReady.initinputui");d===l&&s.createReadyEvent("inputUI")})})},true);
