jQuery.webshims.register("dom-extend",function(e,g,r,h,n){var C=g.modules,t=/\s*,\s*/,k={},u={},l={},A={},s={},z=e.fn.val,B=function(b,a,c,d,f){return f?z.call(e(b)):z.call(e(b),c)};e.fn.val=function(b){var a=this[0];arguments.length&&null==b&&(b="");if(!arguments.length)return!a||1!==a.nodeType?z.call(this):e.prop(a,"value",b,"val",!0);if(e.isArray(b))return z.apply(this,arguments);var c=e.isFunction(b);return this.each(function(d){a=this;1===a.nodeType&&(c?(d=b.call(a,d,e.prop(a,"value",n,"val",
!0)),null==d&&(d=""),e.prop(a,"value",d,"val")):e.prop(a,"value",b,"val"))})};var o="_webshimsLib"+Math.round(1E3*Math.random()),x=function(b,a,c){b=b.jquery?b[0]:b;if(!b)return c||{};var d=e.data(b,o);c!==n&&(d||(d=e.data(b,o,{})),a&&(d[a]=c));return a?d&&d[a]:d};[{name:"getNativeElement",prop:"nativeElement"},{name:"getShadowElement",prop:"shadowElement"},{name:"getShadowFocusElement",prop:"shadowFocusElement"}].forEach(function(b){e.fn[b.name]=function(){return this.map(function(){var a=x(this,
"shadowData");return a&&a[b.prop]||this})}});["removeAttr","prop","attr"].forEach(function(b){k[b]=e[b];e[b]=function(a,c,d,f,v){var j="val"==f,i=!j?k[b]:B;if(!a||!u[c]||1!==a.nodeType||!j&&f&&"attr"==b&&e.attrFn[c])return i(a,c,d,f,v);var p=(a.nodeName||"").toLowerCase(),q=l[p],w="attr"==b&&(!1===d||null===d)?"removeAttr":b,g,m,h;q||(q=l["*"]);q&&(q=q[c]);q&&(g=q[w]);if(g){if("value"==c)m=g.isVal,g.isVal=j;if("removeAttr"===w)return g.value.call(a);if(d===n)return g.get?g.get.call(a):g.value;g.set&&
("attr"==b&&!0===d&&(d=c),h=g.set.call(a,d));if("value"==c)g.isVal=m}else h=i(a,c,d,f,v);if((d!==n||"removeAttr"===w)&&s[p]&&s[p][c]){var o;o="removeAttr"==w?!1:"prop"==w?!!d:!0;s[p][c].forEach(function(c){if(!c.only||(c.only="prop"==b)||"attr"==c.only&&"prop"!=b)c.call(a,d,o,j?"val":w,b)})}return h};A[b]=function(a,c,d){l[a]||(l[a]={});l[a][c]||(l[a][c]={});var f=l[a][c][b],v=function(a,f,p){return f&&f[a]?f[a]:p&&p[a]?p[a]:"prop"==b&&"value"==c?function(a){return d.isVal?B(this,c,a,!1,0===arguments.length):
k[b](this,c,a)}:"prop"==b&&"value"==a&&d.value.apply?function(a){var d=k[b](this,c);d&&d.apply&&(d=d.apply(this,arguments));return d}:function(a){return k[b](this,c,a)}};l[a][c][b]=d;if(d.value===n){if(!d.set)d.set=d.writeable?v("set",d,f):g.cfg.useStrict&&"prop"==c?function(){throw c+" is readonly on "+a;}:e.noop;if(!d.get)d.get=v("get",d,f)}["value","get","set"].forEach(function(a){d[a]&&(d["_sup"+a]=v(a,f))})}});var D=!e.browser.msie||8<parseInt(e.browser.version,10),E=function(){var b=g.getPrototypeOf(h.createElement("foobar")),
a=Object.prototype.hasOwnProperty;return function(c,d,f){var e=h.createElement(c),j=g.getPrototypeOf(e);if(D&&j&&b!==j&&(!e[d]||!a.call(e,d))){var i=e[d];f._supvalue=function(){return i&&i.apply?i.apply(this,arguments):i};j[d]=f.value}else f._supvalue=function(){var a=x(this,"propValue");return a&&a[d]&&a[d].apply?a[d].apply(this,arguments):a&&a[d]},m.extendValue(c,d,f.value);f.value._supvalue=f._supvalue}}(),m=function(){var b={};g.addReady(function(a,c){var d={},i=function(b){d[b]||(d[b]=e(a.getElementsByTagName(b)),
c[0]&&e.nodeName(c[0],b)&&(d[b]=d[b].add(c)))};e.each(b,function(a,b){i(a);!b||!b.forEach?g.warn("Error: with "+a+"-property. methods: "+b):b.forEach(function(b){d[a].each(b)})});d=null});var a,c=e([]),d=function(c,d){b[c]?b[c].push(d):b[c]=[d];e.isDOMReady&&(a||e(h.getElementsByTagName(c))).each(d)};return{createTmpCache:function(b){e.isDOMReady&&(a=a||e(h.getElementsByTagName(b)));return a||c},flushTmpCache:function(){a=null},content:function(a,b){d(a,function(){var a=e.attr(this,b);null!=a&&e.attr(this,
b,a)})},createElement:function(a,b){d(a,b)},extendValue:function(a,b,c){d(a,function(){e(this).each(function(){x(this,"propValue",{})[b]=this[b];this[b]=c})})}}}(),y=function(b,a){if(b.defaultValue===n)b.defaultValue="";if(!b.removeAttr)b.removeAttr={value:function(){b[a||"prop"].set.call(this,b.defaultValue);b.removeAttr._supvalue.call(this)}};if(!b.attr)b.attr={}};e.extend(g,{getID:function(){var b=(new Date).getTime();return function(a){var a=e(a),c=a.attr("id");c||(b++,c="ID-"+b,a.attr("id",c));
return c}}(),extendUNDEFProp:function(b,a){e.each(a,function(a,d){a in b||(b[a]=d)})},createPropDefault:y,data:x,moveToFirstEvent:function(){var b=e._data?"_data":"data";return function(a,c,d){if((a=(e[b](a,"events")||{})[c])&&1<a.length)c=a.pop(),d||(d="bind"),"bind"==d&&a.delegateCount?a.splice(a.delegateCount,0,c):a.unshift(c)}}(),addShadowDom:function(){var b,a,c,d={init:!1,runs:0,test:function(){var a=d.getHeight(),b=d.getWidth();a!=d.height||b!=d.width?(d.height=a,d.width=b,d.handler({type:"docresize"}),
d.runs++,30>d.runs&&setTimeout(d.test,30)):d.runs=0},handler:function(f){clearTimeout(b);b=setTimeout(function(){if("resize"==f.type){var b=e(r).width(),j=e(r).width();if(j==a&&b==c)return;a=j;c=b;d.height=d.getHeight();d.width=d.getWidth()}e.event.trigger("updateshadowdom")},10)},_create:function(){e.each({Height:"getHeight",Width:"getWidth"},function(a,b){var c=h.body,e=h.documentElement;d[b]=function(){return Math.max(c["scroll"+a],e["scroll"+a],c["offset"+a],e["offset"+a],e["client"+a])}})},start:function(){if(!this.init&&
h.body)this.init=!0,this._create(),this.height=d.getHeight(),this.width=d.getWidth(),setInterval(this.test,400),e(this.test),e(r).bind("load",this.test),e(r).bind("resize",this.handler)}};e.event.customEvent.updateshadowdom=!0;return function(a,b,c){c=c||{};a.jquery&&(a=a[0]);b.jquery&&(b=b[0]);var i=e.data(a,o)||e.data(a,o,{}),p=e.data(b,o)||e.data(b,o,{}),q={};if(c.shadowFocusElement){if(c.shadowFocusElement){if(c.shadowFocusElement.jquery)c.shadowFocusElement=c.shadowFocusElement[0];q=e.data(c.shadowFocusElement,
o)||e.data(c.shadowFocusElement,o,q)}}else c.shadowFocusElement=b;i.hasShadow=b;q.nativeElement=p.nativeElement=a;q.shadowData=p.shadowData=i.shadowData={nativeElement:a,shadowElement:b,shadowFocusElement:c.shadowFocusElement};c.shadowChilds&&c.shadowChilds.each(function(){x(this,"shadowData",p.shadowData)});if(c.data)q.shadowData.data=p.shadowData.data=i.shadowData.data=c.data;c=null;g.ready("DOM",function(){d.start()})}}(),propTypes:{standard:function(b){y(b);if(!b.prop)b.prop={set:function(a){b.attr.set.call(this,
""+a)},get:function(){return b.attr.get.call(this)||b.defaultValue}}},"boolean":function(b){y(b);if(!b.prop)b.prop={set:function(a){a?b.attr.set.call(this,""):b.removeAttr.value.call(this)},get:function(){return null!=b.attr.get.call(this)}}},src:function(){var b=h.createElement("a");b.style.display="none";return function(a,c){y(a);if(!a.prop)a.prop={set:function(b){a.attr.set.call(this,b)},get:function(){var a=this.getAttribute(c),f;if(null==a)return"";b.setAttribute("href",a+"");if(!e.support.hrefNormalized){try{e(b).insertAfter(this),
f=b.getAttribute("href",4)}catch(g){f=b.getAttribute("href",4)}e(b).detach()}return f||b.href}}}}(),enumarated:function(b){y(b);if(!b.prop)b.prop={set:function(a){b.attr.set.call(this,a)},get:function(){var a=(b.attr.get.call(this)||"").toLowerCase();if(!a||-1==b.limitedTo.indexOf(a))a=b.defaultValue;return a}}}},reflectProperties:function(b,a){"string"==typeof a&&(a=a.split(t));a.forEach(function(a){g.defineNodeNamesProperty(b,a,{prop:{set:function(b){e.attr(this,a,b)},get:function(){return e.attr(this,
a)||""}}})})},defineNodeNameProperty:function(b,a,c){u[a]=!0;if(c.reflect)g.propTypes[c.propType||"standard"](c,a);["prop","attr","removeAttr"].forEach(function(d){var f=c[d];f&&(f="prop"===d?e.extend({writeable:!0},f):e.extend({},f,{writeable:!0}),A[d](b,a,f),"*"!=b&&g.cfg.extendNative&&"prop"==d&&f.value&&e.isFunction(f.value)&&E(b,a,f),c[d]=f)});c.initAttr&&m.content(b,a);return c},defineNodeNameProperties:function(b,a,c,d){for(var e in a)!d&&a[e].initAttr&&m.createTmpCache(b),c&&!a[e][c]&&(a[e][c]=
{},["value","set","get"].forEach(function(b){b in a[e]&&(a[e][c][b]=a[e][b],delete a[e][b])})),a[e]=g.defineNodeNameProperty(b,e,a[e]);d||m.flushTmpCache();return a},createElement:function(b,a,c){var d;e.isFunction(a)&&(a={after:a});m.createTmpCache(b);a.before&&m.createElement(b,a.before);c&&(d=g.defineNodeNameProperties(b,c,!1,!0));a.after&&m.createElement(b,a.after);m.flushTmpCache();return d},onNodeNamesPropertyModify:function(b,a,c,d){"string"==typeof b&&(b=b.split(t));e.isFunction(c)&&(c={set:c});
b.forEach(function(b){s[b]||(s[b]={});"string"==typeof a&&(a=a.split(t));c.initAttr&&m.createTmpCache(b);a.forEach(function(a){s[b][a]||(s[b][a]=[],u[a]=!0);if(c.set){if(d)c.set.only=d;s[b][a].push(c.set)}c.initAttr&&m.content(b,a)});m.flushTmpCache()})},defineNodeNamesBooleanProperty:function(b,a,c){c||(c={});if(e.isFunction(c))c.set=c;g.defineNodeNamesProperty(b,a,{attr:{set:function(b){this.setAttribute(a,b);c.set&&c.set.call(this,!0)},get:function(){return null==this.getAttribute(a)?n:a}},removeAttr:{value:function(){this.removeAttribute(a);
c.set&&c.set.call(this,!1)}},reflect:!0,propType:"boolean",initAttr:c.initAttr||!1})},contentAttr:function(b,a,c){if(b.nodeName){if(c===n)return b=b.attributes[a]||{},c=b.specified?b.value:null,null==c?n:c;"boolean"==typeof c?c?b.setAttribute(a,a):b.removeAttribute(a):b.setAttribute(a,c)}},activeLang:function(){var b=[],a={},c,d,f=/:\/\/|^\.*\//,h=function(a,b,c){return b&&c&&-1!==e.inArray(b,c.availabeLangs||[])?(a.loading=!0,c=c.langSrc,f.test(c)||(c=g.cfg.basePath+c),g.loader.loadScript(c+b+".js",
function(){a.langObj[b]?(a.loading=!1,i(a,!0)):e(function(){a.langObj[b]&&i(a,!0);a.loading=!1})}),!0):!1},j=function(b){a[b]&&a[b].forEach(function(a){a.callback()})},i=function(a,b){if(a.activeLang!=c&&a.activeLang!==d){var e=C[a.module].options;if(a.langObj[c]||d&&a.langObj[d])a.activeLang=c,a.callback(a.langObj[c]||a.langObj[d],c),j(a.module);else if(!b&&!h(a,c,e)&&!h(a,d,e)&&a.langObj[""]&&""!==a.activeLang)a.activeLang="",a.callback(a.langObj[""],c),j(a.module)}};return function(f){if("string"==
typeof f&&f!==c)c=f,d=c.split("-")[0],c==d&&(d=!1),e.each(b,function(a,b){i(b)});else if("object"==typeof f)if(f.register)a[f.register]||(a[f.register]=[]),a[f.register].push(f),f.callback();else{if(!f.activeLang)f.activeLang="";b.push(f);i(f)}return c}}()});e.each({defineNodeNamesProperty:"defineNodeNameProperty",defineNodeNamesProperties:"defineNodeNameProperties",createElements:"createElement"},function(b,a){g[b]=function(b,d,e,h){"string"==typeof b&&(b=b.split(t));var j={};b.forEach(function(b){j[b]=
g[a](b,d,e,h)});return j}});g.isReady("webshimLocalization",!0)});
(function(e,g){var r=e.webshims.browserVersion;if(!(e.browser.mozilla&&5<r)&&(!e.browser.msie||12>r&&7<r)){var h={article:"article",aside:"complementary",section:"region",nav:"navigation",address:"contentinfo"},n=function(e,g){e.getAttribute("role")||e.setAttribute("role",g)};e.webshims.addReady(function(r,t){e.each(h,function(g,h){for(var k=e(g,r).add(t.filter(g)),l=0,o=k.length;l<o;l++)n(k[l],h)});if(r===g){var k=g.getElementsByTagName("header")[0],u=g.getElementsByTagName("footer"),l=u.length;
k&&!e(k).closest("section, article")[0]&&n(k,"banner");l&&(k=u[l-1],e(k).closest("section, article")[0]||n(k,"contentinfo"))}})}})(jQuery,document);
