(function(){var j=Object.prototype.hasOwnProperty;if(!Array.isArray)Array.isArray=function(b){return Object.prototype.toString.call(b)=="[object Array]"};if(!Array.prototype.forEach)Array.prototype.forEach=function(b,c){for(var a=this.length>>>0,d=0;d<a;d++)d in this&&b.call(c,this[d],d,this)};if(!Array.prototype.map)Array.prototype.map=function(b,c){var a=this.length>>>0;if(typeof b!="function")throw new TypeError;for(var d=Array(a),e=0;e<a;e++)if(e in this)d[e]=b.call(c,this[e],e,this);return d};
if(!Array.prototype.filter)Array.prototype.filter=function(b,c){for(var a=[],d=0;d<this.length;d++)b.call(c,this[d])&&a.push(this[d]);return a};if(!Array.prototype.every)Array.prototype.every=function(b,c){for(var a=0;a<this.length;a++)if(!b.call(c,this[a]))return false;return true};if(!Array.prototype.some)Array.prototype.some=function(b,c){for(var a=0;a<this.length;a++)if(b.call(c,this[a]))return true;return false};if(!Array.prototype.reduce)Array.prototype.reduce=function(b){var c=this.length>>>
0;if(typeof b!="function")throw new TypeError;if(c==0&&arguments.length==1)throw new TypeError;var a=0;if(arguments.length>=2)var d=arguments[1];else{do{if(a in this){d=this[a++];break}if(++a>=c)throw new TypeError;}while(1)}for(;a<c;a++)if(a in this)d=b.call(null,d,this[a],a,this);return d};if(!Array.prototype.reduceRight)Array.prototype.reduceRight=function(b){var c=this.length>>>0;if(typeof b!="function")throw new TypeError;if(c==0&&arguments.length==1)throw new TypeError;c=c-1;if(arguments.length>=
2)var a=arguments[1];else{do{if(c in this){a=this[c--];break}if(--c<0)throw new TypeError;}while(1)}for(;c>=0;c--)if(c in this)a=b.call(null,a,this[c],c,this);return a};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(b,c){var a=this.length;if(!a)return-1;var d=c||0;if(d>=a)return-1;if(d<0)d+=a;for(;d<a;d++)if(j.call(this,d))if(b===this[d])return d;return-1};if(!Array.prototype.lastIndexOf)Array.prototype.lastIndexOf=function(b,c){var a=this.length;if(!a)return-1;var d=c||a;if(d<0)d+=
a;for(d=Math.min(d,a-1);d>=0;d--)if(j.call(this,d))if(b===this[d])return d;return-1};if((!Object.create||!Object.defineProperties)&&window.jQuery&&jQuery.webshims){var k=jQuery.webshims;k.objectCreate=function(b,c){var a=function(){};a.prototype=b;a=new a;c&&k.defineProperties(a,c);return a};k.defineProperties=function(b,c){for(var a in c)j.call(c,a)&&k.defineProperty(b,a,c[a]);return b};k.defineProperty=function(b,c,a){if(typeof a!="object")return b;if(j.call(a,"value")){b[c]=a.value;return b}if(Object.defineProperty)try{Object.defineProperty(b,
c,a)}catch(d){}if(b.__defineGetter__){typeof a.get=="function"&&b.__defineGetter__(c,a.get);typeof a.set=="function"&&b.__defineSetter__(c,a.set)}return b}}if(!Object.keys){var n=true,q=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","constructor"];for(var u in{toString:null})n=false;Object.keys=function(b){if(typeof b!=="object"&&typeof b!=="function"||b===null)throw new TypeError("Object.keys called on a non-object");var c=[];for(var a in b)j.call(b,
a)&&c.push(a);if(n){b=0;for(a=dontEnumLength;b<a;b++){var d=q[b];j.call(o,d)&&c.push(d)}}return c}}if(!Date.prototype.toISOString)Date.prototype.toISOString=function(){return this.getFullYear()+"-"+(this.getMonth()+1)+"-"+this.getDate()+"T"+this.getHours()+":"+this.getMinutes()+":"+this.getSeconds()+"Z"};if(!Date.now)Date.now=function(){return(new Date).getTime()};if(!Date.prototype.toJSON)Date.prototype.toJSON=function(){if(typeof this.toISOString!="function")throw new TypeError;return this.toISOString()};
if(isNaN(Date.parse("T00:00")))Date=function(b){var c=function(e,f,h,g,l,p,r){var i=arguments.length;if(this instanceof b){i=i===1&&String(e)===e?new b(c.parse(e)):i>=7?new b(e,f,h,g,l,p,r):i>=6?new b(e,f,h,g,l,p):i>=5?new b(e,f,h,g,l):i>=4?new b(e,f,h,g):i>=3?new b(e,f,h):i>=2?new b(e,f):i>=1?new b(e):new b;i.constructor=c;return i}return b.apply(this,arguments)},a=RegExp("^(?:((?:[+-]\\d\\d)?\\d\\d\\d\\d)(?:-(\\d\\d)(?:-(\\d\\d))?)?)?(?:T(\\d\\d):(\\d\\d)(?::(\\d\\d)(?:\\.(\\d\\d\\d))?)?)?(?:Z|([+-])(\\d\\d):(\\d\\d))?$");
for(var d in b)c[d]=b[d];c.now=b.now;c.UTC=b.UTC;c.prototype=b.prototype;c.prototype.constructor=c;c.parse=function(e){var f=a.exec(e);if(f){f.shift();for(var h=f[0]===undefined,g=0;g<10;g++)if(g!==7){f[g]=+(f[g]||(g<3?1:0));g===1&&f[g]--}if(h)return((f[3]*60+f[4])*60+f[5])*1E3+f[6];h=(f[8]*60+f[9])*60*1E3;if(f[6]==="-")h=-h;return b.UTC.apply(this,f.slice(0,7))+h}return b.parse.apply(this,arguments)};return c}(Date);var m=Array.prototype.slice;if(!Function.prototype.bind)Function.prototype.bind=
function(b){var c=this;if(typeof c.apply!="function"||typeof c.call!="function")return new TypeError;var a=m.call(arguments),d=function(){if(this instanceof d){var e=Object.create(c.prototype);c.apply(e,a.concat(m.call(arguments)));return e}else return c.call.apply(c,a.concat(m.call(arguments)))};d.bound=c;d.boundTo=b;d.boundArgs=a;d.length=typeof c=="function"?Math.max(c.length-a.length,0):0;return d};if(!String.prototype.trim){var s=/^\s\s*/,t=/\s\s*$/;String.prototype.trim=function(){return String(this).replace(s,
"").replace(t,"")}}})();
