(function(){if(!Modernizr.ES5){var j=Object.prototype.hasOwnProperty,m=Object.prototype.toString;if(!Array.isArray)Array.isArray=function(a){return m.call(a)=="[object Array]"};if(!Object.keys){var l=true,g=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","constructor"],e=g.length;for(var d in{toString:null})l=false;Object.keys=function(a){if(typeof a!=="object"&&typeof a!=="function"||a===null)throw new TypeError("Object.keys called on a non-object");
var f=[];for(var c in a)j.call(a,c)&&f.push(c);if(l)for(c=0;c<e;c++){var h=g[c];j.call(a,h)&&f.push(h)}return f}}if((!Modernizr.advancedObjectProperties||!Object.create||!Object.defineProperties||!Object.getOwnPropertyDescriptor||!Object.defineProperty)&&window.jQuery&&jQuery.webshims){var b=jQuery.webshims;b.objectCreate=function(a,f,c){var h=function(){};h.prototype=a;a=new h;f&&b.defineProperties(a,f);if(c){a.options=jQuery.extend(true,{},a.options||{},c);c=a.options}a._create&&jQuery.isFunction(a._create)&&
a._create(c);return a};b.defineProperties=function(a,f){for(var c in f)j.call(f,c)&&b.defineProperty(a,c,f[c]);return a};var i=["configurable","enumerable","writable"];b.defineProperty=function(a,f,c){if(typeof c!="object")return a;if(Object.defineProperty){for(var h=0;h<3;h++)if(!(i[h]in c)&&(i[h]!=="writable"||c.value!==undefined))c[i[h]]=true;try{Object.defineProperty(a,f,c);return}catch(k){}}if(j.call(c,"value")){a[f]=c.value;return a}if(a.__defineGetter__){typeof c.get=="function"&&a.__defineGetter__(f,
c.get);typeof c.set=="function"&&a.__defineSetter__(f,c.set)}return a};b.getPrototypeOf=function(a){return Object.getPrototypeOf&&Object.getPrototypeOf(a)||a.__proto__||a.constructor&&a.constructor.prototype};b.getOwnPropertyDescriptor=function(a,f){if(typeof a!=="object"&&typeof a!=="function"||a===null)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object");var c;if(Object.defineProperty&&Object.getOwnPropertyDescriptor)try{return c=Object.getOwnPropertyDescriptor(a,f)}catch(h){}c=
{configurable:true,enumerable:true,writable:true,value:undefined};var k=a.__lookupGetter__&&a.__lookupGetter__(f),n=a.__lookupSetter__&&a.__lookupSetter__(f);if(!k&&!n){if(!j.call(a,f))return;c.value=a[f];return c}delete c.writable;delete c.value;c.get=c.set=undefined;if(k)c.get=k;if(n)c.set=n;return c}}var o=Array.prototype.slice;if(!Function.prototype.bind)Function.prototype.bind=function(a){var f=this;if(typeof f.apply!="function"||typeof f.call!="function")return new TypeError;var c=o.call(arguments),
h=function(){if(this instanceof h){var k=Object.create(f.prototype);f.apply(k,c.concat(o.call(arguments)));return k}else return f.call.apply(f,c.concat(o.call(arguments)))};h.bound=f;h.boundTo=a;h.boundArgs=c;h.length=typeof f=="function"?Math.max(f.length-c.length,0):0;return h}}})();
(function(){if(!Modernizr.ES5base){var j=Object.prototype.hasOwnProperty;if(!Array.prototype.forEach)Array.prototype.forEach=function(g,e){for(var d=+this.length,b=0;b<d;b++)b in this&&g.call(e,this[b],b,this)};if(!Array.prototype.map)Array.prototype.map=function(g,e){var d=+this.length;if(typeof g!="function")throw new TypeError;for(var b=Array(d),i=0;i<d;i++)if(i in this)b[i]=g.call(e,this[i],i,this);return b};if(!Array.prototype.filter)Array.prototype.filter=function(g,e){for(var d=[],b=0;b<this.length;b++)g.call(e,
this[b])&&d.push(this[b]);return d};if(!Array.prototype.every)Array.prototype.every=function(g,e){for(var d=0;d<this.length;d++)if(!g.call(e,this[d]))return false;return true};if(!Array.prototype.some)Array.prototype.some=function(g,e){for(var d=0;d<this.length;d++)if(g.call(e,this[d]))return true;return false};if(!Array.prototype.reduce)Array.prototype.reduce=function(g){var e=+this.length;if(typeof g!="function")throw new TypeError;if(e==0&&arguments.length==1)throw new TypeError;var d=0;if(arguments.length>=
2)var b=arguments[1];else{do{if(d in this){b=this[d++];break}if(++d>=e)throw new TypeError;}while(1)}for(;d<e;d++)if(d in this)b=g.call(null,b,this[d],d,this);return b};if(!Array.prototype.reduceRight)Array.prototype.reduceRight=function(g){var e=+this.length;if(typeof g!="function")throw new TypeError;if(e==0&&arguments.length==1)throw new TypeError;e=e-1;if(arguments.length>=2)var d=arguments[1];else{do{if(e in this){d=this[e--];break}if(--e<0)throw new TypeError;}while(1)}for(;e>=0;e--)if(e in
this)d=g.call(null,d,this[e],e,this);return d};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(g,e){var d=this.length;if(!d)return-1;var b=e||0;if(b>=d)return-1;if(b<0)b+=d;for(;b<d;b++)if(j.call(this,b))if(g===this[b])return b;return-1};if(!Array.prototype.lastIndexOf)Array.prototype.lastIndexOf=function(g,e){var d=this.length;if(!d)return-1;var b=e||d;if(b<0)b+=d;for(b=Math.min(b,d-1);b>=0;b--)if(j.call(this,b))if(g===this[b])return b;return-1};if(!Date.prototype.toISOString)Date.prototype.toISOString=
function(){return this.getUTCFullYear()+"-"+(this.getUTCMonth()+1)+"-"+this.getUTCDate()+"T"+this.getUTCHours()+":"+this.getUTCMinutes()+":"+this.getUTCSeconds()+"Z"};if(!Date.now)Date.now=function(){return(new Date).getTime()};if(!Date.prototype.toJSON)Date.prototype.toJSON=function(){if(typeof this.toISOString!="function")throw new TypeError;return this.toISOString()};if(!String.prototype.trim){var m=/^\s\s*/,l=/\s\s*$/;String.prototype.trim=function(){return String(this).replace(m,"").replace(l,
"")}}}})();
