jQuery.webshims.gcEval=function(b,h){with(h&&h.form||window)with(h||window)return function(s){eval(s)}.call(h||window,b)};
jQuery.webshims.register("form-core",function(b,h,s,o,B,t){h.getVisualInput=function(a){a=b(a);return(a.data("inputUIReplace")||{visual:a}).visual};var r=h.getVisualInput,u={checkbox:1,radio:1},C=b([]),v=function(a){a=b(a);return u[a[0].type]&&a[0].name?b(o.getElementsByName(a[0].name)).not(a[0]):C},y={number:1,range:1,date:1,time:1,"datetime-local":1,datetime:1,month:1,week:1};b.extend(b.expr.filters,{"valid-element":function(a){return!!(b.attr(a,"willValidate")&&(b.attr(a,"validity")||{valid:true}).valid)},
"invalid-element":function(a){return!!(b.attr(a,"willValidate")&&!w(a))},"required-element":function(a){return!!(b.attr(a,"willValidate")&&b.attr(a,"required")===true)},"optional-element":function(a){return!!(b.attr(a,"willValidate")&&b.attr(a,"required")===false)},"in-range":function(a){if(!y[b.attr(a,"type")]||!b.attr(a,"willValidate"))return false;a=b.attr(a,"validity");return!!(a&&!a.rangeOverflow&&!a.rangeUnderflow)},"out-of-range":function(a){if(!y[b.attr(a,"type")]||!b.attr(a,"willValidate"))return false;
a=b.attr(a,"validity");return!!(a&&(a.rangeOverflow||a.rangeUnderflow))}});["valid","invalid","required","optional"].forEach(function(a){b.expr.filters[a]=b.expr.filters[a+"-element"]});var w=function(a){return(b.attr(a,"validity")||{valid:true}).valid},z=b.attr,D={selectedIndex:1,value:1,checked:1,disabled:1,readonly:1},x;b.attr=function(a,e,f){if(a&&"form"in a&&D[e]&&f!==B&&b(a).hasClass("form-ui-invalid")){var c=z.apply(this,arguments);if(w(a)){r(a).removeClass("form-ui-invalid");e=="checked"&&
f&&v(a).removeClass("form-ui-invalid").removeAttr("aria-invalid")}return c}return z.apply(this,arguments)};b(document).bind("focusout change refreshValidityStyle",function(a){if(!(x||!a.target||!a.target.form||a.target.type=="submit")){var e=(b.data(a.target,"html5element")||[])[0]||a.target;if(b.attr(e,"willValidate")){var f,c;if(w(a.target)){f="form-ui-valid";c="form-ui-invalid";u[a.target.type]&&a.target.checked&&v(e).removeClass(c).removeAttr("aria-invalid")}else{f="form-ui-invalid";c="form-ui-valid";
u[a.target.type]&&!a.target.checked&&v(e).removeClass(c)}r(e).addClass(f).removeClass(c);x=true;setTimeout(function(){x=false},9)}else r(e).removeClass("form-ui-invalid form-ui-valid")}});h.triggerInlineForm=function(a,e){var f=a["on"+e]||a.getAttribute("on"+e)||"",c;e=b.Event({type:e,target:a[0],currentTarget:a[0]});if(f&&typeof f=="string")c=h.gcEval(f,a);if(c===false){e.stopPropagation();e.preventDefault()}b(a).trigger(e);return c};var A=function(){h.scrollRoot=b.browser.webkit||o.compatMode==
"BackCompat"?b(o.body):b(o.documentElement)};A();h.ready("DOM",A);h.validityAlert=function(){var a=!b.browser.msie||parseInt(b.browser.version,10)>7?"span":"label",e={hideDelay:5E3,showFor:function(g,i,l){g=b(g);var n=r(g);m();e.clear();this.getMessage(g,i);this.position(n);f.css({fontSize:g.css("fontSize"),fontFamily:g.css("fontFamily")});this.show();if(this.hideDelay)c=setTimeout(d,this.hideDelay);l||this.setFocus(n,g[0])},setFocus:function(g,i){var l=b("input, select, textarea, .ui-slider-handle",
g).filter(":visible:first");l[0]||(l=g);var n=h.scrollRoot.scrollTop(),p=l.offset().top,q;h.getID&&a=="label"&&f.attr("for",h.getID(l));if(n>p){if((q=i.id&&b('label[for="'+i.id+'"]',i.form).offset())&&q.top<p)p=q.top;h.scrollRoot.animate({scrollTop:p-5},{queue:false,duration:Math.max(Math.min(600,(n-p)*1.5),80)});q=true}try{l[0].focus()}catch(E){}if(q){h.scrollRoot.scrollTop(n);setTimeout(function(){h.scrollRoot.scrollTop(n)},0)}setTimeout(function(){b(o).bind("focusout.validityalert",d)},10)},getMessage:function(g,
i){b("> span.va-box",f).text(i||h.getContentValidationMessage(g)||g.attr("validationMessage"))},position:function(g){var i=g.offset();i.top+=g.outerHeight();f.css(i)},show:function(){f.css("display")==="none"&&f.css({opacity:0}).show();f.fadeTo(400,1)},hide:function(){e.clear();f.fadeOut()},clear:function(){clearTimeout(j);clearTimeout(c);b(o).unbind("focusout.validityalert");f.stop().removeAttr("for")},errorBubble:b("<"+a+' class="validity-alert" role="alert"><span class="va-arrow"><span class="va-arrow-box"></span></span><span class="va-box"></span></'+
a+">").css({position:"absolute",display:"none"})},f=e.errorBubble,c=false,j=false,d=b.proxy(e,"hide"),k=false,m=function(){if(!k){k=true;b(function(){f.appendTo("body");b.fn.bgIframe&&b.browser.msie&&parseInt(b.browser.version,10)<7&&f.bgIframe()})}};m();return e}();(function(){var a,e=[],f;b(document).bind("invalid",function(c){if(!c.wrongWebkitInvalid){var j=b(c.target).addClass("form-ui-invalid").removeClass("form-ui-valid");if(!a){a=b.Event("firstinvalid");a.isInvalidUIPrevented=c.isDefaultPrevented;
var d=b.Event("firstinvalidsystem");b(document).triggerHandler(d,{element:c.target,form:c.target.form,isInvalidUIPrevented:c.isDefaultPrevented});j.trigger(a)}a&&a.isDefaultPrevented()&&c.preventDefault();e.push(c.target);c.extraData="fix";clearTimeout(f);f=setTimeout(function(){var k={type:"lastinvalid",cancelable:false,invalidlist:b(e)};a=false;e=[];j.trigger(k,k)},9)}})})();t.replaceValidationUI&&b(function(){b(document).bind("firstinvalid",function(a){if(!a.isInvalidUIPrevented()){a.preventDefault();
b.webshims.validityAlert.showFor(a.target,b(a.target).attr("customValidationMessage"))}})});(function(){var a=h.validityMessages,e=t.overrideMessages||t.customMessages?["customValidationMessage"]:[];a.en=a.en||a["en-US"]||{typeMismatch:{email:"Please enter an email address.",url:"Please enter a URL.",number:"Please enter a number.",date:"Please enter a date.",time:"Please enter a time.",range:"Invalid input.","datetime-local":"Please enter a datetime."},rangeUnderflow:"Value must be greater than or equal to {%min}.",
rangeOverflow:"Value must be less than or equal to {%max}.",stepMismatch:"Invalid input.",tooLong:"Please enter at most {%maxlength} character(s). You entered {%valueLen}.",patternMismatch:"Invalid input. {%title}",valueMissing:{defaultMessage:"Please fill out this field.",checkbox:"Please check this box if you want to proceed."}};["date","time","datetime-local"].forEach(function(c){a.en.rangeUnderflow[c]="Value must be at or after {%min}."});["date","time","datetime-local"].forEach(function(c){a.en.rangeOverflow[c]=
"Value must be at or before {%max}."});["select-one","radio"].forEach(function(c){a.en.valueMissing[c]="Please select an option."});a["en-US"]=a["en-US"]||a.en;a[""]=a[""]||a["en-US"];a.de=a.de||{typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},
rangeUnderflow:{defaultMessage:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen."},rangeOverflow:{defaultMessage:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen."},stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",patternMismatch:"{%value} hat f\u00fcr dieses Eingabefeld ein falsches Format! {%title}",
valueMissing:{defaultMessage:"Bitte geben Sie einen Wert ein",checkbox:"Bitte aktivieren Sie das K\u00e4stchen"}};["date","time","datetime-local"].forEach(function(c){a.de.rangeUnderflow[c]="{%value} ist zu fr\u00fch. {%min} ist die fr\u00fcheste Zeit, die Sie benutzen k\u00f6nnen."});["date","time","datetime-local"].forEach(function(c){a.de.rangeOverflow[c]="{%value} ist zu sp\u00e4t. {%max} ist die sp\u00e4teste Zeit, die Sie benutzen k\u00f6nnen."});["select-one","radio"].forEach(function(c){a.de.valueMissing[c]=
"Bitte w\u00e4hlen Sie eine Option aus"});var f=a[""];b(o).bind("webshimLocalizationReady",function(){h.activeLang(a,"form-core",function(c){f=c})});h.createValidationMessage=function(c,j){var d=f[j];if(d&&typeof d!=="string")d=d[(c.getAttribute("type")||"").toLowerCase()||c.type||"defaultMessage"]||d.defaultMessage;d&&["value","min","max","title","maxlength","label"].forEach(function(k){if(d.indexOf("{%"+k)!==-1){var m=(k=="label"?b.trim(b('label[for="'+c.id+'"]',c.form).text()).replace(/\*$|:$/,
""):b.attr(c,k))||"";d=d.replace("{%"+k+"}",m);if("value"==k)d=d.replace("{%valueLen}",m.length)}});return d||""};h.getContentValidationMessage=function(c,j){var d=c.getAttribute("x-moz-errormessage")||c.getAttribute("data-errormessage")||"";if(d&&d.indexOf("{")){try{d=jQuery.parseJSON(d)}catch(k){return d}if(typeof d=="object"){j=j||b.attr(c,"validity")||{valid:1};j.valid||b.each(j,function(m,g){if(g&&m!="valid"&&d[m]){d=d[m];return false}})}if(typeof d=="object")d=d[defaultMessage]}return d||""};
if(!s.noHTMLExtFixes&&!Modernizr.validationmessage||!Modernizr.formvalidation)e.push("validationMessage");jQuery.webshims.ready("dom-support",function(c,j){e.forEach(function(d){["input","select","textarea","fieldset","output","button"].forEach(function(k){var m=j.defineNodeNameProperty(k,d,{get:function(){var g=this,i="";if(!c.attr(g,"willValidate"))return i;var l=c.attr(g,"validity")||{valid:1};if(l.valid)return i;if(i=j.getContentValidationMessage(g,l))return i;if(l.customError&&g.nodeName)if(i=
Modernizr.validationmessage&&m._supget?m._supget.call(g):c.data(g,"customvalidationMessage"))return i;c.each(l,function(n,p){if(!(n=="valid"||!p))if(i=j.createValidationMessage(g,n))return false});return i||""},set:c.noop})})})})})()});
