if(!jQuery.support.jsonStorage)jQuery.support.jsonStorage="shim";
(function(){if(!("JSON"in window)){if(!this.JSON)this.JSON={};(function(){function q(c){return c<10?"0"+c:c}function o(c){j.lastIndex=0;return j.test(c)?'"'+c.replace(j,function(k){var d=e[k];return typeof d==="string"?d:"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+c+'"'}function n(c,k){var d,f,l,r,p=a,i,b=k[c];if(b&&typeof b==="object"&&typeof b.toJSON==="function")b=b.toJSON(c);if(typeof m==="function")b=m.call(k,c,b);switch(typeof b){case "string":return o(b);case "number":return isFinite(b)?
String(b):"null";case "boolean":case "null":return String(b);case "object":if(!b)return"null";a+=g;i=[];if(Object.prototype.toString.apply(b)==="[object Array]"){r=b.length;for(d=0;d<r;d+=1)i[d]=n(d,b)||"null";l=i.length===0?"[]":a?"[\n"+a+i.join(",\n"+a)+"\n"+p+"]":"["+i.join(",")+"]";a=p;return l}if(m&&typeof m==="object"){r=m.length;for(d=0;d<r;d+=1){f=m[d];if(typeof f==="string")if(l=n(f,b))i.push(o(f)+(a?": ":":")+l)}}else for(f in b)if(Object.hasOwnProperty.call(b,f))if(l=n(f,b))i.push(o(f)+
(a?": ":":")+l);l=i.length===0?"{}":a?"{\n"+a+i.join(",\n"+a)+"\n"+p+"}":"{"+i.join(",")+"}";a=p;return l}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+q(this.getUTCMonth()+1)+"-"+q(this.getUTCDate())+"T"+q(this.getUTCHours())+":"+q(this.getUTCMinutes())+":"+q(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var h=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
j=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a,g,e={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;if(typeof JSON.stringify!=="function")JSON.stringify=function(c,k,d){var f;g=a="";if(typeof d==="number")for(f=0;f<d;f+=1)g+=" ";else if(typeof d==="string")g=d;if((m=k)&&typeof k!=="function"&&(typeof k!=="object"||typeof k.length!=="number"))throw Error("JSON.stringify");return n("",
{"":c})};if(typeof JSON.parse!=="function")JSON.parse=function(c,k){function d(l,r){var p,i,b=l[r];if(b&&typeof b==="object")for(p in b)if(Object.hasOwnProperty.call(b,p)){i=d(b,p);if(i!==undefined)b[p]=i;else delete b[p]}return k.call(l,r,b)}var f;c=String(c);h.lastIndex=0;if(h.test(c))c=c.replace(h,function(l){return"\\u"+("0000"+l.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(c.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){f=eval("("+c+")");return typeof k==="function"?d({"":f},""):f}throw new SyntaxError("JSON.parse");}})();window.localStorage&&window.sessionStorage&&$.webshims.createReadyEvent("json-storage")}})();
if(!window.localStorage||!window.sessionStorage)(function(){var q=function(o){function n(a,g,e){var m;if(e){m=new Date;m.setTime(m.getTime()+e*24*60*60*1E3);e="; expires="+m.toGMTString()}else e="";document.cookie=a+"="+g+e+"; path=/"}function h(a){a=JSON.stringify(a);if(o=="session")window.top.name=a;else n("localStorage",a,365)}var j=function(){var a;if(o=="session")a=window.top.name;else a:{a=document.cookie.split(";");var g,e;for(g=0;g<a.length;g++){for(e=a[g];e.charAt(0)==" ";)e=e.substring(1,
e.length);if(e.indexOf("localStorage=")===0){a=e.substring(13,e.length);break a}}a=null}return(a=a)?JSON.parse(a):{}}();return{clear:function(){j={};if(o=="session")window.top.name="";else n("localStorage","",365)},getItem:function(a){return a in j?j[a]:null},key:function(a){var g=0;for(var e in j)if(g==a)return e;else g++;return null},removeItem:function(a){delete j[a];h(j)},setItem:function(a,g){j[a]=g+"";h(j)}}};if(!window.sessionStorage)window.sessionStorage=new q("session");(function(){var o;
$.webshims.localStorageSwfCallback=function(n){clearTimeout(o);if(!window.localStorage){if(n==="swf"){var h=document.getElementById("swflocalstorageshim");if(!h||typeof h.GetVariable=="undefined")h=document.swflocalstorageshim;if(!h||typeof h.GetVariable=="undefined")h=window.localstorageshim;if(h&&typeof h.GetVariable!=="undefined"){window.localStorage={};$.each(["key","setItem","getItem","removeItem","clear"],function(j,a){window.localStorage[a]=h[a]})}}if(!window.localStorage)window.localStorage=
new q("local")}$.webshims.createReadyEvent("json-storage")};$.webshims.ready("ready swfobject",function(){if(swfobject.hasFlashPlayerVersion("8.0.0")){swfobject.createCSS("#swflocalstorageshim","position: absolute; top: -1px; left: -1px; overflow: hidden; height: 1px; width: 1px;");$("body").after('<div id="swflocalstorageshim" />');swfobject.embedSWF($.webshims.loader.basePath+"localStorage.swf","swflocalstorageshim","1","1","8.0.0","",{allowscriptaccess:"always"},{name:"localstorageshim"},function(n){!n.success&&
!window.localStorage&&$.webshims.localStorageSwfCallback()});o=setTimeout($.webshims.localStorageSwfCallback,9999)}else window.localStorage||$.webshims.localStorageSwfCallback()},true,true)})()})();
