jQuery.webshims.register("mediaelement-swf",function(c,e,u,o,n,j){var m=e.mediaelement,x=u.swfobject,y=Modernizr.audio&&Modernizr.video,z=x.hasFlashPlayerVersion("9.0.115"),A,B={paused:!0,ended:!1,currentSrc:"",duration:u.NaN,readyState:0,networkState:0,videoHeight:0,videoWidth:0,error:null,buffered:n},H=Object.keys(B),C={currentTime:0,volume:1,muted:!1};Object.keys(C);var I=c.extend({isActive:"html5",activating:"html5",wasSwfReady:!1,_bufferedEnd:0,_bufferedStart:0,_metadata:!1,currentTime:0,_ppFlag:n},
B,C),D=/^jwplayer-/,f=function(b){if(b=o.getElementById(b.replace(D,"")))return b=e.data(b,"mediaelement"),b.isActive=="flash"?b:null},l=function(b){return(b=e.data(b,"mediaelement"))&&b.isActive=="flash"?b:null},h=function(b,a){a=c.Event(a);a.preventDefault();c.event.trigger(a,n,b)},s,v=e.cfg.basePath+"swf/jwwebshims.swf",J=e.cfg.basePath+"jwplayer/player.swf";z&&e.ready("WINDOWLOAD",function(){A||c.ajax(v,e.xhrPreloadOption)});e.extendUNDEFProp(j.jwParams,{allowscriptaccess:"always",allowfullscreen:"true",
wmode:"transparent"});e.extendUNDEFProp(j.jwVars,{screencolor:"ffffffff",controlbar:"over"});e.extendUNDEFProp(j.jwAttrs,{bgcolor:"#000000"});m.jwEvents={View:{PLAY:function(b){var a=f(b.id);if(a&&!a.stopPlayPause&&(a._ppFlag=!0,a.paused==b.state)){a.paused=!b.state;if(a.ended)a.ended=!1;h(a._elem,b.state?"play":"pause")}}},Model:{BUFFER:function(b){var a=f(b.id);if(a&&a._bufferedEnd!=b.percentage){a.networkState=b.percentage==100?1:2;if(!a.duration){try{if(a.duration=a.jwapi.getPlaylist()[0].duration,
a.duration<=0)a.duration=u.NaN}catch(d){}a.duration&&(h(a._elem,"durationchange"),a._elemNodeName=="audio"&&this.META(c.extend({duration:a.duration},b),a))}if(a.ended)a.ended=!1;if(a.duration){if(b.percentage>1&&a.readyState<3)a.readyState=3,h(a._elem,"canplay");if(a._bufferedEnd&&a._bufferedEnd>b.percentage)a._bufferedStart=a.currentTime||0;a._bufferedEnd=b.percentage;a.buffered.length=1;if(b.percentage==100)a.networkState=1,a.readyState=4;c.event.trigger("progress",n,a._elem,!0)}}},META:function(b,
a){if("duration"in b||"youtubequalitylevels"in b)if((a=a&&a.networkState?a:f(b.id))&&!a._metadata){a._metadata=!0;if(!a.duration||"duration"in b||!("youtubequalitylevels"in b)){var d=a.duration;a.duration=b.duration;a.videoHeight=b.height||0;a.videoWidth=b.width||0;if(!a.networkState)a.networkState=2;if(a.readyState<1)a.readyState=1;d!==a.duration&&h(a._elem,"durationchange")}h(a._elem,"loadedmetadata")}},TIME:function(b){var a=f(b.id);if(a&&a.currentTime!==b.position){a.currentTime=b.position;if(a.readyState<
2)a.readyState=2;if(a.ended)a.ended=!1;h(a._elem,"timeupdate")}},STATE:function(b){var a=f(b.id);if(a)switch(b.newstate){case "BUFFERING":if(a.readyState>1)a.readyState=1;if(a.ended)a.ended=!1;h(a._elem,"waiting");break;case "PLAYING":a.paused=!1;a._ppFlag=!0;if(a.readyState<3)a.readyState=3,h(a._elem,"canplay");if(a.ended)a.ended=!1;h(a._elem,"playing");break;case "PAUSED":if(!a.paused&&!a.stopPlayPause)a.paused=!0,a._ppFlag=!0,h(a._elem,"pause");break;case "COMPLETED":if(a.readyState<4)a.readyState=
4;a.ended=!0;h(a._elem,"ended")}}},Controller:{ERROR:function(b){var a=f(b.id);a&&m.setError(a._elem,b.message)},SEEK:function(b){var a=f(b.id);if(a){if(a.ended)a.ended=!1;if(a.paused)try{a.jwapi.sendEvent("play","false")}catch(d){}if(a.currentTime!=b.position)a.currentTime=b.position,h(a._elem,"timeupdate")}},VOLUME:function(b){var a=f(b.id);if(a&&(b=b.percentage/100,a.volume!=b))a.volume=b,h(a._elem,"volumechange")},MUTE:function(b){if(!s||!b.state){var a=f(b.id);if(a&&a.muted!=b.state)a.muted=
b.state,h(a._elem,"volumechange")}}}};var K=function(b){c.each(m.jwEvents,function(a,d){c.each(d,function(d){b.jwapi["add"+a+"Listener"](d,"jQuery.webshims.mediaelement.jwEvents."+a+"."+d)})})},E=function(b){b&&(b._ppFlag===n&&c.prop(b._elem,"autoplay")||!b.paused)&&setTimeout(function(){if(b.isActive=="flash"&&(b._ppFlag===n||!b.paused))try{c(b._elem).play()}catch(a){}},1)},L=function(b){if(b&&b._elemNodeName=="video"){var a,d,g,e={},i,k,h,f=function(f,p){if(p&&f&&!(p<1||f<1||b.isActive!="flash"))if(a&&
(a.remove(),a=!1),e.width=f,e.height=p,clearTimeout(k),d=b._elem.style.width=="auto",g=b._elem.style.height=="auto",d||g){i=i||c(b._elem).getShadowElement();var q;d&&!g?(q=i.height(),f*=q/p,p=q):!d&&g&&(q=i.width(),p*=q/f,f=q);h=!0;setTimeout(function(){h=!1},9);i.css({width:f,height:p})}},j=function(){if(!(b.isActive!="flash"||c.prop(b._elem,"readyState")&&c.prop(this,"videoWidth"))){var i=c.prop(b._elem,"poster");if(i&&(d=b._elem.style.width=="auto",g=b._elem.style.height=="auto",d||g))a&&(a.remove(),
a=!1),a=c('<img style="position: absolute; height: auto; width: auto; top: 0px; left: 0px; visibility: hidden;" />'),a.bind("load error alreadycomplete",function(){clearTimeout(k);var b=this,d=b.naturalWidth||b.width||b.offsetWidth,i=b.naturalHeight||b.height||b.offsetHeight;i&&d?(f(d,i),b=null):setTimeout(function(){d=b.naturalWidth||b.width||b.offsetWidth;i=b.naturalHeight||b.height||b.offsetHeight;f(d,i);a&&(a.remove(),a=!1);b=null},9);c(this).unbind()}).prop("src",i).appendTo("body").each(function(){this.complete||
this.error?c(this).triggerHandler("alreadycomplete"):(clearTimeout(k),k=setTimeout(function(){c(b._elem).triggerHandler("error")},9999))})}};c(b._elem).bind("loadedmetadata",function(){f(c.prop(this,"videoWidth"),c.prop(this,"videoHeight"))}).bind("emptied",j).bind("swfstageresize",function(){h||f(e.width,e.height)}).triggerHandler("swfstageresize");j();c.prop(b._elem,"readyState")&&f(c.prop(b._elem,"videoWidth"),c.prop(b._elem,"videoHeight"))}};m.playerResize=function(b){b&&(b=o.getElementById(b.replace(D,
"")))&&c(b).triggerHandler("swfstageresize")};c(o).bind("emptied",function(b){b=l(b.target);E(b)});var t;m.jwPlayerReady=function(b){var a=f(b.id);if(a&&a.jwapi){clearTimeout(t);a.jwData=b;if(a.wasSwfReady){c(a._elem).mediaLoad();var b=a.actionQueue.length,d=0,g;if(b&&a.isActive=="flash")for(;a.actionQueue.length&&b>d;)d++,g=a.actionQueue.shift(),a.jwapi[g.fn].apply(a.jwapi,g.args);if(a.actionQueue.length)a.actionQueue=[]}else b=parseFloat(b.version,10),(b<5.6||b>=6)&&e.warn("mediaelement-swf is only testet with jwplayer 5.6+"),
c.prop(a._elem,"volume",a.volume),c.prop(a._elem,"muted",a.muted),K(a);a.wasSwfReady=!0;E(a)}};var F=c.noop;if(y){var M={play:1,playing:1},w=["play","pause","playing","canplay","progress","waiting","ended","loadedmetadata","durationchange","emptied"].map(function(b){return b+".webshimspolyfill"}).join(" "),G=function(b){var a=e.data(b.target,"mediaelement");a&&(b.originalEvent&&b.originalEvent.type===b.type)==(a.activating=="flash")&&(b.stopImmediatePropagation(),M[b.type]&&a.isActive!=a.activating&&
c(b.target).pause())};c(o).bind(w,G);F=function(b){c(b).unbind(w).bind(w,G)}}m.setActive=function(b,a,d){d||(d=e.data(b,"mediaelement"));if(d&&d.isActive!=a){a!="html5"&&a!="flash"&&e.warn("wrong type for mediaelement activating: "+a);var g=e.data(b,"shadowData");d.activating=a;c(b).pause();d.isActive=a;a=="flash"?(g.shadowElement=g.shadowFocusElement=d.shadowElem[0],c(b).hide().getShadowElement().show()):(c(b).show().getShadowElement().hide(),g.shadowElement=g.shadowFocusElement=!1)}};var N=function(){var b=
["_bufferedEnd","_bufferedStart","_metadata","_ppFlag","currentSrc","currentTime","duration","ended","networkState","paused","videoHeight","videoWidth"],a=b.length;return function(d){if(d){for(var c=a,e=d.networkState;--c;)delete d[b[c]];d.actionQueue=[];d.buffered.length=0;e&&h(d._elem,"emptied")}}}();m.createSWF=function(b,a,d){if(z){A=!0;var g=c.extend({},j.jwVars,{image:c.prop(b,"poster")||"",file:a.srcProp}),f=c(b).data("jwvars")||{};if(d&&d.swfCreated)m.setActive(b,"flash",d),N(d),d.currentSrc=
a.srcProp,c.extend(g,f),j.changeJW(g,b,a,d,"load"),r(b,"sendEvent",["LOAD",g]);else{var i=c.prop(b,"controls"),k="jwplayer-"+e.getID(b),h=c.extend({},j.jwParams,c(b).data("jwparams")),l=b.nodeName.toLowerCase(),n=c.extend({},j.jwAttrs,{name:k,id:k},c(b).data("jwattrs")),o=c('<div class="polyfill-'+l+'" id="wrapper-'+k+'"><div id="'+k+'"></div>').css({width:b.style.width||c(b).width(),height:b.style.height||c(b).height(),position:"relative",overflow:"hidden"}).insertBefore(b),d=e.data(b,"mediaelement",
e.objectCreate(I,{actionQueue:{value:[]},shadowElem:{value:o},_elemNodeName:{value:l},_elem:{value:b},currentSrc:{value:a.srcProp},swfCreated:{value:!0},buffered:{value:{start:function(a){if(a>=d.buffered.length)e.error("buffered index size error");else return 0},end:function(a){if(a>=d.buffered.length)e.error("buffered index size error");else return(d.duration-d._bufferedStart)*d._bufferedEnd/100+d._bufferedStart},length:0}}}));y&&c.extend(d,{volume:c.prop(b,"volume"),muted:c.prop(b,"muted")});c.extend(g,
{id:k,controlbar:i?j.jwVars.controlbar||"over":"none",icons:""+i},f,{playerready:"jQuery.webshims.mediaelement.jwPlayerReady"});g.plugins?g.plugins+=","+v:g.plugins=v;e.addShadowDom(b,o);F(b);m.setActive(b,"flash",d);j.changeJW(g,b,a,d,"embed");L(d);x.embedSWF(J,k,"100%","100%","9.0.0",!1,g,h,n,function(a){if(a.success)d.jwapi=a.ref,i||c(a.ref).attr("tabindex","-1").css("outline","none"),t||(clearTimeout(t),t=setTimeout(function(){var b=c(a.ref);b[0].offsetWidth>1&&b[0].offsetHeight>1&&location.protocol.indexOf("file:")===
0?e.warn("Add your local development-directory to the local-trusted security sandbox:  http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html"):(b[0].offsetWidth<2||b[0].offsetHeight<2)&&e.info("JS-SWF connection can't be established on hidden or unconnected flash objects")},8E3))})}}else setTimeout(function(){c(b).mediaLoad()},1)};var r=function(b,a,d,c){return(c=c||l(b))?(c.jwapi&&c.jwapi[a]?c.jwapi[a].apply(c.jwapi,d||[]):(c.actionQueue.push({fn:a,args:d}),
c.actionQueue.length>10&&setTimeout(function(){c.actionQueue.length>5&&c.actionQueue.shift()},99)),c):!1};["audio","video"].forEach(function(b){var a={},d,g=function(c){b=="audio"&&(c=="videoHeight"||c=="videoWidth")||(a[c]={get:function(){var a=l(this);if(a)return a[c];else if(d[c].prop._supget)return d[c].prop._supget.apply(this)},writeable:!1})},f=function(b,c){g(b);delete a[b].writeable;a[b].set=c};f("volume",function(a){var b=l(this);if(b){if(a*=100,!isNaN(a)){(a<0||a>100)&&e.error("volume greater or less than allowed "+
a/100);b.muted&&(s=!0);r(this,"sendEvent",["VOLUME",a],b);if(s){try{b.jwapi.sendEvent("mute","true")}catch(c){}s=!1}setTimeout(function(){a/=100;if(!(b.volume==a||b.isActive!="flash"))b.volume=a,h(b._elem,"volumechange"),b=null},1)}}else if(d.volume.prop._supset)return d.volume.prop._supset.apply(this,arguments)});f("muted",function(a){var b=l(this);if(b)a=!!a,r(this,"sendEvent",["mute",""+a],b),setTimeout(function(){if(!(b.muted==a||b.isActive!="flash"))b.muted=a,h(b._elem,"volumechange"),b=null},
1);else if(d.muted.prop._supset)return d.muted.prop._supset.apply(this,arguments)});f("currentTime",function(a){var b=l(this);if(b){if(a*=1,!isNaN(a)){if(b.paused)clearTimeout(b.stopPlayPause),b.stopPlayPause=setTimeout(function(){b.paused=!0;b.stopPlayPause=!1},50);r(this,"sendEvent",["SEEK",""+a],b);if(b.paused){if(b.readyState>0)b.currentTime=a,h(b._elem,"timeupdate");try{b.jwapi.sendEvent("play","false")}catch(c){}}}}else if(d.currentTime.prop._supset)return d.currentTime.prop._supset.apply(this,
arguments)});["play","pause"].forEach(function(b){a[b]={value:function(){var a=l(this);if(a)a.stopPlayPause&&clearTimeout(a.stopPlayPause),r(this,"sendEvent",["play",b=="play"],a),setTimeout(function(){if(a.isActive=="flash"&&(a._ppFlag=!0,a.paused!=(b!="play")))a.paused=b!="play",h(a._elem,b)},1);else if(d[b].prop._supvalue)return d[b].prop._supvalue.apply(this,arguments)}}});H.forEach(g);e.onNodeNamesPropertyModify(b,"controls",function(a,b){var d=r(this,b?"showControls":"hideControls");d&&c(d.jwapi).attr("tabindex",
b?"0":"-1")});d=e.defineNodeNameProperties(b,a,"prop")})});
