(function(i,j,h){var l=j.audio&&j.video,n=!1;if(l){var m=document.createElement("video");j.videoBuffered="buffered"in m;n="loop"in m;h.capturingEvents(["play","playing","waiting","paused","ended","durationchange","loadedmetadata","canplay","volumechange"]);j.videoBuffered||(h.addPolyfill("mediaelement-native-fix",{feature:"mediaelement",test:j.videoBuffered,dependencies:["dom-support"]}),h.cfg.waitReady&&i.readyWait++,h.loader.loadScript("mediaelement-native-fix",function(){h.cfg.waitReady&&i.ready(!0)}))}i.webshims.ready("dom-support swfobject",
function(d,g,j,h,i){var f=g.mediaelement,m=g.cfg.mediaelement,r=function(a,b){var a=d(a),c={src:a.attr("src")||"",elem:a,srcProp:a.prop("src")};if(!c.src)return c;var e=a.attr("type");if(e)c.type=e,c.container=d.trim(e.split(";")[0]);else if(b||(b=a[0].nodeName.toLowerCase(),b=="source"&&(b=(a.closest("video, audio")[0]||{nodeName:"video"}).nodeName.toLowerCase())),e=f.getTypeForSrc(c.src,b))c.type=e,c.container=e,g.warn("you should always provide a proper mime-type using the source element. "+c.src+
" detected as: "+e),d.nodeName(a[0],"source")&&a.attr("type",e);if(e=a.attr("media"))c.media=e;return c},o=swfobject.hasFlashPlayerVersion("9.0.115"),s=function(){g.ready("mediaelement-swf",function(){if(!f.createSWF)g.modules["mediaelement-swf"].test=!1,delete d.event.special["mediaelement-swfReady"],g.loader.loadList(["mediaelement-swf"])})};o&&g.ready("WINDOWLOAD",s);f.mimeTypes={audio:{"audio/ogg":["ogg","oga","ogm"],"audio/mpeg":["mp2","mp3","mpga","mpega"],"audio/mp4":["mp4","mpg4","m4r"],"audio/wav":["wav"],
"audio/x-m4a":["m4a"],"audio/x-m4p":["m4p"],"audio/3gpp":["3gp","3gpp"],"audio/webm":["webm"]},video:{"video/ogg":["ogg","ogv","ogm"],"video/mpeg":["mpg","mpeg","mpe"],"video/mp4":["mp4","mpg4","m4v"],"video/quicktime":["mov","qt"],"video/x-msvideo":["avi"],"video/x-ms-asf":["asf","asx"],"video/flv":["flv","f4v"],"video/3gpp":["3gp","3gpp"],"video/webm":["webm"]}};f.mimeTypes.source=d.extend({},f.mimeTypes.audio,f.mimeTypes.video);f.getTypeForSrc=function(a,b){if(a.indexOf("youtube.com/watch?")!=
-1)return"video/youtube";var a=a.split("?")[0].split("."),a=a[a.length-1],c;d.each(f.mimeTypes[b],function(b,d){if(d.indexOf(a)!==-1)return c=b,!1});return c};f.srces=function(a,b){a=d(a);if(b)a.removeAttr("src").removeAttr("type").find("source").remove(),d.isArray(b)||(b=[b]),b.forEach(function(b){var c=h.createElement("source");typeof b=="string"&&(b={src:b});c.setAttribute("src",b.src);b.type&&c.setAttribute("type",b.type);b.media&&c.setAttribute("media",b.media);a.append(c)});else{var b=[],c=
a[0].nodeName.toLowerCase(),e=r(a,c);e.src?b.push(e):d("source",a).each(function(){e=r(this,c);e.src&&b.push(e)});return b}};d.fn.loadMediaSrc=function(a,b){return this.each(function(){b!==i&&(d(this).removeAttr("poster"),b&&d.attr(this,"poster",b));f.srces(this,a);d(this).mediaLoad()})};f.swfMimeTypes=["video/3gpp","video/x-msvideo","video/quicktime","video/x-m4v","video/mp4","video/m4p","video/x-flv","video/flv","audio/mpeg","audio/aac","audio/mp4","audio/x-m4a","audio/m4a","audio/mp3","audio/x-fla",
"audio/fla","youtube/flv","jwplayer/jwplayer","video/youtube"];f.canSwfPlaySrces=function(a,b){var c="";o&&(a=d(a),b=b||f.srces(a),d.each(b,function(a,b){if(b.container&&b.src&&f.swfMimeTypes.indexOf(b.container)!=-1)return c=b,!1}));return c};var k={};f.canNativePlaySrces=function(a,b){var c="";if(l){var a=d(a),e=(a[0].nodeName||"").toLowerCase();if(!k[e])return c;b=b||f.srces(a);d.each(b,function(b,d){if(d.type&&k[e].prop._supvalue.call(a[0],d.type))return c=d,!1})}return c};f.setError=function(a,
b){b||(b="can't play sources");d(a).data("mediaerror",b);g.warn("mediaelementError: "+b);setTimeout(function(){d(a).data("mediaerror")&&d(a).trigger("mediaerror")},1)};var t=function(){var a;return function(b,c,e){g.ready("mediaelement-swf",function(){f.createSWF?f.createSWF(b,c,e):a||(a=!0,s(),t(b,c,e))})}}(),p=function(a,b,c,e,d){c||c!==!1&&b&&b.isActive=="flash"?(c=f.canSwfPlaySrces(a,e))?t(a,c,b):d?f.setError(a,!1):p(a,b,!1,e,!0):(c=f.canNativePlaySrces(a,e))?b&&b.isActive=="flash"&&f.setActive(a,
"html5",b):d?f.setError(a,!1):p(a,b,!0,e,!0)},u=/^(?:embed|object)$/i,q=function(a,b){var c=g.data(a,"mediaelementBase")||g.data(a,"mediaelementBase",{}),e=f.srces(a),h=a.parentNode;clearTimeout(c.loadTimer);d.data(a,"mediaerror",!1);if(e.length&&h&&!u.test(h.nodeName||""))b=b||g.data(a,"mediaelement"),p(a,b,m.preferFlash||i,e)};d(h).bind("ended",function(a){var b=g.data(a.target,"mediaelement");(!n||b&&b.isActive!="html5"||d.prop(a.target,"loop"))&&setTimeout(function(){!d.prop(a.target,"paused")&&
d.prop(a.target,"loop")&&d(a.target).prop("currentTime",0).play()},1)});n||g.defineNodeNamesBooleanProperty(["audio","video"],"loop");["audio","video"].forEach(function(a){var b=g.defineNodeNameProperty(a,"load",{prop:{value:function(){var a=g.data(this,"mediaelement");q(this,a);l&&(!a||a.isActive=="html5")&&b.prop._supvalue&&b.prop._supvalue.apply(this,arguments)}}});k[a]=g.defineNodeNameProperty(a,"canPlayType",{prop:{value:function(b){var e="";l&&k[a].prop._supvalue&&(e=k[a].prop._supvalue.call(this,
b),e=="no"&&(e=""));!e&&o&&(b=d.trim((b||"").split(";")[0]),f.swfMimeTypes.indexOf(b)!=-1&&(e="maybe"));return e}}})});g.onNodeNamesPropertyModify(["audio","video"],["src","poster"],{set:function(){var a=this,b=g.data(a,"mediaelementBase")||g.data(a,"mediaelementBase",{});clearTimeout(b.loadTimer);b.loadTimer=setTimeout(function(){q(a);a=null},9)}});g.addReady(function(a,b){d("video, audio",a).add(b.filter("video, audio")).each(function(){q(this)})});g.isReady("mediaelement-core",!0)})})(jQuery,Modernizr,
jQuery.webshims);
