(function(i,k,g){var l=k.audio&&k.video,s=!1,m=g.cfg.mediaelement,n=g.bugs,j;if(l){var p=document.createElement("video");k.videoBuffered="buffered"in p;s="loop"in p;g.capturingEvents("play,playing,waiting,paused,ended,durationchange,loadedmetadata,canplay,volumechange".split(","));k.videoBuffered||(g.addPolyfill("mediaelement-native-fix",{f:"mediaelement",test:k.videoBuffered,d:["dom-support"]}),g.reTest("mediaelement-native-fix"))}if(l&&!m.preferFlash){var o=function(c){var d=c.target.parentNode;
!m.preferFlash&&(i(c.target).is("audio, video")||d&&i("source:last",d)[0]==c.target)&&g.ready("mediaelement-swf",function(){setTimeout(function(){j&&!m.preferFlash&&!i(c.target).closest("audio, video").is(".nonnative-api-active")?(m.preferFlash=!0,document.removeEventListener("error",o,!0),i("audio, video").mediaLoad(),g.info("switching mediaelements option to 'preferFlash', due to an error with native player: "+c.target.src)):j||document.removeEventListener("error",o,!0)},20)})};document.addEventListener("error",
o,!0);i("audio, video").each(function(){this.error&&o({target:this})})}n.track=!1;k.track&&function(){n.track="number"!=typeof i("<track />")[0].readyState||!i("<video />")[0].addTextTrack;if(!n.track)try{new TextTrackCue(2,3,"")}catch(c){try{new TextTrackCue("",2,3,"","",!1);var d=TextTrackCue;window.TextTrackCue=function(c,e,g,j,i,k){return 4<arguments.length?new d(c,e,g,j,i||"",k||!1):new d("",c,e,g,"",!1)}}catch(l){n.track=!0}}var j=g.cfg.track,k=function(c){i(c.target).filter("track").each(e)},
e=function(){if(n.track||!j.override&&3==i.prop(this,"readyState"))j.override=!0,g.reTest("track"),document.removeEventListener("error",k,!0),this&&i.nodeName(this,"track")?g.error("track support was overwritten. Please check your vtt including your vtt mime-type"):g.info("track support was overwritten.")},m=function(){document.addEventListener("error",k,!0);n.track?e():i("track").each(e)};j.override||(g.isReady("track")?m():i(m))}();g.register("mediaelement-core",function(c,d,g,i,o){j=swfobject.hasFlashPlayerVersion("9.0.115");
var e=d.mediaelement,p=function(a,b){var a=c(a),h={src:a.attr("src")||"",elem:a,srcProp:a.prop("src")};if(!h.src)return h;var f=a.attr("type");if(f)h.type=f,h.container=c.trim(f.split(";")[0]);else if(b||(b=a[0].nodeName.toLowerCase(),"source"==b&&(b=(a.closest("video, audio")[0]||{nodeName:"video"}).nodeName.toLowerCase())),f=e.getTypeForSrc(h.src,b))h.type=f,h.container=f;if(f=a.attr("media"))h.media=f;return h},q=!j&&"postMessage"in g&&l,y=function(){d.ready("mediaelement-swf",function(){if(!e.createSWF)d.modules["mediaelement-swf"].test=
c.noop,d.reTest(["mediaelement-swf"],l)})},v=function(){var a;return function(){!a&&q&&(a=!0,d.loader.loadScript("https://www.youtube.com/player_api"),c(function(){d.polyfill("mediaelement-yt")}))}}(),w=function(){j?y():v();c(function(){d.loader.loadList(["track-ui"])})};d.addPolyfill("mediaelement-yt",{test:!q,d:["dom-support"]});e.mimeTypes={audio:{"audio/ogg":["ogg","oga","ogm"],'audio/ogg;codecs="opus"':"opus","audio/mpeg":["mp2","mp3","mpga","mpega"],"audio/mp4":"mp4,mpg4,m4r,m4a,m4p,m4b,aac".split(","),
"audio/wav":["wav"],"audio/3gpp":["3gp","3gpp"],"audio/webm":["webm"],"audio/fla":["flv","f4a","fla"],"application/x-mpegURL":["m3u8","m3u"]},video:{"video/ogg":["ogg","ogv","ogm"],"video/mpeg":["mpg","mpeg","mpe"],"video/mp4":["mp4","mpg4","m4v"],"video/quicktime":["mov","qt"],"video/x-msvideo":["avi"],"video/x-ms-asf":["asf","asx"],"video/flv":["flv","f4v"],"video/3gpp":["3gp","3gpp"],"video/webm":["webm"],"application/x-mpegURL":["m3u8","m3u"],"video/MP2T":["ts"]}};e.mimeTypes.source=c.extend({},
e.mimeTypes.audio,e.mimeTypes.video);e.getTypeForSrc=function(a,b){if(-1!=a.indexOf("youtube.com/watch?")||-1!=a.indexOf("youtube.com/v/"))return"video/youtube";var a=a.split("?")[0].split("."),a=a[a.length-1],h;c.each(e.mimeTypes[b],function(b,c){if(-1!==c.indexOf(a))return h=b,!1});return h};e.srces=function(a,b){a=c(a);if(b)a.removeAttr("src").removeAttr("type").find("source").remove(),c.isArray(b)||(b=[b]),b.forEach(function(b){var c=i.createElement("source");"string"==typeof b&&(b={src:b});c.setAttribute("src",
b.src);b.type&&c.setAttribute("type",b.type);b.media&&c.setAttribute("media",b.media);a.append(c)});else{var b=[],h=a[0].nodeName.toLowerCase(),f=p(a,h);f.src?b.push(f):c("source",a).each(function(){f=p(this,h);f.src&&b.push(f)});return b}};c.fn.loadMediaSrc=function(a,b){return this.each(function(){b!==o&&(c(this).removeAttr("poster"),b&&c.attr(this,"poster",b));e.srces(this,a);c(this).mediaLoad()})};e.swfMimeTypes="video/3gpp,video/x-msvideo,video/quicktime,video/x-m4v,video/mp4,video/m4p,video/x-flv,video/flv,audio/mpeg,audio/aac,audio/mp4,audio/x-m4a,audio/m4a,audio/mp3,audio/x-fla,audio/fla,youtube/flv,jwplayer/jwplayer,video/youtube".split(",");
e.canThirdPlaySrces=function(a,b){var h="";if(j||q)a=c(a),b=b||e.srces(a),c.each(b,function(a,b){if(b.container&&b.src&&(j&&-1!=e.swfMimeTypes.indexOf(b.container)||q&&"video/youtube"==b.container))return h=b,!1});return h};var r={};e.canNativePlaySrces=function(a,b){var h="";if(l){var a=c(a),f=(a[0].nodeName||"").toLowerCase();if(!r[f])return h;b=b||e.srces(a);c.each(b,function(b,c){if(c.type&&r[f].prop._supvalue.call(a[0],c.type))return h=c,!1})}return h};e.setError=function(a,b){b||(b="can't play sources");
c(a).pause().data("mediaerror",b);d.warn("mediaelementError: "+b);setTimeout(function(){c(a).data("mediaerror")&&c(a).trigger("mediaerror")},1)};var x=function(){var a;return function(b,c,f){d.ready(j?"mediaelement-swf":"mediaelement-yt",function(){e.createSWF?e.createSWF(b,c,f):a||(a=!0,w(),x(b,c,f))});!a&&q&&!e.createSWF&&v()}}(),t=function(a,b,c,f,d){c||!1!==c&&b&&"third"==b.isActive?(c=e.canThirdPlaySrces(a,f))?x(a,c,b):d?e.setError(a,!1):t(a,b,!1,f,!0):(c=e.canNativePlaySrces(a,f))?b&&"third"==
b.isActive&&e.setActive(a,"html5",b):d?(e.setError(a,!1),b&&"third"==b.isActive&&e.setActive(a,"html5",b)):t(a,b,!0,f,!0)},z=/^(?:embed|object|datalist)$/i,u=function(a,b){var h=d.data(a,"mediaelementBase")||d.data(a,"mediaelementBase",{}),f=e.srces(a),g=a.parentNode;clearTimeout(h.loadTimer);c.data(a,"mediaerror",!1);if(f.length&&g&&!(1!=g.nodeType||z.test(g.nodeName||"")))b=b||d.data(a,"mediaelement"),t(a,b,m.preferFlash||o,f)};c(i).bind("ended",function(a){var b=d.data(a.target,"mediaelement");
(!s||b&&"html5"!=b.isActive||c.prop(a.target,"loop"))&&setTimeout(function(){!c.prop(a.target,"paused")&&c.prop(a.target,"loop")&&c(a.target).prop("currentTime",0).play()},1)});s||d.defineNodeNamesBooleanProperty(["audio","video"],"loop");["audio","video"].forEach(function(a){var b=d.defineNodeNameProperty(a,"load",{prop:{value:function(){var a=d.data(this,"mediaelement");u(this,a);l&&(!a||"html5"==a.isActive)&&b.prop._supvalue&&b.prop._supvalue.apply(this,arguments)}}});r[a]=d.defineNodeNameProperty(a,
"canPlayType",{prop:{value:function(b){var f="";l&&r[a].prop._supvalue&&(f=r[a].prop._supvalue.call(this,b),"no"==f&&(f=""));!f&&j&&(b=c.trim((b||"").split(";")[0]),-1!=e.swfMimeTypes.indexOf(b)&&(f="maybe"));return f}}})});d.onNodeNamesPropertyModify(["audio","video"],["src","poster"],{set:function(){var a=this,b=d.data(a,"mediaelementBase")||d.data(a,"mediaelementBase",{});clearTimeout(b.loadTimer);b.loadTimer=setTimeout(function(){u(a);a=null},9)}});g=function(){d.addReady(function(a,b){c("video, audio",
a).add(b.filter("video, audio")).each(function(){c.browser.msie&&8<d.browserVersion&&c.prop(this,"paused")&&!c.prop(this,"readyState")&&c(this).is('audio[preload="none"][controls]:not([autoplay])')?c(this).prop("preload","metadata").mediaLoad():u(this);if(l){var a,b,e=this,g=function(){var a=c.prop(e,"buffered");if(a){for(var b="",d=0,f=a.length;d<f;d++)b+=a.end(d);return b}},i=function(){var a=g();a!=b&&(b=a,c(e).triggerHandler("progress"))};c(this).bind("play loadstart progress",function(c){"progress"==
c.type&&(b=g());clearTimeout(a);a=setTimeout(i,999)}).bind("emptied stalled mediaerror abort suspend",function(c){"emptied"==c.type&&(b=!1);clearTimeout(a)})}})})};k.track&&!n.track?(d.defineProperty(TextTrack.prototype,"shimActiveCues",{get:function(){return this._shimActiveCues||this.activeCues}}),c(function(){d.polyfill("track")})):c(function(){d.loader.loadList(["track-ui"])});l?(d.isReady("mediaelement-core",!0),g(),d.ready("WINDOWLOAD mediaelement",w)):d.ready("mediaelement-swf",g)})})(jQuery,
Modernizr,jQuery.webshims);
