jQuery.webshims.register("mediaelement-swf",function(c,e,s,t,m,l){var n=e.mediaelement,w=s.swfobject,x=Modernizr.audio&&Modernizr.video,y=w.hasFlashPlayerVersion("9.0.115"),z,A={paused:!0,ended:!1,currentSrc:"",duration:s.NaN,readyState:0,networkState:0,videoHeight:0,videoWidth:0,error:null,buffered:m},F=Object.keys(A),B={currentTime:0,volume:1,muted:!1};Object.keys(B);var G=c.extend({isActive:"html5",activating:"html5",wasSwfReady:!1,_bufferedEnd:0,_bufferedStart:0,_metadata:!1,currentTime:0,_ppFlag:m},
A,B),H=/^jwplayer-/,i=function(b){if(b=t.getElementById(b.replace(H,"")))return b=e.data(b,"mediaelement"),b.isActive=="flash"?b:null},k=function(b){return(b=e.data(b,"mediaelement"))&&b.isActive=="flash"?b:null},f=function(b,a){a=c.Event(a);a.preventDefault();c.event.trigger(a,m,b)},q,u=e.cfg.basePath+"swf/jwwebshims.swf",I=e.cfg.basePath+"jwplayer/player.swf";y&&e.ready("WINDOWLOAD",function(){z||c.ajax(u,e.xhrPreloadOption)});e.extendUNDEFProp(l.jwParams,{allowscriptaccess:"always",allowfullscreen:"true",
wmode:"transparent"});e.extendUNDEFProp(l.jwVars,{screencolor:"ffffffff",controlbar:"over"});e.extendUNDEFProp(l.jwAttrs,{bgcolor:"#000000"});n.jwEvents={View:{PLAY:function(b){var a=i(b.id);if(a&&!a.stopPlayPause&&(a._ppFlag=!0,a.paused==b.state)){a.paused=!b.state;if(a.ended)a.ended=!1;f(a._elem,b.state?"play":"pause")}}},Model:{BUFFER:function(b){var a=i(b.id);if(a&&a._bufferEnd!=b.percentage){a.networkState=b.percentage==100?1:2;if(!a.duration){try{if(a.duration=a.jwapi.getPlaylist()[0].duration,
a.duration<=0)a.duration=s.NaN}catch(d){}a.duration&&(f(a._elem,"durationchange"),a._elemNodeName=="audio"&&this.META(c.extend({duration:a.duration},b),a))}if(a.ended)a.ended=!1;if(a.duration){a._bufferedEnd=b.percentage;a.buffered.length=1;if(b.percentage==100)a.networkState=1,a.readyState=4;c.event.trigger("progress",m,a._elem,!0)}}},META:function(b,a){if("duration"in b||"youtubequalitylevels"in b)if((a=a&&a.networkState?a:i(b.id))&&!a._metadata){a._metadata=!0;if(!a.duration||"duration"in b||!("youtubequalitylevels"in
b)){var d=a.duration;a.duration=b.duration;a.videoHeight=b.height||0;a.videoWidth=b.width||0;if(!a.networkState)a.networkState=2;if(a.readyState<1)a.readyState=1;d!==a.duration&&f(a._elem,"durationchange")}f(a._elem,"loadedmetadata")}},TIME:function(b){var a=i(b.id);if(a&&a.currentTime!==b.position){a.currentTime=b.position;if(a.readyState<2)a.readyState=2;if(a.ended)a.ended=!1;f(a._elem,"timeupdate")}},STATE:function(b){var a=i(b.id);if(a)switch(b.newstate){case "BUFFERING":if(a.readyState>1)a.readyState=
1;if(a.ended)a.ended=!1;f(a._elem,"waiting");break;case "PLAYING":a.paused=!1;a._ppFlag=!0;if(a.readyState<3)a.readyState=3,f(a._elem,"canplay");if(a.ended)a.ended=!1;f(a._elem,"playing");break;case "PAUSED":if(!a.paused&&!a.stopPlayPause)a.paused=!0,a._ppFlag=!0,f(a._elem,"pause");break;case "COMPLETED":if(a.readyState<4)a.readyState=4;a.ended=!0;f(a._elem,"ended")}}},Controller:{ERROR:function(b){var a=i(b.id);a&&n.setError(a._elem,b.message)},SEEK:function(b){var a=i(b.id);if(a){if(a.ended)a.ended=
!1;if(a.paused)try{a.jwapi.sendEvent("play","false")}catch(d){}if(a.currentTime!=b.position)a.currentTime=b.position,f(a._elem,"timeupdate")}},VOLUME:function(b){var a=i(b.id);if(a&&(b=b.percentage/100,a.volume!=b))a.volume=b,f(a._elem,"volumechange")},MUTE:function(b){if(!q||!b.state){var a=i(b.id);if(a&&a.muted!=b.state)a.muted=b.state,f(a._elem,"volumechange")}}}};var J=function(b){c.each(n.jwEvents,function(a,d){c.each(d,function(d){b.jwapi["add"+a+"Listener"](d,"jQuery.webshims.mediaelement.jwEvents."+
a+"."+d)})})},C=function(b){b&&(b._ppFlag===m&&c.prop(b._elem,"autoplay")||!b.paused)&&setTimeout(function(){if(b.isActive=="flash"&&(b._ppFlag===m||!b.paused))try{c(b._elem).play()}catch(a){}},1)},K=function(b){if(b&&b._elemNodeName=="video"){var a,d,g,e,j,h=function(h,o){if(o&&h&&!(o<1||h<1||b.isActive!="flash"))if(a&&(a.remove(),a=!1),clearTimeout(j),d=b._elem.style.width=="auto",g=b._elem.style.height=="auto",d||g){e=e||c(b._elem).getShadowElement();var f;d&&!g?(f=c(b._elem).height(),h*=f/o,o=
f):!d&&g&&(f=c(b._elem).width(),o*=f/h,h=f);e.css({width:h,height:o})}},f=function(){if(!(b.isActive!="flash"||c.prop(b._elem,"readyState"))){var e=c.prop(b._elem,"poster");if(e&&(d=b._elem.style.width=="auto",g=b._elem.style.height=="auto",d||g))a&&(a.remove(),a=!1),a=c('<img style="position: absolute; height: auto; width: auto; top: 0px; left: 0px; visibility: hidden;" />'),a.bind("load error alreadycomplete",function(){clearTimeout(j);c(this).unbind();var b=this,d=b.naturalWidth||b.width||b.offsetWidth,
g=b.naturalHeight||b.height||b.offsetHeight;g&&d?(h(d,g),b=null):setTimeout(function(){d=b.naturalWidth||b.width||b.offsetWidth;g=b.naturalHeight||b.height||b.offsetHeight;h(d,g);a&&(a.remove(),a=!1);b=null},9)}).prop("src",e).appendTo("body").each(function(){this.complete||this.error?c(this).triggerHandler("alreadycomplete"):(clearTimeout(j),j=setTimeout(function(){c(b._elem).triggerHandler("error")},9E3))})}};c(b._elem).bind("loadedmetadata",function(){h(c.prop(this,"videoWidth"),c.prop(this,"videoHeight"))}).bind("emptied",
f).each(function(){c.prop(b._elem,"readyState")?h(c.prop(this,"videoWidth"),c.prop(this,"videoHeight")):f()})}};c(t).bind("emptied",function(b){b=k(b.target);C(b)});var r;n.jwPlayerReady=function(b){var a=i(b.id);if(a&&a.jwapi){clearTimeout(r);a.jwData=b;if(a.wasSwfReady){var b=a.actionQueue.length,d=0,g;if(b&&a.isActive=="flash")for(;a.actionQueue.length&&b>d;)d++,g=a.actionQueue.shift(),a.jwapi[g.fn].apply(a.jwapi,g.args);if(a.actionQueue.length)a.actionQueue=[]}else b=parseFloat(b.version,10),
(b<5.6||b>=6)&&e.warn("mediaelement-swf is only testet with jwplayer 5.6+"),c.prop(a._elem,"volume",a.volume),c.prop(a._elem,"muted",a.muted),J(a);a.wasSwfReady=!0;C(a)}};var D=c.noop;if(x){var L={play:1,playing:1},v=["play","pause","playing","canplay","progress","waiting","ended","loadedmetadata","durationchange","emptied"].map(function(b){return b+".webshimspolyfill"}).join(" "),E=function(b){var a=e.data(b.target,"mediaelement");a&&(b.originalEvent&&b.originalEvent.type===b.type)==(a.activating==
"flash")&&(b.stopImmediatePropagation(),L[b.type]&&a.isActive!=a.activating&&c(b.target).pause())};c(t).bind(v,E);D=function(b){c(b).unbind(v).bind(v,E)}}n.setActive=function(b,a,d){d||(d=e.data(b,"mediaelement"));if(d&&d.isActive!=a)a!="html5"&&a!="flash"&&e.warn("wrong type for mediaelement activating: "+a),d.activating=a,c(b).pause(),e.data(b,"mediaelementError",!1),d.isActive=a,a=="flash"?c(b).hide().getShadowElement().show():c(b).show().getShadowElement().hide()};var M=function(){var b=["_bufferedEnd",
"_bufferedStart","_metadata","_ppFlag","currentSrc","currentTime","duration","ended","networkState","paused","videoHeight","videoWidth"],a=b.length;return function(d){if(d){for(var c=a,e=d.networkState;--c;)delete d[b[c]];d.actionQueue=[];d.buffered.length=0;e&&f(d._elem,"emptied")}}}();n.createSWF=function(b,a,d){if(y){z=!0;var g=c.extend({},l.jwVars,{image:c.prop(b,"poster")||"",file:a.srcProp}),f=c(b).data("jwvars")||{};if(d)n.setActive(b,"flash",d),M(d),d.currentSrc=a.srcProp,c.extend(g,f),l.changeJW(g,
b,a,d,"load"),p(b,"sendEvent",["LOAD",g]);else{var j=c.prop(b,"controls"),h="jwplayer-"+e.getID(b),i=c.extend({},l.jwParams,c(b).data("jwparams")),k=b.nodeName.toLowerCase(),o=c.extend({},l.jwAttrs,{name:h,id:h},c(b).data("jwattrs")),m=c('<div class="polyfill-'+k+'" id="wrapper-'+h+'"><div id="'+h+'"></div>').css({width:b.style.width||c(b).width(),height:b.style.height||c(b).height(),position:"relative"}).insertBefore(b),d=e.data(b,"mediaelement",e.objectCreate(G,{actionQueue:{value:[]},_elemNodeName:{value:k},
_elem:{value:b},currentSrc:{value:a.srcProp},buffered:{value:{start:function(a){if(a>=d.buffered.length)e.error("buffered index size error");else return 0},end:function(a){if(a>=d.buffered.length)e.error("buffered index size error");else return d.duration*d._bufferedEnd/100+d._bufferedStart},length:0}}}));x&&c.extend(d,{volume:c.prop(b,"volume"),muted:c.prop(b,"muted")});c.extend(g,{id:h,controlbar:j?l.jwVars.controlbar||"over":"none",icons:""+j},f,{playerready:"jQuery.webshims.mediaelement.jwPlayerReady"});
g.plugins?g.plugins+=","+u:g.plugins=u;e.addShadowDom(b,m);D(b);n.setActive(b,"flash",d);l.changeJW(g,b,a,d,"embed");K(d);w.embedSWF(I,h,"100%","100%","9.0.0",!1,g,i,o,function(a){if(a.success)d.jwapi=a.ref,j||c(a.ref).attr("tabindex","-1").css("outline","none"),r||(clearTimeout(r),r=setTimeout(function(){var b=c(a.ref);b[0].offsetWidth>1&&b[0].offsetHeight>1&&location.protocol.indexOf("file:")===0?e.warn("Add your local development-directory to the local-trusted security sandbox:  http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html"):
e.info("JS-SWF connection can't be established on hidden or unconnected flash objects")},8E3))})}}else setTimeout(function(){c(b).mediaLoad()},1)};var p=function(b,a,d,c){return(c=c||k(b))?(c.jwapi&&c.jwapi[a]?c.jwapi[a].apply(c.jwapi,d||[]):(c.actionQueue.push({fn:a,args:d}),c.actionQueue.length>10&&setTimeout(function(){c.actionQueue.length>5&&c.actionQueue.shift()},99)),c):!1};["audio","video"].forEach(function(b){var a={},c,g=function(j){b=="audio"&&(j=="videoHeight"||j=="videoWidth")||(a[j]=
{get:function(){var a=k(this);if(a)return a[j];else if(c[j].prop._supget)return c[j].prop._supget.apply(this)},writeable:!1})},i=function(b,c){g(b);delete a[b].writeable;a[b].set=c};i("volume",function(a){var b=k(this);if(b){if(a*=100,!isNaN(a)){(a<0||a>100)&&e.error("volume greater or less than allowed "+a/100);b.muted&&(q=!0);p(this,"sendEvent",["VOLUME",a],b);if(q){try{b.jwapi.sendEvent("mute","true")}catch(g){}q=!1}setTimeout(function(){if(!(b.volume==a||b.isActive!="flash"))b.volume=a,f(b._elem,
"volumechange"),b=null},1)}}else if(c.volume.prop._supset)return c.volume.prop._supset.apply(this,arguments)});i("muted",function(a){var b=k(this);if(b)a=!!a,p(this,"sendEvent",["mute",""+a],b),setTimeout(function(){if(!(b.muted==a||b.isActive!="flash"))b.muted=a,f(b._elem,"volumechange"),b=null},1);else if(c.muted.prop._supset)return c.muted.prop._supset.apply(this,arguments)});i("currentTime",function(a){var b=k(this);if(b){if(a*=1,!isNaN(a)){if(b.paused)clearTimeout(b.stopPlayPause),b.stopPlayPause=
setTimeout(function(){b.paused=!0;b.stopPlayPause=!1},50);p(this,"sendEvent",["SEEK",""+a],b);if(b.paused){if(b.readyState>0)b.currentTime=a,f(b._elem,"timeupdate");try{b.jwapi.sendEvent("play","false")}catch(e){}}}}else if(c.currentTime.prop._supset)return c.currentTime.prop._supset.apply(this,arguments)});["play","pause"].forEach(function(b){a[b]={value:function(){var a=k(this);if(a)a.stopPlayPause&&clearTimeout(a.stopPlayPause),p(this,"sendEvent",["play",b=="play"],a),setTimeout(function(){if(a.isActive==
"flash"&&(a._ppFlag=!0,a.paused!=(b!="play")))a.paused=b!="play",f(a._elem,b)},1);else if(c[b].prop._supvalue)return c[b].prop._supvalue.apply(this,arguments)}}});F.forEach(g);e.onNodeNamesPropertyModify(b,"controls",function(a,b){p(this,b?"showControls":"hideControls")});c=e.defineNodeNameProperties(b,a,"prop")})});
