jQuery.webshims.register("track",function(g,e,q,r){var h=e.mediaelement;(new Date).getTime();var s={subtitles:1,captions:1},j=function(a){var b={};a.addEventListener=function(a,d){b[a]&&e.error("always use $.bind to the shimed event: "+a+" already bound fn was: "+b[a]+" your fn was: "+d);b[a]=d};a.removeEventListener=function(a,d){b[a]&&b[a]!=d&&e.error("always use $.bind/$.unbind to the shimed event: "+a+" already bound fn was: "+b[a]+" your fn was: "+d);b[a]&&delete b[a]};return a},t={getCueById:function(a){for(var b=
null,f=0,d=this.length;f<d;f++)if(this[f].id===a){b=this[f];break}return b}},u={shimActiveCues:null,_shimActiveCues:null,activeCues:null,cues:null,kind:"subtitles",label:"",language:"",mode:"disabled",readyState:0,oncuechange:null,toString:function(){return"[object TextTrack]"},addCue:function(a){if(this.cues){var b=this.cues[this.cues.length-1];b&&b.startTime>a.startTime&&e.error("cue startTime higher than previous cue's startTime")}else this.cues=h.createCueList();a.track&&e.error("cue already part of a track element");
a.track=this;this.cues.push(a)},removeCue:function(){e.error("not implemented yet")},DISABLED:"disabled",OFF:"disabled",HIDDEN:"hidden",SHOWING:"showing",ERROR:3,LOADED:2,LOADING:1,NONE:0},v=["kind","label","srclang"],w=Function.prototype.call.bind(Object.prototype.hasOwnProperty),m=function(){var a=g.prop(this,"textTracks"),b=e.data(this,"mediaelementBase"),f=a.splice(0),d,c;g("track",this).each(function(){a.push(g.prop(this,"track"))});if(b.scriptedTextTracks)for(d=0,c=b.scriptedTextTracks.length;d<
c;d++)a.push(b.scriptedTextTracks[d]);for(d=0,c=f.length;d<c;d++)if(-1==a.indexOf(f[d]))f[d].mode="disabled";f=null},n=function(a,b){var f,d;b||(b=e.data(a,"trackData"));if(b&&!b.isTriggering)b.isTriggering=!0,f=(b.track||{}).mode,d=(b.track||{}).kind,setTimeout(function(){if(f!==(b.track||{}).mode||d!=(b.track||{}).kind)(b.track||{}).readyState?g(a).parent().triggerHandler("updatetrackdisplay"):g(a).triggerHandler("checktrackmode");b.isTriggering=!1},9)},o=g("<div />")[0];q.TextTrackCue=function(a,
b,f){3!=arguments.length&&e.error("wrong arguments.length for TextTrackCue.constructor");this.startTime=a;this.endTime=b;this.text=f;this.id="";this.pauseOnExit=!1;j(this)};q.TextTrackCue.prototype={onenter:null,onexit:null,pauseOnExit:!1,getCueAsHTML:function(){var a="",b="",f=r.createDocumentFragment(),d;if(!w(this,"getCueAsHTML"))d=this.getCueAsHTML=function(){var c,d;if(a!=this.text){a=this.text;b=h.parseCueTextToHTML(a);o.innerHTML=b;for(c=0,d=o.childNodes.length;c<d;c++)f.appendChild(o.childNodes[c].cloneNode(!0))}return f.cloneNode(!0)};
return d?d.apply(this,arguments):f.cloneNode(!0)},track:null,id:""};h.createCueList=function(){return g.extend([],t)};h.parseCueTextToHTML=function(){var a=/(<\/?[^>]+>)/ig,b=/^(?:c|v|ruby|rt|b|i|u)/,f=/\<\s*\//,d=function(a,b,c,d){f.test(d)?a="</"+a+">":(c.splice(0,1),a="<"+a+" "+b+'="'+c.join(" ").replace(/\"/g,"&#34;")+'">');return a},c=function(a){var c=a.replace(/[<\/>]+/ig,"").split(/[\s\.]+/);c[0]&&(c[0]=c[0].toLowerCase(),b.test(c[0])?"c"==c[0]?a=d("span","class",c,a):"v"==c[0]&&(a=d("q",
"title",c,a)):a="");return a};return function(b){return b.replace(a,c)}}();h.loadTextTrack=function(a,b,f,d){var c=f.track,k=function(){var d=g.prop(b,"src"),f,i;if("disabled"!=c.mode&&d&&g.attr(b,"src")&&(g(a).unbind("play playing timeupdate updatetrackdisplay",k),g(b).unbind("checktrackmode",k),!c.readyState)){f=function(){c.readyState=3;c.cues=null;c.activeCues=c.shimActiveCues=c._shimActiveCues=null;g(b).triggerHandler("error")};c.readyState=1;try{c.cues=h.createCueList(),c.activeCues=c.shimActiveCues=
c._shimActiveCues=h.createCueList(),i=g.ajax({dataType:"text",url:d,success:function(d){"text/vtt"!=i.getResponseHeader("content-type")&&e.warn("set the mime-type of your WebVTT files to text/vtt. see: http://dev.w3.org/html5/webvtt/#text/vtt");h.parseCaptions(d,c,function(d){d&&"length"in d?(c.readyState=2,g(b).triggerHandler("load"),g(a).triggerHandler("updatetrackdisplay")):f()})},error:f})}catch(l){f(),e.warn(l)}}};c.readyState=0;c.shimActiveCues=null;c._shimActiveCues=null;c.activeCues=null;
c.cues=null;g(a).unbind("play playing timeupdate updatetrackdisplay",k);g(b).unbind("checktrackmode",k);g(a).bind("play playing timeupdate updatetrackdisplay",k);g(b).bind("checktrackmode",k);if(d)c.mode=s[c.kind]?"showing":"hidden",k()};h.createTextTrack=function(a,b){var f,d;if(b.nodeName&&(d=e.data(b,"trackData")))n(b,d),f=d.track;if(!f)f=j(e.objectCreate(u)),v.forEach(function(a){var d=g.prop(b,a);d&&("srclang"==a&&(a="language"),f[a]=d)}),b.nodeName?(d=e.data(b,"trackData",{track:f}),h.loadTextTrack(a,
b,d,g.prop(b,"default"))):(f.cues=h.createCueList(),f.activeCues=f._shimActiveCues=f.shimActiveCues=h.createCueList(),f.mode="hidden",f.readyState=2);return f};h.parseCaptionChunk=function(){var a=/^(\d{2})?:?(\d{2}):(\d{2})\.(\d+)\s+\-\-\>\s+(\d{2})?:?(\d{2}):(\d{2})\.(\d+)\s*(.*)/,b=/^(DEFAULTS|DEFAULT)\s+\-\-\>\s+(.*)/g,f=/^(STYLE|STYLES)\s+\-\-\>\s*\n([\s\S]*)/g,d=/^(COMMENT|COMMENTS)\s+\-\-\>\s+(.*)/g;return function(c){var g,e,h,i;if(b.exec(c)||f.exec(c)||d.exec(c))return null;for(c=c.split(/\n/g);!c[0].replace(/\s+/ig,
"").length&&0<c.length;)c.shift();for(c[0].match(/^\s*[a-z0-9]+\s*$/ig)&&(h=""+c.shift().replace(/\s*/ig,""));0<c.length;){if(i=a.exec(c[0]))e=i.slice(1),g=parseInt(3600*(e[0]||0),10)+parseInt(60*(e[1]||0),10)+parseInt(e[2]||0,10)+parseFloat("0."+(e[3]||0)),e=parseInt(3600*(e[4]||0),10)+parseInt(60*(e[5]||0),10)+parseInt(e[6]||0,10)+parseFloat("0."+(e[7]||0));c=c.slice(0,0).concat(c.slice(1));break}if(!g&&!e)return null;c=c.join("\n");g=new TextTrackCue(g,e,c);if(h)g.id=h;return g}}();h.parseCaptions=
function(a,b,f){h.createCueList();var d,c,g,p,j;if(a)g=/^WEBVTT(\s*FILE)?/ig,c=function(i,l){for(;i<l;i++){d=a[i];if(g.test(d))j=!0;else if(d.replace(/\s*/ig,"").length){if(!j){e.error("please use WebVTT format. This is the standard");f(null);break}(d=h.parseCaptionChunk(d,i))&&b.addCue(d)}if(p<(new Date).getTime()-9){i++;setTimeout(function(){p=(new Date).getTime();c(i,l)},90);break}}i>=l&&(j||e.error("please use WebVTT format. This is the standard"),f(b.cues))},a=a.replace(/\r\n/g,"\n"),setTimeout(function(){a=
a.replace(/\r/g,"\n");setTimeout(function(){p=(new Date).getTime();a=a.split(/\n\n+/g);c(0,a.length)},9)},9);else throw Error("Required parameter captionData not supplied.");};h.createTrackList=function(a){a=e.data(a,"mediaelementBase")||e.data(a,"mediaelementBase",{});if(!a.textTracks)a.textTracks=[],e.defineProperties(a.textTracks,{onaddtrack:{value:null}}),j(a.textTracks);return a.textTracks};Modernizr.track||(e.defineNodeNamesBooleanProperty(["track"],"default"),e.reflectProperties(["track"],
["srclang","label"]),e.defineNodeNameProperties("track",{src:{reflect:!0,propType:"src"}}));e.defineNodeNameProperties("track",{kind:{attr:Modernizr.track?{set:function(a){var b=e.data(this,"trackData");this.setAttribute("data-kind",a);if(b)b.attrKind=a},get:function(){var a=e.data(this,"trackData");return a&&"attrKind"in a?a.attrKind:this.getAttribute("kind")}}:{},reflect:!0,propType:"enumarated",defaultValue:"subtitles",limitedTo:["subtitles","captions","descriptions","chapters","metadata"]}});
e.onNodeNamesPropertyModify("track","kind",function(){var a=e.data(this,"trackData");if(a)a.track.kind=g.prop(this,"kind"),n(this,a)});e.onNodeNamesPropertyModify("track","src",function(a){if(a){var a=e.data(this,"trackData"),b;a&&(b=g(this).closest("video, audio"),b[0]&&h.loadTextTrack(b,this,a))}});e.defineNodeNamesProperties(["track"],{ERROR:{value:3},LOADED:{value:2},LOADING:{value:1},NONE:{value:0},readyState:{get:function(){return(g.prop(this,"track")||{readyState:0}).readyState},writeable:!1},
track:{get:function(){return h.createTextTrack(g(this).closest("audio, video")[0],this)},writeable:!1}},"prop");e.defineNodeNamesProperties(["audio","video"],{textTracks:{get:function(){g("track",this).each(function(){n(this)});return h.createTrackList(this)},writeable:!1},addTextTrack:{value:function(a,b,f){a=h.createTextTrack(this,{kind:a||"",label:b||"",srclang:f||""});b=e.data(this,"mediaelementBase")||e.data(this,"mediaelementBase",{});if(!b.scriptedTextTracks)b.scriptedTextTracks=[];b.scriptedTextTracks.push(a);
m.call(this);return a}}},"prop");g(r).bind("emptied ended",function(a){g(a.target).is("audio, video")&&setTimeout(function(){m.call(a.target)},9)});e.addReady(function(a,b){g("video, audio",a).add(b.filter("video, audio, track").closest("audio, video")).each(m).each(function(){if(Modernizr.track){var a=this.textTracks;g.prop(this,"textTracks").length!=a.length&&e.error("textTracks couldn't be copied");g("track",this).each(function(){var a=g.prop(this,"track"),b=this.track,e,f;if(b){e=g.prop(this,
"kind");f=b.readyState||this.readyState;if(b.mode||f)a.mode=b.mode;if("descriptions"!=e)b.mode="string"==typeof b.mode?"disabled":0,this.kind="metadata",g(this).attr({kind:e})}}).bind("load error",function(a){a.originalEvent&&a.stopImmediatePropagation()})}})});Modernizr.track&&g("video, audio").trigger("trackapichange")});
