jQuery.webshims.register("track",function(f,h,o,r){var i=h.mediaelement;(new Date).getTime();var v={subtitles:1,captions:1},s=function(){h.error("not implemented yet")},p=function(a){var c={};a.addEventListener=function(b,a){c[b]&&h.error("always use $.bind to the shimed event: "+b+" already bound fn was: "+c[b]+" your fn was: "+a);c[b]=a};a.removeEventListener=function(a,d){c[a]&&c[a]!=d&&h.error("always use $.unbind to the shimed event: "+a+" already bound fn was: "+c[a]+" your fn was: "+d);c[a]&&
delete c[a]};return a},w={getCueById:s},x={shimActiveCues:null,_shimActiveCues:null,activeCues:null,cues:null,kind:"subtitles",label:"",language:"",mode:0,readyState:0,oncuechange:null,toString:function(){return"[object TextTrack]"},addCue:function(a){if(!this.cues)this.cues=[];a.track&&h.error("cue already part of a track element");a.track=this;this.cues.push(a)},removeCue:s,DISABLED:0,OFF:0,HIDDEN:1,SHOWING:2,ERROR:3,LOADED:2,LOADING:1,NONE:0},y=["kind","label","srclang"],z=Function.prototype.call.bind(Object.prototype.hasOwnProperty),
q=function(){var a=f.prop(this,"textTracks"),c=h.data(this,"mediaelementBase"),b=a.splice(0),d,e;f("track",this).each(function(){a.push(f.prop(this,"track"))});if(c.scriptedTextTracks)for(d=0,e=c.scriptedTextTracks.length;d<e;d++)a.push(c.scriptedTextTracks[d]);if(i.trackDisplay&&c.trackDisplay)for(d=0,e=b.length;d<e;d++)-1==a.indexOf(b[d])&&i.trackDisplay.hide(b[d],c)},t=function(a,c){var b;c||(c=h.data(a,"trackData"));if(c&&!c.isTriggering)c.isTriggering=!0,b=(c.track||{}).mode,setTimeout(function(){if(b!==
(c.track||{}).mode)(c.track||{}).readyState?f(a).parent().triggerHandler("updatetrackdisplay"):f(a).triggerHandler("checktrackmode");c.isTriggering=!1},9)},u=function(){if(!o.TextTrackCue||h.bugs.track){var a=f("<div />")[0];o.TextTrackCue=function(a,b,d,e,k,g){(4>arguments.length||6<arguments.length)&&h.error("wrong arguments.length for TextTrackCue.constructor");this.id=a;this.startTime=b;this.endTime=d;this.text=e;this.pauseOnExit=g||!1;k&&h.warn("webshims currently does not support any cue settings");
p(this)};o.TextTrackCue.prototype={onenter:null,onexit:null,pauseOnExit:!1,getCueAsHTML:function(){var c="",b="",d=r.createDocumentFragment(),e;if(!z(this,"getCueAsHTML"))e=this.getCueAsHTML=function(){var k,g;if(c!=this.text){c=this.text;b=i.parseCueTextToHTML(c);a.innerHTML=b;for(k=0,g=a.childNodes.length;k<g;k++)d.appendChild(a.childNodes[k].cloneNode(!0))}return d.cloneNode(!0)};return e?e.apply(this,arguments):d.cloneNode(!0)},track:null,id:"",snapToLines:!0,line:-1,size:100,position:50,vertical:"",
align:"middle"}}};u();i.TextTrackCue=function(a,c,b,d,e,k){var g;a||(a="");c||(c=0);b||(b=0);d||(d="");i.TextTrackCue=function(a,c,b,g,k,d){return new TextTrackCue(a,c,b,g,k||"",d||!1)};try{g=new TextTrackCue(a,c,b,d,e||"",k||!1)}catch(f){}if(!g)try{g=new TextTrackCue(a,c,b,d)}catch(j){}g?i.TextTrackCue=function(a,c,b,g){return new TextTrackCue(a,c,b,g)}:(h.bugs.track=!0,u());return g};i.createCueList=function(){return f.extend([],w)};i.parseCueTextToHTML=function(){var a=/(<\/?[^>]+>)/ig,c=/^(?:c|v|ruby|rt|b|i|u)/,
b=/\<\s*\//,d=function(a,c,d,e){b.test(e)?a="</"+a+">":(d.splice(0,1),a="<"+a+" "+c+'="'+d.join(" ").replace(/\"/g,"&quot;")+'">');return a},e=function(a){var b=a.replace(/[<\/>]+/ig,"").split(/[\s\.]+/);b[0]&&(b[0]=b[0].toLowerCase(),c.test(b[0])?"c"==b[0]?(b.splice(0,1),a=d("span","class",b,a)):"v"==b[0]&&(a=d("q","title",b,a)):a="");return a};return function(b){return b.replace(a,e)}}();i.createTextTrack=function(a,c){var b,d,e;if(c.nodeName&&(d=h.data(c,"trackData")))t(c,d),b=d.track;if(!b)if(b=
p(h.objectCreate(x)),y.forEach(function(a){var d=f.prop(c,a);d&&("srclang"==a&&(a="language"),b[a]=d)}),c.nodeName){if(e=function(){var d,g;if(b.mode&&(f(a).unbind("play playing timeupdate updatetrackdisplay",e),f(c).unbind("checktrackmode",e),!b.readyState)){d=function(){b.readyState=3;f(c).triggerHandler("error")};b.readyState=1;try{g=f.ajax({dataType:"text",url:f.prop(c,"src"),success:function(e){"text/vtt"!=g.getResponseHeader("content-type")&&h.warn("set the mime-type of your WebVTT files to text/vtt. see: http://dev.w3.org/html5/webvtt/#text/vtt");
i.parseCaptions(e,b,function(e){e&&"length"in e?(b.cues=e,b.activeCues=b.shimActiveCues=b._shimActiveCues=i.createCueList(),b.readyState=2,f(c).triggerHandler("load"),f(a).triggerHandler("updatetrackdisplay")):d()})},error:d})}catch(n){d(),h.warn(n)}}},d=h.data(c,"trackData",{track:b}),f(a).bind("play playing timeupdate updatetrackdisplay",e),f(c).bind("checktrackmode",e),f.prop(c,"default"))b.mode=v[b.kind]?2:1,e()}else b.cues=i.createCueList(),b.activeCues=b._shimActiveCues=b.shimActiveCues=i.createCueList(),
b.mode=1,b.readyState=2;return b};i.parseCaptionChunk=function(){var a=/^(\d{2})?:?(\d{2}):(\d{2})\.(\d+)\s+\-\-\>\s+(\d{2})?:?(\d{2}):(\d{2})\.(\d+)\s*(.*)/,c=/^(DEFAULTS|DEFAULT)\s+\-\-\>\s+(.*)/g,b=/^(STYLE|STYLES)\s+\-\-\>\s*\n([\s\S]*)/g,d=/^(COMMENT|COMMENTS)\s+\-\-\>\s+(.*)/g;return function(e,h){var g,f,j,l,m;if(c.exec(e)||b.exec(e)||d.exec(e))return null;for(g=e.split(/\n/g);!g[0].replace(/\s+/ig,"").length&&0<g.length;)g.shift();for(l=g[0].match(/^\s*[a-z0-9]+\s*$/ig)?""+g.shift().replace(/\s*/ig,
""):h;0<g.length;){if(m=a.exec(g[0]))j=m.slice(1),f=parseInt(3600*(j[0]||0),10)+parseInt(60*(j[1]||0),10)+parseInt(j[2]||0,10)+parseFloat("0."+(j[3]||0)),j=parseInt(3600*(j[4]||0),10)+parseInt(60*(j[5]||0),10)+parseInt(j[6]||0,10)+parseFloat("0."+(j[7]||0));g=g.slice(0,0).concat(g.slice(1));break}if(!f&&!j)return null;g=g.join("\n");return i.TextTrackCue(l,f,j,g,"",!1)}}();i.parseCaptions=function(a,c,b){var d=i.createCueList(),e,f,g,n,j;if(a)g=/^WEBVTT(\s*FILE)?/ig,f=function(l,m){for(;l<m;l++){e=
a[l];if(g.test(e))j=!0;else if(e.replace(/\s*/ig,"").length){if(!j){h.error("please use WebVTT format. This is the standard");b(null);break}if(e=i.parseCaptionChunk(e,l))e.track=c,d.push(e)}if(n<(new Date).getTime()-9){l++;setTimeout(function(){n=(new Date).getTime();f(l,m)},90);break}}l>=m&&(j||h.error("please use WebVTT format. This is the standard"),b(d))},a=a.replace(/\r\n/g,"\n"),setTimeout(function(){a=a.replace(/\r/g,"\n");setTimeout(function(){n=(new Date).getTime();a=a.split(/\n\n+/g);f(0,
a.length)},9)},9);else throw Error("Required parameter captionData not supplied.");};i.createTrackList=function(a){a=h.data(a,"mediaelementBase")||h.data(a,"mediaelementBase",{});if(!a.textTracks)a.textTracks=[],h.defineProperties(a.textTracks,{onaddtrack:{value:null}}),p(a.textTracks);return a.textTracks};Modernizr.track||(h.defineNodeNamesBooleanProperty(["track"],"default"),h.reflectProperties(["track"],["srclang","label"]),h.defineNodeNameProperties("track",{kind:{reflect:!0,propType:"enumarated",
defaultValue:"subtitles",limitedTo:["subtitles","captions","descriptions","chapters","metadata"]},src:{reflect:!0,propType:"src"}}));h.defineNodeNamesProperties(["track"],{ERROR:{value:3},LOADED:{value:2},LOADING:{value:1},NONE:{value:0},readyState:{get:function(){return(f.prop(this,"track")||{readyState:0}).readyState},writeable:!1},track:{get:function(){return i.createTextTrack(f(this).closest("audio, video")[0],this)},writeable:!1}},"prop");h.defineNodeNamesProperties(["audio","video"],{textTracks:{get:function(){f("track",
this).each(function(){t(this)});return i.createTrackList(this)},writeable:!1},addTextTrack:{value:function(a,c,b){a=i.createTextTrack(this,{kind:a||"",label:c||"",srclang:b||""});c=h.data(this,"mediaelementBase")||h.data(this,"mediaelementBase",{});if(!c.scriptedTextTracks)c.scriptedTextTracks=[];c.scriptedTextTracks.push(a);q.call(this);return a}}},"prop");f(r).bind("emptied",function(a){f(a.target).is("audio, video")&&setTimeout(function(){q.call(a.target)},9)});h.addReady(function(a,c){f("video, audio",
a).add(c.filter("video, audio, track").closest("audio, video")).each(q).each(function(){if(Modernizr.track){var a=this.textTracks;f.prop(this,"textTracks").length!=a.length&&h.error("textTracks couldn't be copied");f("track",this).each(function(){var a=f.prop(this,"track"),b=this.track,c;if(b){c=b.readyState||this.readyState;if(b.mode||c)a.mode=b.mode;b.mode=0}}).bind("load error",function(a){if(a.originalEvent)a.stopImmediatePropagation(),this.track.mode=0})}})});Modernizr.track&&f("video, audio").trigger("trackapichange")});
