jQuery.webshims.ready("es5",function(a){a.extend(a.expr.filters,{valid:function(b){return(a.attr(b,"validity")||{valid:true}).valid},invalid:function(b){return!a.expr.filters.valid(b)},willValidate:function(b){return a.attr(b,"willValidate")}});a.webshims.validityAlert=function(){var b={hideDelay:5E3,showFor:function(f,k){f=a(f);var l=(f.data("inputUIReplace")||{visual:f}).visual;n();b.clear();h.attr("for",l.attr("id"));this.getMessage(f);this.position(l);this.show();if(this.hideDelay)e=setTimeout(g,
this.hideDelay);if(!k){l.focus();a(document).bind("focusout.validityalert",g)}},getMessage:function(f){a("> span",h).html(f.attr("validationMessage"))},position:function(f){var k=f.offset();k.top+=f.outerHeight();h.css(k)},show:function(){h.css("display")==="none"?h.fadeIn():h.fadeTo(400,1)},hide:function(){b.clear();h.fadeOut()},clear:function(){clearTimeout(e);a(document).unbind("focusout.validityalert");h.stop().removeAttr("for")},alert:a('<label class="validity-alert" role="alert"><span class="va-box" /></label>').css({position:"absolute",
display:"none"})},h=b.alert,e=false,g=a.proxy(b,"hide"),j=false,n=function(){if(!j){j=true;a(function(){h.appendTo("body")})}};return b}();a.webshims.validityMessages.en=a.webshims.validityMessages.en||a.webshims.validityMessages["en-US"]||{typeMismatch:{email:"{%value} is not a legal email address",url:"{%value} is not a valid web address",number:"{%value} is not a number!",date:"{%value} is not a date",time:"{%value} is not a time",range:"{%value} is not a number!","datetime-local":"{%value} is not a correct date-time format."},
rangeUnderflow:"{%value} is too low. The lowest value you can use is {%min}.",rangeOverflow:"{%value}  is too high. The highest value you can use is {%max}.",stepMismatch:"The value {%value} is not allowed for this form.",tooLong:"The entered text is too large! You used {%valueLen} letters and the limit is {%maxlength}.",patternMismatch:"{%value} is not in the format this page requires! {%title}",valueMissing:"You have to specify a value"};a.webshims.validityMessages["en-US"]=a.webshims.validityMessages["en-US"]||
a.webshims.validityMessages.en;a.webshims.validityMessages[""]=a.webshims.validityMessages[""]||a.webshims.validityMessages.en;a.webshims.validityMessages.de=a.webshims.validityMessages.de||{typeMismatch:{email:"{%value} ist keine zul\u00e4ssige E-Mail-Adresse",url:"{%value} ist keine zul\u00e4ssige Webadresse",number:"{%value} ist keine Nummer!",date:"{%value} ist kein Datum",time:"{%value} ist keine Uhrzeit",range:"{%value} ist keine Nummer!","datetime-local":"{%value} ist kein Datum-Uhrzeit Format."},
rangeUnderflow:"{%value} ist zu niedrig. {%min} ist der unterste Wert, den Sie benutzen k\u00f6nnen.",rangeOverflow:"{%value} ist zu hoch. {%max} ist der oberste Wert, den Sie benutzen k\u00f6nnen.",stepMismatch:"Der Wert {%value} ist in diesem Feld nicht zul\u00e4ssig. Hier sind nur bestimmte Werte zul\u00e4ssig. {%title}",tooLong:"Der eingegebene Text ist zu lang! Sie haben {%valueLen} Buchstaben eingegeben, dabei sind {%maxlength} das Maximum.",patternMismatch:"{%value} hat f\u00fcr diese Seite ein falsches Format! {%title}",
valueMissing:"Sie m\u00fcssen einen Wert eingeben"};var r=a.webshims.validityMessages[""];a(document).bind("htmlExtLangChange",function(){a.webshims.activeLang(a.webshims.validityMessages,"validation-base",function(b){r=b})});a.webshims.createValidationMessage=function(b,h){var e=r[h];if(e&&typeof e!=="string")e=e[(b.getAttribute("type")||"").toLowerCase()]||e.defaultMessage;e&&["value","min","max","title","maxlength","label"].forEach(function(g){if(e.indexOf("{%"+g)!==-1){var j=(g=="label"?a.trim(a("label[for="+
b.id+"]",b.form).text()).replace(/\*$|:$/,""):a.attr(b,g))||"";e=e.replace("{%"+g+"}",j);if("value"==g)e=e.replace("{%valueLen}",j.length)}});return e||""};a.each(a.support.validationMessage?["customValidationMessage"]:["customValidationMessage","validationMessage"],function(b,h){a.webshims.attr(h,{elementNames:["input","select","textarea"],getter:function(e){var g="";if(!a.attr(e,"willValidate"))return g;var j=a.attr(e,"validity")||{valid:1};if(j.valid)return g;if(j.customError||h==="validationMessage")if(g=
"validationMessage"in e?e.validationMessage:a.data(e,"customvalidationMessage"))return g;a.each(j,function(n,f){if(!(n=="valid"||!f))if(g=a.webshims.createValidationMessage(e,n))return false});return g||""}})});(function(){var b,h=[],e,g,j,n;a.support.validity===true&&window.addEventListener&&!window.noHTMLExtFixes&&window.addEventListener("submit",function(f){if(f.target.checkValidity&&a.attr(f.target,"novalidate")===undefined&&!f.target.checkValidity())j=true},true);a(document).bind("invalid",function(f){if(!b){g=
f.target.form;if(a.support.validity===true&&g&&!window.noHTMLExtFixes){var k=a(g).bind("submit.preventInvalidSubmit",function(l){if(a.attr(g,"novalidate")===undefined){l.stopImmediatePropagation();return false}}).data("events").submit;k&&k.length>1&&k.unshift(k.pop())}b=a.Event("firstinvalid");a(f.target).trigger(b)}b&&b.isDefaultPrevented()&&f.preventDefault();if(a.support.validity!==true||h.indexOf(f.target)==-1)h.push(f.target);else if(!window.noHTMLExtFixes){n=true;f.stopImmediatePropagation()}f.extraData=
"fix";clearTimeout(e);e=setTimeout(function(){var l={type:"lastinvalid",cancelable:false,invalidlist:a(h)};j&&!n&&b.target!==document.activeElement&&document.activeElement&&!a.data(b.target,"maybePreventedinvalid")&&a.webshims.validityAlert.showFor(b.target);j=b=n=false;h=[];a(g).unbind("submit.preventInvalidSubmit");a(f.target).trigger(l,l)},0)})})();(function(){if(!(a.support.validity!==true||a.support.fieldsetValidation||window.noHTMLExtFixes)){a.support.fieldsetValidation="shim";a.webshims.addMethod("checkValidity",
function(){if(a.nodeName(this,"fieldset")){var b=true;a(this.elements||"input, textarea, select",this).each(function(){if(this.checkValidity)this.checkValidity()||(b=false)});return b}else if(this.checkValidity)return this.checkValidity()})}})();a.support.validationMessage=a.support.validationMessage||"shim";(function(){if(a.support.validity===true){var b=a('<form><select name="test"><option selected required value=""></option></select></form>').find("select"),h=!(!("required"in b[0])&&b.attr("validity").valid&&
!window.noHTMLExtFixes),e=!!(a('<input type="datetime-local" />')[0].type=="datetime-local"&&a('<input type="range" />')[0].type=="range");b=null;if(!(h&&e)){var g=a.webshims.inputTypes,j={},n=["customError","typeMismatch","rangeUnderflow","rangeOverflow","stepMismatch","tooLong","patternMismatch","valueMissing","valid"],f=a.attr,k=a.fn.val,l={value:1};b=[];var p=function(c){var i=(c.getAttribute&&c.getAttribute("type")||c.type||"").toLowerCase();!h&&i=="select-one"||!g[i]||a.attr(c,"validity")};
if(!h){a.extend(l,{required:1,size:1,multiple:1,selectedIndex:1});b.push("select")}if(!e){a.extend(l,{min:1,max:1,step:1});b.push("input")}a.webshims.addInputType=function(c,i){g[c]=i};a.webshims.addValidityRule=function(c,i){j[c]=i};a.webshims.addValidityRule("typeMismatch",function(c,i,d,m){if(i==="")return false;m=m.typeMismatch;if(!("type"in d))d.type=(c[0].getAttribute("type")||"").toLowerCase();if(g[d.type]&&g[d.type].mismatch)m=g[d.type].mismatch(i,c);return m});a.webshims.attr("validity",
{elementNames:b,getter:function(c){var i=c.validity;if(!i)return i;var d={};n.forEach(function(o){d[o]=i[o]});if(!a.attr(c,"willValidate"))return d;var m=a(c),u={type:(c.getAttribute&&c.getAttribute("type")||"").toLowerCase(),nodeName:(c.nodeName||"").toLowerCase()},v=k.call(m),w=!!a.data(c,"hasCustomError");d.customError=w;if(d.valid&&d.customError)d.valid=false;else if(!d.valid){var s=true;a.each(d,function(o,q){if(q)return s=false});if(s)d.valid=true}a.each(j,function(o,q){var t;d[o]=q(m,v,u,d);
if(d[o]&&d.valid){t=a.webshims.createValidationMessage(c,o);c.setCustomValidity(t);d.valid=false}});d.valid&&c.setCustomValidity("");return d}});a.webshims.addMethod("setCustomValidity",function(c){c+="";this.setCustomValidity(c);a.data(this,"hasCustomError",!!c);p(this)});a.fn.val=function(){var c=k.apply(this,arguments);this.each(function(){p(this)});return c};document.addEventListener&&document.addEventListener("change",function(c){p(c.target)},true);if(!h){a.webshims.createBooleanAttrs("required",
["select"]);a.webshims.addValidityRule("valueMissing",function(c,i,d,m){if(d.nodeName=="select"&&!i&&c.attr("required")&&c[0].size<2){if(!d.type)d.type=c[0].type;if(d.type=="select-one"&&a("> option:first-child",c).attr("selected"))return true}return m.valueMissing})}a.attr=function(c,i,d){var m=f.apply(this,arguments);l[i]&&d!==undefined&&c.form&&p(c);return m};a.webshims.addReady(function(c){a("input",c).each(function(){p(this)})})}}})();a.webshims.createReadyEvent("validation-base")},true);
