(function(b){var k=document;"abbr article aside audio canvas details figcaption figure footer header hgroup mark meter nav output progress section source summary time track video".replace(/\w+/g,function(a){k.createElement(a)});b.support.dynamicHTML5=!!b("<video><div></div></video>")[0].innerHTML;var m=function(a,f,d){if(a){b.isArray(a)||(a=[a]);b.each(a,function(c,e){if(!(d&&b.webshims.loader.modules[e]&&b.webshims.loader.modules[e].noAutoCallback)){f||(e+="Ready");if(!(b.event.special[e]&&b.event.special[e].add)){b.event.trigger(e);
b.event.special[e]={add:function(g){g.handler.call(this,b.Event(e))}}}}})}};b.webshims={version:"not versioned yet",fixHTML5:function(){var a,f;return b.support.dynamicHTML5?function(d){return d}:function(d){if(!a){f=document.body;a=document.createElement("div");a.style.display="none"}var c=a.cloneNode(false);f.appendChild(c);c.innerHTML=d;f.removeChild(c);return c.childNodes}}(),createReadyEvent:m,loader:{basePath:function(){var a=b("script");a=a[a.length-1].src.split("?")[0];return a.slice(0,a.lastIndexOf("/")+
1)}(),combinations:{},moduleList:[],modules:{},features:{},featureList:[],addModule:function(a,f){this.modules[a]=f},loadList:function(){var a=[];return function(f){var d=[],c=b.webshims.loader;b.each(f,function(e,g){var h=c.modules[g];if("test"in h&&h.test())m(g);else{h.css&&c.loadCSS(h.css);d.push(g)}});b.each(c.combinations||[],function(e,g){var h=true;b.each(g,function(i,j){if(b.inArray(j,d)===-1||b.inArray(j,a)!==-1)return h=false});if(h){a=a.concat(g);c.loadScript(e,false,g);return false}});
b.each(d,function(e,g){if(b.inArray(g,a)==-1)c.loadScript(c.modules[g].src||g,false,g)})}}(),makePath:function(a){if(a.indexOf("://")!=-1||a.indexOf("/")===0)return a;if(a.indexOf(".js")==-1&&a.indexOf(".css")==-1)a+=".js";return b.webshims.loader.basePath+a},loadCSS:function(){var a,f=[];return function(d){d=this.makePath(d);if(b.inArray(d,f)==-1){a=a||k.getElementsByTagName("head")[0]||k.body;f.push(d);b('<link rel="stylesheet" href="'+d+'" />').prependTo(a).attr({href:d,rel:"stylesheet"})}}}(),
loadScript:function(){var a,f=[];return function(d,c,e){d=b.webshims.loader.makePath(d);if(b.inArray(d,f)==-1){a=a||k.getElementsByTagName("head")[0]||k.body;if(!a||!a.appendChild)setTimeout(function(){b.webshims.loader.loadScript(d,c)},10);else{var g=k.createElement("script"),h=function(i){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){g.onload=null;g.onerror=null;g.onreadystatechange=null;c&&c(i,this);m(e,false,true);g=null}};g.src=d;g.onload=h;g.onerror=h;g.onreadystatechange=
h;a.appendChild(g);f.push(d)}}}}()},readyModules:function(a,f,d,c){d=d;if(typeof a=="string"){a=a.split(" ");d=true}if(d)a=b.map(a,function(g){return b.webshims.loader.modules[g]||b.webshims.loader.features[g]?g+"Ready":g});if(a.length){d=a.shift();var e=function(){b.webshims.readyModules(a,f,false,c)};d=="ready"?b(e):b(k).one(d,e)}else c?f():setTimeout(f,0)},capturingEvents:function(a){if(k.addEventListener){if(typeof a=="string")a=[a];b.each(a,function(f,d){var c=function(e){e=b.event.fix(e);return b.event.handle.call(this,
e)};b.event.special[d]=b.event.special[d]||{};b.extend(b.event.special[d],{setup:function(){this.addEventListener(d,c,true)},teardown:function(){this.removeEventListener(d,c,true)}})})}},attr:function(){var a=[{}],f=function(d){var c=b.attr;b.attr=function(e,g,h,i,j){if(!d[g]||e.nodeType!==1||d[g].elementNames[0]!=="*"&&b.inArray((e.nodeName||"").toLowerCase(),d[g].elementNames)===-1)return c(e,g,h,i,j);var l=function(){if(h===undefined)return c(e,g,h,i,j);return c(e,g,h,i,j)};if(h===undefined)return d[g].getter(e,
l,h,i,j);d[g].setter(e,h,l,i,j)}};f(a[0]);return function(d,c){c.elementNames=c.elementNames||["*"];if(c.setter){if(!b.isFunction(c.setter))c.setter=function(h,i,j){return j()}}else c.setter=function(){throw d+" is readonly";};if(!c.getter||!b.isFunction(c.getter))c.getter=function(h,i){return i()};if(typeof c.elementNames=="string")c.elementNames=[c.elementNames];var e=false;b.each(a,function(h,i){if(!i[d]){i[d]=c;e=true;return false}});if(!e){var g={};g[d]=c;f(g);a.push(g)}}}(),createBooleanAttrs:function(a,
f){if(typeof name==="string")a=[a];b.each(a,function(d,c){b.webshims.attr(c,{elementNames:f,getter:function(e){return typeof e[c]=="boolean"?e[c]:!!(e.attributes[c]||{}).specified},setter:function(e,g){(g=!!g)?e.setAttribute(c,c):e.removeAttribute(c);e[c]=g}})})},addMethod:function(a,f){var d=b.fn[a].elementNames||["*"];if(typeof d=="string")d=[ext.elementNames];b.fn[a]=function(){var c=arguments,e;this.each(function(){if(d[0]=="*"||b.inArray((this.nodeName||"").toLowerCase(),d)!==-1){e=f.apply(this,
c);return e!==undefined}});return e===undefined?this:e};b.fn[a].elementNames=d;b.fn[a].shim=true},addMethodName:function(a,f){if(!(b.fn[a]&&"shim"in b.fn[a])){b.fn[a]=function(){var d=arguments,c;this.each(function(){if(this[a]){c=this[a].apply(this,d);if(c!==undefined)return false}});return c!==undefined?c:this};b.fn[a].shim=false;b.fn[a].elementNames=f}},addPolyfill:function(a,f){f=f||{};var d=f.feature||a,c=b.webshims.loader,e=c.combinations;if(!c.features[d]){c.features[d]=[];c.featureList.push(d)}c.features[d].push(a);
c.addModule(a,f);c.moduleList.push(a);b.each(f.combination||[],function(g,h){if(e[h])c.combinations[h].push(a);else e[h]=[a]});if(f.methodNames){if(!b.isArray(f.methodNames))f.methodNames=[f.methodNames];b.each(f.methodNames,function(g,h){b.webshims.addMethodName(h.name,h.elementNames)})}},polyfill:function(a){var f=b.webshims.loader,d=[];a=a||f.featureList;if(typeof a=="string")a=a.split(" ");b.each(a,function(c,e){e!==f.features[e][0]&&b.webshims.readyModules(f.features[e],function(){m(e)},true);
d=d.concat(f.features[e])});f.loadCSS("shim.css");f.loadList(d)},activeLang:function(){var a=[navigator.browserLanguage||navigator.language||""],f=b("html").attr("lang"),d;f&&a.push(f);return function(c,e,g){if(c)if(!e||!g){if(c!==a[0]){a[0]=c;clearTimeout(d);d=setTimeout(function(){b(k).triggerHandler("htmlExtLangChange",a)},9)}}else{e=b.webshims.loader.modules[e].options;var h=function(j){if(b.inArray(j,i)!==-1){b.webshims.loader.loadScript(e.langSrc+j+".js",function(){c[j]&&g(c[j])});return true}return false},
i=e&&e.availabeLangs;b.each(a,function(j,l){var n=l.split("-")[0];if(c[l]||c[n]){g(c[l]||c[n]);return false}if(i&&e.langSrc!==undefined&&(h(l)||h(n)))return false})}return a}}()};b.webshims.ready=b.webshims.readyModules;(function(){var a=[];b.extend(b.webshims,{addReady:function(f){var d=function(c){b(function(){f(c)})};a.push(d);d(document)},triggerDomUpdate:function(f){f&&b.each(a,function(d,c){c(f)})}})})();!b.support.dynamicHTML5&&document.attachEvent&&b.webshims.loader.loadScript("http://html5shim.googlecode.com/svn/trunk/html5.js");
b.fn.htmlWebshim=function(a){a=this.html(a?b.webshims.fixHTML5(a):a);a===this&&b.isReady&&this.each(function(){b.webshims.triggerDomUpdate(this)});return a};b.each(["after","before","append","prepend"],function(a,f){b.fn[f+"Webshim"]=function(d){d=b(b.webshims.fixHTML5(d));this[f](d);b.isReady&&d.each(function(){b.webshims.triggerDomUpdate(this)});return this}});m("htmlExtLangChange",true)})(jQuery);
