(function(c){var k=document;"abbr article aside audio canvas details figcaption figure footer header hgroup mark meter nav output progress section source summary time track video".replace(/\w+/g,function(a){k.createElement(a)});c.support.dynamicHTML5=!!c("<video><div></div></video>")[0].innerHTML;var m=function(a,f){if(a){c.isArray(a)||(a=[a]);c.each(a,function(b,d){f||(d+="Ready");c.event.trigger(d);c.event.special[d]={add:function(g){g.handler.call(this,c.Event(d))}}})}};c.htmlExt={createReadyEvent:m,
loader:{basePath:function(){var a=c("script");a=a[a.length-1].src.split("?")[0];return a.slice(0,a.lastIndexOf("/")+1)}(),combinations:{},moduleList:[],modules:{},addModule:function(a,f){this.moduleList.push(a);this.modules[a]=f},loadList:function(){var a=[];return function(f){f=f||this.moduleList;if(typeof f=="string")f=[f];var b=[],d=c.htmlExt.loader;c.each(f,function(g,e){var h=d.modules[e];if("test"in h&&h.test())m(e);else{h.css&&d.loadCSS(h.css);b.push(e)}});c.each(d.combinations,function(g,
e){var h=true;c.each(e,function(i,j){if(c.inArray(j,b)===-1||c.inArray(j,a)!==-1)return h=false});if(h){a=a.concat(e);d.loadScript(g,false,e);return false}});c.each(b,function(g,e){c.inArray(e,a)==-1&&d.loadScript(e,false,e)})}}(),makePath:function(a){if(a.indexOf("://")!=-1||a.indexOf("/")===0)return a;if(a.indexOf(".js")==-1&&a.indexOf(".css")==-1)a+=".js";return c.htmlExt.loader.basePath+a},loadCSS:function(){var a,f=[];return function(b){b=this.makePath(b);if(c.inArray(b,f)==-1){a=a||k.getElementsByTagName("head")[0]||
k.body;f.push(b);c("<link />",{href:b,rel:"stylesheet"}).prependTo(a)}}}(),loadScript:function(){var a,f=[];return function(b,d,g){b=c.htmlExt.loader.makePath(b);if(c.inArray(b,f)==-1){a=a||k.getElementsByTagName("head")[0]||k.body;if(!a||!a.appendChild)setTimeout(function(){c.htmlExt.loader.loadScript(b,d)},10);else{var e=k.createElement("script"),h=function(i){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){e.onload=null;e.onerror=null;e.onreadystatechange=null;d&&d(i,
this);m(g);e=null}};e.src=b;e.onload=h;e.onerror=h;e.onreadystatechange=h;a.appendChild(e);f.push(b)}}}}()},readyModules:function(a,f){if(typeof a=="string")a=c.map(a.split(" "),function(b){return c.htmlExt.loader.modules[b]?b+"Ready":b});a.length?c(k).one(a.shift(),function(){c.htmlExt.readyModules(a,f)}):f()},activeLang:function(){var a=[navigator.browserLanguage||navigator.language||""];if(a[0]=="en-US")a[0]="en";var f=c("html").attr("lang");f&&a.push(f);return function(b,d,g){if(b)if(!d||!g){b=
b=="en-US"?"":b;a[0]=b;c(k).triggerHandler("htmlExtLangChange",a)}else{d=c.htmlExt.loader.modules[d].options;var e=b,h=function(j){if(c.inArray(j,i)!==-1){c.htmlExt.loader.loadScript(d.langSrc+j+".js",function(){e[j]&&g(e[j])});return true}return false},i=d&&d.availabeLangs;c.each(a,function(j,l){var n=l.split("-")[0];if(e[l]||e[n]){g(e[l]||e[n]);return false}if(i&&d.langSrc!==undefined&&(h(l)||h(n)))return false})}return a}}(),capturingEvents:function(a){if(k.addEventListener){if(typeof a=="string")a=
[a];c.each(a,function(f,b){var d=function(g){g=c.event.fix(g);return c.event.handle.call(this,g)};c.event.special[b]=c.event.special[b]||{};c.extend(c.event.special[b],{setup:function(){this.addEventListener(b,d,true)},teardown:function(){this.removeEventListener(b,d,true)}})})}},attr:function(){var a=[{}],f=function(b){var d=c.attr;c.attr=function(g,e,h,i,j){if(!b[e]||g.nodeType!==1||b[e].elementNames[0]!=="*"&&c.inArray((g.nodeName||"").toLowerCase(),b[e].elementNames)===-1)return d(g,e,h,i,j);
var l=function(){if(h===undefined)return d(g,e,h,i,j);return d(g,e,h,i,j)};if(h===undefined)return b[e].getter(g,l,h,i,j);b[e].setter(g,h,l,i,j)}};f(a[0]);return function(b,d){d.elementNames=d.elementNames||["*"];if(d.setter){if(!c.isFunction(d.setter))d.setter=function(h,i,j){return j()}}else d.setter=function(){throw b+" is readonly";};if(!d.getter||!c.isFunction(d.getter))d.getter=function(h,i){return i()};if(typeof d.elementNames=="string")d.elementNames=[d.elementNames];var g=false;c.each(a,
function(h,i){if(!i[b]){i[b]=d;g=true;return false}});if(!g){var e={};e[b]=d;f(e);a.push(e)}}}(),createBooleanAttrs:function(a,f){if(typeof name==="string")a=[a];c.each(a,function(b,d){c.htmlExt.attr(d,{elementNames:f,getter:function(g){return typeof g[d]=="boolean"?g[d]:!!(g.attributes[d]||{}).specified},setter:function(g,e){(e=!!e)?g.setAttribute(d,d):g.removeAttribute(d);g[d]=e}})})},addMethod:function(a,f){var b=c.fn[a].elementNames||["*"];if(typeof b=="string")b=[ext.elementNames];c.fn[a]=function(){var d=
arguments,g;this.each(function(){if(b[0]=="*"||c.inArray((this.nodeName||"").toLowerCase(),b)!==-1){g=f.apply(this,d);return g!==undefined}});return g===undefined?this:g};c.fn[a].elementNames=b;c.fn[a].shim=true},addModule:function(){var a=function(f,b,d,g){var e=g||function(h,i){if(h[b])return h[b].apply(h,i)};c.fn[b]=function(){var h=arguments,i;this.each(function(){i=e(this,h);if(i!==undefined)return false});return i!==undefined?i:this};c.fn[b].shim=false;c.fn[b].elementNames=d};return function(f,
b){b=b||{};c.htmlExt.loader.addModule(f,b);c(k).one(f+"Ready",function(){c("html").addClass(f+"-ready")});var d=c.htmlExt.loader.combinations;c.each(b.combination||[],function(g,e){if(d[e])c.htmlExt.loader.combinations[e].push(f);else d[e]=[f]});if(b.methodNames){if(!c.isArray(b.methodNames))b.methodNames=[b.methodNames];c.each(b.methodNames,function(g,e){a(f,e.name,e.elementNames,e.bugFix)})}}}()};(function(){var a=[];c.extend(c.htmlExt,{addReady:function(f){var b=function(d){c(function(){f(d)})};
a.push(b);b(document)},triggerDomUpdate:function(f){f&&c.each(a,function(b,d){d(f)})}})})();!c.support.dynamicHTML5&&document.attachEvent&&c.htmlExt.loader.loadScript("http://html5shim.googlecode.com/svn/trunk/html5.js");m("htmlExtLangChange",true)})(jQuery);
