(function(b){var k=document;"abbr article aside audio canvas details figcaption figure footer header hgroup mark meter nav output progress section source summary time track video".replace(/\w+/g,function(a){k.createElement(a)});b.support.dynamicHTML5=!!b("<video><div></div></video>")[0].innerHTML;var m=function(a,g,d){if(a){b.isArray(a)||(a=[a]);b.each(a,function(c,f){if(!(d&&b.webshims.loader.modules[f]&&b.webshims.loader.modules[f].noAutoCallback)){g||(f+="Ready");if(!(b.event.special[f]&&b.event.special[f].add)){b.event.trigger(f);
b.event.special[f]={add:function(e){e.handler.call(this,b.Event(f))}}}}})}};b.webshims={version:"not versioned yet",fixHTML5:function(){var a,g;return b.support.dynamicHTML5?function(d){return d}:function(d){if(!a){g=document.body;a=document.createElement("div");a.style.display="none"}var c=a.cloneNode(false);g.appendChild(c);c.innerHTML=d;g.removeChild(c);return c.childNodes}}(),createReadyEvent:m,loader:{basePath:function(){var a=b("script");a=a[a.length-1].src.split("?")[0];return a.slice(0,a.lastIndexOf("/")+
1)}(),combinations:{},moduleList:[],modules:{},features:{},featureList:[],addModule:function(a,g){this.modules[a]=g},loadList:function(){var a=[];return function(g){var d=[],c=b.webshims.loader;b.each(g,function(f,e){var h=c.modules[e];if("test"in h&&h.test())m(e);else{h.css&&c.loadCSS(h.css);d.push(e)}});b.each(c.combinations||[],function(f,e){var h=true;b.each(e,function(i,j){if(b.inArray(j,d)===-1||b.inArray(j,a)!==-1)return h=false});if(h){a=a.concat(e);c.loadScript(f,false,e);return false}});
b.each(d,function(f,e){if(b.inArray(e,a)==-1)c.loadScript(c.modules[e].src||e,false,e)})}}(),makePath:function(a){if(a.indexOf("://")!=-1||a.indexOf("/")===0)return a;if(a.indexOf(".js")==-1&&a.indexOf(".css")==-1)a+=".js";return b.webshims.loader.basePath+a},loadCSS:function(){var a,g=[];return function(d){d=this.makePath(d);if(b.inArray(d,g)==-1){a=a||k.getElementsByTagName("head")[0]||k.body;g.push(d);b('<link rel="stylesheet" href="'+d+'" />').prependTo(a).attr({href:d,rel:"stylesheet"})}}}(),
loadScript:function(){var a,g=[];return function(d,c,f){d=b.webshims.loader.makePath(d);if(b.inArray(d,g)==-1){a=a||k.getElementsByTagName("head")[0]||k.body;if(!a||!a.appendChild)setTimeout(function(){b.webshims.loader.loadScript(d,c)},10);else{var e=k.createElement("script"),h=function(i){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){e.onload=null;e.onerror=null;e.onreadystatechange=null;c&&c(i,this);m(f,false,true);e=null}};e.setAttribute("async","async");e.src=d;
e.onload=h;e.onerror=h;e.onreadystatechange=h;a.appendChild(e);e.async=true;g.push(d)}}}}()},readyModules:function(a,g,d,c){d=d;if(typeof a=="string"){a=a.split(" ");d=true}if(d)a=b.map(a,function(e){return b.webshims.loader.modules[e]||b.webshims.loader.features[e]?e+"Ready":e});if(a.length){d=a.shift();var f=function(){b.webshims.readyModules(a,g,false,c)};d=="ready"?b(f):b(k).one(d,f)}else c?g():setTimeout(g,0)},capturingEvents:function(a,g){if(k.addEventListener){if(typeof a=="string")a=[a];b.each(a,
function(d,c){var f=function(e){e=b.event.fix(e);if(g){var h=e.preventDefault;e.preventDefault=function(){h.apply(this,arguments);var i=b.data(e.target,"maybePrevented"+e.type);i&&clearTimeout(i);b.data(e.target,"maybePrevented"+e.type,setTimeout(function(){b.removeData(e.target,"maybePrevented"+e.type)},90))}}return b.event.handle.call(this,e)};b.event.special[c]=b.event.special[c]||{};b.extend(b.event.special[c],{setup:function(){this.addEventListener(c,f,true)},teardown:function(){this.removeEventListener(c,
f,true)}})})}},attr:function(){var a=[{}],g=function(d){var c=b.attr;b.attr=function(f,e,h,i,j){if(!d[e]||f.nodeType!==1||d[e].elementNames[0]!=="*"&&b.inArray((f.nodeName||"").toLowerCase(),d[e].elementNames)===-1)return c(f,e,h,i,j);var l=function(){if(h===undefined)return c(f,e,h,i,j);return c(f,e,h,i,j)};if(h===undefined)return d[e].getter(f,l,h,i,j);d[e].setter(f,h,l,i,j)}};g(a[0]);return function(d,c){c.elementNames=c.elementNames||["*"];if(c.setter){if(!b.isFunction(c.setter))c.setter=function(h,
i,j){return j()}}else c.setter=function(){throw d+" is readonly";};if(!c.getter||!b.isFunction(c.getter))c.getter=function(h,i){return i()};if(typeof c.elementNames=="string")c.elementNames=[c.elementNames];var f=false;b.each(a,function(h,i){if(!i[d]){i[d]=c;f=true;return false}});if(!f){var e={};e[d]=c;g(e);a.push(e)}}}(),createBooleanAttrs:function(a,g){if(typeof name==="string")a=[a];b.each(a,function(d,c){b.webshims.attr(c,{elementNames:g,getter:function(f){return typeof f[c]=="boolean"?f[c]:
!!(f.attributes[c]||{}).specified},setter:function(f,e){(e=!!e)?f.setAttribute(c,c):f.removeAttribute(c);f[c]=e}})})},addMethod:function(a,g){var d=b.fn[a].elementNames||["*"];if(typeof d=="string")d=[ext.elementNames];b.fn[a]=function(){var c=arguments,f;this.each(function(){if(d[0]=="*"||b.inArray((this.nodeName||"").toLowerCase(),d)!==-1){f=g.apply(this,c);return f!==undefined}});return f===undefined?this:f};b.fn[a].elementNames=d;b.fn[a].shim=true},addMethodName:function(a,g){if(!(b.fn[a]&&"shim"in
b.fn[a])){b.fn[a]=function(){var d=arguments,c;this.each(function(){if(this[a]){c=this[a].apply(this,d);if(c!==undefined)return false}});return c!==undefined?c:this};b.fn[a].shim=false;b.fn[a].elementNames=g}},addPolyfill:function(a,g){g=g||{};var d=g.feature||a,c=b.webshims.loader,f=c.combinations;if(!c.features[d]){c.features[d]=[];c.featureList.push(d)}c.features[d].push(a);c.addModule(a,g);c.moduleList.push(a);b.each(g.combination||[],function(e,h){if(f[h])c.combinations[h].push(a);else f[h]=
[a]});if(g.methodNames){if(!b.isArray(g.methodNames))g.methodNames=[g.methodNames];b.each(g.methodNames,function(e,h){b.webshims.addMethodName(h.name,h.elementNames)})}},polyfill:function(a){var g=b.webshims.loader,d=[];a=a||g.featureList;if(typeof a=="string")a=a.split(" ");b.each(a,function(c,f){f!==g.features[f][0]&&b.webshims.readyModules(g.features[f],function(){m(f)},true);d=d.concat(g.features[f])});g.loadCSS("shim.css");g.loadList(d)},activeLang:function(){var a=[navigator.browserLanguage||
navigator.language||""],g=b("html").attr("lang"),d;g&&a.push(g);return function(c,f,e){if(c)if(!f||!e){if(c!==a[0]){a[0]=c;clearTimeout(d);d=setTimeout(function(){b(k).triggerHandler("htmlExtLangChange",a)},9)}}else{f=b.webshims.loader.modules[f].options;var h=function(j){if(b.inArray(j,i)!==-1){b.webshims.loader.loadScript(f.langSrc+j+".js",function(){c[j]&&e(c[j])});return true}return false},i=f&&f.availabeLangs;b.each(a,function(j,l){var n=l.split("-")[0];if(c[l]||c[n]){e(c[l]||c[n]);return false}if(i&&
f.langSrc!==undefined&&(h(l)||h(n)))return false})}return a}}()};b.webshims.ready=b.webshims.readyModules;(function(){var a=[];b.extend(b.webshims,{addReady:function(g){var d=function(c){b(function(){g(c)})};a.push(d);d(document)},triggerDomUpdate:function(g){g&&b.each(a,function(d,c){c(g)})}})})();!b.support.dynamicHTML5&&document.attachEvent&&b.webshims.loader.loadScript("http://html5shim.googlecode.com/svn/trunk/html5.js");b.fn.htmlWebshim=function(a){a=this.html(a?b.webshims.fixHTML5(a):a);a===
this&&b.isReady&&this.each(function(){b.webshims.triggerDomUpdate(this)});return a};b.each(["after","before","append","prepend"],function(a,g){b.fn[g+"Webshim"]=function(d){d=b(b.webshims.fixHTML5(d));this[g](d);b.isReady&&d.each(function(){b.webshims.triggerDomUpdate(this)});return this}});m("htmlExtLangChange",true)})(jQuery);
