(function(b,n,m,t){m.createElement("datalist");var o=b.event.special;b.webshims={version:"pre1.5.0",cfg:{useImportantStyles:true,removeFOUC:false,waitReady:true,extendNative:false},implement:{},preloadHTCs:[],modules:{},features:{},featureList:[],log:function(a){if(g.debug&&n.console&&console.log)return console.log(a)},addPolyfill:function(a,e){e=e||{};var d=e.feature||a;if(!g.features[d]){g.features[d]=[];g.featureList.push(d)}g.features[d].push(a);j.addModule(a,e);b.each(e.combination||[],function(h,
c){if(x[c])x[c].push(a);else x[c]=[a]});if(e.methodNames){if(!b.isArray(e.methodNames))e.methodNames=[e.methodNames];b.each(e.methodNames,function(h,c){g.addMethodName(c)})}},polyfill:function(){var a=function(e){var d,h=[],c=function(){b("html").removeClass("loading-polyfills long-loading-polyfills polyfill-remove-fouc");b(n).unbind("load.loadingPolyfills error.loadingPolyfills");clearTimeout(d)};if(!b.isReady){g.cfg.removeFOUC&&h.push("polyfill-remove-fouc");h.push("loading-polyfills");b(n).bind("load.loadingPolyfills error.loadingPolyfills",
c);d=setTimeout(function(){b("html").addClass("long-loading-polyfills")},400)}s(e,c);g.cfg.useImportantStyles&&h.push("polyfill-important");h[0]&&b("html").addClass(h.join(" "));b(n).load(function(){j.loadList(["html5a11y"])});j.loadCSS("shim.css");a=b.noop};return function(e,d){var h=[];e=e||g.featureList;if(e=="lightweight")e=g.light;if(typeof e=="string")e=e.split(" ");d&&s(e,function(){d(b,g,n,m)});b.each(e,function(c,f){f!==g.features[f][0]&&s(g.features[f],function(){u(f,true)});h=h.concat(g.features[f])});
a(e);j.loadList(h)}}(),isReady:function(a,e){if(e&&g.waitReadys[a]){g.waitReadys[a+"ReadyCall"]=true;return false}a+="Ready";if(e){if(o[a]&&o[a].add)return true;o[a]=b.extend(o[a]||{},{add:function(d){d.handler.call(this,b.Event(a))}});b.event.trigger(a)}return o[a]&&o[a].add||false},waitReadys:{},waitReady:function(a){g.waitReadys[a]=g.waitReadys[a]||0;g.waitReadys[a]++},unwaitReady:function(a){g.waitReadys[a]=g.waitReadys[a]||1;g.waitReadys[a]--;g.waitReadys[a+"ReadyCall"]&&!g.waitReadys[a]&&g.isReady(a,
true)},ready:function(a,e,d){if(typeof a=="string")a=a.split(" ");d||(a=b.map(b.grep(a,function(c){return!u(c)}),function(c){return c+"Ready"}));if(a.length){d=a.shift();var h=function(){s(a,e,true)};d=="readyReady"?b(h):b(m).one(d,h)}else e(b,g,n,m)},addMethodName:function(a){b.fn[a]&&"shim"in b.fn[a]||(b.fn[a]=function(){var e=arguments,d;this.each(function(){var h=b.attr(this,a);if(h&&h.apply){d=h.apply(this,e);if(d!==t)return false}});return d!==t?d:this})},getID:function(){var a=(new Date).getTime();
return function(e){e=b(e);var d=e.attr("id");if(!d){a++;d="elem-id-"+a;e.attr("id",d)}return d}}(),fixHTML5:function(a){return a},capturingEvents:function(a,e){if(m.addEventListener){if(typeof a=="string")a=[a];b.each(a,function(d,h){var c=function(f){f=b.event.fix(f);if(e){var k=f.preventDefault;f.preventDefault=function(){k.apply(this,arguments);clearTimeout(b.data(f.target,"maybePrevented"+f.type));b.data(f.target,"maybePrevented"+f.type,setTimeout(function(){b.removeData(f.target,"maybePrevented"+
f.type)},90))}}return b.event.handle.call(this,f)};o[h]=o[h]||{};o[h].setup||o[h].teardown||b.extend(o[h],{setup:function(){this.addEventListener(h,c,true)},teardown:function(){this.removeEventListener(h,c,true)}})})}},loader:{basePath:function(){var a=b("script");a=a[a.length-1].src.split("?")[0];return a.slice(0,a.lastIndexOf("/")+1)}(),combinations:{},addModule:function(a,e){q[a]=e},loadList:function(){var a=[];return function(e){var d=[];b.each(e,function(h,c){var f=q[c];if("test"in f&&f.test(e))u(c,
true);else{f.css&&j.loadCSS(f.css);d.push(c);f.loadInit&&f.loadInit()}});g.debug||b.each(j.combinations||[],function(h,c){var f=true;b.each(c,function(k,v){if(b.inArray(v,d)===-1||b.inArray(v,a)!==-1)return f=false});if(f){a=a.concat(c);j.loadScript(h,false,c);return false}});b.each(d,function(h,c){if(b.inArray(c,a)==-1)j.loadScript(q[c].src||c,false,c)})}}(),makePath:function(a){if(a.indexOf("://")!=-1||a.indexOf("/")===0)return a;if(a.indexOf(".")==-1)a+=".js";return j.basePath+a},loadCSS:function(){var a,
e=[];return function(d){d=this.makePath(d);if(b.inArray(d,e)==-1){a=a||m.getElementsByTagName("head")[0]||m.body;e.push(d);b('<link rel="stylesheet" />').prependTo(a).attr({href:d})}}}(),loadScript:function(){var a,e=[];return function(d,h,c){d=j.makePath(d);if(b.inArray(d,e)==-1){a=a||m.getElementsByTagName("head")[0]||m.body;if(!a||!a.appendChild)setTimeout(function(){j.loadScript(d,h,c)},9);else{var f=m.createElement("script"),k=function(v){if(!this.readyState||this.readyState=="loaded"||this.readyState==
"complete"){f.onload=null;f.onerror=null;f.onreadystatechange=null;h&&h(v,this);if(c){if(typeof c=="string")c=c.split(" ");b.each(c,function(z,y){q[y]&&!q[y].noAutoCallback&&u(y,true)})}f=null}};f.setAttribute("async","async");f.src=d;f.onload=k;f.onerror=k;f.onreadystatechange=k;a.appendChild(f);f.async=true;e.push(d)}}}}()}};var g=b.webshims,u=g.isReady,s=g.ready,l=g.addPolyfill,q=g.modules,j=g.loader,x=j.combinations,i=b.support;(function(){var a=[],e=b([]);b.extend(g,{addReady:function(d){var h=
function(c,f){b(function(){d(c,f)})};a.push(h);h(m,e)},triggerDomUpdate:function(d){if(d&&d.nodeType){var h=d.nodeType;if(!(h!=1&&h!=9)){var c=d!==m?b(d):e;b.each(a,function(f,k){k(d,c)})}}}});b.fn.htmlWebshim=function(d){d=this.html(d?g.fixHTML5(d):d);d===this&&b.isReady&&this.each(function(){this.nodeType==1&&g.triggerDomUpdate(this)});return d};b.each(["after","before","append","prepend"],function(d,h){b.fn[h+"Webshim"]=function(c){c=b(g.fixHTML5(c));this[h](c);b.isReady&&c.each(function(){this.nodeType==
1&&g.triggerDomUpdate(this)});return this}})})();(function(){var a=Object.prototype.hasOwnProperty,e=["configurable","enumerable","writable"],d=function(c){for(var f=0;f<3;f++)if(c[e[f]]===t&&(e[f]!=="writable"||c.value!==t))c[e[f]]=true},h=function(c){if(c)for(var f in c)a.call(c,f)&&d(c[f])};g.objectCreate=function(c,f,k){h(f);c=Object.create(c,f);if(k){c.options=b.extend(true,{},c.options||{},k);k=c.options}c._create&&b.isFunction(c._create)&&c._create(k);return c};g.defineProperty=function(c,
f,k){d(k);return Object.defineProperty(c,f,k)};g.defineProperties=function(c,f){h(f);return Object.defineProperties(c,f)};g.getOwnPropertyDescriptor=Object.getOwnPropertyDescriptor;g.getPrototypeOf=Object.getPrototypeOf})();var w=parseFloat(b.browser.version,10),r=location.protocol=="https:"?"https:":"http:";j.addModule("html5a11y",{src:"html5a11y",test:function(){return!(b.browser.msie&&w<10&&w>7||b.browser.mozilla&&w<2||b.browser.webkit&&w<540)}});j.addModule("jquery-ui",{src:r+"//ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js",
test:function(){return!!(b.widget&&b.Widget)}});j.addModule("input-widgets",{src:"",test:function(){return!(b.widget&&!(b.datepicker||b.fn.slider))}});j.addModule("swfobject",{src:r+"//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js",test:function(){return"swfobject"in n}});r=b("<div />")[0];var p=[];p.push(!!(Array.isArray&&Object.keys&&Object.create&&Function.prototype.bind&&Object.defineProperties&&!isNaN(Date.parse("T00:00"))));p.push(!!(String.prototype.trim&&Date.now&&Date.prototype.toISOString));
p[1]&&b.each(["filter","map","every","reduce","reduceRight","lastIndexOf"],function(a,e){if(!Array.prototype[e])return p[1]=false});i.es5=p[0]&&p[1];i.advancedObjectProperties=!!(Object.create&&Object.defineProperties&&Object.getOwnPropertyDescriptor);i.objectAccessor=!!(i.advancedObjectProperties||Object.prototype.__defineGetter__&&Object.prototype.__lookupSetter__);i.domAccessor=!!(i.advancedObjectProperties||Object.prototype.__defineGetter__&&Object.prototype.__lookupSetter__||Object.defineProperty&&
Object.getOwnPropertyDescriptor);i.dhtmlBehavior=!!r.addBehavior;r.setAttribute("dataContentAttr",":-)");i.contentAttr=!r.dataContentAttr;l("es5-1",{feature:"es5",test:function(){return p[1]&&p[0]},combination:["combined-ie7","combined-ie8","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ff3-light","combined-webkit"]});l("es5-2",{feature:"es5",test:function(){return p[1]},combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});l("dom-extend",{noAutoCallback:true,
loadInit:function(){setTimeout(function(){g.polyfill(["es5"])},0)},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit","combined-base"]});i.geolocation="geolocation"in navigator;l("geolocation",{test:function(){return i.geolocation},options:{destroyWrite:true},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ie7-light","combined-ie8-light","combined-ie9-light"]});
i.canvas="getContext"in b("<canvas />")[0];l("canvas",{test:function(){return i.canvas},noAutoCallback:true,methodNames:["getContext"],combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});g.validityMessages=[];g.inputTypes={};(function(){var a=b('<form action="#"><fieldset><input name="a" required /><select><option>y</option></select></fieldset></form>'),e=b("fieldset",a)[0],d=b('<input type="range" />')[0],h=b('<input type="date" />')[0];i.validity="checkValidity"in
a[0];i.validationMessage=!!b("input",a).attr("validationMessage");i.fieldsetValidation=!!(e.elements&&e.checkValidity&&"disabled"in e&&!e.checkValidity());i.output=!!("value"in m.createElement("output"));i.datalistProp="list"in b("input",a)[0]&&"options"in m.createElement("datalist");i.datalist=i.datalistProp&&n.HTMLDataListElement;i.numericDateProps=d.type=="range"&&h.type=="date";i.requiredSelect="required"in b("select",a)[0];i.rangeUI=i.numericDateProps;i.dateUI=i.numericDateProps;if(n.Modernizr){i.rangeUI=
Modernizr.inputtypes.range;i.dateUI=Modernizr.inputtypes.date}})();l("form-core",{feature:"forms",noAutoCallback:true,loadInit:function(){setTimeout(function(){g.polyfill(["es5"])},0)},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit","combined-base"]});l("form-message",{feature:"forms",test:function(a){return i.validationMessage&&!g.implement.customValidationMessage&&
q["form-extend"].test(a)},options:{},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit"]});if(i.validity){g.capturingEvents(["input"]);g.capturingEvents(["invalid"],true);l("form-extend",{feature:"forms",src:"form-native-extend",noAutoCallback:true,test:function(a){return i.requiredSelect&&i.validationMessage&&(i.numericDateProps||b.inArray("form-number-date",
a)==-1)&&!g.overrideValidationMessages},loadInit:function(){setTimeout(function(){j.loadList(["form-message"])},0)},methodNames:["setCustomValidity","checkValidity"],combination:["combined-ff4","combined-webkit"]});l("form-native-fix",{feature:"forms",test:function(){return i.requiredSelect&&i.validationMessage&&i.output&&i.datalist},combination:["combined-webkit"]})}else l("form-extend",{feature:"forms",src:"form-shim-extend",noAutoCallback:true,test:function(){return false},methodNames:["setCustomValidity",
"checkValidity"],combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});l("form-number-date",{feature:"forms-ext",noAutoCallback:true,test:function(){return i.numericDateProps},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4"],options:{stepArrows:{number:1,time:1},calculateWidth:true}});l("inputUI",{feature:"forms-ext",src:"form-date-range-ui",test:function(){return i.rangeUI&&
i.dateUI&&!q.inputUI.options.replaceNative},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4"],noAutoCallback:true,loadInit:function(){j.loadList(["jquery-ui"]);q["input-widgets"].src&&j.loadList(["input-widgets"])},options:{slider:{},datepicker:{},langSrc:"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/i18n/jquery.ui.datepicker-",availabeLangs:"af ar az bg bs cs da de el en-GB eo es et eu fa fi fo fr fr-CH he hr hu hy id is it ja ko it lt lv ms nl no pl pt-BR ro ru sk sl sq sr sr-SR sv ta th tr uk vi zh-CN zh-HK zh-TW".split(" "),
recalcWidth:true,replaceNative:false}});l("form-output-datalist",{feature:"forms",noAutoCallback:true,test:function(){return i.output&&i.datalist},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});b.support.datalistProp&&s("dom-extend",function(){b.webshims.defineNodeNameProperty("input","list",{set:function(a){if(a&&a.getAttribute)a=b.webshims.getID(a);this.setAttribute("list",a)}})});i.placeholder=
b('<input type="text" />').attr("placeholder")!=null;l("form-placeholder",{feature:"forms",test:function(){return i.placeholder},noAutoCallback:true,combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});i.jsonStorage="JSON"in n&&"localStorage"in n&&"sessionStorage"in n;l("json-storage",{test:function(){return i.jsonStorage},loadInit:function(){j.loadList(["swfobject"])},noAutoCallback:true,combination:["combined-ie7",
"combined-ie7-light"]});i.dynamicHTML5=!!b("<video><div></div></video>")[0].innerHTML;l("html5shiv",{test:function(){return i.dynamicHTML5},combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});g.light=["es5","dom-extend","html5shiv","canvas","geolocation","forms","json-storage"]})(jQuery,this,this.document);
