(function(b,m,k,u){b.each(["jQuery","Modernizr"],function(a,c){if(!m[c])throw"you have to include "+c+" before webshims lib";});k.createElement("datalist");var o=b.event.special,p=Modernizr.input,z=Modernizr.inputtypes,v=parseFloat(b.browser.version,10);(function(){var a=Modernizr.addTest,c=b('<form action="#"><input name="a" required /><select><option>y</option></select><input required id="date-input-test" type="date" /></form>');a("formvalidation",function(){return!!("checkValidity"in c[0])});a("datalist",
function(){return!!(p.list&&m.HTMLDataListElement)});a("validationmessage",function(){if(!Modernizr.formvalidation)return false;c.appendTo("head");return!!b("input",c).attr("validationMessage")});a("output",function(){if(!Modernizr.formvalidation)return false;return"value"in k.createElement("output")});Modernizr.genericDOM=!!b("<video><div></div></video>")[0].innerHTML;Modernizr.requiredSelect=!!(Modernizr.formvalidation&&"required"in b("select",c)[0]);Modernizr.bugfreeformvalidation=Modernizr.formvalidation&&
Modernizr.requiredSelect&&Modernizr.validationmessage&&(!b.browser.webkit||v>534.16);p.valueAsNumber=false;p.valueAsDate=false;if(Modernizr.formvalidation){a=b("#date-input-test",c)[0];p.valueAsNumber="valueAsNumber"in a;p.valueAsDate="valueAsDate"in a;a=null}Modernizr.formvalidation&&c.remove();c=null;Modernizr.ES5base=!!(String.prototype.trim&&Date.now&&Date.prototype.toISOString);Modernizr.ES5extras=!!(Array.isArray&&Object.keys&&Object.create&&Function.prototype.bind&&Object.defineProperties&&
!isNaN(Date.parse("T00:00")));Modernizr.ES5base&&b.each(["filter","map","every","reduce","reduceRight","lastIndexOf"],function(e,f){if(!Array.prototype[f])return Modernizr.ES5base=false});Modernizr.ES5=Modernizr.ES5base&&Modernizr.ES5extras;Modernizr.advancedObjectProperties=!!(Object.create&&Object.defineProperties&&Object.getOwnPropertyDescriptor);!b.browser.msie&&Object.defineProperty&&Object.prototype.__defineGetter__&&function(){try{var e=k.createElement("foo");Object.defineProperty(e,"bar",
{get:function(){return true}});Modernizr.advancedObjectProperties=!!e.bar}catch(f){Modernizr.advancedObjectProperties=false}e=null}();Modernizr.objectAccessor=!!(Modernizr.advancedObjectProperties||Object.prototype.__defineGetter__&&Object.prototype.__lookupSetter__);Modernizr.domAccessor=!!(Modernizr.objectAccessor||Object.defineProperty&&Object.getOwnPropertyDescriptor)})();b.webshims={version:"pre1.5.0",cfg:{useImportantStyles:true,removeFOUC:true,waitReady:true},modules:{},features:{},featureList:[],
setOptions:function(a,c){if(typeof a=="string"&&c!==u&&h.cfg[a])if(typeof c!="object")h.cfg[a]=c;else b.extend(true,h.cfg[a],c);else typeof a=="object"&&b.extend(true,h.cfg,a)},addPolyfill:function(a,c){c=c||{};var e=c.feature||a;if(!h.features[e]){h.features[e]=[];h.featureList.push(e);h.cfg[e]={}}h.features[e].push(a);c.options=b.extend(h.cfg[e],c.options);j.addModule(a,c);b.each(c.combination||[],function(f,g){if(x[g])x[g].push(a);else x[g]=[a]});if(c.methodNames){if(!b.isArray(c.methodNames))c.methodNames=
[c.methodNames];b.each(c.methodNames,function(f,g){h.addMethodName(g)})}},polyfill:function(){var a=function(c){var e,f=[],g=c,d=function(){b("html").removeClass("loading-polyfills long-loading-polyfills polyfill-remove-fouc");b(m).unbind(".loadingPolyfills");clearTimeout(e)};if(b.isReady)h.info("You should call $.webshims.polyfill before DOM-Ready");else{if(h.cfg.removeFOUC){if(h.cfg.waitReady)g=g.concat(["DOM"]);f.push("polyfill-remove-fouc")}f.push("loading-polyfills");b(m).bind("load.loadingPolyfills error.loadingPolyfills",
d);e=setTimeout(function(){b("html").addClass("long-loading-polyfills")},600)}t(c,d);h.cfg.useImportantStyles&&f.push("polyfill-important");f[0]&&b("html").addClass(f.join(" "));b(function(){j.loadList(["html5a11y"])});j.loadCSS("shim.css");a=b.noop};return function(c,e){var f=[];c=c||h.featureList;if(c=="lightweight")c=h.light;if(typeof c=="string")c=c.split(" ");if(e||h.cfg.waitReady){h.cfg.waitReady&&b.readyWait++;t(c,function(){h.cfg.waitReady&&b.ready(true);e&&e(b,h,m,k)})}b.each(c,function(g,
d){d!==h.features[d][0]&&t(h.features[d],function(){q(d,true)});f=f.concat(h.features[d])});a(c);j.loadList(f)}}(),isReady:function(a,c){if(c&&h.waitReadys[a]){h.waitReadys[a+"ReadyCall"]=true;return false}a+="Ready";if(c){if(o[a]&&o[a].add)return true;o[a]=b.extend(o[a]||{},{add:function(e){e.handler.call(this,b.Event(a))}});b.event.trigger(a)}return!!(o[a]&&o[a].add)||false},waitReadys:{},ready:function(a,c,e){if(typeof a=="string")a=a.split(" ");e||(a=b.map(b.grep(a,function(f){return!q(f)}),function(f){return f+
"Ready"}));if(a.length){e=a.shift();b(k).one(e,function(){t(a,c,true)})}else c(b,h,m,k)},addMethodName:function(a){b.fn[a]&&"shim"in b.fn[a]||(b.fn[a]=function(){var c=arguments,e;this.each(function(){var f=b.attr(this,a);if(f&&f.apply){e=f.apply(this,c);if(e!==u)return false}});return e!==u?e:this})},getID:function(){var a=(new Date).getTime();return function(c){c=b(c);var e=c.attr("id");if(!e){a++;e="elem-id-"+a;c.attr("id",e)}return e}}(),fixHTML5:function(a){return a},capturingEvents:function(a,
c){if(k.addEventListener){if(typeof a=="string")a=[a];b.each(a,function(e,f){var g=function(d){d=b.event.fix(d);if(c){var i=d.preventDefault;d.preventDefault=function(){i.apply(this,arguments);clearTimeout(b.data(d.target,"maybePrevented"+d.type));b.data(d.target,"maybePrevented"+d.type,setTimeout(function(){b.removeData(d.target,"maybePrevented"+d.type)},90))}}return b.event.handle.call(this,d)};o[f]=o[f]||{};o[f].setup||o[f].teardown||b.extend(o[f],{setup:function(){this.addEventListener(f,g,true)},
teardown:function(){this.removeEventListener(f,g,true)}})})}},loader:{basePath:function(){var a=b('meta[name="polyfill-path"]').attr("content");if(a)return a;a=b("script");a=a[a.length-1];a=(!b.browser.msie||k.documentMode>=8?a.src:a.getAttribute("src",4)).split("?")[0];return a.slice(0,a.lastIndexOf("/")+1)+"shims/"}(),combinations:{},addModule:function(a,c){r[a]=c},loadList:function(){var a=[],c=function(e,f,g){if(q(e))return true;var d=r[e];if(d){if("test"in d&&d.test(f)){q(e,true);return true}else if(g&&
!q(e)&&b.inArray(e,g)==-1&&b.inArray(e,f)==-1){g.push(e);return false}return q(e)}else if(h.features[e]&&g&&e!==h.features[e][0]){t(h.features[e],function(){q(e,true)});b.each(h.features[e],function(i,n){!c(n,f)&&b.inArray(n,g)==-1&&b.inArray(n,f)==-1&&g.push(n)})}return true};return function(e){var f=[];b.each(e,function(g,d){var i=r[d];if(!c(d,e)){i.css&&j.loadCSS(i.css);f.push(d);i.dependencies&&b.each(i.dependencies,function(n,s){c(s,e,f)});i.loadInit&&i.loadInit()}});h.debug||b.each(j.combinations||
[],function(g,d){var i=true;b.each(d,function(n,s){if(b.inArray(s,f)===-1||b.inArray(s,a)!==-1)return i=false});if(i){a=a.concat(d);j.loadScript(g,false,d);return false}});b.each(f,function(g,d){if(b.inArray(d,a)==-1)j.loadScript(r[d].src||d,false,d)})}}(),makePath:function(a){if(a.indexOf("://")!=-1||a.indexOf("/")===0)return a;if(a.indexOf(".")==-1)a+=".js";return j.basePath+a},loadCSS:function(){var a,c=[];return function(e){e=this.makePath(e);if(b.inArray(e,c)==-1){a=a||k.getElementsByTagName("head")[0]||
k.body;c.push(e);b('<link rel="stylesheet" />').prependTo(a).attr({href:e})}}}(),loadScript:function(){var a,c=[];return function(e,f,g){e=j.makePath(e);if(b.inArray(e,c)==-1){a=a||k.getElementsByTagName("head")[0]||k.body;if(!a||!a.appendChild)setTimeout(function(){j.loadScript(e,f,g)},9);else{var d=k.createElement("script"),i,n=function(s){s&&s.type==="error"&&h.warn("Error: could not find script @"+e+'| configure polyfill-path: $.webshims.loader.basePath = "path/to/shims-folder" or by using markup: <meta name="polyfill-path" content="path/to/shims-folder/" />');
if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){d.onload=null;d.onreadystatechange=null;f&&f(s,this);if(g){if(typeof g=="string")g=g.split(" ");b.each(g,function(A,w){if(r[w]){r[w].afterLoad&&r[w].afterLoad();r[w].noAutoCallback||q(w,true)}})}d=null;clearTimeout(i)}};d.setAttribute("async","async");d.src=e;i=setTimeout(function(){n({type:"error"})},2E4);d.onload=n;b(d).one("error",n);d.onreadystatechange=n;a.appendChild(d);d.async=true;c.push(e)}}}}()}};var h=b.webshims,
q=h.isReady,t=h.ready,l=h.addPolyfill,r=h.modules,j=h.loader,x=j.combinations;b.each(["log","error","warn","info"],function(a,c){h[c]=function(e){if(h.debug&&m.console&&console.log)return console[console[c]?c:"log"](e)}});(function(){var a=[],c=b([]);b.extend(h,{addReady:function(f){var g=function(d,i){t("DOM",function(){f(d,i)})};a.push(g);g(k,c)},triggerDomUpdate:function(f){if(f&&f.nodeType){var g=f.nodeType;if(!(g!=1&&g!=9)){var d=f!==k?b(f):c;b.each(a,function(i,n){n(f,d)})}}}});b.fn.htmlWebshim=
function(f){f=this.html(f?h.fixHTML5(f):f);f===this&&b.isReady&&this.each(function(){this.nodeType==1&&h.triggerDomUpdate(this)});return f};b.each(["after","before","append","prepend"],function(f,g){b.fn[g+"Webshim"]=function(d){d=b(h.fixHTML5(d));this[g](d);b.isReady&&d.each(function(){this.nodeType==1&&h.triggerDomUpdate(this)});return this}});b.isDOMReady=b.isReady;if(b.isDOMReady)q("DOM",true);else{var e=b.ready;b.ready=function(f){if(f!==true&&!b.isDOMReady&&k.body){b.isDOMReady=true;q("DOM",
true);b.ready=e}return e.apply(this,arguments)}}})();(function(){var a=Object.prototype.hasOwnProperty,c=["configurable","enumerable","writable"],e=function(g){for(var d=0;d<3;d++)if(g[c[d]]===u&&(c[d]!=="writable"||g.value!==u))g[c[d]]=true},f=function(g){if(g)for(var d in g)a.call(g,d)&&e(g[d])};if(Object.create)h.objectCreate=function(g,d,i){f(d);g=Object.create(g,d);if(i){g.options=b.extend(true,{},g.options||{},i);i=g.options}g._create&&b.isFunction(g._create)&&g._create(i);return g};if(Object.defineProperty)h.defineProperty=
function(g,d,i){e(i);return Object.defineProperty(g,d,i)};if(Object.defineProperties)h.defineProperties=function(g,d){f(d);return Object.defineProperties(g,d)};h.getOwnPropertyDescriptor=Object.getOwnPropertyDescriptor;h.getPrototypeOf=Object.getPrototypeOf})();var y=location.protocol=="https:"?"https:":"http:";j.addModule("html5a11y",{src:"html5a11y",test:function(){return!(b.browser.msie&&v<9&&v>7||b.browser.mozilla&&v<2||b.browser.webkit&&v<535||!m.HTMLArticleElement)}});j.addModule("jquery-ui",
{src:y+"//ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js",test:function(){return!!(b.widget&&b.Widget)}});j.addModule("input-widgets",{src:"",test:function(){var a=!(b.widget&&!(b.fn.datepicker||b.fn.slider));if(!this.src){a||h.warn('jQuery UI Widget factory is already included, but not datepicker or slider. configure src of $.webshims.modules["input-widgets"].src');return true}return a}});j.addModule("swfobject",{src:y+"//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js",test:function(){return"swfobject"in
m}});l("es5-1",{feature:"es5",test:function(){return Modernizr.ES5},combination:["combined-ie7","combined-ie8","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ff3-light","combined-webkit"]});l("es5-2",{feature:"es5",test:function(){return Modernizr.ES5base},combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});l("dom-extend",{feature:"dom-support",noAutoCallback:true,dependencies:["es5"],combination:["combined-ie7","combined-ie8","combined-ie9",
"combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit"]});l("html5shiv",{feature:"dom-support",test:function(){return Modernizr.genericDOM},combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});l("geolocation",{test:function(){return Modernizr.geolocation},options:{destroyWrite:true,confirmText:""},dependencies:["json-storage"],combination:["combined-ie7","combined-ie8","combined-ie9","combined-ie7-light",
"combined-ie8-light","combined-ie9-light"]});(function(){var a=m.FlashCanvas;l("canvas",{src:"excanvas",test:function(){return Modernizr.canvas},options:{type:"excanvas"},noAutoCallback:true,loadInit:function(){var c=this.options.type;if(c&&c.indexOf("flash")!==-1){m.FlashCanvas=m.FlashCanvas||{};a=m.FlashCanvas;if(c=="flash"){b.extend(a,{swfPath:j.basePath+"FlashCanvas/"});this.src="FlashCanvas/flashcanvas";c=a.swfPath+"flashcanvas.swf"}else{b.extend(a,{swfPath:j.basePath+"FlashCanvasPro/"});this.src=
"FlashCanvasPro/flashcanvas";c=a.swfPath+"flash10canvas.swf"}c&&b.ajax({url:c,cache:true,dataType:"text"})}},afterLoad:function(){h.ready("dom-extend",function(c,e,f,g){e.defineNodeNameProperty("canvas","getContext",{value:function(d){this.getContext||G_vmlCanvasManager.initElement(this);return this.getContext(d)}});e.addReady(function(d,i){c("canvas",d).add(i.filter("canvas")).each(function(){if(this.getContext){if(d===g)return false}else G_vmlCanvasManager.initElement(this)});g===d&&q("canvas",
true)})})},methodNames:["getContext"],dependencies:["es5","dom-support"]})})();h.validityMessages=[];h.validationMessages=h.validityMessages;h.inputTypes={};l("form-core",{feature:"forms",noAutoCallback:true,dependencies:["es5"],combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit"]});l("form-message",{feature:"forms",test:function(a){return Modernizr.validationMessage&&
!this.options.customMessages&&r["form-extend"].test(a)},options:{customMessages:false,overrideMessages:false},dependencies:["dom-support"],noAutoCallback:true,combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit"]});if(Modernizr.formvalidation){h.capturingEvents(["input"]);h.capturingEvents(["invalid"],true);l("form-extend",{feature:"forms",src:"form-native-extend",
noAutoCallback:true,test:function(a){return Modernizr.requiredSelect&&Modernizr.validationMessage&&(p.valueAsNumber&&p.valueAsDate||b.inArray("form-number-date",a)==-1)&&!this.options.overrideMessages},dependencies:["dom-support"],methodNames:["setCustomValidity","checkValidity"],combination:["combined-ff4","combined-webkit"]});l("form-native-fix",{feature:"forms",test:function(){return Modernizr.bugfreeformvalidation},dependencies:["dom-support"],combination:["combined-webkit"]})}else l("form-extend",
{feature:"forms",src:"form-shim-extend",noAutoCallback:true,methodNames:["setCustomValidity","checkValidity"],dependencies:["dom-support"],combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});l("form-output-datalist",{feature:"forms",noAutoCallback:true,test:function(){return Modernizr.output&&Modernizr.datalist},dependencies:["dom-support","json-storage"],combination:["combined-ie7","combined-ie8",
"combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});l("form-number-date",{feature:"forms-ext",noAutoCallback:true,dependencies:["es5","forms","json-storage","dom-support"],test:function(){return p.valueAsNumber&&p.valueAsDate},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4"],options:{stepArrows:{number:1,time:1},calculateWidth:true}});l("inputUI",{feature:"forms-ext",src:"form-date-range-ui",test:function(){return z.slider&&
z.date&&!this.options.replaceUI},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4"],noAutoCallback:true,dependencies:["es5","forms","dom-support"],loadInit:function(){j.loadList(["jquery-ui"]);r["input-widgets"].src&&j.loadList(["input-widgets"])},options:{slider:{},datepicker:{},langSrc:y+"//ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/i18n/jquery.ui.datepicker-",availabeLangs:"af ar az bg bs cs da de el en-GB eo es et eu fa fi fo fr fr-CH he hr hu hy id is it ja ko it lt lv ms nl no pl pt-BR ro ru sk sl sq sr sr-SR sv ta th tr uk vi zh-CN zh-HK zh-TW".split(" "),
recalcWidth:true,replaceUI:false}});p.list&&t("dom-extend",function(){b.webshims.defineNodeNameProperty("input","list",{set:function(a){if(a&&a.getAttribute)a=b.webshims.getID(a);this.setAttribute("list",a)}})});l("form-placeholder",{feature:"forms",test:function(){return p.placeholder},options:{placeholderType:"value"},noAutoCallback:true,combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});
l("json-storage",{test:function(){return Modernizr.localstorage&&Modernizr.sessionstorage&&"JSON"in m},loadInit:function(){j.loadList(["swfobject"]);b.ajax({url:j.basePath+"localStorage.swf",cache:true,dataType:"text"})},noAutoCallback:true,combination:["combined-ie7","combined-ie7-light"]});h.xlight=["es5","geolocation","forms","json-storage"];h.light=["es5","canvas","geolocation","forms","json-storage"]})(jQuery,this,this.document);
