(function(b){var s=document,k=b.support,w=b.event.special;"abbr article aside audio canvas datalist details figcaption figure footer header hgroup mark meter nav output progress section source summary time track video".replace(/\w+/g,function(a){s.createElement(a)});k.dynamicHTML5=!!b("<video><div></div></video>")[0].innerHTML;b("html").addClass("js-on").removeClass("js-off");b.webshims={version:"1.1.0",useImportantStyles:true,fix:{},implement:{},fixHTML5:function(a){return a},createReadyEvent:function(){var a=
function(d,c){if(t[c]||j.features[c])d+="Ready";if(!(w[d]&&w[d].add)){w[d]=b.extend(w[d]||{},{add:function(e){e.handler.call(this,b.Event(d))}});b.event.trigger(d)}};return function(d,c){if(d){b.isArray(d)||(d=[d]);b.each(d,function(e,f){if(!(c&&t[f]&&t[f].noAutoCallback)){a(f+"SYS",f,c);a(f,f,c)}})}}}(),moduleList:[],modules:{},features:{},featureList:[],loader:{basePath:function(){var a=b("script");a=a[a.length-1].src.split("?")[0];return a.slice(0,a.lastIndexOf("/")+1)}(),combinations:{},addModule:function(a,
d){t[a]=d},loadList:function(){var a=[];return function(d){var c=[];b.each(d,function(e,f){var g=t[f];if("test"in g&&g.test(d))y(f);else{g.css&&q.loadCSS(g.css);c.push(f);g.loadInit&&g.loadInit()}});j.debug||b.each(q.combinations||[],function(e,f){var g=true;b.each(f,function(h,l){if(b.inArray(l,c)===-1||b.inArray(l,a)!==-1)return g=false});if(g){a=a.concat(f);q.loadScript(e,false,f);return false}});b.each(c,function(e,f){if(b.inArray(f,a)==-1)q.loadScript(t[f].src||f,false,f)})}}(),makePath:function(a){if(a.indexOf("://")!=
-1||a.indexOf("/")===0)return a;if(a.indexOf(".")==-1)a+=".js";return q.basePath+a},loadCSS:function(){var a,d=[];return function(c){c=this.makePath(c);if(b.inArray(c,d)==-1){a=a||s.getElementsByTagName("head")[0]||s.body;d.push(c);b('<link rel="stylesheet" />').prependTo(a).attr({href:c})}}}(),loadScript:function(){var a,d=[];return function(c,e,f){c=q.makePath(c);if(b.inArray(c,d)==-1){a=a||s.getElementsByTagName("head")[0]||s.body;if(!a||!a.appendChild)setTimeout(function(){q.loadScript(c,e,f)},
9);else{var g=s.createElement("script"),h=function(l){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){g.onload=null;g.onerror=null;g.onreadystatechange=null;e&&e(l,this);y(f,true);g=null}};g.setAttribute("async","async");g.src=c;g.onload=h;g.onerror=h;g.onreadystatechange=h;a.appendChild(g);g.async=true;d.push(c)}}}}()},ready:function(a,d,c,e){if(typeof a=="string")a=a.split(" ");e||(a=b.map(a,function(g){var h=g;if(c&&h!="ready")h+="SYS";if(t[g]||j.features[g])h+="Ready";
return h}));if(a.length){e=a.shift();var f=function(){j.ready(a,d,c,true)};e=="ready"?b(f):b(s).one(e,f)}else d(b,j,window,document)},capturingEvents:function(a,d){if(s.addEventListener){if(typeof a=="string")a=[a];b.each(a,function(c,e){var f=function(g){g=b.event.fix(g);if(d){var h=g.preventDefault;g.preventDefault=function(){h.apply(this,arguments);clearTimeout(b.data(g.target,"maybePrevented"+g.type));b.data(g.target,"maybePrevented"+g.type,setTimeout(function(){b.removeData(g.target,"maybePrevented"+
g.type)},90))}}return b.event.handle.call(this,g)};w[e]=w[e]||{};w[e].setup||w[e].teardown||b.extend(w[e],{setup:function(){this.addEventListener(e,f,true)},teardown:function(){this.removeEventListener(e,f,true)}})})}},defineNodeNamesProperty:function(a,d,c){j.ready("es5",function(){if(typeof a=="string")a=a.split(/\s*,\s*/);a.forEach(function(e){j.defineNodeNameProperty(e,d,c)})},true)},contentAttr:function(a,d,c){if(a.nodeName){if(c===void 0){c=a.getAttribute(d);return c==null?void 0:c}if(typeof c==
"boolean")c?a.setAttribute(d,d):a.removeAttribute(d);else a.setAttribute(d,c)}},defineNodeNamesBooleanProperty:function(a,d,c){j.defineNodeNamesProperty(a,d,{set:function(e,f){f=!!f;e[d]=f;j.contentAttr(e,d,f);return f},get:function(e){return k.contentAttr&&d in e?!!e[d]:j.contentAttr(e,d)!=null}});c&&j.onNodeNamesPropertyModify(a,d,c)},addMethodName:function(a){b.fn[a]&&"shim"in b.fn[a]||(b.fn[a]=function(){var d=arguments,c;this.each(function(){var e=b.attr(this,a);if(e&&e.apply){c=e.apply(this,
d);if(c!==void 0)return false}});return c!==void 0?c:this})},addPolyfill:function(a,d){d=d||{};var c=d.feature||a,e=j;if(!e.features[c]){e.features[c]=[];e.featureList.push(c)}e.features[c].push(a);q.addModule(a,d);e.moduleList.push(a);b.each(d.combination||[],function(f,g){if(A[g])A[g].push(a);else A[g]=[a]});if(d.methodNames){if(!b.isArray(d.methodNames))d.methodNames=[d.methodNames];b.each(d.methodNames,function(f,g){j.addMethodName(g)})}},polyfill:function(a,d){var c=this,e=c.loader,f=[],g=function(){b("html").removeClass("loading-polyfills long-loading-polyfills polyfill-remove-fouc");
b(window).unbind("load.loadingPolyfills error.loadingPolyfills");clearTimeout(h)},h;d=d||b.noop;a=a||c.featureList;if(a=="lightweight")a=j.light;if(typeof a=="string")a=a.split(" ");if(!b.isReady){j.removeFOUC&&b("html").addClass("polyfill-remove-fouc");b("html").addClass("loading-polyfills");b(window).bind("load.loadingPolyfills error.loadingPolyfills",g);h=setTimeout(function(){b("html").addClass("long-loading-polyfills")},400)}j.ready(a,function(){g();d(b,j,window,document)});b.each(a,function(l,
i){i!==c.features[i][0]&&c.ready(c.features[i],function(){y(i)},true);f=f.concat(c.features[i])});j.useImportantStyles&&b("html").addClass("polyfill-important");e.loadCSS("shim.css");e.loadList(f);b(function(){e.loadList(["html5a11y"])})},getID:function(){var a=(new Date).getTime();return function(d){d=b(d);var c=d.attr("id");if(!c){a++;c="elem-id-"+a;d.attr("id",c)}return c}}(),activeLang:function(){var a=[navigator.browserLanguage||navigator.language||""],d=b("html").attr("lang"),c;d&&a.push(d);
return function(e,f,g){if(e)if(!f||!g){if(e!==a[0]){a[0]=e;clearTimeout(c);c=setTimeout(function(){b(s).triggerHandler("htmlExtLangChange",a)},9)}}else{f=t[f].options;var h=function(i){if(b.inArray(i,l)!==-1){q.loadScript(f.langSrc+i+".js",function(){e[i]&&g(e[i])});return true}return false},l=f&&f.availabeLangs;b.each(a,function(i,m){var p=m.split("-")[0];if(e[m]||e[p]){g(e[m]||e[p]);return false}if(l&&f.langSrc&&(h(m)||h(p)))return false})}return a}}()};var j=b.webshims,y=j.createReadyEvent,q=j.loader,
t=j.modules,A=q.combinations,r=j.addPolyfill;(function(){var a=[],d=b([]);b.extend(j,{addReady:function(c){var e=function(f,g){b(function(){c(f,g)})};a.push(e);e(s,d)},triggerDomUpdate:function(c){if(c){var e=c!==document?b(c):d;b.each(a,function(f,g){g(c,e)})}}});j.defineNodeNameProperty=function(){var c=b.attr,e={},f={};b.attr=function(h,l,i,m,p){var n=(h.nodeName||"").toLowerCase();if(!n||h.nodeType!==1)return c(h,l,i,m,p);var o=e[n],u,v;if(o)o=o[l];if(!o)if(o=e["*"])o=o[l];if(o)if(i===void 0){if(o.get)return o.get(h,
i);return o.value}else if(o.set){v=o.set(h,i);u=true}u||(v=c(h,l,i,m,p));i!==void 0&&f[n]&&f[n][l]&&f[n][l].forEach(function(B){B(h,i)});return v};j.onNodeNamesPropertyModify=function(h,l,i){if(typeof h=="string")h=h.split(/\s*,\s*/);if(b.isFunction(i))i={set:i};h.forEach(function(m){f[m]||(f[m]={});f[m][l]||(f[m][l]=[]);i.set&&f[m][l].push(i.set);i.init&&g(m,l)})};var g=function(){var h={},l={},i;j.addReady(function(m,p){h={};b.each(l,function(n,o){h[n]=b(m.getElementsByTagName(n));if(p[0]&&b.nodeName(p[0],
n))h[n]=h[n].add(p);o.forEach(function(u){h[n].filter("["+u+"]").attr(u,function(v,B){return B})})});i=true});return function(m,p){if(l[m])l[m].push(p);else l[m]=[p];if(i){h[m]=h[m]||b(document.getElementsByTagName(m));h[m].filter("["+p+"]").attr(p,function(n,o){return o})}}}();return function(h,l,i){i=b.extend({writeable:true},i);e[h]||(e[h]={});var m=e[h][l],p=function(n,o){if(o&&o[n])return o[n];return n=="value"?function(u){var v=c(u,l);if(v&&v.apply)return v.apply(u,arguments)}:function(u,v){return c(u,
l,v)}};e[h][l]=i;if(i.value===void 0){if(!i.set)i.set=i.writeable?p("set",i):function(){throw l+"is readonly on "+h;};if(!i.get)i.get=p("get",i)}["value","get","set"].forEach(function(n){if(i[n])i[n]._polyfilled=p(n,m)});i.init&&g(h,l);return i}}()})();b.fn.htmlWebshim=function(a){a=this.html(a?j.fixHTML5(a):a);a===this&&b.isReady&&this.each(function(){j.triggerDomUpdate(this)});return a};b.each(["after","before","append","prepend"],function(a,d){b.fn[d+"Webshim"]=function(c){c=b(j.fixHTML5(c));this[d](c);
b.isReady&&c.each(function(){j.triggerDomUpdate(this)});return this}});y("htmlExtLangChange",true);var z=parseFloat(b.browser.version,10);q.addModule("html5a11y",{src:"html5a11y",test:function(){return!(b.browser.msie&&z<10&&z>7||b.browser.mozilla&&z<2||b.browser.webkit&&z<540)}});q.addModule("jquery-ui",{src:"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js",test:function(){return!!(b.widget&&b.Widget)}});q.addModule("input-widgets",{src:"",test:function(){return!(b.widget&&!(b.datepicker||
b.fn.slider))}});q.addModule("swfobject",{src:"http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js",test:function(){return"swfobject"in window}});var C=b("<div />")[0],x=[];x.push(!!(Array.isArray&&Object.keys&&Object.create&&Function.prototype.bind&&Object.defineProperties&&!isNaN(Date.parse("T00:00"))));x.push(!!(String.prototype.trim&&Date.now&&Date.prototype.toISOString));x[1]&&b.each(["filter","map","every","reduce","reduceRight","lastIndexOf"],function(a,d){if(!Array.prototype[d])return x[1]=
false});k.es5=x[0]&&x[1];k.objectAccessor=!!(Object.create&&Object.defineProperties&&Object.getOwnPropertyDescriptor||Object.prototype.__defineGetter__&&Object.prototype.__lookupSetter__);k.domAccessor=!!(Object.prototype.__defineGetter__&&Object.prototype.__lookupSetter__||Object.defineProperty&&Object.getOwnPropertyDescriptor);C.setAttribute("dataHttpAttr",":-)");k.contentAttr=!C.dataHttpAttr;j.objectCreate=Object.create;j.defineProperty=Object.defineProperty;j.defineProperties=Object.defineProperties;
j.getOwnPropertyDescriptor=Object.getOwnPropertyDescriptor;r("es5-1",{feature:"es5",test:function(){return x[1]&&x[0]},combination:["combined-ie7","combined-ie8","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ff3-light","combined-webkit"]});r("es5-2",{feature:"es5",test:function(){return x[1]},combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});k.geolocation="geolocation"in navigator;r("geolocation",{test:function(){return k.geolocation},options:{destroyWrite:true},
combination:["combined-ie7","combined-ie8","combined-ie9","combined-ie7-light","combined-ie8-light","combined-ie9-light"]});k.canvas="getContext"in b("<canvas />")[0];r("canvas",{test:function(){return k.canvas},noAutoCallback:true,methodNames:["getContext"],combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});j.validityMessages=[];j.inputTypes={};(function(){var a=b('<form action="#"><fieldset><input name="a" required /><select><option>y</option></select></fieldset></form>'),
d=b("fieldset",a)[0],c=b('<input type="range" />')[0],e=b('<input type="date" />')[0];k.validity="checkValidity"in a[0];k.validationMessage=!!b("input",a).attr("validationMessage");k.fieldsetValidation=!!(d.elements&&d.checkValidity&&"disabled"in d&&!d.checkValidity());k.output=!!("value"in s.createElement("output"));k.numericDateProps=c.type=="range"&&e.type=="date";k.requiredSelect="required"in b("select",a)[0];k.rangeUI=k.numericDateProps;k.dateUI=k.numericDateProps;if(window.Modernizr){k.rangeUI=
Modernizr.inputtypes.range;k.dateUI=Modernizr.inputtypes.date}})();r("form-core",{feature:"forms",noAutoCallback:true,loadInit:function(){setTimeout(function(){j.polyfill(["es5"])},0)},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit"]});r("form-message",{feature:"forms",test:function(){return k.validity&&k.validationMessage&&j.implement.customValidationMessage&&
t["form-extend"]()},options:{},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light","combined-webkit"]});if(k.validity){j.capturingEvents(["input"]);j.capturingEvents(["invalid"],true);r("form-extend",{feature:"forms",src:"form-native-extend",noAutoCallback:true,test:function(a){return k.requiredSelect&&k.validationMessage&&(k.numericDateProps||b.inArray("form-number-date",a)==-1)&&
!j.overrideValidationMessages},loadInit:function(){setTimeout(function(){q.loadList(["form-message"])},0)},methodNames:["setCustomValidity","checkValidity"],combination:["combined-ff4","combined-webkit"]});r("form-native-fix",{feature:"forms",test:function(){return k.requiredSelect},combination:["combined-webkit"]})}else r("form-extend",{feature:"forms",src:"form-shim-extend",noAutoCallback:true,test:function(){return false},methodNames:["setCustomValidity","checkValidity"],combination:["combined-ie7",
"combined-ie8","combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});r("form-number-date",{feature:"forms-ext",noAutoCallback:true,test:function(){return k.numericDateProps},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4"],options:{stepArrows:{number:1,time:1},calculateWidth:true}});r("inputUI",{feature:"forms-ext",src:"form-date-range-ui",test:function(){return k.rangeUI&&k.dateUI&&!t.inputUI.options.replaceNative},
combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ff4"],noAutoCallback:true,loadInit:function(){q.loadList(["jquery-ui"]);t["input-widgets"].src&&q.loadList(["input-widgets"])},options:{slider:{},datepicker:{},langSrc:"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/i18n/jquery.ui.datepicker-",availabeLangs:"af ar az bg bs cs da de el en-GB eo es et eu fa fi fo fr fr-CH he hr hu hy id is it ja ko it lt lv ms nl no pl pt-BR ro ru sk sl sq sr sr-SR sv ta th tr uk vi zh-CN zh-HK zh-TW".split(" "),
recalcWidth:true,replaceNative:false}});r("form-output",{feature:"forms",noAutoCallback:true,test:function(){return k.output},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3","combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});k.placeholder=b('<input type="text" />').attr("placeholder")!=null;r("form-placeholder",{feature:"forms",test:function(){return k.placeholder},combination:["combined-ie7","combined-ie8","combined-ie9","combined-ff3",
"combined-ie7-light","combined-ie8-light","combined-ie9-light","combined-ff3-light"]});k.jsonStorage="JSON"in window&&"localStorage"in window&&"sessionStorage"in window;r("json-storage",{test:function(){return k.jsonStorage},loadInit:function(){q.loadList(["swfobject"])},noAutoCallback:true,combination:["combined-ie7","combined-ie7-light"]});r("html5shiv",{test:function(){return k.dynamicHTML5},combination:["combined-ie7","combined-ie8","combined-ie7-light","combined-ie8-light"]});j.light=["es5",
"html5shiv","canvas","geolocation","forms","json-storage"]})(jQuery);
