window.Modernizr=function(r,c,D){function z(a,b){for(var d in a)if(K[a[d]]!==D)return"pfx"==b?a[d]:!0;return!1}function u(a,b,d){var m=a.charAt(0).toUpperCase()+a.slice(1),c=(a+" "+v.join(m+" ")+m).split(" ");if("string"===typeof b||"undefined"===typeof b)b=z(c,b);else{c=(a+" "+s.join(m+" ")+m).split(" ");a:{var a=c,i;for(i in a)if(m=b[a[i]],m!==D){b=!1===d?a[i]:"function"===typeof m?m.bind(d||b):m;break a}b=!1}}return b}function E(){f.input=function(a){for(var b=0,d=a.length;b<d;b++)t[a[b]]=a[b]in
h;return t.list&&(t.list=!!c.createElement("datalist")&&!!r.HTMLDataListElement),t}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));f.inputtypes=function(a){for(var b=0,d,m,f,i=a.length;b<i;b++)h.setAttribute("type",m=a[b]),d="text"!==h.type,d&&(h.value=q,h.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(m)&&h.style.WebkitAppearance!==D?(n.appendChild(h),f=c.defaultView,d=f.getComputedStyle&&"textfield"!==f.getComputedStyle(h,null).WebkitAppearance&&
0!==h.offsetHeight,n.removeChild(h)):/^(search|tel)$/.test(m)||(/^(url|email)$/.test(m)?d=h.checkValidity&&!1===h.checkValidity():d=h.value!=q)),F[a[b]]=!!d;return F}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f={},n=c.documentElement,k=c.createElement("modernizr"),K=k.style,h=c.createElement("input"),q=":)",v="Webkit Moz O ms".split(" "),s="webkit moz o ms".split(" "),k={},F={},t={},w=[],G=w.slice,A,H={}.hasOwnProperty,B;"undefined"!==typeof H&&
"undefined"!==typeof H.call?B=function(a,b){return H.call(a,b)}:B=function(a,b){return b in a&&"undefined"===typeof a.constructor.prototype[b]};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var d=G.call(arguments,1),c=function(){if(this instanceof c){var f=function(){};f.prototype=b.prototype;var f=new f,i=b.apply(f,d.concat(G.call(arguments)));return Object(i)===i?i:f}return b.apply(a,d.concat(G.call(arguments)))};return c});
k.canvas=function(){var a=c.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")};k.geolocation=function(){return"geolocation"in navigator};k.video=function(){var a=c.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(d){}return b};k.audio=function(){var a=
c.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(d){}return b};k.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};
k.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};for(var J in k)B(k,J)&&(A=J.toLowerCase(),f[A]=k[J](),w.push((f[A]?"":"no-")+A));f.input||E();f.addTest=function(a,b){if("object"==typeof a)for(var d in a)B(a,d)&&f.addTest(d,a[d]);else{a=a.toLowerCase();if(f[a]!==D)return f;b="function"==typeof b?b():b;n.className+=" "+(b?"":"no-")+a;f[a]=b}return f};K.cssText="";return k=h=null,function(a,b){function d(){var b=
x.elements;return"string"==typeof b?b.split(" "):b}function f(b){var a=p[b[o]];return a||(a={},g++,b[o]=g,p[g]=a),a}function c(a,j,e){j||(j=b);if(l)return j.createElement(a);e||(e=f(j));var d;return e.cache[a]?d=e.cache[a].cloneNode():I.test(a)?d=(e.cache[a]=e.createElem(a)).cloneNode():d=e.createElem(a),d.canHaveChildren&&!h.test(a)?e.frag.appendChild(d):d}function i(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag());a.createElement=
function(e){return x.shivMethods?c(e,a,b):b.createElem(e)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+d().join().replace(/\w+/g,function(a){return b.createElem(a),b.frag.createElement(a),'c("'+a+'")'})+");return n}")(x,b.frag)}function j(a){a||(a=b);var j=f(a);if(x.shivCSS&&!y&&!j.hasCSS){var e,d=a;e=d.createElement("p");d=d.getElementsByTagName("head")[0]||d.documentElement;e=(e.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>",
d.insertBefore(e.lastChild,d.firstChild));j.hasCSS=!!e}return l||i(a,j),a}var C=a.html5||{},h=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,I=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,y,o="_html5shiv",g=0,p={},l;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";y="hidden"in a;var j;if(!(j=1==a.childNodes.length)){b.createElement("a");
var e=b.createDocumentFragment();j="undefined"==typeof e.cloneNode||"undefined"==typeof e.createDocumentFragment||"undefined"==typeof e.createElement}l=j}catch(d){y=!0,l=!0}})();var x={elements:C.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==C.shivCSS,supportsUnknownElements:l,shivMethods:!1!==C.shivMethods,type:"default",shivDocument:j,createElement:c,createDocumentFragment:function(a,
j){a||(a=b);if(l)return a.createDocumentFragment();for(var j=j||f(a),e=j.frag.cloneNode(),C=0,c=d(),p=c.length;C<p;C++)e.createElement(c[C]);return e}};a.html5=x;j(b)}(this,c),f._version="2.6.0",f._domPrefixes=s,f._cssomPrefixes=v,f.testProp=function(a){return z([a])},f.testAllProps=u,f.prefixed=function(a,b,d){return b?u(a,b,d):u(a,"pfx")},n.className=n.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+w.join(" ")),f}(this,this.document);
(function(r,c,D){function z(a){return"[object Function]"==F.call(a)}function u(a){return"string"==typeof a}function E(){}function f(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function n(){var a=t.shift();w=1;a?a.t?v(function(){("c"==a.t?i.injectCss:i.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),n()):w=0}function k(a,b,h,I,m,o,g){function p(e){if(!x&&f(l.readyState)&&(M.r=x=1,!w&&n(),l.onload=l.onreadystatechange=null,e)){"img"!=a&&v(function(){H.removeChild(l)},50);for(var c in d[b])d[b].hasOwnProperty(c)&&
d[b][c].onload()}}var g=g||i.errorTimeout,l={},x=0,k=0,M={t:h,s:b,e:m,a:o,x:g};1===d[b]&&(k=1,d[b]=[],l=c.createElement(a));"object"==a?l.data=b:(l.src=b,l.type=a);l.width=l.height="0";l.onerror=l.onload=l.onreadystatechange=function(){p.call(this,k)};t.splice(I,0,M);"img"!=a&&(k||2===d[b]?(H.insertBefore(l,A?null:s),v(p,g)):d[b].push(l))}function K(a,b,d,c,f){return w=0,b=b||"j",u(a)?k("c"==b?J:B,a,b,this.i++,d,c,f):(t.splice(this.i++,0,a),1==t.length&&n()),this}function h(){var a=i;return a.loader=
{load:K,i:0},a}var q=c.documentElement,v=r.setTimeout,s=c.getElementsByTagName("script")[0],F={}.toString,t=[],w=0,G="MozAppearance"in q.style,A=G&&!!c.createRange().compareNode,H=A?q:s.parentNode,q=r.opera&&"[object Opera]"==F.call(r.opera),q=!!c.attachEvent&&!q,B=G?"object":q?"script":"img",J=q?"script":B,a=Array.isArray||function(a){return"[object Array]"==F.call(a)},b=[],d={},m={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},L,i;i=function(c){function f(a){var a=a.split("!"),d=b.length,
c=a.pop(),g=a.length,c={url:c,origUrl:c,prefixes:a},j,e,k;for(e=0;e<g;e++)k=a[e].split("="),(j=m[k.shift()])&&(c=j(c,k));for(e=0;e<d;e++)c=b[e](c);return c}function k(a,b,c,j,g){var e=f(a),i=e.autoCallback;e.url.split(".").pop().split("?").shift();e.bypass||(b&&(b=z(b)?b:b[a]||b[j]||b[a.split("/").pop().split("?")[0]]||n),e.instead?e.instead(a,b,c,j,g):(d[e.url]?e.noexec=!0:d[e.url]=1,c.load(e.url,e.forceCSS||!e.forceJS&&"css"==e.url.split(".").pop().split("?").shift()?"c":D,e.noexec,e.attrs,e.timeout),
(z(b)||z(i))&&c.load(function(){h();b&&b(e.origUrl,g,j);i&&i(e.origUrl,g,j);d[e.url]=2})))}function I(a,b){function c(a,f){if(a)if(u(a))f||(e=function(){var a=[].slice.call(arguments);j.apply(this,a);g()}),k(a,e,b,0,d);else{if(Object(a)===a)for(h in i=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(h)&&(!f&&!--i&&(z(e)?e=function(){var a=[].slice.call(arguments);j.apply(this,a);g()}:e[h]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);g()}}(j[h])),k(a[h],e,b,h,d))}else!f&&g()}var d=!!a.test,f=a.load||a.both,e=a.callback||E,j=e,g=a.complete||E,i,h;c(d?a.yep:a.nope,!!f);f&&c(f)}var y,o,g=this.yepnope.loader;if(u(c))k(c,0,g,0);else if(a(c))for(y=0;y<c.length;y++)o=c[y],u(o)?k(o,0,g,0):a(o)?i(o):Object(o)===o&&I(o,g);else Object(c)===c&&I(c,g)};i.addPrefix=function(a,b){m[a]=b};i.addFilter=function(a){b.push(a)};i.errorTimeout=1E4;null==c.readyState&&c.addEventListener&&(c.readyState="loading",c.addEventListener("DOMContentLoaded",
L=function(){c.removeEventListener("DOMContentLoaded",L,0);c.readyState="complete"},0));r.yepnope=h();r.yepnope.executeStack=n;r.yepnope.injectJs=function(a,b,d,h,k,m){var g=c.createElement("script"),p,l,h=h||i.errorTimeout;g.src=a;for(l in d)g.setAttribute(l,d[l]);b=m?n:b||E;g.onreadystatechange=g.onload=function(){!p&&f(g.readyState)&&(p=1,b(),g.onload=g.onreadystatechange=null)};v(function(){p||(p=1,b(1))},h);k?g.onload():s.parentNode.insertBefore(g,s)};r.yepnope.injectCss=function(a,b,d,f,h,i){var f=
c.createElement("link"),g,b=i?n:b||E;f.href=a;f.rel="stylesheet";f.type="text/css";for(g in d)f.setAttribute(g,d[g]);h||(s.parentNode.insertBefore(f,s),v(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
