window.Modernizr=function(u,c,l){function k(){d.input=function(a){for(var b=0,f=a.length;b<f;b++)m[a[b]]=a[b]in e;return m}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));d.inputtypes=function(a){for(var b=0,f,v,d,g=a.length;b<g;b++)e.setAttribute("type",v=a[b]),f="text"!==e.type,f&&(e.value=j,e.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(v)&&e.style.WebkitAppearance!==l?(r.appendChild(e),d=c.defaultView,f=d.getComputedStyle&&"textfield"!==
d.getComputedStyle(e,null).WebkitAppearance&&0!==e.offsetHeight,r.removeChild(e)):/^(search|tel)$/.test(v)||(/^(url|email)$/.test(v)?f=e.checkValidity&&!1===e.checkValidity():/^color$/.test(v)?(r.appendChild(e),f=e.value!=j,r.removeChild(e)):f=e.value!=j)),x[a[b]]=!!f;return x}("search tel url email datetime date month week time datetime-local number range color".split(" "))}function F(a,b){var f=a.charAt(0).toUpperCase()+a.substr(1),f=(a+" "+p.join(f+" ")+f).split(" ");return G(f,b)}function G(a,
b){for(var f in a)if(B[a[f]]!==l)return"pfx"==b?a[f]:!0;return!1}var d={},r=c.documentElement;c.head||c.getElementsByTagName("head");var g=c.createElement("modernizr"),B=g.style,e=c.createElement("input"),j=":)",p="Webkit Moz O ms Khtml".split(" "),g={},x={},m={},y=[],s,w={}.hasOwnProperty,t;typeof w!==l&&typeof w.call!==l?t=function(a,b){return w.call(a,b)}:t=function(a,b){return b in a&&typeof a.constructor.prototype[b]===l};g.canvas=function(){var a=c.createElement("canvas");return!!a.getContext&&
!!a.getContext("2d")};g.geolocation=function(){return!!navigator.geolocation};g.video=function(){var a=c.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"'),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"')||a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"'),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"')}catch(f){}return b};g.audio=function(){var a=c.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=
new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"'),b.mp3=a.canPlayType("audio/mpeg;"),b.wav=a.canPlayType('audio/wav; codecs="1"'),b.m4a=a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")}catch(f){}return b};g.localstorage=function(){try{return!!localStorage.getItem}catch(a){return!1}};g.sessionstorage=function(){try{return!!sessionStorage.getItem}catch(a){return!1}};for(var C in g)t(g,C)&&(s=C.toLowerCase(),d[s]=g[C](),y.push((d[s]?"":"no-")+s));d.input||k();d.addTest=function(a,
b){if("object"==typeof a)for(var f in a)t(a,f)&&d.addTest(f,a[f]);else{a=a.toLowerCase();if(d[a]!==l)return;b="boolean"==typeof b?b:!!b();r.className+=" "+(b?"":"no-")+a;d[a]=b}return d};B.cssText="";g=e=null;u.attachEvent&&function(){var a=c.createElement("div");a.innerHTML="<elem></elem>";return 1!==a.childNodes.length}()&&function(a,b){function f(a){for(var h=-1;++h<g;)a.createElement(e[h])}a.iepp=a.iepp||{};var c=a.iepp,d=c.html5elements||"abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",
e=d.split("|"),g=e.length,j=RegExp("(^|\\s)("+d+")","gi"),k=RegExp("<(/*)("+d+")","gi"),m=/^\s*[\{\}]\s*$/,n=RegExp("(^|[^\\n]*?\\s)("+d+")([^\\n]*)({[\\n\\w\\W]*?})","gi"),i=b.createDocumentFragment(),o=b.documentElement,d=o.firstChild,z=b.createElement("body"),D=b.createElement("style"),N=/print|all/,q;c.getCSS=function(a,h){if(a+""===l)return"";for(var b=-1,i=a.length,o,d=[];++b<i;)o=a[b],o.disabled||(h=o.media||h,N.test(h)&&d.push(c.getCSS(o.imports,h),o.cssText),h="all");return d.join("")};c.parseCSS=
function(a){for(var b=[],i;null!=(i=n.exec(a));)b.push(((m.exec(i[1])?"\n":i[1])+i[2]+i[3]).replace(j,"$1.iepp_$2")+i[4]);return b.join("\n")};c.writeHTML=function(){var a=-1;for(q=q||b.body;++a<g;)for(var h=b.getElementsByTagName(e[a]),c=h.length,d=-1;++d<c;)0>h[d].className.indexOf("iepp_")&&(h[d].className+=" iepp_"+e[a]);i.appendChild(q);o.appendChild(z);z.className=q.className;z.id=q.id;z.innerHTML=q.innerHTML.replace(k,"<$1font")};c._beforePrint=function(){D.styleSheet.cssText=c.parseCSS(c.getCSS(b.styleSheets,
"all"));c.writeHTML()};c.restoreHTML=function(){z.innerHTML="";o.removeChild(z);o.appendChild(q)};c._afterPrint=function(){c.restoreHTML();D.styleSheet.cssText=""};f(b);f(i);c.disablePP||(d.insertBefore(D,d.firstChild),D.media="print",D.className="iepp-printshim",a.attachEvent("onbeforeprint",c._beforePrint),a.attachEvent("onafterprint",c._afterPrint))}(u,c);d._version="2.0.6";d._domPrefixes=p;d.testProp=function(a){return G([a])};d.testAllProps=F;d.prefixed=function(a){return F(a,"pfx")};return d}(this,
this.document);
(function(u,c,l){function k(){for(var a=1,b=-1;m.length-++b&&(!m[b].s||(a=m[b].r)););a&&d()}function F(a){var b=c.createElement("script"),d;b.src=a.s;b.onreadystatechange=b.onload=function(){!d&&(!b.readyState||"loaded"==b.readyState||"complete"==b.readyState)&&(d=1,k(),b.onload=b.onreadystatechange=null)};j(function(){d||(d=1,k())},n.errorTimeout);a.e?b.onload():p.parentNode.insertBefore(b,p)}function G(b){var d=c.createElement("link"),f;d.href=b.s;d.rel="stylesheet";d.type="text/css";if(!b.e&&(a||
s)){var e=function(a){j(function(){if(!f)try{a.sheet.cssRules.length?(f=1,k()):e(a)}catch(b){1E3==b.code||"security"==b.message||"denied"==b.message?(f=1,j(function(){k()},0)):e(a)}},0)};e(d)}else d.onload=function(){f||(f=1,j(function(){k()},0))},b.e&&d.onload();j(function(){f||(f=1,k())},n.errorTimeout);!b.e&&p.parentNode.insertBefore(d,p)}function d(){var a=m.shift();y=1;a?a.t?j(function(){"c"==a.t?G(a):F(a)},0):(a(),k()):y=0}function r(a,b,f,e,g,q){function l(){!H&&(!h.readyState||"loaded"==h.readyState||
"complete"==h.readyState)&&(A.r=H=1,!y&&k(),h.onload=h.onreadystatechange=null,j(function(){t.removeChild(h)},0))}var h=c.createElement(a),H=0,A={t:f,s:b,e:q};h.src=h.data=b;!w&&(h.style.display="none");h.width=h.height="0";"object"!=a&&(h.type=f);h.onload=h.onreadystatechange=l;"img"==a?h.onerror=l:"script"==a&&(h.onerror=function(){A.e=A.r=1;d()});m.splice(e,0,A);t.insertBefore(h,w?null:p);j(function(){H||(t.removeChild(h),A.r=A.e=H=1,k())},n.errorTimeout)}function g(a,b,c){var g="c"==b?v:f;y=0;
b=b||"j";E(a)?r(g,a,b,this.i++,e,c):(m.splice(this.i++,0,a),1==m.length&&d());return this}function B(){var a=n;a.loader={load:g,i:0};return a}var e=c.documentElement,j=u.setTimeout,p=c.getElementsByTagName("script")[0],x={}.toString,m=[],y=0,s="MozAppearance"in e.style,w=s&&!!c.createRange().compareNode,t=w?e:p.parentNode,C=u.opera&&"[object Opera]"==x.call(u.opera),a="webkitAppearance"in e.style,b=a&&"async"in c.createElement("script"),f=s?"object":C||b?"img":"script",v=a?"img":f,K=Array.isArray||
function(a){return"[object Array]"==x.call(a)},E=function(a){return"string"==typeof a},I=function(a){return"[object Function]"==x.call(a)},J=[],L={},M,n;n=function(a){function b(a){var a=a.split("!"),d=J.length,c=a.pop(),f=a.length,c={url:c,origUrl:c,prefixes:a},e,g;for(g=0;g<f;g++)e=L[a[g]],e&&(c=e(c));for(g=0;g<d;g++)c=J[g](c);return c}function d(a,c,f,e,g){var i=b(a),j=i.autoCallback;if(!i.bypass){c&&(c=I(c)?c:c[a]||c[e]||c[a.split("/").pop().split("?")[0]]);if(i.instead)return i.instead(a,c,f,
e,g);f.load(i.url,i.forceCSS||!i.forceJS&&/css$/.test(i.url)?"c":l,i.noexec);(I(c)||I(j))&&f.load(function(){B();c&&c(i.origUrl,g,e);j&&j(i.origUrl,g,e)})}}function c(a,b){function f(a){if(E(a))d(a,i,b,0,e);else if(Object(a)===a)for(j in a)a.hasOwnProperty(j)&&d(a[j],i,b,j,e)}var e=!!a.test,g=a.load||a.both,i=a.callback,j;f(e?a.yep:a.nope);f(g);a.complete&&b.load(a.complete)}var f,e,g=this.yepnope.loader;if(E(a))d(a,0,g,0);else if(K(a))for(f=0;f<a.length;f++)e=a[f],E(e)?d(e,0,g,0):K(e)?n(e):Object(e)===
e&&c(e,g);else Object(a)===a&&c(a,g)};n.addPrefix=function(a,b){L[a]=b};n.addFilter=function(a){J.push(a)};n.errorTimeout=1E4;null==c.readyState&&c.addEventListener&&(c.readyState="loading",c.addEventListener("DOMContentLoaded",M=function(){c.removeEventListener("DOMContentLoaded",M,0);c.readyState="complete"},0));u.yepnope=B()})(this,this.document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
